package fi.csc.smear.db.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import fi.csc.smear.db.model.SmearvariableEvent;
import fi.csc.smear.db.service.SmearvariableEventLocalService;
import fi.csc.smear.db.service.persistence.Hyde_eddy233Persistence;
import fi.csc.smear.db.service.persistence.Hyde_eddytowPersistence;
import fi.csc.smear.db.service.persistence.HydemetaPersistence;
import fi.csc.smear.db.service.persistence.HyyAeroPersistence;
import fi.csc.smear.db.service.persistence.HyyDMPSPersistence;
import fi.csc.smear.db.service.persistence.Hyy_eddysubPersistence;
import fi.csc.smear.db.service.persistence.KumpulaDMPSPersistence;
import fi.csc.smear.db.service.persistence.Kumpula_eddyPersistence;
import fi.csc.smear.db.service.persistence.KumpulametaPersistence;
import fi.csc.smear.db.service.persistence.Sii1eddyPersistence;
import fi.csc.smear.db.service.persistence.Sii1metaPersistence;
import fi.csc.smear.db.service.persistence.Sii2eddyPersistence;
import fi.csc.smear.db.service.persistence.Sii2metaPersistence;
import fi.csc.smear.db.service.persistence.SmearEventsPersistence;
import fi.csc.smear.db.service.persistence.SmearTableMetadataPersistence;
import fi.csc.smear.db.service.persistence.SmearTagsPersistence;
import fi.csc.smear.db.service.persistence.SmearVariableMetadataPersistence;
import fi.csc.smear.db.service.persistence.SmearmetadataPersistence;
import fi.csc.smear.db.service.persistence.SmearstationPersistence;
import fi.csc.smear.db.service.persistence.SmearvariableEventPK;
import fi.csc.smear.db.service.persistence.SmearvariableEventPersistence;
import fi.csc.smear.db.service.persistence.SmearvariableTagsPersistence;
import fi.csc.smear.db.service.persistence.TowermetaPersistence;
import fi.csc.smear.db.service.persistence.VarDMPSPersistence;
import fi.csc.smear.db.service.persistence.VareddyPersistence;
import fi.csc.smear.db.service.persistence.Varrio_treePersistence;
import fi.csc.smear.db.service.persistence.VarriometaPersistence;
import fi.csc.smear.db.service.persistence.kvjEddyPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the smearvariable event local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link fi.csc.smear.db.service.impl.SmearvariableEventLocalServiceImpl}.
 * </p>
 *
 * @author pj
 * @see fi.csc.smear.db.service.impl.SmearvariableEventLocalServiceImpl
 * @see fi.csc.smear.db.service.SmearvariableEventLocalServiceUtil
 * @generated
 */
public abstract class SmearvariableEventLocalServiceBaseImpl
    extends BaseLocalServiceImpl implements SmearvariableEventLocalService,
        IdentifiableBean {
    @BeanReference(type = fi.csc.smear.db.service.Hyde_eddy233LocalService.class)
    protected fi.csc.smear.db.service.Hyde_eddy233LocalService hyde_eddy233LocalService;
    @BeanReference(type = fi.csc.smear.db.service.Hyde_eddy233Service.class)
    protected fi.csc.smear.db.service.Hyde_eddy233Service hyde_eddy233Service;
    @BeanReference(type = Hyde_eddy233Persistence.class)
    protected Hyde_eddy233Persistence hyde_eddy233Persistence;
    @BeanReference(type = fi.csc.smear.db.service.Hyde_eddytowLocalService.class)
    protected fi.csc.smear.db.service.Hyde_eddytowLocalService hyde_eddytowLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Hyde_eddytowService.class)
    protected fi.csc.smear.db.service.Hyde_eddytowService hyde_eddytowService;
    @BeanReference(type = Hyde_eddytowPersistence.class)
    protected Hyde_eddytowPersistence hyde_eddytowPersistence;
    @BeanReference(type = fi.csc.smear.db.service.HydemetaLocalService.class)
    protected fi.csc.smear.db.service.HydemetaLocalService hydemetaLocalService;
    @BeanReference(type = fi.csc.smear.db.service.HydemetaService.class)
    protected fi.csc.smear.db.service.HydemetaService hydemetaService;
    @BeanReference(type = HydemetaPersistence.class)
    protected HydemetaPersistence hydemetaPersistence;
    @BeanReference(type = fi.csc.smear.db.service.Hyy_eddysubLocalService.class)
    protected fi.csc.smear.db.service.Hyy_eddysubLocalService hyy_eddysubLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Hyy_eddysubService.class)
    protected fi.csc.smear.db.service.Hyy_eddysubService hyy_eddysubService;
    @BeanReference(type = Hyy_eddysubPersistence.class)
    protected Hyy_eddysubPersistence hyy_eddysubPersistence;
    @BeanReference(type = fi.csc.smear.db.service.HyyAeroLocalService.class)
    protected fi.csc.smear.db.service.HyyAeroLocalService hyyAeroLocalService;
    @BeanReference(type = fi.csc.smear.db.service.HyyAeroService.class)
    protected fi.csc.smear.db.service.HyyAeroService hyyAeroService;
    @BeanReference(type = HyyAeroPersistence.class)
    protected HyyAeroPersistence hyyAeroPersistence;
    @BeanReference(type = fi.csc.smear.db.service.HyyDMPSLocalService.class)
    protected fi.csc.smear.db.service.HyyDMPSLocalService hyyDMPSLocalService;
    @BeanReference(type = fi.csc.smear.db.service.HyyDMPSService.class)
    protected fi.csc.smear.db.service.HyyDMPSService hyyDMPSService;
    @BeanReference(type = HyyDMPSPersistence.class)
    protected HyyDMPSPersistence hyyDMPSPersistence;
    @BeanReference(type = fi.csc.smear.db.service.Kumpula_eddyLocalService.class)
    protected fi.csc.smear.db.service.Kumpula_eddyLocalService kumpula_eddyLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Kumpula_eddyService.class)
    protected fi.csc.smear.db.service.Kumpula_eddyService kumpula_eddyService;
    @BeanReference(type = Kumpula_eddyPersistence.class)
    protected Kumpula_eddyPersistence kumpula_eddyPersistence;
    @BeanReference(type = fi.csc.smear.db.service.KumpulaDMPSLocalService.class)
    protected fi.csc.smear.db.service.KumpulaDMPSLocalService kumpulaDMPSLocalService;
    @BeanReference(type = fi.csc.smear.db.service.KumpulaDMPSService.class)
    protected fi.csc.smear.db.service.KumpulaDMPSService kumpulaDMPSService;
    @BeanReference(type = KumpulaDMPSPersistence.class)
    protected KumpulaDMPSPersistence kumpulaDMPSPersistence;
    @BeanReference(type = fi.csc.smear.db.service.KumpulametaLocalService.class)
    protected fi.csc.smear.db.service.KumpulametaLocalService kumpulametaLocalService;
    @BeanReference(type = fi.csc.smear.db.service.KumpulametaService.class)
    protected fi.csc.smear.db.service.KumpulametaService kumpulametaService;
    @BeanReference(type = KumpulametaPersistence.class)
    protected KumpulametaPersistence kumpulametaPersistence;
    @BeanReference(type = fi.csc.smear.db.service.kvjEddyLocalService.class)
    protected fi.csc.smear.db.service.kvjEddyLocalService kvjEddyLocalService;
    @BeanReference(type = fi.csc.smear.db.service.kvjEddyService.class)
    protected fi.csc.smear.db.service.kvjEddyService kvjEddyService;
    @BeanReference(type = kvjEddyPersistence.class)
    protected kvjEddyPersistence kvjEddyPersistence;
    @BeanReference(type = fi.csc.smear.db.service.Sii1eddyLocalService.class)
    protected fi.csc.smear.db.service.Sii1eddyLocalService sii1eddyLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Sii1eddyService.class)
    protected fi.csc.smear.db.service.Sii1eddyService sii1eddyService;
    @BeanReference(type = Sii1eddyPersistence.class)
    protected Sii1eddyPersistence sii1eddyPersistence;
    @BeanReference(type = fi.csc.smear.db.service.Sii1metaLocalService.class)
    protected fi.csc.smear.db.service.Sii1metaLocalService sii1metaLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Sii1metaService.class)
    protected fi.csc.smear.db.service.Sii1metaService sii1metaService;
    @BeanReference(type = Sii1metaPersistence.class)
    protected Sii1metaPersistence sii1metaPersistence;
    @BeanReference(type = fi.csc.smear.db.service.Sii2eddyLocalService.class)
    protected fi.csc.smear.db.service.Sii2eddyLocalService sii2eddyLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Sii2eddyService.class)
    protected fi.csc.smear.db.service.Sii2eddyService sii2eddyService;
    @BeanReference(type = Sii2eddyPersistence.class)
    protected Sii2eddyPersistence sii2eddyPersistence;
    @BeanReference(type = fi.csc.smear.db.service.Sii2metaLocalService.class)
    protected fi.csc.smear.db.service.Sii2metaLocalService sii2metaLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Sii2metaService.class)
    protected fi.csc.smear.db.service.Sii2metaService sii2metaService;
    @BeanReference(type = Sii2metaPersistence.class)
    protected Sii2metaPersistence sii2metaPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearEventsLocalService.class)
    protected fi.csc.smear.db.service.SmearEventsLocalService smearEventsLocalService;
    @BeanReference(type = fi.csc.smear.db.service.SmearEventsService.class)
    protected fi.csc.smear.db.service.SmearEventsService smearEventsService;
    @BeanReference(type = SmearEventsPersistence.class)
    protected SmearEventsPersistence smearEventsPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearmetadataLocalService.class)
    protected fi.csc.smear.db.service.SmearmetadataLocalService smearmetadataLocalService;
    @BeanReference(type = fi.csc.smear.db.service.SmearmetadataService.class)
    protected fi.csc.smear.db.service.SmearmetadataService smearmetadataService;
    @BeanReference(type = SmearmetadataPersistence.class)
    protected SmearmetadataPersistence smearmetadataPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearstationLocalService.class)
    protected fi.csc.smear.db.service.SmearstationLocalService smearstationLocalService;
    @BeanReference(type = fi.csc.smear.db.service.SmearstationService.class)
    protected fi.csc.smear.db.service.SmearstationService smearstationService;
    @BeanReference(type = SmearstationPersistence.class)
    protected SmearstationPersistence smearstationPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearTableMetadataLocalService.class)
    protected fi.csc.smear.db.service.SmearTableMetadataLocalService smearTableMetadataLocalService;
    @BeanReference(type = fi.csc.smear.db.service.SmearTableMetadataService.class)
    protected fi.csc.smear.db.service.SmearTableMetadataService smearTableMetadataService;
    @BeanReference(type = SmearTableMetadataPersistence.class)
    protected SmearTableMetadataPersistence smearTableMetadataPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearTagsLocalService.class)
    protected fi.csc.smear.db.service.SmearTagsLocalService smearTagsLocalService;
    @BeanReference(type = fi.csc.smear.db.service.SmearTagsService.class)
    protected fi.csc.smear.db.service.SmearTagsService smearTagsService;
    @BeanReference(type = SmearTagsPersistence.class)
    protected SmearTagsPersistence smearTagsPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearvariableEventLocalService.class)
    protected fi.csc.smear.db.service.SmearvariableEventLocalService smearvariableEventLocalService;
    @BeanReference(type = SmearvariableEventPersistence.class)
    protected SmearvariableEventPersistence smearvariableEventPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearVariableMetadataLocalService.class)
    protected fi.csc.smear.db.service.SmearVariableMetadataLocalService smearVariableMetadataLocalService;
    @BeanReference(type = fi.csc.smear.db.service.SmearVariableMetadataService.class)
    protected fi.csc.smear.db.service.SmearVariableMetadataService smearVariableMetadataService;
    @BeanReference(type = SmearVariableMetadataPersistence.class)
    protected SmearVariableMetadataPersistence smearVariableMetadataPersistence;
    @BeanReference(type = fi.csc.smear.db.service.SmearvariableTagsLocalService.class)
    protected fi.csc.smear.db.service.SmearvariableTagsLocalService smearvariableTagsLocalService;
    @BeanReference(type = fi.csc.smear.db.service.SmearvariableTagsService.class)
    protected fi.csc.smear.db.service.SmearvariableTagsService smearvariableTagsService;
    @BeanReference(type = SmearvariableTagsPersistence.class)
    protected SmearvariableTagsPersistence smearvariableTagsPersistence;
    @BeanReference(type = fi.csc.smear.db.service.TowermetaLocalService.class)
    protected fi.csc.smear.db.service.TowermetaLocalService towermetaLocalService;
    @BeanReference(type = fi.csc.smear.db.service.TowermetaService.class)
    protected fi.csc.smear.db.service.TowermetaService towermetaService;
    @BeanReference(type = TowermetaPersistence.class)
    protected TowermetaPersistence towermetaPersistence;
    @BeanReference(type = fi.csc.smear.db.service.VarDMPSLocalService.class)
    protected fi.csc.smear.db.service.VarDMPSLocalService varDMPSLocalService;
    @BeanReference(type = fi.csc.smear.db.service.VarDMPSService.class)
    protected fi.csc.smear.db.service.VarDMPSService varDMPSService;
    @BeanReference(type = VarDMPSPersistence.class)
    protected VarDMPSPersistence varDMPSPersistence;
    @BeanReference(type = fi.csc.smear.db.service.VareddyLocalService.class)
    protected fi.csc.smear.db.service.VareddyLocalService vareddyLocalService;
    @BeanReference(type = fi.csc.smear.db.service.VareddyService.class)
    protected fi.csc.smear.db.service.VareddyService vareddyService;
    @BeanReference(type = VareddyPersistence.class)
    protected VareddyPersistence vareddyPersistence;
    @BeanReference(type = fi.csc.smear.db.service.Varrio_treeLocalService.class)
    protected fi.csc.smear.db.service.Varrio_treeLocalService varrio_treeLocalService;
    @BeanReference(type = fi.csc.smear.db.service.Varrio_treeService.class)
    protected fi.csc.smear.db.service.Varrio_treeService varrio_treeService;
    @BeanReference(type = Varrio_treePersistence.class)
    protected Varrio_treePersistence varrio_treePersistence;
    @BeanReference(type = fi.csc.smear.db.service.VarriometaLocalService.class)
    protected fi.csc.smear.db.service.VarriometaLocalService varriometaLocalService;
    @BeanReference(type = fi.csc.smear.db.service.VarriometaService.class)
    protected fi.csc.smear.db.service.VarriometaService varriometaService;
    @BeanReference(type = VarriometaPersistence.class)
    protected VarriometaPersistence varriometaPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private SmearvariableEventLocalServiceClpInvoker _clpInvoker = new SmearvariableEventLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link fi.csc.smear.db.service.SmearvariableEventLocalServiceUtil} to access the smearvariable event local service.
     */

    /**
     * Adds the smearvariable event to the database. Also notifies the appropriate model listeners.
     *
     * @param smearvariableEvent the smearvariable event
     * @return the smearvariable event that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public SmearvariableEvent addSmearvariableEvent(
        SmearvariableEvent smearvariableEvent) throws SystemException {
        smearvariableEvent.setNew(true);

        return smearvariableEventPersistence.update(smearvariableEvent);
    }

    /**
     * Creates a new smearvariable event with the primary key. Does not add the smearvariable event to the database.
     *
     * @param smearvariableEventPK the primary key for the new smearvariable event
     * @return the new smearvariable event
     */
    @Override
    public SmearvariableEvent createSmearvariableEvent(
        SmearvariableEventPK smearvariableEventPK) {
        return smearvariableEventPersistence.create(smearvariableEventPK);
    }

    /**
     * Deletes the smearvariable event with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param smearvariableEventPK the primary key of the smearvariable event
     * @return the smearvariable event that was removed
     * @throws PortalException if a smearvariable event with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public SmearvariableEvent deleteSmearvariableEvent(
        SmearvariableEventPK smearvariableEventPK)
        throws PortalException, SystemException {
        return smearvariableEventPersistence.remove(smearvariableEventPK);
    }

    /**
     * Deletes the smearvariable event from the database. Also notifies the appropriate model listeners.
     *
     * @param smearvariableEvent the smearvariable event
     * @return the smearvariable event that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public SmearvariableEvent deleteSmearvariableEvent(
        SmearvariableEvent smearvariableEvent) throws SystemException {
        return smearvariableEventPersistence.remove(smearvariableEvent);
    }

    @Override
    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(SmearvariableEvent.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return smearvariableEventPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link fi.csc.smear.db.model.impl.SmearvariableEventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return smearvariableEventPersistence.findWithDynamicQuery(dynamicQuery,
            start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link fi.csc.smear.db.model.impl.SmearvariableEventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return smearvariableEventPersistence.findWithDynamicQuery(dynamicQuery,
            start, end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return smearvariableEventPersistence.countWithDynamicQuery(dynamicQuery);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @param projection the projection to apply to the query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery,
        Projection projection) throws SystemException {
        return smearvariableEventPersistence.countWithDynamicQuery(dynamicQuery,
            projection);
    }

    @Override
    public SmearvariableEvent fetchSmearvariableEvent(
        SmearvariableEventPK smearvariableEventPK) throws SystemException {
        return smearvariableEventPersistence.fetchByPrimaryKey(smearvariableEventPK);
    }

    /**
     * Returns the smearvariable event with the primary key.
     *
     * @param smearvariableEventPK the primary key of the smearvariable event
     * @return the smearvariable event
     * @throws PortalException if a smearvariable event with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public SmearvariableEvent getSmearvariableEvent(
        SmearvariableEventPK smearvariableEventPK)
        throws PortalException, SystemException {
        return smearvariableEventPersistence.findByPrimaryKey(smearvariableEventPK);
    }

    @Override
    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return smearvariableEventPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the smearvariable events.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link fi.csc.smear.db.model.impl.SmearvariableEventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param start the lower bound of the range of smearvariable events
     * @param end the upper bound of the range of smearvariable events (not inclusive)
     * @return the range of smearvariable events
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<SmearvariableEvent> getSmearvariableEvents(int start, int end)
        throws SystemException {
        return smearvariableEventPersistence.findAll(start, end);
    }

    /**
     * Returns the number of smearvariable events.
     *
     * @return the number of smearvariable events
     * @throws SystemException if a system exception occurred
     */
    @Override
    public int getSmearvariableEventsCount() throws SystemException {
        return smearvariableEventPersistence.countAll();
    }

    /**
     * Updates the smearvariable event in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param smearvariableEvent the smearvariable event
     * @return the smearvariable event that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public SmearvariableEvent updateSmearvariableEvent(
        SmearvariableEvent smearvariableEvent) throws SystemException {
        return smearvariableEventPersistence.update(smearvariableEvent);
    }

    /**
     * Returns the hyde_eddy233 local service.
     *
     * @return the hyde_eddy233 local service
     */
    public fi.csc.smear.db.service.Hyde_eddy233LocalService getHyde_eddy233LocalService() {
        return hyde_eddy233LocalService;
    }

    /**
     * Sets the hyde_eddy233 local service.
     *
     * @param hyde_eddy233LocalService the hyde_eddy233 local service
     */
    public void setHyde_eddy233LocalService(
        fi.csc.smear.db.service.Hyde_eddy233LocalService hyde_eddy233LocalService) {
        this.hyde_eddy233LocalService = hyde_eddy233LocalService;
    }

    /**
     * Returns the hyde_eddy233 remote service.
     *
     * @return the hyde_eddy233 remote service
     */
    public fi.csc.smear.db.service.Hyde_eddy233Service getHyde_eddy233Service() {
        return hyde_eddy233Service;
    }

    /**
     * Sets the hyde_eddy233 remote service.
     *
     * @param hyde_eddy233Service the hyde_eddy233 remote service
     */
    public void setHyde_eddy233Service(
        fi.csc.smear.db.service.Hyde_eddy233Service hyde_eddy233Service) {
        this.hyde_eddy233Service = hyde_eddy233Service;
    }

    /**
     * Returns the hyde_eddy233 persistence.
     *
     * @return the hyde_eddy233 persistence
     */
    public Hyde_eddy233Persistence getHyde_eddy233Persistence() {
        return hyde_eddy233Persistence;
    }

    /**
     * Sets the hyde_eddy233 persistence.
     *
     * @param hyde_eddy233Persistence the hyde_eddy233 persistence
     */
    public void setHyde_eddy233Persistence(
        Hyde_eddy233Persistence hyde_eddy233Persistence) {
        this.hyde_eddy233Persistence = hyde_eddy233Persistence;
    }

    /**
     * Returns the hyde_eddytow local service.
     *
     * @return the hyde_eddytow local service
     */
    public fi.csc.smear.db.service.Hyde_eddytowLocalService getHyde_eddytowLocalService() {
        return hyde_eddytowLocalService;
    }

    /**
     * Sets the hyde_eddytow local service.
     *
     * @param hyde_eddytowLocalService the hyde_eddytow local service
     */
    public void setHyde_eddytowLocalService(
        fi.csc.smear.db.service.Hyde_eddytowLocalService hyde_eddytowLocalService) {
        this.hyde_eddytowLocalService = hyde_eddytowLocalService;
    }

    /**
     * Returns the hyde_eddytow remote service.
     *
     * @return the hyde_eddytow remote service
     */
    public fi.csc.smear.db.service.Hyde_eddytowService getHyde_eddytowService() {
        return hyde_eddytowService;
    }

    /**
     * Sets the hyde_eddytow remote service.
     *
     * @param hyde_eddytowService the hyde_eddytow remote service
     */
    public void setHyde_eddytowService(
        fi.csc.smear.db.service.Hyde_eddytowService hyde_eddytowService) {
        this.hyde_eddytowService = hyde_eddytowService;
    }

    /**
     * Returns the hyde_eddytow persistence.
     *
     * @return the hyde_eddytow persistence
     */
    public Hyde_eddytowPersistence getHyde_eddytowPersistence() {
        return hyde_eddytowPersistence;
    }

    /**
     * Sets the hyde_eddytow persistence.
     *
     * @param hyde_eddytowPersistence the hyde_eddytow persistence
     */
    public void setHyde_eddytowPersistence(
        Hyde_eddytowPersistence hyde_eddytowPersistence) {
        this.hyde_eddytowPersistence = hyde_eddytowPersistence;
    }

    /**
     * Returns the hydemeta local service.
     *
     * @return the hydemeta local service
     */
    public fi.csc.smear.db.service.HydemetaLocalService getHydemetaLocalService() {
        return hydemetaLocalService;
    }

    /**
     * Sets the hydemeta local service.
     *
     * @param hydemetaLocalService the hydemeta local service
     */
    public void setHydemetaLocalService(
        fi.csc.smear.db.service.HydemetaLocalService hydemetaLocalService) {
        this.hydemetaLocalService = hydemetaLocalService;
    }

    /**
     * Returns the hydemeta remote service.
     *
     * @return the hydemeta remote service
     */
    public fi.csc.smear.db.service.HydemetaService getHydemetaService() {
        return hydemetaService;
    }

    /**
     * Sets the hydemeta remote service.
     *
     * @param hydemetaService the hydemeta remote service
     */
    public void setHydemetaService(
        fi.csc.smear.db.service.HydemetaService hydemetaService) {
        this.hydemetaService = hydemetaService;
    }

    /**
     * Returns the hydemeta persistence.
     *
     * @return the hydemeta persistence
     */
    public HydemetaPersistence getHydemetaPersistence() {
        return hydemetaPersistence;
    }

    /**
     * Sets the hydemeta persistence.
     *
     * @param hydemetaPersistence the hydemeta persistence
     */
    public void setHydemetaPersistence(HydemetaPersistence hydemetaPersistence) {
        this.hydemetaPersistence = hydemetaPersistence;
    }

    /**
     * Returns the hyy_eddysub local service.
     *
     * @return the hyy_eddysub local service
     */
    public fi.csc.smear.db.service.Hyy_eddysubLocalService getHyy_eddysubLocalService() {
        return hyy_eddysubLocalService;
    }

    /**
     * Sets the hyy_eddysub local service.
     *
     * @param hyy_eddysubLocalService the hyy_eddysub local service
     */
    public void setHyy_eddysubLocalService(
        fi.csc.smear.db.service.Hyy_eddysubLocalService hyy_eddysubLocalService) {
        this.hyy_eddysubLocalService = hyy_eddysubLocalService;
    }

    /**
     * Returns the hyy_eddysub remote service.
     *
     * @return the hyy_eddysub remote service
     */
    public fi.csc.smear.db.service.Hyy_eddysubService getHyy_eddysubService() {
        return hyy_eddysubService;
    }

    /**
     * Sets the hyy_eddysub remote service.
     *
     * @param hyy_eddysubService the hyy_eddysub remote service
     */
    public void setHyy_eddysubService(
        fi.csc.smear.db.service.Hyy_eddysubService hyy_eddysubService) {
        this.hyy_eddysubService = hyy_eddysubService;
    }

    /**
     * Returns the hyy_eddysub persistence.
     *
     * @return the hyy_eddysub persistence
     */
    public Hyy_eddysubPersistence getHyy_eddysubPersistence() {
        return hyy_eddysubPersistence;
    }

    /**
     * Sets the hyy_eddysub persistence.
     *
     * @param hyy_eddysubPersistence the hyy_eddysub persistence
     */
    public void setHyy_eddysubPersistence(
        Hyy_eddysubPersistence hyy_eddysubPersistence) {
        this.hyy_eddysubPersistence = hyy_eddysubPersistence;
    }

    /**
     * Returns the hyy aero local service.
     *
     * @return the hyy aero local service
     */
    public fi.csc.smear.db.service.HyyAeroLocalService getHyyAeroLocalService() {
        return hyyAeroLocalService;
    }

    /**
     * Sets the hyy aero local service.
     *
     * @param hyyAeroLocalService the hyy aero local service
     */
    public void setHyyAeroLocalService(
        fi.csc.smear.db.service.HyyAeroLocalService hyyAeroLocalService) {
        this.hyyAeroLocalService = hyyAeroLocalService;
    }

    /**
     * Returns the hyy aero remote service.
     *
     * @return the hyy aero remote service
     */
    public fi.csc.smear.db.service.HyyAeroService getHyyAeroService() {
        return hyyAeroService;
    }

    /**
     * Sets the hyy aero remote service.
     *
     * @param hyyAeroService the hyy aero remote service
     */
    public void setHyyAeroService(
        fi.csc.smear.db.service.HyyAeroService hyyAeroService) {
        this.hyyAeroService = hyyAeroService;
    }

    /**
     * Returns the hyy aero persistence.
     *
     * @return the hyy aero persistence
     */
    public HyyAeroPersistence getHyyAeroPersistence() {
        return hyyAeroPersistence;
    }

    /**
     * Sets the hyy aero persistence.
     *
     * @param hyyAeroPersistence the hyy aero persistence
     */
    public void setHyyAeroPersistence(HyyAeroPersistence hyyAeroPersistence) {
        this.hyyAeroPersistence = hyyAeroPersistence;
    }

    /**
     * Returns the hyy d m p s local service.
     *
     * @return the hyy d m p s local service
     */
    public fi.csc.smear.db.service.HyyDMPSLocalService getHyyDMPSLocalService() {
        return hyyDMPSLocalService;
    }

    /**
     * Sets the hyy d m p s local service.
     *
     * @param hyyDMPSLocalService the hyy d m p s local service
     */
    public void setHyyDMPSLocalService(
        fi.csc.smear.db.service.HyyDMPSLocalService hyyDMPSLocalService) {
        this.hyyDMPSLocalService = hyyDMPSLocalService;
    }

    /**
     * Returns the hyy d m p s remote service.
     *
     * @return the hyy d m p s remote service
     */
    public fi.csc.smear.db.service.HyyDMPSService getHyyDMPSService() {
        return hyyDMPSService;
    }

    /**
     * Sets the hyy d m p s remote service.
     *
     * @param hyyDMPSService the hyy d m p s remote service
     */
    public void setHyyDMPSService(
        fi.csc.smear.db.service.HyyDMPSService hyyDMPSService) {
        this.hyyDMPSService = hyyDMPSService;
    }

    /**
     * Returns the hyy d m p s persistence.
     *
     * @return the hyy d m p s persistence
     */
    public HyyDMPSPersistence getHyyDMPSPersistence() {
        return hyyDMPSPersistence;
    }

    /**
     * Sets the hyy d m p s persistence.
     *
     * @param hyyDMPSPersistence the hyy d m p s persistence
     */
    public void setHyyDMPSPersistence(HyyDMPSPersistence hyyDMPSPersistence) {
        this.hyyDMPSPersistence = hyyDMPSPersistence;
    }

    /**
     * Returns the kumpula_eddy local service.
     *
     * @return the kumpula_eddy local service
     */
    public fi.csc.smear.db.service.Kumpula_eddyLocalService getKumpula_eddyLocalService() {
        return kumpula_eddyLocalService;
    }

    /**
     * Sets the kumpula_eddy local service.
     *
     * @param kumpula_eddyLocalService the kumpula_eddy local service
     */
    public void setKumpula_eddyLocalService(
        fi.csc.smear.db.service.Kumpula_eddyLocalService kumpula_eddyLocalService) {
        this.kumpula_eddyLocalService = kumpula_eddyLocalService;
    }

    /**
     * Returns the kumpula_eddy remote service.
     *
     * @return the kumpula_eddy remote service
     */
    public fi.csc.smear.db.service.Kumpula_eddyService getKumpula_eddyService() {
        return kumpula_eddyService;
    }

    /**
     * Sets the kumpula_eddy remote service.
     *
     * @param kumpula_eddyService the kumpula_eddy remote service
     */
    public void setKumpula_eddyService(
        fi.csc.smear.db.service.Kumpula_eddyService kumpula_eddyService) {
        this.kumpula_eddyService = kumpula_eddyService;
    }

    /**
     * Returns the kumpula_eddy persistence.
     *
     * @return the kumpula_eddy persistence
     */
    public Kumpula_eddyPersistence getKumpula_eddyPersistence() {
        return kumpula_eddyPersistence;
    }

    /**
     * Sets the kumpula_eddy persistence.
     *
     * @param kumpula_eddyPersistence the kumpula_eddy persistence
     */
    public void setKumpula_eddyPersistence(
        Kumpula_eddyPersistence kumpula_eddyPersistence) {
        this.kumpula_eddyPersistence = kumpula_eddyPersistence;
    }

    /**
     * Returns the kumpula d m p s local service.
     *
     * @return the kumpula d m p s local service
     */
    public fi.csc.smear.db.service.KumpulaDMPSLocalService getKumpulaDMPSLocalService() {
        return kumpulaDMPSLocalService;
    }

    /**
     * Sets the kumpula d m p s local service.
     *
     * @param kumpulaDMPSLocalService the kumpula d m p s local service
     */
    public void setKumpulaDMPSLocalService(
        fi.csc.smear.db.service.KumpulaDMPSLocalService kumpulaDMPSLocalService) {
        this.kumpulaDMPSLocalService = kumpulaDMPSLocalService;
    }

    /**
     * Returns the kumpula d m p s remote service.
     *
     * @return the kumpula d m p s remote service
     */
    public fi.csc.smear.db.service.KumpulaDMPSService getKumpulaDMPSService() {
        return kumpulaDMPSService;
    }

    /**
     * Sets the kumpula d m p s remote service.
     *
     * @param kumpulaDMPSService the kumpula d m p s remote service
     */
    public void setKumpulaDMPSService(
        fi.csc.smear.db.service.KumpulaDMPSService kumpulaDMPSService) {
        this.kumpulaDMPSService = kumpulaDMPSService;
    }

    /**
     * Returns the kumpula d m p s persistence.
     *
     * @return the kumpula d m p s persistence
     */
    public KumpulaDMPSPersistence getKumpulaDMPSPersistence() {
        return kumpulaDMPSPersistence;
    }

    /**
     * Sets the kumpula d m p s persistence.
     *
     * @param kumpulaDMPSPersistence the kumpula d m p s persistence
     */
    public void setKumpulaDMPSPersistence(
        KumpulaDMPSPersistence kumpulaDMPSPersistence) {
        this.kumpulaDMPSPersistence = kumpulaDMPSPersistence;
    }

    /**
     * Returns the kumpulameta local service.
     *
     * @return the kumpulameta local service
     */
    public fi.csc.smear.db.service.KumpulametaLocalService getKumpulametaLocalService() {
        return kumpulametaLocalService;
    }

    /**
     * Sets the kumpulameta local service.
     *
     * @param kumpulametaLocalService the kumpulameta local service
     */
    public void setKumpulametaLocalService(
        fi.csc.smear.db.service.KumpulametaLocalService kumpulametaLocalService) {
        this.kumpulametaLocalService = kumpulametaLocalService;
    }

    /**
     * Returns the kumpulameta remote service.
     *
     * @return the kumpulameta remote service
     */
    public fi.csc.smear.db.service.KumpulametaService getKumpulametaService() {
        return kumpulametaService;
    }

    /**
     * Sets the kumpulameta remote service.
     *
     * @param kumpulametaService the kumpulameta remote service
     */
    public void setKumpulametaService(
        fi.csc.smear.db.service.KumpulametaService kumpulametaService) {
        this.kumpulametaService = kumpulametaService;
    }

    /**
     * Returns the kumpulameta persistence.
     *
     * @return the kumpulameta persistence
     */
    public KumpulametaPersistence getKumpulametaPersistence() {
        return kumpulametaPersistence;
    }

    /**
     * Sets the kumpulameta persistence.
     *
     * @param kumpulametaPersistence the kumpulameta persistence
     */
    public void setKumpulametaPersistence(
        KumpulametaPersistence kumpulametaPersistence) {
        this.kumpulametaPersistence = kumpulametaPersistence;
    }

    /**
     * Returns the kvj eddy local service.
     *
     * @return the kvj eddy local service
     */
    public fi.csc.smear.db.service.kvjEddyLocalService getkvjEddyLocalService() {
        return kvjEddyLocalService;
    }

    /**
     * Sets the kvj eddy local service.
     *
     * @param kvjEddyLocalService the kvj eddy local service
     */
    public void setkvjEddyLocalService(
        fi.csc.smear.db.service.kvjEddyLocalService kvjEddyLocalService) {
        this.kvjEddyLocalService = kvjEddyLocalService;
    }

    /**
     * Returns the kvj eddy remote service.
     *
     * @return the kvj eddy remote service
     */
    public fi.csc.smear.db.service.kvjEddyService getkvjEddyService() {
        return kvjEddyService;
    }

    /**
     * Sets the kvj eddy remote service.
     *
     * @param kvjEddyService the kvj eddy remote service
     */
    public void setkvjEddyService(
        fi.csc.smear.db.service.kvjEddyService kvjEddyService) {
        this.kvjEddyService = kvjEddyService;
    }

    /**
     * Returns the kvj eddy persistence.
     *
     * @return the kvj eddy persistence
     */
    public kvjEddyPersistence getkvjEddyPersistence() {
        return kvjEddyPersistence;
    }

    /**
     * Sets the kvj eddy persistence.
     *
     * @param kvjEddyPersistence the kvj eddy persistence
     */
    public void setkvjEddyPersistence(kvjEddyPersistence kvjEddyPersistence) {
        this.kvjEddyPersistence = kvjEddyPersistence;
    }

    /**
     * Returns the sii1eddy local service.
     *
     * @return the sii1eddy local service
     */
    public fi.csc.smear.db.service.Sii1eddyLocalService getSii1eddyLocalService() {
        return sii1eddyLocalService;
    }

    /**
     * Sets the sii1eddy local service.
     *
     * @param sii1eddyLocalService the sii1eddy local service
     */
    public void setSii1eddyLocalService(
        fi.csc.smear.db.service.Sii1eddyLocalService sii1eddyLocalService) {
        this.sii1eddyLocalService = sii1eddyLocalService;
    }

    /**
     * Returns the sii1eddy remote service.
     *
     * @return the sii1eddy remote service
     */
    public fi.csc.smear.db.service.Sii1eddyService getSii1eddyService() {
        return sii1eddyService;
    }

    /**
     * Sets the sii1eddy remote service.
     *
     * @param sii1eddyService the sii1eddy remote service
     */
    public void setSii1eddyService(
        fi.csc.smear.db.service.Sii1eddyService sii1eddyService) {
        this.sii1eddyService = sii1eddyService;
    }

    /**
     * Returns the sii1eddy persistence.
     *
     * @return the sii1eddy persistence
     */
    public Sii1eddyPersistence getSii1eddyPersistence() {
        return sii1eddyPersistence;
    }

    /**
     * Sets the sii1eddy persistence.
     *
     * @param sii1eddyPersistence the sii1eddy persistence
     */
    public void setSii1eddyPersistence(Sii1eddyPersistence sii1eddyPersistence) {
        this.sii1eddyPersistence = sii1eddyPersistence;
    }

    /**
     * Returns the sii1meta local service.
     *
     * @return the sii1meta local service
     */
    public fi.csc.smear.db.service.Sii1metaLocalService getSii1metaLocalService() {
        return sii1metaLocalService;
    }

    /**
     * Sets the sii1meta local service.
     *
     * @param sii1metaLocalService the sii1meta local service
     */
    public void setSii1metaLocalService(
        fi.csc.smear.db.service.Sii1metaLocalService sii1metaLocalService) {
        this.sii1metaLocalService = sii1metaLocalService;
    }

    /**
     * Returns the sii1meta remote service.
     *
     * @return the sii1meta remote service
     */
    public fi.csc.smear.db.service.Sii1metaService getSii1metaService() {
        return sii1metaService;
    }

    /**
     * Sets the sii1meta remote service.
     *
     * @param sii1metaService the sii1meta remote service
     */
    public void setSii1metaService(
        fi.csc.smear.db.service.Sii1metaService sii1metaService) {
        this.sii1metaService = sii1metaService;
    }

    /**
     * Returns the sii1meta persistence.
     *
     * @return the sii1meta persistence
     */
    public Sii1metaPersistence getSii1metaPersistence() {
        return sii1metaPersistence;
    }

    /**
     * Sets the sii1meta persistence.
     *
     * @param sii1metaPersistence the sii1meta persistence
     */
    public void setSii1metaPersistence(Sii1metaPersistence sii1metaPersistence) {
        this.sii1metaPersistence = sii1metaPersistence;
    }

    /**
     * Returns the sii2eddy local service.
     *
     * @return the sii2eddy local service
     */
    public fi.csc.smear.db.service.Sii2eddyLocalService getSii2eddyLocalService() {
        return sii2eddyLocalService;
    }

    /**
     * Sets the sii2eddy local service.
     *
     * @param sii2eddyLocalService the sii2eddy local service
     */
    public void setSii2eddyLocalService(
        fi.csc.smear.db.service.Sii2eddyLocalService sii2eddyLocalService) {
        this.sii2eddyLocalService = sii2eddyLocalService;
    }

    /**
     * Returns the sii2eddy remote service.
     *
     * @return the sii2eddy remote service
     */
    public fi.csc.smear.db.service.Sii2eddyService getSii2eddyService() {
        return sii2eddyService;
    }

    /**
     * Sets the sii2eddy remote service.
     *
     * @param sii2eddyService the sii2eddy remote service
     */
    public void setSii2eddyService(
        fi.csc.smear.db.service.Sii2eddyService sii2eddyService) {
        this.sii2eddyService = sii2eddyService;
    }

    /**
     * Returns the sii2eddy persistence.
     *
     * @return the sii2eddy persistence
     */
    public Sii2eddyPersistence getSii2eddyPersistence() {
        return sii2eddyPersistence;
    }

    /**
     * Sets the sii2eddy persistence.
     *
     * @param sii2eddyPersistence the sii2eddy persistence
     */
    public void setSii2eddyPersistence(Sii2eddyPersistence sii2eddyPersistence) {
        this.sii2eddyPersistence = sii2eddyPersistence;
    }

    /**
     * Returns the sii2meta local service.
     *
     * @return the sii2meta local service
     */
    public fi.csc.smear.db.service.Sii2metaLocalService getSii2metaLocalService() {
        return sii2metaLocalService;
    }

    /**
     * Sets the sii2meta local service.
     *
     * @param sii2metaLocalService the sii2meta local service
     */
    public void setSii2metaLocalService(
        fi.csc.smear.db.service.Sii2metaLocalService sii2metaLocalService) {
        this.sii2metaLocalService = sii2metaLocalService;
    }

    /**
     * Returns the sii2meta remote service.
     *
     * @return the sii2meta remote service
     */
    public fi.csc.smear.db.service.Sii2metaService getSii2metaService() {
        return sii2metaService;
    }

    /**
     * Sets the sii2meta remote service.
     *
     * @param sii2metaService the sii2meta remote service
     */
    public void setSii2metaService(
        fi.csc.smear.db.service.Sii2metaService sii2metaService) {
        this.sii2metaService = sii2metaService;
    }

    /**
     * Returns the sii2meta persistence.
     *
     * @return the sii2meta persistence
     */
    public Sii2metaPersistence getSii2metaPersistence() {
        return sii2metaPersistence;
    }

    /**
     * Sets the sii2meta persistence.
     *
     * @param sii2metaPersistence the sii2meta persistence
     */
    public void setSii2metaPersistence(Sii2metaPersistence sii2metaPersistence) {
        this.sii2metaPersistence = sii2metaPersistence;
    }

    /**
     * Returns the smear events local service.
     *
     * @return the smear events local service
     */
    public fi.csc.smear.db.service.SmearEventsLocalService getSmearEventsLocalService() {
        return smearEventsLocalService;
    }

    /**
     * Sets the smear events local service.
     *
     * @param smearEventsLocalService the smear events local service
     */
    public void setSmearEventsLocalService(
        fi.csc.smear.db.service.SmearEventsLocalService smearEventsLocalService) {
        this.smearEventsLocalService = smearEventsLocalService;
    }

    /**
     * Returns the smear events remote service.
     *
     * @return the smear events remote service
     */
    public fi.csc.smear.db.service.SmearEventsService getSmearEventsService() {
        return smearEventsService;
    }

    /**
     * Sets the smear events remote service.
     *
     * @param smearEventsService the smear events remote service
     */
    public void setSmearEventsService(
        fi.csc.smear.db.service.SmearEventsService smearEventsService) {
        this.smearEventsService = smearEventsService;
    }

    /**
     * Returns the smear events persistence.
     *
     * @return the smear events persistence
     */
    public SmearEventsPersistence getSmearEventsPersistence() {
        return smearEventsPersistence;
    }

    /**
     * Sets the smear events persistence.
     *
     * @param smearEventsPersistence the smear events persistence
     */
    public void setSmearEventsPersistence(
        SmearEventsPersistence smearEventsPersistence) {
        this.smearEventsPersistence = smearEventsPersistence;
    }

    /**
     * Returns the smearmetadata local service.
     *
     * @return the smearmetadata local service
     */
    public fi.csc.smear.db.service.SmearmetadataLocalService getSmearmetadataLocalService() {
        return smearmetadataLocalService;
    }

    /**
     * Sets the smearmetadata local service.
     *
     * @param smearmetadataLocalService the smearmetadata local service
     */
    public void setSmearmetadataLocalService(
        fi.csc.smear.db.service.SmearmetadataLocalService smearmetadataLocalService) {
        this.smearmetadataLocalService = smearmetadataLocalService;
    }

    /**
     * Returns the smearmetadata remote service.
     *
     * @return the smearmetadata remote service
     */
    public fi.csc.smear.db.service.SmearmetadataService getSmearmetadataService() {
        return smearmetadataService;
    }

    /**
     * Sets the smearmetadata remote service.
     *
     * @param smearmetadataService the smearmetadata remote service
     */
    public void setSmearmetadataService(
        fi.csc.smear.db.service.SmearmetadataService smearmetadataService) {
        this.smearmetadataService = smearmetadataService;
    }

    /**
     * Returns the smearmetadata persistence.
     *
     * @return the smearmetadata persistence
     */
    public SmearmetadataPersistence getSmearmetadataPersistence() {
        return smearmetadataPersistence;
    }

    /**
     * Sets the smearmetadata persistence.
     *
     * @param smearmetadataPersistence the smearmetadata persistence
     */
    public void setSmearmetadataPersistence(
        SmearmetadataPersistence smearmetadataPersistence) {
        this.smearmetadataPersistence = smearmetadataPersistence;
    }

    /**
     * Returns the smearstation local service.
     *
     * @return the smearstation local service
     */
    public fi.csc.smear.db.service.SmearstationLocalService getSmearstationLocalService() {
        return smearstationLocalService;
    }

    /**
     * Sets the smearstation local service.
     *
     * @param smearstationLocalService the smearstation local service
     */
    public void setSmearstationLocalService(
        fi.csc.smear.db.service.SmearstationLocalService smearstationLocalService) {
        this.smearstationLocalService = smearstationLocalService;
    }

    /**
     * Returns the smearstation remote service.
     *
     * @return the smearstation remote service
     */
    public fi.csc.smear.db.service.SmearstationService getSmearstationService() {
        return smearstationService;
    }

    /**
     * Sets the smearstation remote service.
     *
     * @param smearstationService the smearstation remote service
     */
    public void setSmearstationService(
        fi.csc.smear.db.service.SmearstationService smearstationService) {
        this.smearstationService = smearstationService;
    }

    /**
     * Returns the smearstation persistence.
     *
     * @return the smearstation persistence
     */
    public SmearstationPersistence getSmearstationPersistence() {
        return smearstationPersistence;
    }

    /**
     * Sets the smearstation persistence.
     *
     * @param smearstationPersistence the smearstation persistence
     */
    public void setSmearstationPersistence(
        SmearstationPersistence smearstationPersistence) {
        this.smearstationPersistence = smearstationPersistence;
    }

    /**
     * Returns the smear table metadata local service.
     *
     * @return the smear table metadata local service
     */
    public fi.csc.smear.db.service.SmearTableMetadataLocalService getSmearTableMetadataLocalService() {
        return smearTableMetadataLocalService;
    }

    /**
     * Sets the smear table metadata local service.
     *
     * @param smearTableMetadataLocalService the smear table metadata local service
     */
    public void setSmearTableMetadataLocalService(
        fi.csc.smear.db.service.SmearTableMetadataLocalService smearTableMetadataLocalService) {
        this.smearTableMetadataLocalService = smearTableMetadataLocalService;
    }

    /**
     * Returns the smear table metadata remote service.
     *
     * @return the smear table metadata remote service
     */
    public fi.csc.smear.db.service.SmearTableMetadataService getSmearTableMetadataService() {
        return smearTableMetadataService;
    }

    /**
     * Sets the smear table metadata remote service.
     *
     * @param smearTableMetadataService the smear table metadata remote service
     */
    public void setSmearTableMetadataService(
        fi.csc.smear.db.service.SmearTableMetadataService smearTableMetadataService) {
        this.smearTableMetadataService = smearTableMetadataService;
    }

    /**
     * Returns the smear table metadata persistence.
     *
     * @return the smear table metadata persistence
     */
    public SmearTableMetadataPersistence getSmearTableMetadataPersistence() {
        return smearTableMetadataPersistence;
    }

    /**
     * Sets the smear table metadata persistence.
     *
     * @param smearTableMetadataPersistence the smear table metadata persistence
     */
    public void setSmearTableMetadataPersistence(
        SmearTableMetadataPersistence smearTableMetadataPersistence) {
        this.smearTableMetadataPersistence = smearTableMetadataPersistence;
    }

    /**
     * Returns the smear tags local service.
     *
     * @return the smear tags local service
     */
    public fi.csc.smear.db.service.SmearTagsLocalService getSmearTagsLocalService() {
        return smearTagsLocalService;
    }

    /**
     * Sets the smear tags local service.
     *
     * @param smearTagsLocalService the smear tags local service
     */
    public void setSmearTagsLocalService(
        fi.csc.smear.db.service.SmearTagsLocalService smearTagsLocalService) {
        this.smearTagsLocalService = smearTagsLocalService;
    }

    /**
     * Returns the smear tags remote service.
     *
     * @return the smear tags remote service
     */
    public fi.csc.smear.db.service.SmearTagsService getSmearTagsService() {
        return smearTagsService;
    }

    /**
     * Sets the smear tags remote service.
     *
     * @param smearTagsService the smear tags remote service
     */
    public void setSmearTagsService(
        fi.csc.smear.db.service.SmearTagsService smearTagsService) {
        this.smearTagsService = smearTagsService;
    }

    /**
     * Returns the smear tags persistence.
     *
     * @return the smear tags persistence
     */
    public SmearTagsPersistence getSmearTagsPersistence() {
        return smearTagsPersistence;
    }

    /**
     * Sets the smear tags persistence.
     *
     * @param smearTagsPersistence the smear tags persistence
     */
    public void setSmearTagsPersistence(
        SmearTagsPersistence smearTagsPersistence) {
        this.smearTagsPersistence = smearTagsPersistence;
    }

    /**
     * Returns the smearvariable event local service.
     *
     * @return the smearvariable event local service
     */
    public fi.csc.smear.db.service.SmearvariableEventLocalService getSmearvariableEventLocalService() {
        return smearvariableEventLocalService;
    }

    /**
     * Sets the smearvariable event local service.
     *
     * @param smearvariableEventLocalService the smearvariable event local service
     */
    public void setSmearvariableEventLocalService(
        fi.csc.smear.db.service.SmearvariableEventLocalService smearvariableEventLocalService) {
        this.smearvariableEventLocalService = smearvariableEventLocalService;
    }

    /**
     * Returns the smearvariable event persistence.
     *
     * @return the smearvariable event persistence
     */
    public SmearvariableEventPersistence getSmearvariableEventPersistence() {
        return smearvariableEventPersistence;
    }

    /**
     * Sets the smearvariable event persistence.
     *
     * @param smearvariableEventPersistence the smearvariable event persistence
     */
    public void setSmearvariableEventPersistence(
        SmearvariableEventPersistence smearvariableEventPersistence) {
        this.smearvariableEventPersistence = smearvariableEventPersistence;
    }

    /**
     * Returns the smear variable metadata local service.
     *
     * @return the smear variable metadata local service
     */
    public fi.csc.smear.db.service.SmearVariableMetadataLocalService getSmearVariableMetadataLocalService() {
        return smearVariableMetadataLocalService;
    }

    /**
     * Sets the smear variable metadata local service.
     *
     * @param smearVariableMetadataLocalService the smear variable metadata local service
     */
    public void setSmearVariableMetadataLocalService(
        fi.csc.smear.db.service.SmearVariableMetadataLocalService smearVariableMetadataLocalService) {
        this.smearVariableMetadataLocalService = smearVariableMetadataLocalService;
    }

    /**
     * Returns the smear variable metadata remote service.
     *
     * @return the smear variable metadata remote service
     */
    public fi.csc.smear.db.service.SmearVariableMetadataService getSmearVariableMetadataService() {
        return smearVariableMetadataService;
    }

    /**
     * Sets the smear variable metadata remote service.
     *
     * @param smearVariableMetadataService the smear variable metadata remote service
     */
    public void setSmearVariableMetadataService(
        fi.csc.smear.db.service.SmearVariableMetadataService smearVariableMetadataService) {
        this.smearVariableMetadataService = smearVariableMetadataService;
    }

    /**
     * Returns the smear variable metadata persistence.
     *
     * @return the smear variable metadata persistence
     */
    public SmearVariableMetadataPersistence getSmearVariableMetadataPersistence() {
        return smearVariableMetadataPersistence;
    }

    /**
     * Sets the smear variable metadata persistence.
     *
     * @param smearVariableMetadataPersistence the smear variable metadata persistence
     */
    public void setSmearVariableMetadataPersistence(
        SmearVariableMetadataPersistence smearVariableMetadataPersistence) {
        this.smearVariableMetadataPersistence = smearVariableMetadataPersistence;
    }

    /**
     * Returns the smearvariable tags local service.
     *
     * @return the smearvariable tags local service
     */
    public fi.csc.smear.db.service.SmearvariableTagsLocalService getSmearvariableTagsLocalService() {
        return smearvariableTagsLocalService;
    }

    /**
     * Sets the smearvariable tags local service.
     *
     * @param smearvariableTagsLocalService the smearvariable tags local service
     */
    public void setSmearvariableTagsLocalService(
        fi.csc.smear.db.service.SmearvariableTagsLocalService smearvariableTagsLocalService) {
        this.smearvariableTagsLocalService = smearvariableTagsLocalService;
    }

    /**
     * Returns the smearvariable tags remote service.
     *
     * @return the smearvariable tags remote service
     */
    public fi.csc.smear.db.service.SmearvariableTagsService getSmearvariableTagsService() {
        return smearvariableTagsService;
    }

    /**
     * Sets the smearvariable tags remote service.
     *
     * @param smearvariableTagsService the smearvariable tags remote service
     */
    public void setSmearvariableTagsService(
        fi.csc.smear.db.service.SmearvariableTagsService smearvariableTagsService) {
        this.smearvariableTagsService = smearvariableTagsService;
    }

    /**
     * Returns the smearvariable tags persistence.
     *
     * @return the smearvariable tags persistence
     */
    public SmearvariableTagsPersistence getSmearvariableTagsPersistence() {
        return smearvariableTagsPersistence;
    }

    /**
     * Sets the smearvariable tags persistence.
     *
     * @param smearvariableTagsPersistence the smearvariable tags persistence
     */
    public void setSmearvariableTagsPersistence(
        SmearvariableTagsPersistence smearvariableTagsPersistence) {
        this.smearvariableTagsPersistence = smearvariableTagsPersistence;
    }

    /**
     * Returns the towermeta local service.
     *
     * @return the towermeta local service
     */
    public fi.csc.smear.db.service.TowermetaLocalService getTowermetaLocalService() {
        return towermetaLocalService;
    }

    /**
     * Sets the towermeta local service.
     *
     * @param towermetaLocalService the towermeta local service
     */
    public void setTowermetaLocalService(
        fi.csc.smear.db.service.TowermetaLocalService towermetaLocalService) {
        this.towermetaLocalService = towermetaLocalService;
    }

    /**
     * Returns the towermeta remote service.
     *
     * @return the towermeta remote service
     */
    public fi.csc.smear.db.service.TowermetaService getTowermetaService() {
        return towermetaService;
    }

    /**
     * Sets the towermeta remote service.
     *
     * @param towermetaService the towermeta remote service
     */
    public void setTowermetaService(
        fi.csc.smear.db.service.TowermetaService towermetaService) {
        this.towermetaService = towermetaService;
    }

    /**
     * Returns the towermeta persistence.
     *
     * @return the towermeta persistence
     */
    public TowermetaPersistence getTowermetaPersistence() {
        return towermetaPersistence;
    }

    /**
     * Sets the towermeta persistence.
     *
     * @param towermetaPersistence the towermeta persistence
     */
    public void setTowermetaPersistence(
        TowermetaPersistence towermetaPersistence) {
        this.towermetaPersistence = towermetaPersistence;
    }

    /**
     * Returns the var d m p s local service.
     *
     * @return the var d m p s local service
     */
    public fi.csc.smear.db.service.VarDMPSLocalService getVarDMPSLocalService() {
        return varDMPSLocalService;
    }

    /**
     * Sets the var d m p s local service.
     *
     * @param varDMPSLocalService the var d m p s local service
     */
    public void setVarDMPSLocalService(
        fi.csc.smear.db.service.VarDMPSLocalService varDMPSLocalService) {
        this.varDMPSLocalService = varDMPSLocalService;
    }

    /**
     * Returns the var d m p s remote service.
     *
     * @return the var d m p s remote service
     */
    public fi.csc.smear.db.service.VarDMPSService getVarDMPSService() {
        return varDMPSService;
    }

    /**
     * Sets the var d m p s remote service.
     *
     * @param varDMPSService the var d m p s remote service
     */
    public void setVarDMPSService(
        fi.csc.smear.db.service.VarDMPSService varDMPSService) {
        this.varDMPSService = varDMPSService;
    }

    /**
     * Returns the var d m p s persistence.
     *
     * @return the var d m p s persistence
     */
    public VarDMPSPersistence getVarDMPSPersistence() {
        return varDMPSPersistence;
    }

    /**
     * Sets the var d m p s persistence.
     *
     * @param varDMPSPersistence the var d m p s persistence
     */
    public void setVarDMPSPersistence(VarDMPSPersistence varDMPSPersistence) {
        this.varDMPSPersistence = varDMPSPersistence;
    }

    /**
     * Returns the vareddy local service.
     *
     * @return the vareddy local service
     */
    public fi.csc.smear.db.service.VareddyLocalService getVareddyLocalService() {
        return vareddyLocalService;
    }

    /**
     * Sets the vareddy local service.
     *
     * @param vareddyLocalService the vareddy local service
     */
    public void setVareddyLocalService(
        fi.csc.smear.db.service.VareddyLocalService vareddyLocalService) {
        this.vareddyLocalService = vareddyLocalService;
    }

    /**
     * Returns the vareddy remote service.
     *
     * @return the vareddy remote service
     */
    public fi.csc.smear.db.service.VareddyService getVareddyService() {
        return vareddyService;
    }

    /**
     * Sets the vareddy remote service.
     *
     * @param vareddyService the vareddy remote service
     */
    public void setVareddyService(
        fi.csc.smear.db.service.VareddyService vareddyService) {
        this.vareddyService = vareddyService;
    }

    /**
     * Returns the vareddy persistence.
     *
     * @return the vareddy persistence
     */
    public VareddyPersistence getVareddyPersistence() {
        return vareddyPersistence;
    }

    /**
     * Sets the vareddy persistence.
     *
     * @param vareddyPersistence the vareddy persistence
     */
    public void setVareddyPersistence(VareddyPersistence vareddyPersistence) {
        this.vareddyPersistence = vareddyPersistence;
    }

    /**
     * Returns the varrio_tree local service.
     *
     * @return the varrio_tree local service
     */
    public fi.csc.smear.db.service.Varrio_treeLocalService getVarrio_treeLocalService() {
        return varrio_treeLocalService;
    }

    /**
     * Sets the varrio_tree local service.
     *
     * @param varrio_treeLocalService the varrio_tree local service
     */
    public void setVarrio_treeLocalService(
        fi.csc.smear.db.service.Varrio_treeLocalService varrio_treeLocalService) {
        this.varrio_treeLocalService = varrio_treeLocalService;
    }

    /**
     * Returns the varrio_tree remote service.
     *
     * @return the varrio_tree remote service
     */
    public fi.csc.smear.db.service.Varrio_treeService getVarrio_treeService() {
        return varrio_treeService;
    }

    /**
     * Sets the varrio_tree remote service.
     *
     * @param varrio_treeService the varrio_tree remote service
     */
    public void setVarrio_treeService(
        fi.csc.smear.db.service.Varrio_treeService varrio_treeService) {
        this.varrio_treeService = varrio_treeService;
    }

    /**
     * Returns the varrio_tree persistence.
     *
     * @return the varrio_tree persistence
     */
    public Varrio_treePersistence getVarrio_treePersistence() {
        return varrio_treePersistence;
    }

    /**
     * Sets the varrio_tree persistence.
     *
     * @param varrio_treePersistence the varrio_tree persistence
     */
    public void setVarrio_treePersistence(
        Varrio_treePersistence varrio_treePersistence) {
        this.varrio_treePersistence = varrio_treePersistence;
    }

    /**
     * Returns the varriometa local service.
     *
     * @return the varriometa local service
     */
    public fi.csc.smear.db.service.VarriometaLocalService getVarriometaLocalService() {
        return varriometaLocalService;
    }

    /**
     * Sets the varriometa local service.
     *
     * @param varriometaLocalService the varriometa local service
     */
    public void setVarriometaLocalService(
        fi.csc.smear.db.service.VarriometaLocalService varriometaLocalService) {
        this.varriometaLocalService = varriometaLocalService;
    }

    /**
     * Returns the varriometa remote service.
     *
     * @return the varriometa remote service
     */
    public fi.csc.smear.db.service.VarriometaService getVarriometaService() {
        return varriometaService;
    }

    /**
     * Sets the varriometa remote service.
     *
     * @param varriometaService the varriometa remote service
     */
    public void setVarriometaService(
        fi.csc.smear.db.service.VarriometaService varriometaService) {
        this.varriometaService = varriometaService;
    }

    /**
     * Returns the varriometa persistence.
     *
     * @return the varriometa persistence
     */
    public VarriometaPersistence getVarriometaPersistence() {
        return varriometaPersistence;
    }

    /**
     * Sets the varriometa persistence.
     *
     * @param varriometaPersistence the varriometa persistence
     */
    public void setVarriometaPersistence(
        VarriometaPersistence varriometaPersistence) {
        this.varriometaPersistence = varriometaPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("fi.csc.smear.db.model.SmearvariableEvent",
            smearvariableEventLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "fi.csc.smear.db.model.SmearvariableEvent");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return SmearvariableEvent.class;
    }

    protected String getModelClassName() {
        return SmearvariableEvent.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = smearvariableEventPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
