package fi.csc.smear.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Hydemeta service. Represents a row in the &quot;HYY_META&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.smear.db.model.impl.HydemetaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.smear.db.model.impl.HydemetaImpl}.
 * </p>
 *
 * @author pj
 * @see Hydemeta
 * @see fi.csc.smear.db.model.impl.HydemetaImpl
 * @see fi.csc.smear.db.model.impl.HydemetaModelImpl
 * @generated
 */
public interface HydemetaModel extends BaseModel<Hydemeta> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a hydemeta model instance should use the {@link Hydemeta} interface instead.
     */

    /**
     * Returns the primary key of this hydemeta.
     *
     * @return the primary key of this hydemeta
     */
    public java.util.Date getPrimaryKey();

    /**
     * Sets the primary key of this hydemeta.
     *
     * @param primaryKey the primary key of this hydemeta
     */
    public void setPrimaryKey(java.util.Date primaryKey);

    /**
     * Returns the samptime of this hydemeta.
     *
     * @return the samptime of this hydemeta
     */
    public Date getSamptime();

    /**
     * Sets the samptime of this hydemeta.
     *
     * @param samptime the samptime of this hydemeta
     */
    public void setSamptime(Date samptime);

    /**
     * Returns the u v_ a of this hydemeta.
     *
     * @return the u v_ a of this hydemeta
     */
    public float getUV_A();

    /**
     * Sets the u v_ a of this hydemeta.
     *
     * @param UV_A the u v_ a of this hydemeta
     */
    public void setUV_A(float UV_A);

    /**
     * Returns the u v_ b of this hydemeta.
     *
     * @return the u v_ b of this hydemeta
     */
    public float getUV_B();

    /**
     * Sets the u v_ b of this hydemeta.
     *
     * @param UV_B the u v_ b of this hydemeta
     */
    public void setUV_B(float UV_B);

    /**
     * Returns the diff p a r of this hydemeta.
     *
     * @return the diff p a r of this hydemeta
     */
    public float getDiffPAR();

    /**
     * Sets the diff p a r of this hydemeta.
     *
     * @param diffPAR the diff p a r of this hydemeta
     */
    public void setDiffPAR(float diffPAR);

    /**
     * Returns the diff g l o b of this hydemeta.
     *
     * @return the diff g l o b of this hydemeta
     */
    public float getDiffGLOB();

    /**
     * Sets the diff g l o b of this hydemeta.
     *
     * @param diffGLOB the diff g l o b of this hydemeta
     */
    public void setDiffGLOB(float diffGLOB);

    /**
     * Returns the dir g l o b of this hydemeta.
     *
     * @return the dir g l o b of this hydemeta
     */
    public float getDirGLOB();

    /**
     * Sets the dir g l o b of this hydemeta.
     *
     * @param dirGLOB the dir g l o b of this hydemeta
     */
    public void setDirGLOB(float dirGLOB);

    /**
     * Returns the net of this hydemeta.
     *
     * @return the net of this hydemeta
     */
    public float getNet();

    /**
     * Sets the net of this hydemeta.
     *
     * @param Net the net of this hydemeta
     */
    public void setNet(float Net);

    /**
     * Returns the r glob of this hydemeta.
     *
     * @return the r glob of this hydemeta
     */
    public float getRGlob();

    /**
     * Sets the r glob of this hydemeta.
     *
     * @param RGlob the r glob of this hydemeta
     */
    public void setRGlob(float RGlob);

    /**
     * Returns the glob of this hydemeta.
     *
     * @return the glob of this hydemeta
     */
    public float getGlob();

    /**
     * Sets the glob of this hydemeta.
     *
     * @param Glob the glob of this hydemeta
     */
    public void setGlob(float Glob);

    /**
     * Returns the r p a r of this hydemeta.
     *
     * @return the r p a r of this hydemeta
     */
    public float getRPAR();

    /**
     * Sets the r p a r of this hydemeta.
     *
     * @param RPAR the r p a r of this hydemeta
     */
    public void setRPAR(float RPAR);

    /**
     * Returns the p a r of this hydemeta.
     *
     * @return the p a r of this hydemeta
     */
    public float getPAR();

    /**
     * Sets the p a r of this hydemeta.
     *
     * @param PAR the p a r of this hydemeta
     */
    public void setPAR(float PAR);

    /**
     * Returns the dir p a r of this hydemeta.
     *
     * @return the dir p a r of this hydemeta
     */
    public float getDirPAR();

    /**
     * Sets the dir p a r of this hydemeta.
     *
     * @param dirPAR the dir p a r of this hydemeta
     */
    public void setDirPAR(float dirPAR);

    /**
     * Returns the can i r of this hydemeta.
     *
     * @return the can i r of this hydemeta
     */
    public float getCanIR();

    /**
     * Sets the can i r of this hydemeta.
     *
     * @param canIR the can i r of this hydemeta
     */
    public void setCanIR(float canIR);

    /**
     * Returns the sky i r of this hydemeta.
     *
     * @return the sky i r of this hydemeta
     */
    public float getSkyIR();

    /**
     * Sets the sky i r of this hydemeta.
     *
     * @param skyIR the sky i r of this hydemeta
     */
    public void setSkyIR(float skyIR);

    /**
     * Returns the precip of this hydemeta.
     *
     * @return the precip of this hydemeta
     */
    public float getPrecip();

    /**
     * Sets the precip of this hydemeta.
     *
     * @param Precip the precip of this hydemeta
     */
    public void setPrecip(float Precip);

    /**
     * Returns the s w s of this hydemeta.
     *
     * @return the s w s of this hydemeta
     */
    public float getSWS();

    /**
     * Sets the s w s of this hydemeta.
     *
     * @param SWS the s w s of this hydemeta
     */
    public void setSWS(float SWS);

    /**
     * Returns the td of this hydemeta.
     *
     * @return the td of this hydemeta
     */
    public float getTd();

    /**
     * Sets the td of this hydemeta.
     *
     * @param Td the td of this hydemeta
     */
    public void setTd(float Td);

    /**
     * Returns the pamb0 of this hydemeta.
     *
     * @return the pamb0 of this hydemeta
     */
    public float getPamb0();

    /**
     * Sets the pamb0 of this hydemeta.
     *
     * @param Pamb0 the pamb0 of this hydemeta
     */
    public void setPamb0(float Pamb0);

    /**
     * Returns the t672 of this hydemeta.
     *
     * @return the t672 of this hydemeta
     */
    public float getT672();

    /**
     * Sets the t672 of this hydemeta.
     *
     * @param T672 the t672 of this hydemeta
     */
    public void setT672(float T672);

    /**
     * Returns the t504 of this hydemeta.
     *
     * @return the t504 of this hydemeta
     */
    public float getT504();

    /**
     * Sets the t504 of this hydemeta.
     *
     * @param T504 the t504 of this hydemeta
     */
    public void setT504(float T504);

    /**
     * Returns the t336 of this hydemeta.
     *
     * @return the t336 of this hydemeta
     */
    public float getT336();

    /**
     * Sets the t336 of this hydemeta.
     *
     * @param T336 the t336 of this hydemeta
     */
    public void setT336(float T336);

    /**
     * Returns the t168 of this hydemeta.
     *
     * @return the t168 of this hydemeta
     */
    public float getT168();

    /**
     * Sets the t168 of this hydemeta.
     *
     * @param T168 the t168 of this hydemeta
     */
    public void setT168(float T168);

    /**
     * Returns the t84 of this hydemeta.
     *
     * @return the t84 of this hydemeta
     */
    public float getT84();

    /**
     * Sets the t84 of this hydemeta.
     *
     * @param T84 the t84 of this hydemeta
     */
    public void setT84(float T84);

    /**
     * Returns the t42 of this hydemeta.
     *
     * @return the t42 of this hydemeta
     */
    public float getT42();

    /**
     * Sets the t42 of this hydemeta.
     *
     * @param T42 the t42 of this hydemeta
     */
    public void setT42(float T42);

    /**
     * Returns the w s672 of this hydemeta.
     *
     * @return the w s672 of this hydemeta
     */
    public float getWS672();

    /**
     * Sets the w s672 of this hydemeta.
     *
     * @param WS672 the w s672 of this hydemeta
     */
    public void setWS672(float WS672);

    /**
     * Returns the w s504 of this hydemeta.
     *
     * @return the w s504 of this hydemeta
     */
    public float getWS504();

    /**
     * Sets the w s504 of this hydemeta.
     *
     * @param WS504 the w s504 of this hydemeta
     */
    public void setWS504(float WS504);

    /**
     * Returns the w s336 of this hydemeta.
     *
     * @return the w s336 of this hydemeta
     */
    public float getWS336();

    /**
     * Sets the w s336 of this hydemeta.
     *
     * @param WS336 the w s336 of this hydemeta
     */
    public void setWS336(float WS336);

    /**
     * Returns the w s168 of this hydemeta.
     *
     * @return the w s168 of this hydemeta
     */
    public float getWS168();

    /**
     * Sets the w s168 of this hydemeta.
     *
     * @param WS168 the w s168 of this hydemeta
     */
    public void setWS168(float WS168);

    /**
     * Returns the w s84 of this hydemeta.
     *
     * @return the w s84 of this hydemeta
     */
    public float getWS84();

    /**
     * Sets the w s84 of this hydemeta.
     *
     * @param WS84 the w s84 of this hydemeta
     */
    public void setWS84(float WS84);

    /**
     * Returns the w s42 of this hydemeta.
     *
     * @return the w s42 of this hydemeta
     */
    public float getWS42();

    /**
     * Sets the w s42 of this hydemeta.
     *
     * @param WS42 the w s42 of this hydemeta
     */
    public void setWS42(float WS42);

    /**
     * Returns the w s u740 of this hydemeta.
     *
     * @return the w s u740 of this hydemeta
     */
    public float getWSU740();

    /**
     * Sets the w s u740 of this hydemeta.
     *
     * @param WSU740 the w s u740 of this hydemeta
     */
    public void setWSU740(float WSU740);

    /**
     * Returns the w s u336 of this hydemeta.
     *
     * @return the w s u336 of this hydemeta
     */
    public float getWSU336();

    /**
     * Sets the w s u336 of this hydemeta.
     *
     * @param WSU336 the w s u336 of this hydemeta
     */
    public void setWSU336(float WSU336);

    /**
     * Returns the w s u168 of this hydemeta.
     *
     * @return the w s u168 of this hydemeta
     */
    public float getWSU168();

    /**
     * Sets the w s u168 of this hydemeta.
     *
     * @param WSU168 the w s u168 of this hydemeta
     */
    public void setWSU168(float WSU168);

    /**
     * Returns the w s u84 of this hydemeta.
     *
     * @return the w s u84 of this hydemeta
     */
    public float getWSU84();

    /**
     * Sets the w s u84 of this hydemeta.
     *
     * @param WSU84 the w s u84 of this hydemeta
     */
    public void setWSU84(float WSU84);

    /**
     * Returns the w d of this hydemeta.
     *
     * @return the w d of this hydemeta
     */
    public float getWD();

    /**
     * Sets the w d of this hydemeta.
     *
     * @param WD the w d of this hydemeta
     */
    public void setWD(float WD);

    /**
     * Returns the w d504 of this hydemeta.
     *
     * @return the w d504 of this hydemeta
     */
    public float getWD504();

    /**
     * Sets the w d504 of this hydemeta.
     *
     * @param WD504 the w d504 of this hydemeta
     */
    public void setWD504(float WD504);

    /**
     * Returns the w d336 of this hydemeta.
     *
     * @return the w d336 of this hydemeta
     */
    public float getWD336();

    /**
     * Sets the w d336 of this hydemeta.
     *
     * @param WD336 the w d336 of this hydemeta
     */
    public void setWD336(float WD336);

    /**
     * Returns the w d168 of this hydemeta.
     *
     * @return the w d168 of this hydemeta
     */
    public float getWD168();

    /**
     * Sets the w d168 of this hydemeta.
     *
     * @param WD168 the w d168 of this hydemeta
     */
    public void setWD168(float WD168);

    /**
     * Returns the w d u740 of this hydemeta.
     *
     * @return the w d u740 of this hydemeta
     */
    public float getWDU740();

    /**
     * Sets the w d u740 of this hydemeta.
     *
     * @param WDU740 the w d u740 of this hydemeta
     */
    public void setWDU740(float WDU740);

    /**
     * Returns the w d u336 of this hydemeta.
     *
     * @return the w d u336 of this hydemeta
     */
    public float getWDU336();

    /**
     * Sets the w d u336 of this hydemeta.
     *
     * @param WDU336 the w d u336 of this hydemeta
     */
    public void setWDU336(float WDU336);

    /**
     * Returns the w d u168 of this hydemeta.
     *
     * @return the w d u168 of this hydemeta
     */
    public float getWDU168();

    /**
     * Sets the w d u168 of this hydemeta.
     *
     * @param WDU168 the w d u168 of this hydemeta
     */
    public void setWDU168(float WDU168);

    /**
     * Returns the w d u84 of this hydemeta.
     *
     * @return the w d u84 of this hydemeta
     */
    public float getWDU84();

    /**
     * Sets the w d u84 of this hydemeta.
     *
     * @param WDU84 the w d u84 of this hydemeta
     */
    public void setWDU84(float WDU84);

    /**
     * Returns the n o672 of this hydemeta.
     *
     * @return the n o672 of this hydemeta
     */
    public float getNO672();

    /**
     * Sets the n o672 of this hydemeta.
     *
     * @param NO672 the n o672 of this hydemeta
     */
    public void setNO672(float NO672);

    /**
     * Returns the n o504 of this hydemeta.
     *
     * @return the n o504 of this hydemeta
     */
    public float getNO504();

    /**
     * Sets the n o504 of this hydemeta.
     *
     * @param NO504 the n o504 of this hydemeta
     */
    public void setNO504(float NO504);

    /**
     * Returns the n o336 of this hydemeta.
     *
     * @return the n o336 of this hydemeta
     */
    public float getNO336();

    /**
     * Sets the n o336 of this hydemeta.
     *
     * @param NO336 the n o336 of this hydemeta
     */
    public void setNO336(float NO336);

    /**
     * Returns the n o168 of this hydemeta.
     *
     * @return the n o168 of this hydemeta
     */
    public float getNO168();

    /**
     * Sets the n o168 of this hydemeta.
     *
     * @param NO168 the n o168 of this hydemeta
     */
    public void setNO168(float NO168);

    /**
     * Returns the n o84 of this hydemeta.
     *
     * @return the n o84 of this hydemeta
     */
    public float getNO84();

    /**
     * Sets the n o84 of this hydemeta.
     *
     * @param NO84 the n o84 of this hydemeta
     */
    public void setNO84(float NO84);

    /**
     * Returns the n o42 of this hydemeta.
     *
     * @return the n o42 of this hydemeta
     */
    public float getNO42();

    /**
     * Sets the n o42 of this hydemeta.
     *
     * @param NO42 the n o42 of this hydemeta
     */
    public void setNO42(float NO42);

    /**
     * Returns the n ox672 of this hydemeta.
     *
     * @return the n ox672 of this hydemeta
     */
    public float getNOx672();

    /**
     * Sets the n ox672 of this hydemeta.
     *
     * @param NOx672 the n ox672 of this hydemeta
     */
    public void setNOx672(float NOx672);

    /**
     * Returns the n ox504 of this hydemeta.
     *
     * @return the n ox504 of this hydemeta
     */
    public float getNOx504();

    /**
     * Sets the n ox504 of this hydemeta.
     *
     * @param NOx504 the n ox504 of this hydemeta
     */
    public void setNOx504(float NOx504);

    /**
     * Returns the n ox336 of this hydemeta.
     *
     * @return the n ox336 of this hydemeta
     */
    public float getNOx336();

    /**
     * Sets the n ox336 of this hydemeta.
     *
     * @param NOx336 the n ox336 of this hydemeta
     */
    public void setNOx336(float NOx336);

    /**
     * Returns the n ox168 of this hydemeta.
     *
     * @return the n ox168 of this hydemeta
     */
    public float getNOx168();

    /**
     * Sets the n ox168 of this hydemeta.
     *
     * @param NOx168 the n ox168 of this hydemeta
     */
    public void setNOx168(float NOx168);

    /**
     * Returns the n ox84 of this hydemeta.
     *
     * @return the n ox84 of this hydemeta
     */
    public float getNOx84();

    /**
     * Sets the n ox84 of this hydemeta.
     *
     * @param NOx84 the n ox84 of this hydemeta
     */
    public void setNOx84(float NOx84);

    /**
     * Returns the n ox42 of this hydemeta.
     *
     * @return the n ox42 of this hydemeta
     */
    public float getNOx42();

    /**
     * Sets the n ox42 of this hydemeta.
     *
     * @param NOx42 the n ox42 of this hydemeta
     */
    public void setNOx42(float NOx42);

    /**
     * Returns the o3672 of this hydemeta.
     *
     * @return the o3672 of this hydemeta
     */
    public float getO3672();

    /**
     * Sets the o3672 of this hydemeta.
     *
     * @param O3672 the o3672 of this hydemeta
     */
    public void setO3672(float O3672);

    /**
     * Returns the o3504 of this hydemeta.
     *
     * @return the o3504 of this hydemeta
     */
    public float getO3504();

    /**
     * Sets the o3504 of this hydemeta.
     *
     * @param O3504 the o3504 of this hydemeta
     */
    public void setO3504(float O3504);

    /**
     * Returns the o3336 of this hydemeta.
     *
     * @return the o3336 of this hydemeta
     */
    public float getO3336();

    /**
     * Sets the o3336 of this hydemeta.
     *
     * @param O3336 the o3336 of this hydemeta
     */
    public void setO3336(float O3336);

    /**
     * Returns the o3168 of this hydemeta.
     *
     * @return the o3168 of this hydemeta
     */
    public float getO3168();

    /**
     * Sets the o3168 of this hydemeta.
     *
     * @param O3168 the o3168 of this hydemeta
     */
    public void setO3168(float O3168);

    /**
     * Returns the o384 of this hydemeta.
     *
     * @return the o384 of this hydemeta
     */
    public float getO384();

    /**
     * Sets the o384 of this hydemeta.
     *
     * @param O384 the o384 of this hydemeta
     */
    public void setO384(float O384);

    /**
     * Returns the o342 of this hydemeta.
     *
     * @return the o342 of this hydemeta
     */
    public float getO342();

    /**
     * Sets the o342 of this hydemeta.
     *
     * @param O342 the o342 of this hydemeta
     */
    public void setO342(float O342);

    /**
     * Returns the s o2672 of this hydemeta.
     *
     * @return the s o2672 of this hydemeta
     */
    public float getSO2672();

    /**
     * Sets the s o2672 of this hydemeta.
     *
     * @param SO2672 the s o2672 of this hydemeta
     */
    public void setSO2672(float SO2672);

    /**
     * Returns the s o2504 of this hydemeta.
     *
     * @return the s o2504 of this hydemeta
     */
    public float getSO2504();

    /**
     * Sets the s o2504 of this hydemeta.
     *
     * @param SO2504 the s o2504 of this hydemeta
     */
    public void setSO2504(float SO2504);

    /**
     * Returns the s o2336 of this hydemeta.
     *
     * @return the s o2336 of this hydemeta
     */
    public float getSO2336();

    /**
     * Sets the s o2336 of this hydemeta.
     *
     * @param SO2336 the s o2336 of this hydemeta
     */
    public void setSO2336(float SO2336);

    /**
     * Returns the s o2168 of this hydemeta.
     *
     * @return the s o2168 of this hydemeta
     */
    public float getSO2168();

    /**
     * Sets the s o2168 of this hydemeta.
     *
     * @param SO2168 the s o2168 of this hydemeta
     */
    public void setSO2168(float SO2168);

    /**
     * Returns the s o284 of this hydemeta.
     *
     * @return the s o284 of this hydemeta
     */
    public float getSO284();

    /**
     * Sets the s o284 of this hydemeta.
     *
     * @param SO284 the s o284 of this hydemeta
     */
    public void setSO284(float SO284);

    /**
     * Returns the s o242 of this hydemeta.
     *
     * @return the s o242 of this hydemeta
     */
    public float getSO242();

    /**
     * Sets the s o242 of this hydemeta.
     *
     * @param SO242 the s o242 of this hydemeta
     */
    public void setSO242(float SO242);

    /**
     * Returns the h2 o672 of this hydemeta.
     *
     * @return the h2 o672 of this hydemeta
     */
    public float getH2O672();

    /**
     * Sets the h2 o672 of this hydemeta.
     *
     * @param H2O672 the h2 o672 of this hydemeta
     */
    public void setH2O672(float H2O672);

    /**
     * Returns the h2 o504 of this hydemeta.
     *
     * @return the h2 o504 of this hydemeta
     */
    public float getH2O504();

    /**
     * Sets the h2 o504 of this hydemeta.
     *
     * @param H2O504 the h2 o504 of this hydemeta
     */
    public void setH2O504(float H2O504);

    /**
     * Returns the h2 o336 of this hydemeta.
     *
     * @return the h2 o336 of this hydemeta
     */
    public float getH2O336();

    /**
     * Sets the h2 o336 of this hydemeta.
     *
     * @param H2O336 the h2 o336 of this hydemeta
     */
    public void setH2O336(float H2O336);

    /**
     * Returns the h2 o168 of this hydemeta.
     *
     * @return the h2 o168 of this hydemeta
     */
    public float getH2O168();

    /**
     * Sets the h2 o168 of this hydemeta.
     *
     * @param H2O168 the h2 o168 of this hydemeta
     */
    public void setH2O168(float H2O168);

    /**
     * Returns the h2 o84 of this hydemeta.
     *
     * @return the h2 o84 of this hydemeta
     */
    public float getH2O84();

    /**
     * Sets the h2 o84 of this hydemeta.
     *
     * @param H2O84 the h2 o84 of this hydemeta
     */
    public void setH2O84(float H2O84);

    /**
     * Returns the h2 o42 of this hydemeta.
     *
     * @return the h2 o42 of this hydemeta
     */
    public float getH2O42();

    /**
     * Sets the h2 o42 of this hydemeta.
     *
     * @param H2O42 the h2 o42 of this hydemeta
     */
    public void setH2O42(float H2O42);

    /**
     * Returns the c o2672 of this hydemeta.
     *
     * @return the c o2672 of this hydemeta
     */
    public float getCO2672();

    /**
     * Sets the c o2672 of this hydemeta.
     *
     * @param CO2672 the c o2672 of this hydemeta
     */
    public void setCO2672(float CO2672);

    /**
     * Returns the c o2504 of this hydemeta.
     *
     * @return the c o2504 of this hydemeta
     */
    public float getCO2504();

    /**
     * Sets the c o2504 of this hydemeta.
     *
     * @param CO2504 the c o2504 of this hydemeta
     */
    public void setCO2504(float CO2504);

    /**
     * Returns the c o2336 of this hydemeta.
     *
     * @return the c o2336 of this hydemeta
     */
    public float getCO2336();

    /**
     * Sets the c o2336 of this hydemeta.
     *
     * @param CO2336 the c o2336 of this hydemeta
     */
    public void setCO2336(float CO2336);

    /**
     * Returns the c o2168 of this hydemeta.
     *
     * @return the c o2168 of this hydemeta
     */
    public float getCO2168();

    /**
     * Sets the c o2168 of this hydemeta.
     *
     * @param CO2168 the c o2168 of this hydemeta
     */
    public void setCO2168(float CO2168);

    /**
     * Returns the c o284 of this hydemeta.
     *
     * @return the c o284 of this hydemeta
     */
    public float getCO284();

    /**
     * Sets the c o284 of this hydemeta.
     *
     * @param CO284 the c o284 of this hydemeta
     */
    public void setCO284(float CO284);

    /**
     * Returns the c o242 of this hydemeta.
     *
     * @return the c o242 of this hydemeta
     */
    public float getCO242();

    /**
     * Sets the c o242 of this hydemeta.
     *
     * @param CO242 the c o242 of this hydemeta
     */
    public void setCO242(float CO242);

    /**
     * Returns the h2 s672 of this hydemeta.
     *
     * @return the h2 s672 of this hydemeta
     */
    public float getH2S672();

    /**
     * Sets the h2 s672 of this hydemeta.
     *
     * @param H2S672 the h2 s672 of this hydemeta
     */
    public void setH2S672(float H2S672);

    /**
     * Returns the h2 s504 of this hydemeta.
     *
     * @return the h2 s504 of this hydemeta
     */
    public float getH2S504();

    /**
     * Sets the h2 s504 of this hydemeta.
     *
     * @param H2S504 the h2 s504 of this hydemeta
     */
    public void setH2S504(float H2S504);

    /**
     * Returns the h2 s336 of this hydemeta.
     *
     * @return the h2 s336 of this hydemeta
     */
    public float getH2S336();

    /**
     * Sets the h2 s336 of this hydemeta.
     *
     * @param H2S336 the h2 s336 of this hydemeta
     */
    public void setH2S336(float H2S336);

    /**
     * Returns the h2 s168 of this hydemeta.
     *
     * @return the h2 s168 of this hydemeta
     */
    public float getH2S168();

    /**
     * Sets the h2 s168 of this hydemeta.
     *
     * @param H2S168 the h2 s168 of this hydemeta
     */
    public void setH2S168(float H2S168);

    /**
     * Returns the h2 s84 of this hydemeta.
     *
     * @return the h2 s84 of this hydemeta
     */
    public float getH2S84();

    /**
     * Sets the h2 s84 of this hydemeta.
     *
     * @param H2S84 the h2 s84 of this hydemeta
     */
    public void setH2S84(float H2S84);

    /**
     * Returns the h2 s42 of this hydemeta.
     *
     * @return the h2 s42 of this hydemeta
     */
    public float getH2S42();

    /**
     * Sets the h2 s42 of this hydemeta.
     *
     * @param H2S42 the h2 s42 of this hydemeta
     */
    public void setH2S42(float H2S42);

    /**
     * Returns the r h i r g a672 of this hydemeta.
     *
     * @return the r h i r g a672 of this hydemeta
     */
    public float getRHIRGA672();

    /**
     * Sets the r h i r g a672 of this hydemeta.
     *
     * @param RHIRGA672 the r h i r g a672 of this hydemeta
     */
    public void setRHIRGA672(float RHIRGA672);

    /**
     * Returns the r h i r g a504 of this hydemeta.
     *
     * @return the r h i r g a504 of this hydemeta
     */
    public float getRHIRGA504();

    /**
     * Sets the r h i r g a504 of this hydemeta.
     *
     * @param RHIRGA504 the r h i r g a504 of this hydemeta
     */
    public void setRHIRGA504(float RHIRGA504);

    /**
     * Returns the r h i r g a336 of this hydemeta.
     *
     * @return the r h i r g a336 of this hydemeta
     */
    public float getRHIRGA336();

    /**
     * Sets the r h i r g a336 of this hydemeta.
     *
     * @param RHIRGA336 the r h i r g a336 of this hydemeta
     */
    public void setRHIRGA336(float RHIRGA336);

    /**
     * Returns the r h i r g a168 of this hydemeta.
     *
     * @return the r h i r g a168 of this hydemeta
     */
    public float getRHIRGA168();

    /**
     * Sets the r h i r g a168 of this hydemeta.
     *
     * @param RHIRGA168 the r h i r g a168 of this hydemeta
     */
    public void setRHIRGA168(float RHIRGA168);

    /**
     * Returns the r h i r g a84 of this hydemeta.
     *
     * @return the r h i r g a84 of this hydemeta
     */
    public float getRHIRGA84();

    /**
     * Sets the r h i r g a84 of this hydemeta.
     *
     * @param RHIRGA84 the r h i r g a84 of this hydemeta
     */
    public void setRHIRGA84(float RHIRGA84);

    /**
     * Returns the r h i r g a42 of this hydemeta.
     *
     * @return the r h i r g a42 of this hydemeta
     */
    public float getRHIRGA42();

    /**
     * Sets the r h i r g a42 of this hydemeta.
     *
     * @param RHIRGA42 the r h i r g a42 of this hydemeta
     */
    public void setRHIRGA42(float RHIRGA42);

    /**
     * Returns the c o672 of this hydemeta.
     *
     * @return the c o672 of this hydemeta
     */
    public float getCO672();

    /**
     * Sets the c o672 of this hydemeta.
     *
     * @param CO672 the c o672 of this hydemeta
     */
    public void setCO672(float CO672);

    /**
     * Returns the c o504 of this hydemeta.
     *
     * @return the c o504 of this hydemeta
     */
    public float getCO504();

    /**
     * Sets the c o504 of this hydemeta.
     *
     * @param CO504 the c o504 of this hydemeta
     */
    public void setCO504(float CO504);

    /**
     * Returns the c o336 of this hydemeta.
     *
     * @return the c o336 of this hydemeta
     */
    public float getCO336();

    /**
     * Sets the c o336 of this hydemeta.
     *
     * @param CO336 the c o336 of this hydemeta
     */
    public void setCO336(float CO336);

    /**
     * Returns the c o168 of this hydemeta.
     *
     * @return the c o168 of this hydemeta
     */
    public float getCO168();

    /**
     * Sets the c o168 of this hydemeta.
     *
     * @param CO168 the c o168 of this hydemeta
     */
    public void setCO168(float CO168);

    /**
     * Returns the c o84 of this hydemeta.
     *
     * @return the c o84 of this hydemeta
     */
    public float getCO84();

    /**
     * Sets the c o84 of this hydemeta.
     *
     * @param CO84 the c o84 of this hydemeta
     */
    public void setCO84(float CO84);

    /**
     * Returns the c o42 of this hydemeta.
     *
     * @return the c o42 of this hydemeta
     */
    public float getCO42();

    /**
     * Sets the c o42 of this hydemeta.
     *
     * @param CO42 the c o42 of this hydemeta
     */
    public void setCO42(float CO42);

    /**
     * Returns the r h td of this hydemeta.
     *
     * @return the r h td of this hydemeta
     */
    public float getRHTd();

    /**
     * Sets the r h td of this hydemeta.
     *
     * @param RHTd the r h td of this hydemeta
     */
    public void setRHTd(float RHTd);

    /**
     * Returns the p t g of this hydemeta.
     *
     * @return the p t g of this hydemeta
     */
    public float getPTG();

    /**
     * Sets the p t g of this hydemeta.
     *
     * @param PTG the p t g of this hydemeta
     */
    public void setPTG(float PTG);

    /**
     * Returns the visibility of this hydemeta.
     *
     * @return the visibility of this hydemeta
     */
    public float getVisibility();

    /**
     * Sets the visibility of this hydemeta.
     *
     * @param Visibility the visibility of this hydemeta
     */
    public void setVisibility(float Visibility);

    /**
     * Returns the visibilitymin of this hydemeta.
     *
     * @return the visibilitymin of this hydemeta
     */
    public float getVisibilitymin();

    /**
     * Sets the visibilitymin of this hydemeta.
     *
     * @param Visibilitymin the visibilitymin of this hydemeta
     */
    public void setVisibilitymin(float Visibilitymin);

    /**
     * Returns the visibilitymax of this hydemeta.
     *
     * @return the visibilitymax of this hydemeta
     */
    public float getVisibilitymax();

    /**
     * Sets the visibilitymax of this hydemeta.
     *
     * @param Visibilitymax the visibilitymax of this hydemeta
     */
    public void setVisibilitymax(float Visibilitymax);

    /**
     * Returns the precipint of this hydemeta.
     *
     * @return the precipint of this hydemeta
     */
    public float getPrecipint();

    /**
     * Sets the precipint of this hydemeta.
     *
     * @param Precipint the precipint of this hydemeta
     */
    public void setPrecipint(float Precipint);

    /**
     * Returns the precipintmin of this hydemeta.
     *
     * @return the precipintmin of this hydemeta
     */
    public float getPrecipintmin();

    /**
     * Sets the precipintmin of this hydemeta.
     *
     * @param Precipintmin the precipintmin of this hydemeta
     */
    public void setPrecipintmin(float Precipintmin);

    /**
     * Returns the precipintmax of this hydemeta.
     *
     * @return the precipintmax of this hydemeta
     */
    public float getPrecipintmax();

    /**
     * Sets the precipintmax of this hydemeta.
     *
     * @param Precipintmax the precipintmax of this hydemeta
     */
    public void setPrecipintmax(float Precipintmax);

    /**
     * Returns the precipacc of this hydemeta.
     *
     * @return the precipacc of this hydemeta
     */
    public float getPrecipacc();

    /**
     * Sets the precipacc of this hydemeta.
     *
     * @param Precipacc the precipacc of this hydemeta
     */
    public void setPrecipacc(float Precipacc);

    /**
     * Returns the snowfallacc of this hydemeta.
     *
     * @return the snowfallacc of this hydemeta
     */
    public float getSnowfallacc();

    /**
     * Sets the snowfallacc of this hydemeta.
     *
     * @param Snowfallacc the snowfallacc of this hydemeta
     */
    public void setSnowfallacc(float Snowfallacc);

    /**
     * Returns the wthcode of this hydemeta.
     *
     * @return the wthcode of this hydemeta
     */
    public int getWthcode();

    /**
     * Sets the wthcode of this hydemeta.
     *
     * @param wthcode the wthcode of this hydemeta
     */
    public void setWthcode(int wthcode);

    /**
     * Returns the wthcodemin of this hydemeta.
     *
     * @return the wthcodemin of this hydemeta
     */
    public int getWthcodemin();

    /**
     * Sets the wthcodemin of this hydemeta.
     *
     * @param wthcodemin the wthcodemin of this hydemeta
     */
    public void setWthcodemin(int wthcodemin);

    /**
     * Returns the wthcodemax of this hydemeta.
     *
     * @return the wthcodemax of this hydemeta
     */
    public int getWthcodemax();

    /**
     * Sets the wthcodemax of this hydemeta.
     *
     * @param wthcodemax the wthcodemax of this hydemeta
     */
    public void setWthcodemax(int wthcodemax);

    /**
     * Returns the tsoil_humus of this hydemeta.
     *
     * @return the tsoil_humus of this hydemeta
     */
    public float getTsoil_humus();

    /**
     * Sets the tsoil_humus of this hydemeta.
     *
     * @param tsoil_humus the tsoil_humus of this hydemeta
     */
    public void setTsoil_humus(float tsoil_humus);

    /**
     * Returns the tsoil_ a of this hydemeta.
     *
     * @return the tsoil_ a of this hydemeta
     */
    public float getTsoil_A();

    /**
     * Sets the tsoil_ a of this hydemeta.
     *
     * @param tsoil_A the tsoil_ a of this hydemeta
     */
    public void setTsoil_A(float tsoil_A);

    /**
     * Returns the tsoil_ b1 of this hydemeta.
     *
     * @return the tsoil_ b1 of this hydemeta
     */
    public float getTsoil_B1();

    /**
     * Sets the tsoil_ b1 of this hydemeta.
     *
     * @param tsoil_B1 the tsoil_ b1 of this hydemeta
     */
    public void setTsoil_B1(float tsoil_B1);

    /**
     * Returns the tsoil_ b2 of this hydemeta.
     *
     * @return the tsoil_ b2 of this hydemeta
     */
    public float getTsoil_B2();

    /**
     * Sets the tsoil_ b2 of this hydemeta.
     *
     * @param tsoil_B2 the tsoil_ b2 of this hydemeta
     */
    public void setTsoil_B2(float tsoil_B2);

    /**
     * Returns the tsoil_ c1 of this hydemeta.
     *
     * @return the tsoil_ c1 of this hydemeta
     */
    public float getTsoil_C1();

    /**
     * Sets the tsoil_ c1 of this hydemeta.
     *
     * @param tsoil_C1 the tsoil_ c1 of this hydemeta
     */
    public void setTsoil_C1(float tsoil_C1);

    /**
     * Returns the h2 o td of this hydemeta.
     *
     * @return the h2 o td of this hydemeta
     */
    public float getH2OTd();

    /**
     * Sets the h2 o td of this hydemeta.
     *
     * @param H2OTd the h2 o td of this hydemeta
     */
    public void setH2OTd(float H2OTd);

    /**
     * Returns the c o2_storage_flux of this hydemeta.
     *
     * @return the c o2_storage_flux of this hydemeta
     */
    public float getCO2_storage_flux();

    /**
     * Sets the c o2_storage_flux of this hydemeta.
     *
     * @param CO2_storage_flux the c o2_storage_flux of this hydemeta
     */
    public void setCO2_storage_flux(float CO2_storage_flux);

    /**
     * Returns the wsoil_humus of this hydemeta.
     *
     * @return the wsoil_humus of this hydemeta
     */
    public float getWsoil_humus();

    /**
     * Sets the wsoil_humus of this hydemeta.
     *
     * @param wsoil_humus the wsoil_humus of this hydemeta
     */
    public void setWsoil_humus(float wsoil_humus);

    /**
     * Returns the wsoil_ a of this hydemeta.
     *
     * @return the wsoil_ a of this hydemeta
     */
    public float getWsoil_A();

    /**
     * Sets the wsoil_ a of this hydemeta.
     *
     * @param wsoil_A the wsoil_ a of this hydemeta
     */
    public void setWsoil_A(float wsoil_A);

    /**
     * Returns the wsoil_ b1 of this hydemeta.
     *
     * @return the wsoil_ b1 of this hydemeta
     */
    public float getWsoil_B1();

    /**
     * Sets the wsoil_ b1 of this hydemeta.
     *
     * @param wsoil_B1 the wsoil_ b1 of this hydemeta
     */
    public void setWsoil_B1(float wsoil_B1);

    /**
     * Returns the wsoil_ b2 of this hydemeta.
     *
     * @return the wsoil_ b2 of this hydemeta
     */
    public float getWsoil_B2();

    /**
     * Sets the wsoil_ b2 of this hydemeta.
     *
     * @param wsoil_B2 the wsoil_ b2 of this hydemeta
     */
    public void setWsoil_B2(float wsoil_B2);

    /**
     * Returns the wsoil_ c1 of this hydemeta.
     *
     * @return the wsoil_ c1 of this hydemeta
     */
    public float getWsoil_C1();

    /**
     * Sets the wsoil_ c1 of this hydemeta.
     *
     * @param wsoil_C1 the wsoil_ c1 of this hydemeta
     */
    public void setWsoil_C1(float wsoil_C1);

    /**
     * Returns the l win of this hydemeta.
     *
     * @return the l win of this hydemeta
     */
    public float getLWin();

    /**
     * Sets the l win of this hydemeta.
     *
     * @param LWin the l win of this hydemeta
     */
    public void setLWin(float LWin);

    /**
     * Returns the l wout of this hydemeta.
     *
     * @return the l wout of this hydemeta
     */
    public float getLWout();

    /**
     * Sets the l wout of this hydemeta.
     *
     * @param LWout the l wout of this hydemeta
     */
    public void setLWout(float LWout);

    /**
     * Returns the p r i of this hydemeta.
     *
     * @return the p r i of this hydemeta
     */
    public float getPRI();

    /**
     * Sets the p r i of this hydemeta.
     *
     * @param PRI the p r i of this hydemeta
     */
    public void setPRI(float PRI);

    /**
     * Returns the n d v i of this hydemeta.
     *
     * @return the n d v i of this hydemeta
     */
    public float getNDVI();

    /**
     * Sets the n d v i of this hydemeta.
     *
     * @param NDVI the n d v i of this hydemeta
     */
    public void setNDVI(float NDVI);

    /**
     * Returns the b n d v i of this hydemeta.
     *
     * @return the b n d v i of this hydemeta
     */
    public float getBNDVI();

    /**
     * Sets the b n d v i of this hydemeta.
     *
     * @param BNDVI the b n d v i of this hydemeta
     */
    public void setBNDVI(float BNDVI);

    /**
     * Returns the can p a r1 of this hydemeta.
     *
     * @return the can p a r1 of this hydemeta
     */
    public float getCanPAR1();

    /**
     * Sets the can p a r1 of this hydemeta.
     *
     * @param canPAR1 the can p a r1 of this hydemeta
     */
    public void setCanPAR1(float canPAR1);

    /**
     * Returns the can p a r2 of this hydemeta.
     *
     * @return the can p a r2 of this hydemeta
     */
    public float getCanPAR2();

    /**
     * Sets the can p a r2 of this hydemeta.
     *
     * @param canPAR2 the can p a r2 of this hydemeta
     */
    public void setCanPAR2(float canPAR2);

    /**
     * Returns the can p a r3 of this hydemeta.
     *
     * @return the can p a r3 of this hydemeta
     */
    public float getCanPAR3();

    /**
     * Sets the can p a r3 of this hydemeta.
     *
     * @param canPAR3 the can p a r3 of this hydemeta
     */
    public void setCanPAR3(float canPAR3);

    /**
     * Returns the maa p a r of this hydemeta.
     *
     * @return the maa p a r of this hydemeta
     */
    public float getMaaPAR();

    /**
     * Sets the maa p a r of this hydemeta.
     *
     * @param maaPAR the maa p a r of this hydemeta
     */
    public void setMaaPAR(float maaPAR);

    /**
     * Returns the maa net of this hydemeta.
     *
     * @return the maa net of this hydemeta
     */
    public float getMaaNet();

    /**
     * Sets the maa net of this hydemeta.
     *
     * @param maaNet the maa net of this hydemeta
     */
    public void setMaaNet(float maaNet);

    /**
     * Returns the p a r2 of this hydemeta.
     *
     * @return the p a r2 of this hydemeta
     */
    public float getPAR2();

    /**
     * Sets the p a r2 of this hydemeta.
     *
     * @param PAR2 the p a r2 of this hydemeta
     */
    public void setPAR2(float PAR2);

    /**
     * Returns the globmast of this hydemeta.
     *
     * @return the globmast of this hydemeta
     */
    public float getGlobmast();

    /**
     * Sets the globmast of this hydemeta.
     *
     * @param Globmast the globmast of this hydemeta
     */
    public void setGlobmast(float Globmast);

    /**
     * Returns the w d u672 of this hydemeta.
     *
     * @return the w d u672 of this hydemeta
     */
    public float getWDU672();

    /**
     * Sets the w d u672 of this hydemeta.
     *
     * @param WDU672 the w d u672 of this hydemeta
     */
    public void setWDU672(float WDU672);

    /**
     * Returns the w s u672 of this hydemeta.
     *
     * @return the w s u672 of this hydemeta
     */
    public float getWSU672();

    /**
     * Sets the w s u672 of this hydemeta.
     *
     * @param WSU672 the w s u672 of this hydemeta
     */
    public void setWSU672(float WSU672);

    /**
     * Returns the r glob125 of this hydemeta.
     *
     * @return the r glob125 of this hydemeta
     */
    public float getRGlob125();

    /**
     * Sets the r glob125 of this hydemeta.
     *
     * @param RGlob125 the r glob125 of this hydemeta
     */
    public void setRGlob125(float RGlob125);

    /**
     * Returns the c h4168 of this hydemeta.
     *
     * @return the c h4168 of this hydemeta
     */
    public float getCH4168();

    /**
     * Sets the c h4168 of this hydemeta.
     *
     * @param CH4168 the c h4168 of this hydemeta
     */
    public void setCH4168(float CH4168);

    /**
     * Returns the c h4672 of this hydemeta.
     *
     * @return the c h4672 of this hydemeta
     */
    public float getCH4672();

    /**
     * Sets the c h4672 of this hydemeta.
     *
     * @param CH4672 the c h4672 of this hydemeta
     */
    public void setCH4672(float CH4672);

    /**
     * Returns the c h41250 of this hydemeta.
     *
     * @return the c h41250 of this hydemeta
     */
    public float getCH41250();

    /**
     * Sets the c h41250 of this hydemeta.
     *
     * @param CH41250 the c h41250 of this hydemeta
     */
    public void setCH41250(float CH41250);

    /**
     * Returns the t1250 of this hydemeta.
     *
     * @return the t1250 of this hydemeta
     */
    public float getT1250();

    /**
     * Sets the t1250 of this hydemeta.
     *
     * @param T1250 the t1250 of this hydemeta
     */
    public void setT1250(float T1250);

    /**
     * Returns the wpsoil_ a of this hydemeta.
     *
     * @return the wpsoil_ a of this hydemeta
     */
    public float getWpsoil_A();

    /**
     * Sets the wpsoil_ a of this hydemeta.
     *
     * @param wpsoil_A the wpsoil_ a of this hydemeta
     */
    public void setWpsoil_A(float wpsoil_A);

    /**
     * Returns the wpsoil_ b of this hydemeta.
     *
     * @return the wpsoil_ b of this hydemeta
     */
    public float getWpsoil_B();

    /**
     * Sets the wpsoil_ b of this hydemeta.
     *
     * @param wpsoil_B the wpsoil_ b of this hydemeta
     */
    public void setWpsoil_B(float wpsoil_B);

    /**
     * Returns the runoff1 of this hydemeta.
     *
     * @return the runoff1 of this hydemeta
     */
    public float getRunoff1();

    /**
     * Sets the runoff1 of this hydemeta.
     *
     * @param runoff1 the runoff1 of this hydemeta
     */
    public void setRunoff1(float runoff1);

    /**
     * Returns the runoff2 of this hydemeta.
     *
     * @return the runoff2 of this hydemeta
     */
    public float getRunoff2();

    /**
     * Sets the runoff2 of this hydemeta.
     *
     * @param runoff2 the runoff2 of this hydemeta
     */
    public void setRunoff2(float runoff2);

    /**
     * Returns the drainage1 of this hydemeta.
     *
     * @return the drainage1 of this hydemeta
     */
    public float getDrainage1();

    /**
     * Sets the drainage1 of this hydemeta.
     *
     * @param drainage1 the drainage1 of this hydemeta
     */
    public void setDrainage1(float drainage1);

    /**
     * Returns the c o2icos168 of this hydemeta.
     *
     * @return the c o2icos168 of this hydemeta
     */
    public float getCO2icos168();

    /**
     * Sets the c o2icos168 of this hydemeta.
     *
     * @param CO2icos168 the c o2icos168 of this hydemeta
     */
    public void setCO2icos168(float CO2icos168);

    /**
     * Returns the c o2icos672 of this hydemeta.
     *
     * @return the c o2icos672 of this hydemeta
     */
    public float getCO2icos672();

    /**
     * Sets the c o2icos672 of this hydemeta.
     *
     * @param CO2icos672 the c o2icos672 of this hydemeta
     */
    public void setCO2icos672(float CO2icos672);

    /**
     * Returns the c o2icos1250 of this hydemeta.
     *
     * @return the c o2icos1250 of this hydemeta
     */
    public float getCO2icos1250();

    /**
     * Sets the c o2icos1250 of this hydemeta.
     *
     * @param CO2icos1250 the c o2icos1250 of this hydemeta
     */
    public void setCO2icos1250(float CO2icos1250);

    /**
     * Returns the h2 oicos168 of this hydemeta.
     *
     * @return the h2 oicos168 of this hydemeta
     */
    public float getH2Oicos168();

    /**
     * Sets the h2 oicos168 of this hydemeta.
     *
     * @param H2Oicos168 the h2 oicos168 of this hydemeta
     */
    public void setH2Oicos168(float H2Oicos168);

    /**
     * Returns the h2 oicos672 of this hydemeta.
     *
     * @return the h2 oicos672 of this hydemeta
     */
    public float getH2Oicos672();

    /**
     * Sets the h2 oicos672 of this hydemeta.
     *
     * @param H2Oicos672 the h2 oicos672 of this hydemeta
     */
    public void setH2Oicos672(float H2Oicos672);

    /**
     * Returns the h2 oicos1250 of this hydemeta.
     *
     * @return the h2 oicos1250 of this hydemeta
     */
    public float getH2Oicos1250();

    /**
     * Sets the h2 oicos1250 of this hydemeta.
     *
     * @param H2Oicos1250 the h2 oicos1250 of this hydemeta
     */
    public void setH2Oicos1250(float H2Oicos1250);

    /**
     * Returns the u v_ a_ e m e p of this hydemeta.
     *
     * @return the u v_ a_ e m e p of this hydemeta
     */
    public int getUV_A_EMEP();

    /**
     * Sets the u v_ a_ e m e p of this hydemeta.
     *
     * @param UV_A_EMEP the u v_ a_ e m e p of this hydemeta
     */
    public void setUV_A_EMEP(int UV_A_EMEP);

    /**
     * Returns the u v_ b_ e m e p of this hydemeta.
     *
     * @return the u v_ b_ e m e p of this hydemeta
     */
    public int getUV_B_EMEP();

    /**
     * Sets the u v_ b_ e m e p of this hydemeta.
     *
     * @param UV_B_EMEP the u v_ b_ e m e p of this hydemeta
     */
    public void setUV_B_EMEP(int UV_B_EMEP);

    /**
     * Returns the diff p a r_ e m e p of this hydemeta.
     *
     * @return the diff p a r_ e m e p of this hydemeta
     */
    public int getDiffPAR_EMEP();

    /**
     * Sets the diff p a r_ e m e p of this hydemeta.
     *
     * @param diffPAR_EMEP the diff p a r_ e m e p of this hydemeta
     */
    public void setDiffPAR_EMEP(int diffPAR_EMEP);

    /**
     * Returns the diff g l o b_ e m e p of this hydemeta.
     *
     * @return the diff g l o b_ e m e p of this hydemeta
     */
    public int getDiffGLOB_EMEP();

    /**
     * Sets the diff g l o b_ e m e p of this hydemeta.
     *
     * @param diffGLOB_EMEP the diff g l o b_ e m e p of this hydemeta
     */
    public void setDiffGLOB_EMEP(int diffGLOB_EMEP);

    /**
     * Returns the dir g l o b_ e m e p of this hydemeta.
     *
     * @return the dir g l o b_ e m e p of this hydemeta
     */
    public int getDirGLOB_EMEP();

    /**
     * Sets the dir g l o b_ e m e p of this hydemeta.
     *
     * @param dirGLOB_EMEP the dir g l o b_ e m e p of this hydemeta
     */
    public void setDirGLOB_EMEP(int dirGLOB_EMEP);

    /**
     * Returns the net_ e m e p of this hydemeta.
     *
     * @return the net_ e m e p of this hydemeta
     */
    public int getNet_EMEP();

    /**
     * Sets the net_ e m e p of this hydemeta.
     *
     * @param Net_EMEP the net_ e m e p of this hydemeta
     */
    public void setNet_EMEP(int Net_EMEP);

    /**
     * Returns the r glob_ e m e p of this hydemeta.
     *
     * @return the r glob_ e m e p of this hydemeta
     */
    public int getRGlob_EMEP();

    /**
     * Sets the r glob_ e m e p of this hydemeta.
     *
     * @param RGlob_EMEP the r glob_ e m e p of this hydemeta
     */
    public void setRGlob_EMEP(int RGlob_EMEP);

    /**
     * Returns the glob_ e m e p of this hydemeta.
     *
     * @return the glob_ e m e p of this hydemeta
     */
    public int getGlob_EMEP();

    /**
     * Sets the glob_ e m e p of this hydemeta.
     *
     * @param Glob_EMEP the glob_ e m e p of this hydemeta
     */
    public void setGlob_EMEP(int Glob_EMEP);

    /**
     * Returns the r p a r_ e m e p of this hydemeta.
     *
     * @return the r p a r_ e m e p of this hydemeta
     */
    public int getRPAR_EMEP();

    /**
     * Sets the r p a r_ e m e p of this hydemeta.
     *
     * @param RPAR_EMEP the r p a r_ e m e p of this hydemeta
     */
    public void setRPAR_EMEP(int RPAR_EMEP);

    /**
     * Returns the p a r_ e m e p of this hydemeta.
     *
     * @return the p a r_ e m e p of this hydemeta
     */
    public int getPAR_EMEP();

    /**
     * Sets the p a r_ e m e p of this hydemeta.
     *
     * @param PAR_EMEP the p a r_ e m e p of this hydemeta
     */
    public void setPAR_EMEP(int PAR_EMEP);

    /**
     * Returns the dir p a r_ e m e p of this hydemeta.
     *
     * @return the dir p a r_ e m e p of this hydemeta
     */
    public int getDirPAR_EMEP();

    /**
     * Sets the dir p a r_ e m e p of this hydemeta.
     *
     * @param dirPAR_EMEP the dir p a r_ e m e p of this hydemeta
     */
    public void setDirPAR_EMEP(int dirPAR_EMEP);

    /**
     * Returns the can i r_ e m e p of this hydemeta.
     *
     * @return the can i r_ e m e p of this hydemeta
     */
    public int getCanIR_EMEP();

    /**
     * Sets the can i r_ e m e p of this hydemeta.
     *
     * @param canIR_EMEP the can i r_ e m e p of this hydemeta
     */
    public void setCanIR_EMEP(int canIR_EMEP);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Hydemeta hydemeta);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Hydemeta> toCacheModel();

    @Override
    public Hydemeta toEscapedModel();

    @Override
    public Hydemeta toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
