package fi.csc.smear.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Hyde_eddytow service. Represents a row in the &quot;HYY_EDDYTOW&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.smear.db.model.impl.Hyde_eddytowModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.smear.db.model.impl.Hyde_eddytowImpl}.
 * </p>
 *
 * @author pj
 * @see Hyde_eddytow
 * @see fi.csc.smear.db.model.impl.Hyde_eddytowImpl
 * @see fi.csc.smear.db.model.impl.Hyde_eddytowModelImpl
 * @generated
 */
public interface Hyde_eddytowModel extends BaseModel<Hyde_eddytow> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a hyde_eddytow model instance should use the {@link Hyde_eddytow} interface instead.
     */

    /**
     * Returns the primary key of this hyde_eddytow.
     *
     * @return the primary key of this hyde_eddytow
     */
    public java.util.Date getPrimaryKey();

    /**
     * Sets the primary key of this hyde_eddytow.
     *
     * @param primaryKey the primary key of this hyde_eddytow
     */
    public void setPrimaryKey(java.util.Date primaryKey);

    /**
     * Returns the samptime of this hyde_eddytow.
     *
     * @return the samptime of this hyde_eddytow
     */
    public Date getSamptime();

    /**
     * Sets the samptime of this hyde_eddytow.
     *
     * @param samptime the samptime of this hyde_eddytow
     */
    public void setSamptime(Date samptime);

    /**
     * Returns the h_radtow of this hyde_eddytow.
     *
     * @return the h_radtow of this hyde_eddytow
     */
    public float getH_radtow();

    /**
     * Sets the h_radtow of this hyde_eddytow.
     *
     * @param H_radtow the h_radtow of this hyde_eddytow
     */
    public void setH_radtow(float H_radtow);

    /**
     * Returns the h_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the h_radtow_ e m e p of this hyde_eddytow
     */
    public int getH_radtow_EMEP();

    /**
     * Sets the h_radtow_ e m e p of this hyde_eddytow.
     *
     * @param H_radtow_EMEP the h_radtow_ e m e p of this hyde_eddytow
     */
    public void setH_radtow_EMEP(int H_radtow_EMEP);

    /**
     * Returns the qc_ h_radtow of this hyde_eddytow.
     *
     * @return the qc_ h_radtow of this hyde_eddytow
     */
    public int getQc_H_radtow();

    /**
     * Sets the qc_ h_radtow of this hyde_eddytow.
     *
     * @param Qc_H_radtow the qc_ h_radtow of this hyde_eddytow
     */
    public void setQc_H_radtow(int Qc_H_radtow);

    /**
     * Returns the qc_ h_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the qc_ h_radtow_ e m e p of this hyde_eddytow
     */
    public int getQc_H_radtow_EMEP();

    /**
     * Sets the qc_ h_radtow_ e m e p of this hyde_eddytow.
     *
     * @param Qc_H_radtow_EMEP the qc_ h_radtow_ e m e p of this hyde_eddytow
     */
    public void setQc_H_radtow_EMEP(int Qc_H_radtow_EMEP);

    /**
     * Returns the l e_radtow of this hyde_eddytow.
     *
     * @return the l e_radtow of this hyde_eddytow
     */
    public float getLE_radtow();

    /**
     * Sets the l e_radtow of this hyde_eddytow.
     *
     * @param LE_radtow the l e_radtow of this hyde_eddytow
     */
    public void setLE_radtow(float LE_radtow);

    /**
     * Returns the l e_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the l e_radtow_ e m e p of this hyde_eddytow
     */
    public int getLE_radtow_EMEP();

    /**
     * Sets the l e_radtow_ e m e p of this hyde_eddytow.
     *
     * @param LE_radtow_EMEP the l e_radtow_ e m e p of this hyde_eddytow
     */
    public void setLE_radtow_EMEP(int LE_radtow_EMEP);

    /**
     * Returns the qc_ l e_radtow of this hyde_eddytow.
     *
     * @return the qc_ l e_radtow of this hyde_eddytow
     */
    public int getQc_LE_radtow();

    /**
     * Sets the qc_ l e_radtow of this hyde_eddytow.
     *
     * @param Qc_LE_radtow the qc_ l e_radtow of this hyde_eddytow
     */
    public void setQc_LE_radtow(int Qc_LE_radtow);

    /**
     * Returns the qc_ l e_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the qc_ l e_radtow_ e m e p of this hyde_eddytow
     */
    public int getQc_LE_radtow_EMEP();

    /**
     * Sets the qc_ l e_radtow_ e m e p of this hyde_eddytow.
     *
     * @param Qc_LE_radtow_EMEP the qc_ l e_radtow_ e m e p of this hyde_eddytow
     */
    public void setQc_LE_radtow_EMEP(int Qc_LE_radtow_EMEP);

    /**
     * Returns the e_radtow of this hyde_eddytow.
     *
     * @return the e_radtow of this hyde_eddytow
     */
    public float getE_radtow();

    /**
     * Sets the e_radtow of this hyde_eddytow.
     *
     * @param E_radtow the e_radtow of this hyde_eddytow
     */
    public void setE_radtow(float E_radtow);

    /**
     * Returns the e_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the e_radtow_ e m e p of this hyde_eddytow
     */
    public int getE_radtow_EMEP();

    /**
     * Sets the e_radtow_ e m e p of this hyde_eddytow.
     *
     * @param E_radtow_EMEP the e_radtow_ e m e p of this hyde_eddytow
     */
    public void setE_radtow_EMEP(int E_radtow_EMEP);

    /**
     * Returns the qc_ e_radtow of this hyde_eddytow.
     *
     * @return the qc_ e_radtow of this hyde_eddytow
     */
    public int getQc_E_radtow();

    /**
     * Sets the qc_ e_radtow of this hyde_eddytow.
     *
     * @param Qc_E_radtow the qc_ e_radtow of this hyde_eddytow
     */
    public void setQc_E_radtow(int Qc_E_radtow);

    /**
     * Returns the qc_ e_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the qc_ e_radtow_ e m e p of this hyde_eddytow
     */
    public int getQc_E_radtow_EMEP();

    /**
     * Sets the qc_ e_radtow_ e m e p of this hyde_eddytow.
     *
     * @param Qc_E_radtow_EMEP the qc_ e_radtow_ e m e p of this hyde_eddytow
     */
    public void setQc_E_radtow_EMEP(int Qc_E_radtow_EMEP);

    /**
     * Returns the f_c_radtow of this hyde_eddytow.
     *
     * @return the f_c_radtow of this hyde_eddytow
     */
    public float getF_c_radtow();

    /**
     * Sets the f_c_radtow of this hyde_eddytow.
     *
     * @param F_c_radtow the f_c_radtow of this hyde_eddytow
     */
    public void setF_c_radtow(float F_c_radtow);

    /**
     * Returns the f_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the f_c_radtow_ e m e p of this hyde_eddytow
     */
    public int getF_c_radtow_EMEP();

    /**
     * Sets the f_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @param F_c_radtow_EMEP the f_c_radtow_ e m e p of this hyde_eddytow
     */
    public void setF_c_radtow_EMEP(int F_c_radtow_EMEP);

    /**
     * Returns the qc_ f_c_radtow of this hyde_eddytow.
     *
     * @return the qc_ f_c_radtow of this hyde_eddytow
     */
    public int getQc_F_c_radtow();

    /**
     * Sets the qc_ f_c_radtow of this hyde_eddytow.
     *
     * @param Qc_F_c_radtow the qc_ f_c_radtow of this hyde_eddytow
     */
    public void setQc_F_c_radtow(int Qc_F_c_radtow);

    /**
     * Returns the qc_ f_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the qc_ f_c_radtow_ e m e p of this hyde_eddytow
     */
    public int getQc_F_c_radtow_EMEP();

    /**
     * Sets the qc_ f_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @param Qc_F_c_radtow_EMEP the qc_ f_c_radtow_ e m e p of this hyde_eddytow
     */
    public void setQc_F_c_radtow_EMEP(int Qc_F_c_radtow_EMEP);

    /**
     * Returns the tau_radtow of this hyde_eddytow.
     *
     * @return the tau_radtow of this hyde_eddytow
     */
    public float getTau_radtow();

    /**
     * Sets the tau_radtow of this hyde_eddytow.
     *
     * @param tau_radtow the tau_radtow of this hyde_eddytow
     */
    public void setTau_radtow(float tau_radtow);

    /**
     * Returns the tau_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the tau_radtow_ e m e p of this hyde_eddytow
     */
    public int getTau_radtow_EMEP();

    /**
     * Sets the tau_radtow_ e m e p of this hyde_eddytow.
     *
     * @param tau_radtow_EMEP the tau_radtow_ e m e p of this hyde_eddytow
     */
    public void setTau_radtow_EMEP(int tau_radtow_EMEP);

    /**
     * Returns the qc_tau_radtow of this hyde_eddytow.
     *
     * @return the qc_tau_radtow of this hyde_eddytow
     */
    public int getQc_tau_radtow();

    /**
     * Sets the qc_tau_radtow of this hyde_eddytow.
     *
     * @param Qc_tau_radtow the qc_tau_radtow of this hyde_eddytow
     */
    public void setQc_tau_radtow(int Qc_tau_radtow);

    /**
     * Returns the qc_tau_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the qc_tau_radtow_ e m e p of this hyde_eddytow
     */
    public int getQc_tau_radtow_EMEP();

    /**
     * Sets the qc_tau_radtow_ e m e p of this hyde_eddytow.
     *
     * @param Qc_tau_radtow_EMEP the qc_tau_radtow_ e m e p of this hyde_eddytow
     */
    public void setQc_tau_radtow_EMEP(int Qc_tau_radtow_EMEP);

    /**
     * Returns the u_star_radtow of this hyde_eddytow.
     *
     * @return the u_star_radtow of this hyde_eddytow
     */
    public float getU_star_radtow();

    /**
     * Sets the u_star_radtow of this hyde_eddytow.
     *
     * @param u_star_radtow the u_star_radtow of this hyde_eddytow
     */
    public void setU_star_radtow(float u_star_radtow);

    /**
     * Returns the u_star_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the u_star_radtow_ e m e p of this hyde_eddytow
     */
    public int getU_star_radtow_EMEP();

    /**
     * Sets the u_star_radtow_ e m e p of this hyde_eddytow.
     *
     * @param u_star_radtow_EMEP the u_star_radtow_ e m e p of this hyde_eddytow
     */
    public void setU_star_radtow_EMEP(int u_star_radtow_EMEP);

    /**
     * Returns the m o_length_radtow of this hyde_eddytow.
     *
     * @return the m o_length_radtow of this hyde_eddytow
     */
    public float getMO_length_radtow();

    /**
     * Sets the m o_length_radtow of this hyde_eddytow.
     *
     * @param MO_length_radtow the m o_length_radtow of this hyde_eddytow
     */
    public void setMO_length_radtow(float MO_length_radtow);

    /**
     * Returns the m o_length_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the m o_length_radtow_ e m e p of this hyde_eddytow
     */
    public int getMO_length_radtow_EMEP();

    /**
     * Sets the m o_length_radtow_ e m e p of this hyde_eddytow.
     *
     * @param MO_length_radtow_EMEP the m o_length_radtow_ e m e p of this hyde_eddytow
     */
    public void setMO_length_radtow_EMEP(int MO_length_radtow_EMEP);

    /**
     * Returns the std_u_radtow of this hyde_eddytow.
     *
     * @return the std_u_radtow of this hyde_eddytow
     */
    public float getStd_u_radtow();

    /**
     * Sets the std_u_radtow of this hyde_eddytow.
     *
     * @param std_u_radtow the std_u_radtow of this hyde_eddytow
     */
    public void setStd_u_radtow(float std_u_radtow);

    /**
     * Returns the std_u_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the std_u_radtow_ e m e p of this hyde_eddytow
     */
    public int getStd_u_radtow_EMEP();

    /**
     * Sets the std_u_radtow_ e m e p of this hyde_eddytow.
     *
     * @param std_u_radtow_EMEP the std_u_radtow_ e m e p of this hyde_eddytow
     */
    public void setStd_u_radtow_EMEP(int std_u_radtow_EMEP);

    /**
     * Returns the std_v_radtow of this hyde_eddytow.
     *
     * @return the std_v_radtow of this hyde_eddytow
     */
    public float getStd_v_radtow();

    /**
     * Sets the std_v_radtow of this hyde_eddytow.
     *
     * @param std_v_radtow the std_v_radtow of this hyde_eddytow
     */
    public void setStd_v_radtow(float std_v_radtow);

    /**
     * Returns the std_v_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the std_v_radtow_ e m e p of this hyde_eddytow
     */
    public int getStd_v_radtow_EMEP();

    /**
     * Sets the std_v_radtow_ e m e p of this hyde_eddytow.
     *
     * @param std_v_radtow_EMEP the std_v_radtow_ e m e p of this hyde_eddytow
     */
    public void setStd_v_radtow_EMEP(int std_v_radtow_EMEP);

    /**
     * Returns the std_w_radtow of this hyde_eddytow.
     *
     * @return the std_w_radtow of this hyde_eddytow
     */
    public float getStd_w_radtow();

    /**
     * Sets the std_w_radtow of this hyde_eddytow.
     *
     * @param std_w_radtow the std_w_radtow of this hyde_eddytow
     */
    public void setStd_w_radtow(float std_w_radtow);

    /**
     * Returns the std_w_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the std_w_radtow_ e m e p of this hyde_eddytow
     */
    public int getStd_w_radtow_EMEP();

    /**
     * Sets the std_w_radtow_ e m e p of this hyde_eddytow.
     *
     * @param std_w_radtow_EMEP the std_w_radtow_ e m e p of this hyde_eddytow
     */
    public void setStd_w_radtow_EMEP(int std_w_radtow_EMEP);

    /**
     * Returns the std_t_radtow of this hyde_eddytow.
     *
     * @return the std_t_radtow of this hyde_eddytow
     */
    public float getStd_t_radtow();

    /**
     * Sets the std_t_radtow of this hyde_eddytow.
     *
     * @param std_t_radtow the std_t_radtow of this hyde_eddytow
     */
    public void setStd_t_radtow(float std_t_radtow);

    /**
     * Returns the std_t_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the std_t_radtow_ e m e p of this hyde_eddytow
     */
    public int getStd_t_radtow_EMEP();

    /**
     * Sets the std_t_radtow_ e m e p of this hyde_eddytow.
     *
     * @param std_t_radtow_EMEP the std_t_radtow_ e m e p of this hyde_eddytow
     */
    public void setStd_t_radtow_EMEP(int std_t_radtow_EMEP);

    /**
     * Returns the std_c_radtow of this hyde_eddytow.
     *
     * @return the std_c_radtow of this hyde_eddytow
     */
    public float getStd_c_radtow();

    /**
     * Sets the std_c_radtow of this hyde_eddytow.
     *
     * @param std_c_radtow the std_c_radtow of this hyde_eddytow
     */
    public void setStd_c_radtow(float std_c_radtow);

    /**
     * Returns the std_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the std_c_radtow_ e m e p of this hyde_eddytow
     */
    public int getStd_c_radtow_EMEP();

    /**
     * Sets the std_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @param std_c_radtow_EMEP the std_c_radtow_ e m e p of this hyde_eddytow
     */
    public void setStd_c_radtow_EMEP(int std_c_radtow_EMEP);

    /**
     * Returns the std_h_radtow of this hyde_eddytow.
     *
     * @return the std_h_radtow of this hyde_eddytow
     */
    public float getStd_h_radtow();

    /**
     * Sets the std_h_radtow of this hyde_eddytow.
     *
     * @param std_h_radtow the std_h_radtow of this hyde_eddytow
     */
    public void setStd_h_radtow(float std_h_radtow);

    /**
     * Returns the std_h_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the std_h_radtow_ e m e p of this hyde_eddytow
     */
    public int getStd_h_radtow_EMEP();

    /**
     * Sets the std_h_radtow_ e m e p of this hyde_eddytow.
     *
     * @param std_h_radtow_EMEP the std_h_radtow_ e m e p of this hyde_eddytow
     */
    public void setStd_h_radtow_EMEP(int std_h_radtow_EMEP);

    /**
     * Returns the av_u_radtow of this hyde_eddytow.
     *
     * @return the av_u_radtow of this hyde_eddytow
     */
    public float getAv_u_radtow();

    /**
     * Sets the av_u_radtow of this hyde_eddytow.
     *
     * @param av_u_radtow the av_u_radtow of this hyde_eddytow
     */
    public void setAv_u_radtow(float av_u_radtow);

    /**
     * Returns the av_u_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the av_u_radtow_ e m e p of this hyde_eddytow
     */
    public int getAv_u_radtow_EMEP();

    /**
     * Sets the av_u_radtow_ e m e p of this hyde_eddytow.
     *
     * @param av_u_radtow_EMEP the av_u_radtow_ e m e p of this hyde_eddytow
     */
    public void setAv_u_radtow_EMEP(int av_u_radtow_EMEP);

    /**
     * Returns the av_v_radtow of this hyde_eddytow.
     *
     * @return the av_v_radtow of this hyde_eddytow
     */
    public float getAv_v_radtow();

    /**
     * Sets the av_v_radtow of this hyde_eddytow.
     *
     * @param av_v_radtow the av_v_radtow of this hyde_eddytow
     */
    public void setAv_v_radtow(float av_v_radtow);

    /**
     * Returns the av_v_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the av_v_radtow_ e m e p of this hyde_eddytow
     */
    public int getAv_v_radtow_EMEP();

    /**
     * Sets the av_v_radtow_ e m e p of this hyde_eddytow.
     *
     * @param av_v_radtow_EMEP the av_v_radtow_ e m e p of this hyde_eddytow
     */
    public void setAv_v_radtow_EMEP(int av_v_radtow_EMEP);

    /**
     * Returns the av_w_radtow of this hyde_eddytow.
     *
     * @return the av_w_radtow of this hyde_eddytow
     */
    public float getAv_w_radtow();

    /**
     * Sets the av_w_radtow of this hyde_eddytow.
     *
     * @param av_w_radtow the av_w_radtow of this hyde_eddytow
     */
    public void setAv_w_radtow(float av_w_radtow);

    /**
     * Returns the av_w_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the av_w_radtow_ e m e p of this hyde_eddytow
     */
    public int getAv_w_radtow_EMEP();

    /**
     * Sets the av_w_radtow_ e m e p of this hyde_eddytow.
     *
     * @param av_w_radtow_EMEP the av_w_radtow_ e m e p of this hyde_eddytow
     */
    public void setAv_w_radtow_EMEP(int av_w_radtow_EMEP);

    /**
     * Returns the av_t_radtow of this hyde_eddytow.
     *
     * @return the av_t_radtow of this hyde_eddytow
     */
    public float getAv_t_radtow();

    /**
     * Sets the av_t_radtow of this hyde_eddytow.
     *
     * @param av_t_radtow the av_t_radtow of this hyde_eddytow
     */
    public void setAv_t_radtow(float av_t_radtow);

    /**
     * Returns the av_t_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the av_t_radtow_ e m e p of this hyde_eddytow
     */
    public int getAv_t_radtow_EMEP();

    /**
     * Sets the av_t_radtow_ e m e p of this hyde_eddytow.
     *
     * @param av_t_radtow_EMEP the av_t_radtow_ e m e p of this hyde_eddytow
     */
    public void setAv_t_radtow_EMEP(int av_t_radtow_EMEP);

    /**
     * Returns the av_c_radtow of this hyde_eddytow.
     *
     * @return the av_c_radtow of this hyde_eddytow
     */
    public float getAv_c_radtow();

    /**
     * Sets the av_c_radtow of this hyde_eddytow.
     *
     * @param av_c_radtow the av_c_radtow of this hyde_eddytow
     */
    public void setAv_c_radtow(float av_c_radtow);

    /**
     * Returns the av_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the av_c_radtow_ e m e p of this hyde_eddytow
     */
    public int getAv_c_radtow_EMEP();

    /**
     * Sets the av_c_radtow_ e m e p of this hyde_eddytow.
     *
     * @param av_c_radtow_EMEP the av_c_radtow_ e m e p of this hyde_eddytow
     */
    public void setAv_c_radtow_EMEP(int av_c_radtow_EMEP);

    /**
     * Returns the av_h_radtow of this hyde_eddytow.
     *
     * @return the av_h_radtow of this hyde_eddytow
     */
    public float getAv_h_radtow();

    /**
     * Sets the av_h_radtow of this hyde_eddytow.
     *
     * @param av_h_radtow the av_h_radtow of this hyde_eddytow
     */
    public void setAv_h_radtow(float av_h_radtow);

    /**
     * Returns the av_h_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the av_h_radtow_ e m e p of this hyde_eddytow
     */
    public int getAv_h_radtow_EMEP();

    /**
     * Sets the av_h_radtow_ e m e p of this hyde_eddytow.
     *
     * @param av_h_radtow_EMEP the av_h_radtow_ e m e p of this hyde_eddytow
     */
    public void setAv_h_radtow_EMEP(int av_h_radtow_EMEP);

    /**
     * Returns the u_radtow of this hyde_eddytow.
     *
     * @return the u_radtow of this hyde_eddytow
     */
    public float getU_radtow();

    /**
     * Sets the u_radtow of this hyde_eddytow.
     *
     * @param U_radtow the u_radtow of this hyde_eddytow
     */
    public void setU_radtow(float U_radtow);

    /**
     * Returns the u_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the u_radtow_ e m e p of this hyde_eddytow
     */
    public int getU_radtow_EMEP();

    /**
     * Sets the u_radtow_ e m e p of this hyde_eddytow.
     *
     * @param U_radtow_EMEP the u_radtow_ e m e p of this hyde_eddytow
     */
    public void setU_radtow_EMEP(int U_radtow_EMEP);

    /**
     * Returns the wind_dir_radtow of this hyde_eddytow.
     *
     * @return the wind_dir_radtow of this hyde_eddytow
     */
    public float getWind_dir_radtow();

    /**
     * Sets the wind_dir_radtow of this hyde_eddytow.
     *
     * @param wind_dir_radtow the wind_dir_radtow of this hyde_eddytow
     */
    public void setWind_dir_radtow(float wind_dir_radtow);

    /**
     * Returns the wind_dir_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the wind_dir_radtow_ e m e p of this hyde_eddytow
     */
    public int getWind_dir_radtow_EMEP();

    /**
     * Sets the wind_dir_radtow_ e m e p of this hyde_eddytow.
     *
     * @param wind_dir_radtow_EMEP the wind_dir_radtow_ e m e p of this hyde_eddytow
     */
    public void setWind_dir_radtow_EMEP(int wind_dir_radtow_EMEP);

    /**
     * Returns the eta_radtow of this hyde_eddytow.
     *
     * @return the eta_radtow of this hyde_eddytow
     */
    public float getEta_radtow();

    /**
     * Sets the eta_radtow of this hyde_eddytow.
     *
     * @param eta_radtow the eta_radtow of this hyde_eddytow
     */
    public void setEta_radtow(float eta_radtow);

    /**
     * Returns the eta_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the eta_radtow_ e m e p of this hyde_eddytow
     */
    public int getEta_radtow_EMEP();

    /**
     * Sets the eta_radtow_ e m e p of this hyde_eddytow.
     *
     * @param eta_radtow_EMEP the eta_radtow_ e m e p of this hyde_eddytow
     */
    public void setEta_radtow_EMEP(int eta_radtow_EMEP);

    /**
     * Returns the theta_radtow of this hyde_eddytow.
     *
     * @return the theta_radtow of this hyde_eddytow
     */
    public float getTheta_radtow();

    /**
     * Sets the theta_radtow of this hyde_eddytow.
     *
     * @param theta_radtow the theta_radtow of this hyde_eddytow
     */
    public void setTheta_radtow(float theta_radtow);

    /**
     * Returns the theta_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the theta_radtow_ e m e p of this hyde_eddytow
     */
    public int getTheta_radtow_EMEP();

    /**
     * Sets the theta_radtow_ e m e p of this hyde_eddytow.
     *
     * @param theta_radtow_EMEP the theta_radtow_ e m e p of this hyde_eddytow
     */
    public void setTheta_radtow_EMEP(int theta_radtow_EMEP);

    /**
     * Returns the beta_radtow of this hyde_eddytow.
     *
     * @return the beta_radtow of this hyde_eddytow
     */
    public float getBeta_radtow();

    /**
     * Sets the beta_radtow of this hyde_eddytow.
     *
     * @param beta_radtow the beta_radtow of this hyde_eddytow
     */
    public void setBeta_radtow(float beta_radtow);

    /**
     * Returns the beta_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the beta_radtow_ e m e p of this hyde_eddytow
     */
    public int getBeta_radtow_EMEP();

    /**
     * Sets the beta_radtow_ e m e p of this hyde_eddytow.
     *
     * @param beta_radtow_EMEP the beta_radtow_ e m e p of this hyde_eddytow
     */
    public void setBeta_radtow_EMEP(int beta_radtow_EMEP);

    /**
     * Returns the c_lag_radtow of this hyde_eddytow.
     *
     * @return the c_lag_radtow of this hyde_eddytow
     */
    public float getC_lag_radtow();

    /**
     * Sets the c_lag_radtow of this hyde_eddytow.
     *
     * @param c_lag_radtow the c_lag_radtow of this hyde_eddytow
     */
    public void setC_lag_radtow(float c_lag_radtow);

    /**
     * Returns the c_lag_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the c_lag_radtow_ e m e p of this hyde_eddytow
     */
    public int getC_lag_radtow_EMEP();

    /**
     * Sets the c_lag_radtow_ e m e p of this hyde_eddytow.
     *
     * @param c_lag_radtow_EMEP the c_lag_radtow_ e m e p of this hyde_eddytow
     */
    public void setC_lag_radtow_EMEP(int c_lag_radtow_EMEP);

    /**
     * Returns the h_lag_radtow of this hyde_eddytow.
     *
     * @return the h_lag_radtow of this hyde_eddytow
     */
    public float getH_lag_radtow();

    /**
     * Sets the h_lag_radtow of this hyde_eddytow.
     *
     * @param h_lag_radtow the h_lag_radtow of this hyde_eddytow
     */
    public void setH_lag_radtow(float h_lag_radtow);

    /**
     * Returns the h_lag_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the h_lag_radtow_ e m e p of this hyde_eddytow
     */
    public int getH_lag_radtow_EMEP();

    /**
     * Sets the h_lag_radtow_ e m e p of this hyde_eddytow.
     *
     * @param h_lag_radtow_EMEP the h_lag_radtow_ e m e p of this hyde_eddytow
     */
    public void setH_lag_radtow_EMEP(int h_lag_radtow_EMEP);

    /**
     * Returns the err_packet_radtow of this hyde_eddytow.
     *
     * @return the err_packet_radtow of this hyde_eddytow
     */
    public float getErr_packet_radtow();

    /**
     * Sets the err_packet_radtow of this hyde_eddytow.
     *
     * @param err_packet_radtow the err_packet_radtow of this hyde_eddytow
     */
    public void setErr_packet_radtow(float err_packet_radtow);

    /**
     * Returns the err_packet_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the err_packet_radtow_ e m e p of this hyde_eddytow
     */
    public int getErr_packet_radtow_EMEP();

    /**
     * Sets the err_packet_radtow_ e m e p of this hyde_eddytow.
     *
     * @param err_packet_radtow_EMEP the err_packet_radtow_ e m e p of this hyde_eddytow
     */
    public void setErr_packet_radtow_EMEP(int err_packet_radtow_EMEP);

    /**
     * Returns the licor_t_std_radtow of this hyde_eddytow.
     *
     * @return the licor_t_std_radtow of this hyde_eddytow
     */
    public float getLicor_t_std_radtow();

    /**
     * Sets the licor_t_std_radtow of this hyde_eddytow.
     *
     * @param licor_t_std_radtow the licor_t_std_radtow of this hyde_eddytow
     */
    public void setLicor_t_std_radtow(float licor_t_std_radtow);

    /**
     * Returns the licor_t_std_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the licor_t_std_radtow_ e m e p of this hyde_eddytow
     */
    public int getLicor_t_std_radtow_EMEP();

    /**
     * Sets the licor_t_std_radtow_ e m e p of this hyde_eddytow.
     *
     * @param licor_t_std_radtow_EMEP the licor_t_std_radtow_ e m e p of this hyde_eddytow
     */
    public void setLicor_t_std_radtow_EMEP(int licor_t_std_radtow_EMEP);

    /**
     * Returns the licor_t_av_radtow of this hyde_eddytow.
     *
     * @return the licor_t_av_radtow of this hyde_eddytow
     */
    public float getLicor_t_av_radtow();

    /**
     * Sets the licor_t_av_radtow of this hyde_eddytow.
     *
     * @param licor_t_av_radtow the licor_t_av_radtow of this hyde_eddytow
     */
    public void setLicor_t_av_radtow(float licor_t_av_radtow);

    /**
     * Returns the licor_t_av_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the licor_t_av_radtow_ e m e p of this hyde_eddytow
     */
    public int getLicor_t_av_radtow_EMEP();

    /**
     * Sets the licor_t_av_radtow_ e m e p of this hyde_eddytow.
     *
     * @param licor_t_av_radtow_EMEP the licor_t_av_radtow_ e m e p of this hyde_eddytow
     */
    public void setLicor_t_av_radtow_EMEP(int licor_t_av_radtow_EMEP);

    /**
     * Returns the licor_p_std_radtow of this hyde_eddytow.
     *
     * @return the licor_p_std_radtow of this hyde_eddytow
     */
    public float getLicor_p_std_radtow();

    /**
     * Sets the licor_p_std_radtow of this hyde_eddytow.
     *
     * @param licor_p_std_radtow the licor_p_std_radtow of this hyde_eddytow
     */
    public void setLicor_p_std_radtow(float licor_p_std_radtow);

    /**
     * Returns the licor_p_std_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the licor_p_std_radtow_ e m e p of this hyde_eddytow
     */
    public int getLicor_p_std_radtow_EMEP();

    /**
     * Sets the licor_p_std_radtow_ e m e p of this hyde_eddytow.
     *
     * @param licor_p_std_radtow_EMEP the licor_p_std_radtow_ e m e p of this hyde_eddytow
     */
    public void setLicor_p_std_radtow_EMEP(int licor_p_std_radtow_EMEP);

    /**
     * Returns the licor_p_av_radtow of this hyde_eddytow.
     *
     * @return the licor_p_av_radtow of this hyde_eddytow
     */
    public float getLicor_p_av_radtow();

    /**
     * Sets the licor_p_av_radtow of this hyde_eddytow.
     *
     * @param licor_p_av_radtow the licor_p_av_radtow of this hyde_eddytow
     */
    public void setLicor_p_av_radtow(float licor_p_av_radtow);

    /**
     * Returns the licor_p_av_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the licor_p_av_radtow_ e m e p of this hyde_eddytow
     */
    public int getLicor_p_av_radtow_EMEP();

    /**
     * Sets the licor_p_av_radtow_ e m e p of this hyde_eddytow.
     *
     * @param licor_p_av_radtow_EMEP the licor_p_av_radtow_ e m e p of this hyde_eddytow
     */
    public void setLicor_p_av_radtow_EMEP(int licor_p_av_radtow_EMEP);

    /**
     * Returns the f_ o3_radtow of this hyde_eddytow.
     *
     * @return the f_ o3_radtow of this hyde_eddytow
     */
    public float getF_O3_radtow();

    /**
     * Sets the f_ o3_radtow of this hyde_eddytow.
     *
     * @param F_O3_radtow the f_ o3_radtow of this hyde_eddytow
     */
    public void setF_O3_radtow(float F_O3_radtow);

    /**
     * Returns the f_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the f_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public int getF_O3_radtow_EMEP();

    /**
     * Sets the f_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @param F_O3_radtow_EMEP the f_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public void setF_O3_radtow_EMEP(int F_O3_radtow_EMEP);

    /**
     * Returns the qc_ f_ o3_radtow of this hyde_eddytow.
     *
     * @return the qc_ f_ o3_radtow of this hyde_eddytow
     */
    public int getQc_F_O3_radtow();

    /**
     * Sets the qc_ f_ o3_radtow of this hyde_eddytow.
     *
     * @param Qc_F_O3_radtow the qc_ f_ o3_radtow of this hyde_eddytow
     */
    public void setQc_F_O3_radtow(int Qc_F_O3_radtow);

    /**
     * Returns the qc_ f_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the qc_ f_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public int getQc_F_O3_radtow_EMEP();

    /**
     * Sets the qc_ f_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @param Qc_F_O3_radtow_EMEP the qc_ f_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public void setQc_F_O3_radtow_EMEP(int Qc_F_O3_radtow_EMEP);

    /**
     * Returns the std_ o3_radtow of this hyde_eddytow.
     *
     * @return the std_ o3_radtow of this hyde_eddytow
     */
    public float getStd_O3_radtow();

    /**
     * Sets the std_ o3_radtow of this hyde_eddytow.
     *
     * @param std_O3_radtow the std_ o3_radtow of this hyde_eddytow
     */
    public void setStd_O3_radtow(float std_O3_radtow);

    /**
     * Returns the std_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the std_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public int getStd_O3_radtow_EMEP();

    /**
     * Sets the std_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @param std_O3_radtow_EMEP the std_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public void setStd_O3_radtow_EMEP(int std_O3_radtow_EMEP);

    /**
     * Returns the av_ o3_radtow of this hyde_eddytow.
     *
     * @return the av_ o3_radtow of this hyde_eddytow
     */
    public float getAv_O3_radtow();

    /**
     * Sets the av_ o3_radtow of this hyde_eddytow.
     *
     * @param av_O3_radtow the av_ o3_radtow of this hyde_eddytow
     */
    public void setAv_O3_radtow(float av_O3_radtow);

    /**
     * Returns the av_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the av_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public int getAv_O3_radtow_EMEP();

    /**
     * Sets the av_ o3_radtow_ e m e p of this hyde_eddytow.
     *
     * @param av_O3_radtow_EMEP the av_ o3_radtow_ e m e p of this hyde_eddytow
     */
    public void setAv_O3_radtow_EMEP(int av_O3_radtow_EMEP);

    /**
     * Returns the o3_lag_radtow of this hyde_eddytow.
     *
     * @return the o3_lag_radtow of this hyde_eddytow
     */
    public float getO3_lag_radtow();

    /**
     * Sets the o3_lag_radtow of this hyde_eddytow.
     *
     * @param O3_lag_radtow the o3_lag_radtow of this hyde_eddytow
     */
    public void setO3_lag_radtow(float O3_lag_radtow);

    /**
     * Returns the o3_lag_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the o3_lag_radtow_ e m e p of this hyde_eddytow
     */
    public int getO3_lag_radtow_EMEP();

    /**
     * Sets the o3_lag_radtow_ e m e p of this hyde_eddytow.
     *
     * @param O3_lag_radtow_EMEP the o3_lag_radtow_ e m e p of this hyde_eddytow
     */
    public void setO3_lag_radtow_EMEP(int O3_lag_radtow_EMEP);

    /**
     * Returns the n e e_radtow of this hyde_eddytow.
     *
     * @return the n e e_radtow of this hyde_eddytow
     */
    public float getNEE_radtow();

    /**
     * Sets the n e e_radtow of this hyde_eddytow.
     *
     * @param NEE_radtow the n e e_radtow of this hyde_eddytow
     */
    public void setNEE_radtow(float NEE_radtow);

    /**
     * Returns the n e e_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the n e e_radtow_ e m e p of this hyde_eddytow
     */
    public int getNEE_radtow_EMEP();

    /**
     * Sets the n e e_radtow_ e m e p of this hyde_eddytow.
     *
     * @param NEE_radtow_EMEP the n e e_radtow_ e m e p of this hyde_eddytow
     */
    public void setNEE_radtow_EMEP(int NEE_radtow_EMEP);

    /**
     * Returns the qc_gapf_ n e e_radtow of this hyde_eddytow.
     *
     * @return the qc_gapf_ n e e_radtow of this hyde_eddytow
     */
    public int getQc_gapf_NEE_radtow();

    /**
     * Sets the qc_gapf_ n e e_radtow of this hyde_eddytow.
     *
     * @param Qc_gapf_NEE_radtow the qc_gapf_ n e e_radtow of this hyde_eddytow
     */
    public void setQc_gapf_NEE_radtow(int Qc_gapf_NEE_radtow);

    /**
     * Returns the qc_gapf_ n e e_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the qc_gapf_ n e e_radtow_ e m e p of this hyde_eddytow
     */
    public int getQc_gapf_NEE_radtow_EMEP();

    /**
     * Sets the qc_gapf_ n e e_radtow_ e m e p of this hyde_eddytow.
     *
     * @param Qc_gapf_NEE_radtow_EMEP the qc_gapf_ n e e_radtow_ e m e p of this hyde_eddytow
     */
    public void setQc_gapf_NEE_radtow_EMEP(int Qc_gapf_NEE_radtow_EMEP);

    /**
     * Returns the g p p_radtow of this hyde_eddytow.
     *
     * @return the g p p_radtow of this hyde_eddytow
     */
    public float getGPP_radtow();

    /**
     * Sets the g p p_radtow of this hyde_eddytow.
     *
     * @param GPP_radtow the g p p_radtow of this hyde_eddytow
     */
    public void setGPP_radtow(float GPP_radtow);

    /**
     * Returns the g p p_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the g p p_radtow_ e m e p of this hyde_eddytow
     */
    public int getGPP_radtow_EMEP();

    /**
     * Sets the g p p_radtow_ e m e p of this hyde_eddytow.
     *
     * @param GPP_radtow_EMEP the g p p_radtow_ e m e p of this hyde_eddytow
     */
    public void setGPP_radtow_EMEP(int GPP_radtow_EMEP);

    /**
     * Returns the t e r_radtow of this hyde_eddytow.
     *
     * @return the t e r_radtow of this hyde_eddytow
     */
    public float getTER_radtow();

    /**
     * Sets the t e r_radtow of this hyde_eddytow.
     *
     * @param TER_radtow the t e r_radtow of this hyde_eddytow
     */
    public void setTER_radtow(float TER_radtow);

    /**
     * Returns the t e r_radtow_ e m e p of this hyde_eddytow.
     *
     * @return the t e r_radtow_ e m e p of this hyde_eddytow
     */
    public int getTER_radtow_EMEP();

    /**
     * Sets the t e r_radtow_ e m e p of this hyde_eddytow.
     *
     * @param TER_radtow_EMEP the t e r_radtow_ e m e p of this hyde_eddytow
     */
    public void setTER_radtow_EMEP(int TER_radtow_EMEP);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Hyde_eddytow hyde_eddytow);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Hyde_eddytow> toCacheModel();

    @Override
    public Hyde_eddytow toEscapedModel();

    @Override
    public Hyde_eddytow toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
