package fi.csc.smear.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Kumpula_eddy service. Represents a row in the &quot;KUM_EDDY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.smear.db.model.impl.Kumpula_eddyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.smear.db.model.impl.Kumpula_eddyImpl}.
 * </p>
 *
 * @author pj
 * @see Kumpula_eddy
 * @see fi.csc.smear.db.model.impl.Kumpula_eddyImpl
 * @see fi.csc.smear.db.model.impl.Kumpula_eddyModelImpl
 * @generated
 */
public interface Kumpula_eddyModel extends BaseModel<Kumpula_eddy> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a kumpula_eddy model instance should use the {@link Kumpula_eddy} interface instead.
     */

    /**
     * Returns the primary key of this kumpula_eddy.
     *
     * @return the primary key of this kumpula_eddy
     */
    public java.util.Date getPrimaryKey();

    /**
     * Sets the primary key of this kumpula_eddy.
     *
     * @param primaryKey the primary key of this kumpula_eddy
     */
    public void setPrimaryKey(java.util.Date primaryKey);

    /**
     * Returns the samptime of this kumpula_eddy.
     *
     * @return the samptime of this kumpula_eddy
     */
    public Date getSamptime();

    /**
     * Sets the samptime of this kumpula_eddy.
     *
     * @param samptime the samptime of this kumpula_eddy
     */
    public void setSamptime(Date samptime);

    /**
     * Returns the h of this kumpula_eddy.
     *
     * @return the h of this kumpula_eddy
     */
    public int getH();

    /**
     * Sets the h of this kumpula_eddy.
     *
     * @param H the h of this kumpula_eddy
     */
    public void setH(int H);

    /**
     * Returns the h_ e m e p of this kumpula_eddy.
     *
     * @return the h_ e m e p of this kumpula_eddy
     */
    public int getH_EMEP();

    /**
     * Sets the h_ e m e p of this kumpula_eddy.
     *
     * @param H_EMEP the h_ e m e p of this kumpula_eddy
     */
    public void setH_EMEP(int H_EMEP);

    /**
     * Returns the qc_ h of this kumpula_eddy.
     *
     * @return the qc_ h of this kumpula_eddy
     */
    public int getQc_H();

    /**
     * Sets the qc_ h of this kumpula_eddy.
     *
     * @param Qc_H the qc_ h of this kumpula_eddy
     */
    public void setQc_H(int Qc_H);

    /**
     * Returns the qc_ h_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ h_ e m e p of this kumpula_eddy
     */
    public int getQc_H_EMEP();

    /**
     * Sets the qc_ h_ e m e p of this kumpula_eddy.
     *
     * @param Qc_H_EMEP the qc_ h_ e m e p of this kumpula_eddy
     */
    public void setQc_H_EMEP(int Qc_H_EMEP);

    /**
     * Returns the l e of this kumpula_eddy.
     *
     * @return the l e of this kumpula_eddy
     */
    public float getLE();

    /**
     * Sets the l e of this kumpula_eddy.
     *
     * @param LE the l e of this kumpula_eddy
     */
    public void setLE(float LE);

    /**
     * Returns the l e_ e m e p of this kumpula_eddy.
     *
     * @return the l e_ e m e p of this kumpula_eddy
     */
    public int getLE_EMEP();

    /**
     * Sets the l e_ e m e p of this kumpula_eddy.
     *
     * @param LE_EMEP the l e_ e m e p of this kumpula_eddy
     */
    public void setLE_EMEP(int LE_EMEP);

    /**
     * Returns the qc_ l e of this kumpula_eddy.
     *
     * @return the qc_ l e of this kumpula_eddy
     */
    public int getQc_LE();

    /**
     * Sets the qc_ l e of this kumpula_eddy.
     *
     * @param Qc_LE the qc_ l e of this kumpula_eddy
     */
    public void setQc_LE(int Qc_LE);

    /**
     * Returns the qc_ l e_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ l e_ e m e p of this kumpula_eddy
     */
    public int getQc_LE_EMEP();

    /**
     * Sets the qc_ l e_ e m e p of this kumpula_eddy.
     *
     * @param Qc_LE_EMEP the qc_ l e_ e m e p of this kumpula_eddy
     */
    public void setQc_LE_EMEP(int Qc_LE_EMEP);

    /**
     * Returns the e of this kumpula_eddy.
     *
     * @return the e of this kumpula_eddy
     */
    public float getE();

    /**
     * Sets the e of this kumpula_eddy.
     *
     * @param E the e of this kumpula_eddy
     */
    public void setE(float E);

    /**
     * Returns the e_ e m e p of this kumpula_eddy.
     *
     * @return the e_ e m e p of this kumpula_eddy
     */
    public int getE_EMEP();

    /**
     * Sets the e_ e m e p of this kumpula_eddy.
     *
     * @param E_EMEP the e_ e m e p of this kumpula_eddy
     */
    public void setE_EMEP(int E_EMEP);

    /**
     * Returns the qc_ e of this kumpula_eddy.
     *
     * @return the qc_ e of this kumpula_eddy
     */
    public int getQc_E();

    /**
     * Sets the qc_ e of this kumpula_eddy.
     *
     * @param Qc_E the qc_ e of this kumpula_eddy
     */
    public void setQc_E(int Qc_E);

    /**
     * Returns the qc_ e_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ e_ e m e p of this kumpula_eddy
     */
    public int getQc_E_EMEP();

    /**
     * Sets the qc_ e_ e m e p of this kumpula_eddy.
     *
     * @param Qc_E_EMEP the qc_ e_ e m e p of this kumpula_eddy
     */
    public void setQc_E_EMEP(int Qc_E_EMEP);

    /**
     * Returns the f_c of this kumpula_eddy.
     *
     * @return the f_c of this kumpula_eddy
     */
    public float getF_c();

    /**
     * Sets the f_c of this kumpula_eddy.
     *
     * @param F_c the f_c of this kumpula_eddy
     */
    public void setF_c(float F_c);

    /**
     * Returns the f_c_ e m e p of this kumpula_eddy.
     *
     * @return the f_c_ e m e p of this kumpula_eddy
     */
    public int getF_c_EMEP();

    /**
     * Sets the f_c_ e m e p of this kumpula_eddy.
     *
     * @param F_c_EMEP the f_c_ e m e p of this kumpula_eddy
     */
    public void setF_c_EMEP(int F_c_EMEP);

    /**
     * Returns the qc_ f_c of this kumpula_eddy.
     *
     * @return the qc_ f_c of this kumpula_eddy
     */
    public int getQc_F_c();

    /**
     * Sets the qc_ f_c of this kumpula_eddy.
     *
     * @param Qc_F_c the qc_ f_c of this kumpula_eddy
     */
    public void setQc_F_c(int Qc_F_c);

    /**
     * Returns the qc_ f_c_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ f_c_ e m e p of this kumpula_eddy
     */
    public int getQc_F_c_EMEP();

    /**
     * Sets the qc_ f_c_ e m e p of this kumpula_eddy.
     *
     * @param Qc_F_c_EMEP the qc_ f_c_ e m e p of this kumpula_eddy
     */
    public void setQc_F_c_EMEP(int Qc_F_c_EMEP);

    /**
     * Returns the tau of this kumpula_eddy.
     *
     * @return the tau of this kumpula_eddy
     */
    public float getTau();

    /**
     * Sets the tau of this kumpula_eddy.
     *
     * @param tau the tau of this kumpula_eddy
     */
    public void setTau(float tau);

    /**
     * Returns the tau_ e m e p of this kumpula_eddy.
     *
     * @return the tau_ e m e p of this kumpula_eddy
     */
    public int getTau_EMEP();

    /**
     * Sets the tau_ e m e p of this kumpula_eddy.
     *
     * @param tau_EMEP the tau_ e m e p of this kumpula_eddy
     */
    public void setTau_EMEP(int tau_EMEP);

    /**
     * Returns the qc_tau of this kumpula_eddy.
     *
     * @return the qc_tau of this kumpula_eddy
     */
    public int getQc_tau();

    /**
     * Sets the qc_tau of this kumpula_eddy.
     *
     * @param Qc_tau the qc_tau of this kumpula_eddy
     */
    public void setQc_tau(int Qc_tau);

    /**
     * Returns the qc_tau_ e m e p of this kumpula_eddy.
     *
     * @return the qc_tau_ e m e p of this kumpula_eddy
     */
    public int getQc_tau_EMEP();

    /**
     * Sets the qc_tau_ e m e p of this kumpula_eddy.
     *
     * @param Qc_tau_EMEP the qc_tau_ e m e p of this kumpula_eddy
     */
    public void setQc_tau_EMEP(int Qc_tau_EMEP);

    /**
     * Returns the u_star of this kumpula_eddy.
     *
     * @return the u_star of this kumpula_eddy
     */
    public float getU_star();

    /**
     * Sets the u_star of this kumpula_eddy.
     *
     * @param u_star the u_star of this kumpula_eddy
     */
    public void setU_star(float u_star);

    /**
     * Returns the u_star_ e m e p of this kumpula_eddy.
     *
     * @return the u_star_ e m e p of this kumpula_eddy
     */
    public int getU_star_EMEP();

    /**
     * Sets the u_star_ e m e p of this kumpula_eddy.
     *
     * @param u_star_EMEP the u_star_ e m e p of this kumpula_eddy
     */
    public void setU_star_EMEP(int u_star_EMEP);

    /**
     * Returns the m o_length of this kumpula_eddy.
     *
     * @return the m o_length of this kumpula_eddy
     */
    public float getMO_length();

    /**
     * Sets the m o_length of this kumpula_eddy.
     *
     * @param MO_length the m o_length of this kumpula_eddy
     */
    public void setMO_length(float MO_length);

    /**
     * Returns the m o_length_ e m e p of this kumpula_eddy.
     *
     * @return the m o_length_ e m e p of this kumpula_eddy
     */
    public int getMO_length_EMEP();

    /**
     * Sets the m o_length_ e m e p of this kumpula_eddy.
     *
     * @param MO_length_EMEP the m o_length_ e m e p of this kumpula_eddy
     */
    public void setMO_length_EMEP(int MO_length_EMEP);

    /**
     * Returns the std_u of this kumpula_eddy.
     *
     * @return the std_u of this kumpula_eddy
     */
    public float getStd_u();

    /**
     * Sets the std_u of this kumpula_eddy.
     *
     * @param std_u the std_u of this kumpula_eddy
     */
    public void setStd_u(float std_u);

    /**
     * Returns the std_u_ e m e p of this kumpula_eddy.
     *
     * @return the std_u_ e m e p of this kumpula_eddy
     */
    public int getStd_u_EMEP();

    /**
     * Sets the std_u_ e m e p of this kumpula_eddy.
     *
     * @param std_u_EMEP the std_u_ e m e p of this kumpula_eddy
     */
    public void setStd_u_EMEP(int std_u_EMEP);

    /**
     * Returns the std_v of this kumpula_eddy.
     *
     * @return the std_v of this kumpula_eddy
     */
    public float getStd_v();

    /**
     * Sets the std_v of this kumpula_eddy.
     *
     * @param std_v the std_v of this kumpula_eddy
     */
    public void setStd_v(float std_v);

    /**
     * Returns the std_v_ e m e p of this kumpula_eddy.
     *
     * @return the std_v_ e m e p of this kumpula_eddy
     */
    public int getStd_v_EMEP();

    /**
     * Sets the std_v_ e m e p of this kumpula_eddy.
     *
     * @param std_v_EMEP the std_v_ e m e p of this kumpula_eddy
     */
    public void setStd_v_EMEP(int std_v_EMEP);

    /**
     * Returns the std_w of this kumpula_eddy.
     *
     * @return the std_w of this kumpula_eddy
     */
    public float getStd_w();

    /**
     * Sets the std_w of this kumpula_eddy.
     *
     * @param std_w the std_w of this kumpula_eddy
     */
    public void setStd_w(float std_w);

    /**
     * Returns the std_w_ e m e p of this kumpula_eddy.
     *
     * @return the std_w_ e m e p of this kumpula_eddy
     */
    public int getStd_w_EMEP();

    /**
     * Sets the std_w_ e m e p of this kumpula_eddy.
     *
     * @param std_w_EMEP the std_w_ e m e p of this kumpula_eddy
     */
    public void setStd_w_EMEP(int std_w_EMEP);

    /**
     * Returns the std_t of this kumpula_eddy.
     *
     * @return the std_t of this kumpula_eddy
     */
    public float getStd_t();

    /**
     * Sets the std_t of this kumpula_eddy.
     *
     * @param std_t the std_t of this kumpula_eddy
     */
    public void setStd_t(float std_t);

    /**
     * Returns the std_t_ e m e p of this kumpula_eddy.
     *
     * @return the std_t_ e m e p of this kumpula_eddy
     */
    public int getStd_t_EMEP();

    /**
     * Sets the std_t_ e m e p of this kumpula_eddy.
     *
     * @param std_t_EMEP the std_t_ e m e p of this kumpula_eddy
     */
    public void setStd_t_EMEP(int std_t_EMEP);

    /**
     * Returns the std_c of this kumpula_eddy.
     *
     * @return the std_c of this kumpula_eddy
     */
    public float getStd_c();

    /**
     * Sets the std_c of this kumpula_eddy.
     *
     * @param std_c the std_c of this kumpula_eddy
     */
    public void setStd_c(float std_c);

    /**
     * Returns the std_c_ e m e p of this kumpula_eddy.
     *
     * @return the std_c_ e m e p of this kumpula_eddy
     */
    public int getStd_c_EMEP();

    /**
     * Sets the std_c_ e m e p of this kumpula_eddy.
     *
     * @param std_c_EMEP the std_c_ e m e p of this kumpula_eddy
     */
    public void setStd_c_EMEP(int std_c_EMEP);

    /**
     * Returns the std_h of this kumpula_eddy.
     *
     * @return the std_h of this kumpula_eddy
     */
    public float getStd_h();

    /**
     * Sets the std_h of this kumpula_eddy.
     *
     * @param std_h the std_h of this kumpula_eddy
     */
    public void setStd_h(float std_h);

    /**
     * Returns the std_h_ e m e p of this kumpula_eddy.
     *
     * @return the std_h_ e m e p of this kumpula_eddy
     */
    public int getStd_h_EMEP();

    /**
     * Sets the std_h_ e m e p of this kumpula_eddy.
     *
     * @param std_h_EMEP the std_h_ e m e p of this kumpula_eddy
     */
    public void setStd_h_EMEP(int std_h_EMEP);

    /**
     * Returns the av_u of this kumpula_eddy.
     *
     * @return the av_u of this kumpula_eddy
     */
    public float getAv_u();

    /**
     * Sets the av_u of this kumpula_eddy.
     *
     * @param av_u the av_u of this kumpula_eddy
     */
    public void setAv_u(float av_u);

    /**
     * Returns the av_u_ e m e p of this kumpula_eddy.
     *
     * @return the av_u_ e m e p of this kumpula_eddy
     */
    public int getAv_u_EMEP();

    /**
     * Sets the av_u_ e m e p of this kumpula_eddy.
     *
     * @param av_u_EMEP the av_u_ e m e p of this kumpula_eddy
     */
    public void setAv_u_EMEP(int av_u_EMEP);

    /**
     * Returns the av_v of this kumpula_eddy.
     *
     * @return the av_v of this kumpula_eddy
     */
    public float getAv_v();

    /**
     * Sets the av_v of this kumpula_eddy.
     *
     * @param av_v the av_v of this kumpula_eddy
     */
    public void setAv_v(float av_v);

    /**
     * Returns the av_v_ e m e p of this kumpula_eddy.
     *
     * @return the av_v_ e m e p of this kumpula_eddy
     */
    public int getAv_v_EMEP();

    /**
     * Sets the av_v_ e m e p of this kumpula_eddy.
     *
     * @param av_v_EMEP the av_v_ e m e p of this kumpula_eddy
     */
    public void setAv_v_EMEP(int av_v_EMEP);

    /**
     * Returns the av_w of this kumpula_eddy.
     *
     * @return the av_w of this kumpula_eddy
     */
    public float getAv_w();

    /**
     * Sets the av_w of this kumpula_eddy.
     *
     * @param av_w the av_w of this kumpula_eddy
     */
    public void setAv_w(float av_w);

    /**
     * Returns the av_w_ e m e p of this kumpula_eddy.
     *
     * @return the av_w_ e m e p of this kumpula_eddy
     */
    public int getAv_w_EMEP();

    /**
     * Sets the av_w_ e m e p of this kumpula_eddy.
     *
     * @param av_w_EMEP the av_w_ e m e p of this kumpula_eddy
     */
    public void setAv_w_EMEP(int av_w_EMEP);

    /**
     * Returns the av_t of this kumpula_eddy.
     *
     * @return the av_t of this kumpula_eddy
     */
    public float getAv_t();

    /**
     * Sets the av_t of this kumpula_eddy.
     *
     * @param av_t the av_t of this kumpula_eddy
     */
    public void setAv_t(float av_t);

    /**
     * Returns the av_t_ e m e p of this kumpula_eddy.
     *
     * @return the av_t_ e m e p of this kumpula_eddy
     */
    public int getAv_t_EMEP();

    /**
     * Sets the av_t_ e m e p of this kumpula_eddy.
     *
     * @param av_t_EMEP the av_t_ e m e p of this kumpula_eddy
     */
    public void setAv_t_EMEP(int av_t_EMEP);

    /**
     * Returns the av_c of this kumpula_eddy.
     *
     * @return the av_c of this kumpula_eddy
     */
    public float getAv_c();

    /**
     * Sets the av_c of this kumpula_eddy.
     *
     * @param av_c the av_c of this kumpula_eddy
     */
    public void setAv_c(float av_c);

    /**
     * Returns the av_c_ e m e p of this kumpula_eddy.
     *
     * @return the av_c_ e m e p of this kumpula_eddy
     */
    public int getAv_c_EMEP();

    /**
     * Sets the av_c_ e m e p of this kumpula_eddy.
     *
     * @param av_c_EMEP the av_c_ e m e p of this kumpula_eddy
     */
    public void setAv_c_EMEP(int av_c_EMEP);

    /**
     * Returns the av_h of this kumpula_eddy.
     *
     * @return the av_h of this kumpula_eddy
     */
    public float getAv_h();

    /**
     * Sets the av_h of this kumpula_eddy.
     *
     * @param av_h the av_h of this kumpula_eddy
     */
    public void setAv_h(float av_h);

    /**
     * Returns the av_h_ e m e p of this kumpula_eddy.
     *
     * @return the av_h_ e m e p of this kumpula_eddy
     */
    public int getAv_h_EMEP();

    /**
     * Sets the av_h_ e m e p of this kumpula_eddy.
     *
     * @param av_h_EMEP the av_h_ e m e p of this kumpula_eddy
     */
    public void setAv_h_EMEP(int av_h_EMEP);

    /**
     * Returns the u of this kumpula_eddy.
     *
     * @return the u of this kumpula_eddy
     */
    public float getU();

    /**
     * Sets the u of this kumpula_eddy.
     *
     * @param U the u of this kumpula_eddy
     */
    public void setU(float U);

    /**
     * Returns the u_ e m e p of this kumpula_eddy.
     *
     * @return the u_ e m e p of this kumpula_eddy
     */
    public int getU_EMEP();

    /**
     * Sets the u_ e m e p of this kumpula_eddy.
     *
     * @param U_EMEP the u_ e m e p of this kumpula_eddy
     */
    public void setU_EMEP(int U_EMEP);

    /**
     * Returns the wind_dir of this kumpula_eddy.
     *
     * @return the wind_dir of this kumpula_eddy
     */
    public float getWind_dir();

    /**
     * Sets the wind_dir of this kumpula_eddy.
     *
     * @param wind_dir the wind_dir of this kumpula_eddy
     */
    public void setWind_dir(float wind_dir);

    /**
     * Returns the wind_dir_ e m e p of this kumpula_eddy.
     *
     * @return the wind_dir_ e m e p of this kumpula_eddy
     */
    public int getWind_dir_EMEP();

    /**
     * Sets the wind_dir_ e m e p of this kumpula_eddy.
     *
     * @param wind_dir_EMEP the wind_dir_ e m e p of this kumpula_eddy
     */
    public void setWind_dir_EMEP(int wind_dir_EMEP);

    /**
     * Returns the eta of this kumpula_eddy.
     *
     * @return the eta of this kumpula_eddy
     */
    public float getEta();

    /**
     * Sets the eta of this kumpula_eddy.
     *
     * @param eta the eta of this kumpula_eddy
     */
    public void setEta(float eta);

    /**
     * Returns the eta_ e m e p of this kumpula_eddy.
     *
     * @return the eta_ e m e p of this kumpula_eddy
     */
    public int getEta_EMEP();

    /**
     * Sets the eta_ e m e p of this kumpula_eddy.
     *
     * @param eta_EMEP the eta_ e m e p of this kumpula_eddy
     */
    public void setEta_EMEP(int eta_EMEP);

    /**
     * Returns the theta of this kumpula_eddy.
     *
     * @return the theta of this kumpula_eddy
     */
    public float getTheta();

    /**
     * Sets the theta of this kumpula_eddy.
     *
     * @param theta the theta of this kumpula_eddy
     */
    public void setTheta(float theta);

    /**
     * Returns the theta_ e m e p of this kumpula_eddy.
     *
     * @return the theta_ e m e p of this kumpula_eddy
     */
    public int getTheta_EMEP();

    /**
     * Sets the theta_ e m e p of this kumpula_eddy.
     *
     * @param theta_EMEP the theta_ e m e p of this kumpula_eddy
     */
    public void setTheta_EMEP(int theta_EMEP);

    /**
     * Returns the beta of this kumpula_eddy.
     *
     * @return the beta of this kumpula_eddy
     */
    public float getBeta();

    /**
     * Sets the beta of this kumpula_eddy.
     *
     * @param beta the beta of this kumpula_eddy
     */
    public void setBeta(float beta);

    /**
     * Returns the beta_ e m e p of this kumpula_eddy.
     *
     * @return the beta_ e m e p of this kumpula_eddy
     */
    public int getBeta_EMEP();

    /**
     * Sets the beta_ e m e p of this kumpula_eddy.
     *
     * @param beta_EMEP the beta_ e m e p of this kumpula_eddy
     */
    public void setBeta_EMEP(int beta_EMEP);

    /**
     * Returns the c_lag of this kumpula_eddy.
     *
     * @return the c_lag of this kumpula_eddy
     */
    public float getC_lag();

    /**
     * Sets the c_lag of this kumpula_eddy.
     *
     * @param c_lag the c_lag of this kumpula_eddy
     */
    public void setC_lag(float c_lag);

    /**
     * Returns the c_lag_ e m e p of this kumpula_eddy.
     *
     * @return the c_lag_ e m e p of this kumpula_eddy
     */
    public int getC_lag_EMEP();

    /**
     * Sets the c_lag_ e m e p of this kumpula_eddy.
     *
     * @param c_lag_EMEP the c_lag_ e m e p of this kumpula_eddy
     */
    public void setC_lag_EMEP(int c_lag_EMEP);

    /**
     * Returns the h_lag of this kumpula_eddy.
     *
     * @return the h_lag of this kumpula_eddy
     */
    public float getH_lag();

    /**
     * Sets the h_lag of this kumpula_eddy.
     *
     * @param h_lag the h_lag of this kumpula_eddy
     */
    public void setH_lag(float h_lag);

    /**
     * Returns the h_lag_ e m e p of this kumpula_eddy.
     *
     * @return the h_lag_ e m e p of this kumpula_eddy
     */
    public int getH_lag_EMEP();

    /**
     * Sets the h_lag_ e m e p of this kumpula_eddy.
     *
     * @param h_lag_EMEP the h_lag_ e m e p of this kumpula_eddy
     */
    public void setH_lag_EMEP(int h_lag_EMEP);

    /**
     * Returns the err_packet of this kumpula_eddy.
     *
     * @return the err_packet of this kumpula_eddy
     */
    public float getErr_packet();

    /**
     * Sets the err_packet of this kumpula_eddy.
     *
     * @param err_packet the err_packet of this kumpula_eddy
     */
    public void setErr_packet(float err_packet);

    /**
     * Returns the err_packet_ e m e p of this kumpula_eddy.
     *
     * @return the err_packet_ e m e p of this kumpula_eddy
     */
    public int getErr_packet_EMEP();

    /**
     * Sets the err_packet_ e m e p of this kumpula_eddy.
     *
     * @param err_packet_EMEP the err_packet_ e m e p of this kumpula_eddy
     */
    public void setErr_packet_EMEP(int err_packet_EMEP);

    /**
     * Returns the licor_t_std of this kumpula_eddy.
     *
     * @return the licor_t_std of this kumpula_eddy
     */
    public float getLicor_t_std();

    /**
     * Sets the licor_t_std of this kumpula_eddy.
     *
     * @param licor_t_std the licor_t_std of this kumpula_eddy
     */
    public void setLicor_t_std(float licor_t_std);

    /**
     * Returns the licor_t_std_ e m e p of this kumpula_eddy.
     *
     * @return the licor_t_std_ e m e p of this kumpula_eddy
     */
    public int getLicor_t_std_EMEP();

    /**
     * Sets the licor_t_std_ e m e p of this kumpula_eddy.
     *
     * @param licor_t_std_EMEP the licor_t_std_ e m e p of this kumpula_eddy
     */
    public void setLicor_t_std_EMEP(int licor_t_std_EMEP);

    /**
     * Returns the licor_t_av of this kumpula_eddy.
     *
     * @return the licor_t_av of this kumpula_eddy
     */
    public float getLicor_t_av();

    /**
     * Sets the licor_t_av of this kumpula_eddy.
     *
     * @param licor_t_av the licor_t_av of this kumpula_eddy
     */
    public void setLicor_t_av(float licor_t_av);

    /**
     * Returns the licor_t_av_ e m e p of this kumpula_eddy.
     *
     * @return the licor_t_av_ e m e p of this kumpula_eddy
     */
    public int getLicor_t_av_EMEP();

    /**
     * Sets the licor_t_av_ e m e p of this kumpula_eddy.
     *
     * @param licor_t_av_EMEP the licor_t_av_ e m e p of this kumpula_eddy
     */
    public void setLicor_t_av_EMEP(int licor_t_av_EMEP);

    /**
     * Returns the licor_p_std of this kumpula_eddy.
     *
     * @return the licor_p_std of this kumpula_eddy
     */
    public float getLicor_p_std();

    /**
     * Sets the licor_p_std of this kumpula_eddy.
     *
     * @param licor_p_std the licor_p_std of this kumpula_eddy
     */
    public void setLicor_p_std(float licor_p_std);

    /**
     * Returns the licor_p_std_ e m e p of this kumpula_eddy.
     *
     * @return the licor_p_std_ e m e p of this kumpula_eddy
     */
    public int getLicor_p_std_EMEP();

    /**
     * Sets the licor_p_std_ e m e p of this kumpula_eddy.
     *
     * @param licor_p_std_EMEP the licor_p_std_ e m e p of this kumpula_eddy
     */
    public void setLicor_p_std_EMEP(int licor_p_std_EMEP);

    /**
     * Returns the licor_p_av of this kumpula_eddy.
     *
     * @return the licor_p_av of this kumpula_eddy
     */
    public float getLicor_p_av();

    /**
     * Sets the licor_p_av of this kumpula_eddy.
     *
     * @param licor_p_av the licor_p_av of this kumpula_eddy
     */
    public void setLicor_p_av(float licor_p_av);

    /**
     * Returns the licor_p_av_ e m e p of this kumpula_eddy.
     *
     * @return the licor_p_av_ e m e p of this kumpula_eddy
     */
    public int getLicor_p_av_EMEP();

    /**
     * Sets the licor_p_av_ e m e p of this kumpula_eddy.
     *
     * @param licor_p_av_EMEP the licor_p_av_ e m e p of this kumpula_eddy
     */
    public void setLicor_p_av_EMEP(int licor_p_av_EMEP);

    /**
     * Returns the l e_op of this kumpula_eddy.
     *
     * @return the l e_op of this kumpula_eddy
     */
    public float getLE_op();

    /**
     * Sets the l e_op of this kumpula_eddy.
     *
     * @param LE_op the l e_op of this kumpula_eddy
     */
    public void setLE_op(float LE_op);

    /**
     * Returns the l e_op_ e m e p of this kumpula_eddy.
     *
     * @return the l e_op_ e m e p of this kumpula_eddy
     */
    public int getLE_op_EMEP();

    /**
     * Sets the l e_op_ e m e p of this kumpula_eddy.
     *
     * @param LE_op_EMEP the l e_op_ e m e p of this kumpula_eddy
     */
    public void setLE_op_EMEP(int LE_op_EMEP);

    /**
     * Returns the qc_ l e_op of this kumpula_eddy.
     *
     * @return the qc_ l e_op of this kumpula_eddy
     */
    public int getQc_LE_op();

    /**
     * Sets the qc_ l e_op of this kumpula_eddy.
     *
     * @param Qc_LE_op the qc_ l e_op of this kumpula_eddy
     */
    public void setQc_LE_op(int Qc_LE_op);

    /**
     * Returns the qc_ l e_op_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ l e_op_ e m e p of this kumpula_eddy
     */
    public int getQc_LE_op_EMEP();

    /**
     * Sets the qc_ l e_op_ e m e p of this kumpula_eddy.
     *
     * @param Qc_LE_op_EMEP the qc_ l e_op_ e m e p of this kumpula_eddy
     */
    public void setQc_LE_op_EMEP(int Qc_LE_op_EMEP);

    /**
     * Returns the e_op of this kumpula_eddy.
     *
     * @return the e_op of this kumpula_eddy
     */
    public float getE_op();

    /**
     * Sets the e_op of this kumpula_eddy.
     *
     * @param E_op the e_op of this kumpula_eddy
     */
    public void setE_op(float E_op);

    /**
     * Returns the e_op_ e m e p of this kumpula_eddy.
     *
     * @return the e_op_ e m e p of this kumpula_eddy
     */
    public int getE_op_EMEP();

    /**
     * Sets the e_op_ e m e p of this kumpula_eddy.
     *
     * @param E_op_EMEP the e_op_ e m e p of this kumpula_eddy
     */
    public void setE_op_EMEP(int E_op_EMEP);

    /**
     * Returns the qc_ e_op of this kumpula_eddy.
     *
     * @return the qc_ e_op of this kumpula_eddy
     */
    public int getQc_E_op();

    /**
     * Sets the qc_ e_op of this kumpula_eddy.
     *
     * @param Qc_E_op the qc_ e_op of this kumpula_eddy
     */
    public void setQc_E_op(int Qc_E_op);

    /**
     * Returns the qc_ e_op_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ e_op_ e m e p of this kumpula_eddy
     */
    public int getQc_E_op_EMEP();

    /**
     * Sets the qc_ e_op_ e m e p of this kumpula_eddy.
     *
     * @param Qc_E_op_EMEP the qc_ e_op_ e m e p of this kumpula_eddy
     */
    public void setQc_E_op_EMEP(int Qc_E_op_EMEP);

    /**
     * Returns the f_c_op of this kumpula_eddy.
     *
     * @return the f_c_op of this kumpula_eddy
     */
    public float getF_c_op();

    /**
     * Sets the f_c_op of this kumpula_eddy.
     *
     * @param F_c_op the f_c_op of this kumpula_eddy
     */
    public void setF_c_op(float F_c_op);

    /**
     * Returns the f_c_op_ e m e p of this kumpula_eddy.
     *
     * @return the f_c_op_ e m e p of this kumpula_eddy
     */
    public int getF_c_op_EMEP();

    /**
     * Sets the f_c_op_ e m e p of this kumpula_eddy.
     *
     * @param F_c_op_EMEP the f_c_op_ e m e p of this kumpula_eddy
     */
    public void setF_c_op_EMEP(int F_c_op_EMEP);

    /**
     * Returns the qc_ f_c_op of this kumpula_eddy.
     *
     * @return the qc_ f_c_op of this kumpula_eddy
     */
    public int getQc_F_c_op();

    /**
     * Sets the qc_ f_c_op of this kumpula_eddy.
     *
     * @param Qc_F_c_op the qc_ f_c_op of this kumpula_eddy
     */
    public void setQc_F_c_op(int Qc_F_c_op);

    /**
     * Returns the qc_ f_c_op_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ f_c_op_ e m e p of this kumpula_eddy
     */
    public int getQc_F_c_op_EMEP();

    /**
     * Sets the qc_ f_c_op_ e m e p of this kumpula_eddy.
     *
     * @param Qc_F_c_op_EMEP the qc_ f_c_op_ e m e p of this kumpula_eddy
     */
    public void setQc_F_c_op_EMEP(int Qc_F_c_op_EMEP);

    /**
     * Returns the std_c_op of this kumpula_eddy.
     *
     * @return the std_c_op of this kumpula_eddy
     */
    public float getStd_c_op();

    /**
     * Sets the std_c_op of this kumpula_eddy.
     *
     * @param std_c_op the std_c_op of this kumpula_eddy
     */
    public void setStd_c_op(float std_c_op);

    /**
     * Returns the std_c_op_ e m e p of this kumpula_eddy.
     *
     * @return the std_c_op_ e m e p of this kumpula_eddy
     */
    public int getStd_c_op_EMEP();

    /**
     * Sets the std_c_op_ e m e p of this kumpula_eddy.
     *
     * @param std_c_op_EMEP the std_c_op_ e m e p of this kumpula_eddy
     */
    public void setStd_c_op_EMEP(int std_c_op_EMEP);

    /**
     * Returns the std_h_op of this kumpula_eddy.
     *
     * @return the std_h_op of this kumpula_eddy
     */
    public float getStd_h_op();

    /**
     * Sets the std_h_op of this kumpula_eddy.
     *
     * @param std_h_op the std_h_op of this kumpula_eddy
     */
    public void setStd_h_op(float std_h_op);

    /**
     * Returns the std_h_op_ e m e p of this kumpula_eddy.
     *
     * @return the std_h_op_ e m e p of this kumpula_eddy
     */
    public int getStd_h_op_EMEP();

    /**
     * Sets the std_h_op_ e m e p of this kumpula_eddy.
     *
     * @param std_h_op_EMEP the std_h_op_ e m e p of this kumpula_eddy
     */
    public void setStd_h_op_EMEP(int std_h_op_EMEP);

    /**
     * Returns the av_c_op of this kumpula_eddy.
     *
     * @return the av_c_op of this kumpula_eddy
     */
    public float getAv_c_op();

    /**
     * Sets the av_c_op of this kumpula_eddy.
     *
     * @param av_c_op the av_c_op of this kumpula_eddy
     */
    public void setAv_c_op(float av_c_op);

    /**
     * Returns the av_c_op_ e m e p of this kumpula_eddy.
     *
     * @return the av_c_op_ e m e p of this kumpula_eddy
     */
    public int getAv_c_op_EMEP();

    /**
     * Sets the av_c_op_ e m e p of this kumpula_eddy.
     *
     * @param av_c_op_EMEP the av_c_op_ e m e p of this kumpula_eddy
     */
    public void setAv_c_op_EMEP(int av_c_op_EMEP);

    /**
     * Returns the av_h_op of this kumpula_eddy.
     *
     * @return the av_h_op of this kumpula_eddy
     */
    public float getAv_h_op();

    /**
     * Sets the av_h_op of this kumpula_eddy.
     *
     * @param av_h_op the av_h_op of this kumpula_eddy
     */
    public void setAv_h_op(float av_h_op);

    /**
     * Returns the av_h_op_ e m e p of this kumpula_eddy.
     *
     * @return the av_h_op_ e m e p of this kumpula_eddy
     */
    public int getAv_h_op_EMEP();

    /**
     * Sets the av_h_op_ e m e p of this kumpula_eddy.
     *
     * @param av_h_op_EMEP the av_h_op_ e m e p of this kumpula_eddy
     */
    public void setAv_h_op_EMEP(int av_h_op_EMEP);

    /**
     * Returns the c_lag_op of this kumpula_eddy.
     *
     * @return the c_lag_op of this kumpula_eddy
     */
    public float getC_lag_op();

    /**
     * Sets the c_lag_op of this kumpula_eddy.
     *
     * @param c_lag_op the c_lag_op of this kumpula_eddy
     */
    public void setC_lag_op(float c_lag_op);

    /**
     * Returns the c_lag_op_ e m e p of this kumpula_eddy.
     *
     * @return the c_lag_op_ e m e p of this kumpula_eddy
     */
    public int getC_lag_op_EMEP();

    /**
     * Sets the c_lag_op_ e m e p of this kumpula_eddy.
     *
     * @param c_lag_op_EMEP the c_lag_op_ e m e p of this kumpula_eddy
     */
    public void setC_lag_op_EMEP(int c_lag_op_EMEP);

    /**
     * Returns the h_lag_op of this kumpula_eddy.
     *
     * @return the h_lag_op of this kumpula_eddy
     */
    public float getH_lag_op();

    /**
     * Sets the h_lag_op of this kumpula_eddy.
     *
     * @param h_lag_op the h_lag_op of this kumpula_eddy
     */
    public void setH_lag_op(float h_lag_op);

    /**
     * Returns the h_lag_op_ e m e p of this kumpula_eddy.
     *
     * @return the h_lag_op_ e m e p of this kumpula_eddy
     */
    public int getH_lag_op_EMEP();

    /**
     * Sets the h_lag_op_ e m e p of this kumpula_eddy.
     *
     * @param h_lag_op_EMEP the h_lag_op_ e m e p of this kumpula_eddy
     */
    public void setH_lag_op_EMEP(int h_lag_op_EMEP);

    /**
     * Returns the f_ c p c of this kumpula_eddy.
     *
     * @return the f_ c p c of this kumpula_eddy
     */
    public float getF_CPC();

    /**
     * Sets the f_ c p c of this kumpula_eddy.
     *
     * @param F_CPC the f_ c p c of this kumpula_eddy
     */
    public void setF_CPC(float F_CPC);

    /**
     * Returns the f_ c p c_ e m e p of this kumpula_eddy.
     *
     * @return the f_ c p c_ e m e p of this kumpula_eddy
     */
    public int getF_CPC_EMEP();

    /**
     * Sets the f_ c p c_ e m e p of this kumpula_eddy.
     *
     * @param F_CPC_EMEP the f_ c p c_ e m e p of this kumpula_eddy
     */
    public void setF_CPC_EMEP(int F_CPC_EMEP);

    /**
     * Returns the qc_ f_ c p c of this kumpula_eddy.
     *
     * @return the qc_ f_ c p c of this kumpula_eddy
     */
    public int getQc_F_CPC();

    /**
     * Sets the qc_ f_ c p c of this kumpula_eddy.
     *
     * @param Qc_F_CPC the qc_ f_ c p c of this kumpula_eddy
     */
    public void setQc_F_CPC(int Qc_F_CPC);

    /**
     * Returns the qc_ f_ c p c_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ f_ c p c_ e m e p of this kumpula_eddy
     */
    public int getQc_F_CPC_EMEP();

    /**
     * Sets the qc_ f_ c p c_ e m e p of this kumpula_eddy.
     *
     * @param Qc_F_CPC_EMEP the qc_ f_ c p c_ e m e p of this kumpula_eddy
     */
    public void setQc_F_CPC_EMEP(int Qc_F_CPC_EMEP);

    /**
     * Returns the std_ c p c of this kumpula_eddy.
     *
     * @return the std_ c p c of this kumpula_eddy
     */
    public float getStd_CPC();

    /**
     * Sets the std_ c p c of this kumpula_eddy.
     *
     * @param std_CPC the std_ c p c of this kumpula_eddy
     */
    public void setStd_CPC(float std_CPC);

    /**
     * Returns the std_ c p c_ e m e p of this kumpula_eddy.
     *
     * @return the std_ c p c_ e m e p of this kumpula_eddy
     */
    public int getStd_CPC_EMEP();

    /**
     * Sets the std_ c p c_ e m e p of this kumpula_eddy.
     *
     * @param std_CPC_EMEP the std_ c p c_ e m e p of this kumpula_eddy
     */
    public void setStd_CPC_EMEP(int std_CPC_EMEP);

    /**
     * Returns the av_ c p c of this kumpula_eddy.
     *
     * @return the av_ c p c of this kumpula_eddy
     */
    public float getAv_CPC();

    /**
     * Sets the av_ c p c of this kumpula_eddy.
     *
     * @param av_CPC the av_ c p c of this kumpula_eddy
     */
    public void setAv_CPC(float av_CPC);

    /**
     * Returns the av_ c p c_ e m e p of this kumpula_eddy.
     *
     * @return the av_ c p c_ e m e p of this kumpula_eddy
     */
    public int getAv_CPC_EMEP();

    /**
     * Sets the av_ c p c_ e m e p of this kumpula_eddy.
     *
     * @param av_CPC_EMEP the av_ c p c_ e m e p of this kumpula_eddy
     */
    public void setAv_CPC_EMEP(int av_CPC_EMEP);

    /**
     * Returns the c p c_lag of this kumpula_eddy.
     *
     * @return the c p c_lag of this kumpula_eddy
     */
    public float getCPC_lag();

    /**
     * Sets the c p c_lag of this kumpula_eddy.
     *
     * @param CPC_lag the c p c_lag of this kumpula_eddy
     */
    public void setCPC_lag(float CPC_lag);

    /**
     * Returns the c p c_lag_ e m e p of this kumpula_eddy.
     *
     * @return the c p c_lag_ e m e p of this kumpula_eddy
     */
    public int getCPC_lag_EMEP();

    /**
     * Sets the c p c_lag_ e m e p of this kumpula_eddy.
     *
     * @param CPC_lag_EMEP the c p c_lag_ e m e p of this kumpula_eddy
     */
    public void setCPC_lag_EMEP(int CPC_lag_EMEP);

    /**
     * Returns the f_ n2 o of this kumpula_eddy.
     *
     * @return the f_ n2 o of this kumpula_eddy
     */
    public float getF_N2O();

    /**
     * Sets the f_ n2 o of this kumpula_eddy.
     *
     * @param F_N2O the f_ n2 o of this kumpula_eddy
     */
    public void setF_N2O(float F_N2O);

    /**
     * Returns the f_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @return the f_ n2 o_ e m e p of this kumpula_eddy
     */
    public int getF_N2O_EMEP();

    /**
     * Sets the f_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @param F_N2O_EMEP the f_ n2 o_ e m e p of this kumpula_eddy
     */
    public void setF_N2O_EMEP(int F_N2O_EMEP);

    /**
     * Returns the qc_ f_ n2 o of this kumpula_eddy.
     *
     * @return the qc_ f_ n2 o of this kumpula_eddy
     */
    public int getQc_F_N2O();

    /**
     * Sets the qc_ f_ n2 o of this kumpula_eddy.
     *
     * @param Qc_F_N2O the qc_ f_ n2 o of this kumpula_eddy
     */
    public void setQc_F_N2O(int Qc_F_N2O);

    /**
     * Returns the qc_ f_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @return the qc_ f_ n2 o_ e m e p of this kumpula_eddy
     */
    public int getQc_F_N2O_EMEP();

    /**
     * Sets the qc_ f_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @param Qc_F_N2O_EMEP the qc_ f_ n2 o_ e m e p of this kumpula_eddy
     */
    public void setQc_F_N2O_EMEP(int Qc_F_N2O_EMEP);

    /**
     * Returns the std_ n2 o of this kumpula_eddy.
     *
     * @return the std_ n2 o of this kumpula_eddy
     */
    public float getStd_N2O();

    /**
     * Sets the std_ n2 o of this kumpula_eddy.
     *
     * @param std_N2O the std_ n2 o of this kumpula_eddy
     */
    public void setStd_N2O(float std_N2O);

    /**
     * Returns the std_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @return the std_ n2 o_ e m e p of this kumpula_eddy
     */
    public int getStd_N2O_EMEP();

    /**
     * Sets the std_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @param std_N2O_EMEP the std_ n2 o_ e m e p of this kumpula_eddy
     */
    public void setStd_N2O_EMEP(int std_N2O_EMEP);

    /**
     * Returns the av_ n2 o of this kumpula_eddy.
     *
     * @return the av_ n2 o of this kumpula_eddy
     */
    public float getAv_N2O();

    /**
     * Sets the av_ n2 o of this kumpula_eddy.
     *
     * @param av_N2O the av_ n2 o of this kumpula_eddy
     */
    public void setAv_N2O(float av_N2O);

    /**
     * Returns the av_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @return the av_ n2 o_ e m e p of this kumpula_eddy
     */
    public int getAv_N2O_EMEP();

    /**
     * Sets the av_ n2 o_ e m e p of this kumpula_eddy.
     *
     * @param av_N2O_EMEP the av_ n2 o_ e m e p of this kumpula_eddy
     */
    public void setAv_N2O_EMEP(int av_N2O_EMEP);

    /**
     * Returns the n2 o_lag of this kumpula_eddy.
     *
     * @return the n2 o_lag of this kumpula_eddy
     */
    public float getN2O_lag();

    /**
     * Sets the n2 o_lag of this kumpula_eddy.
     *
     * @param N2O_lag the n2 o_lag of this kumpula_eddy
     */
    public void setN2O_lag(float N2O_lag);

    /**
     * Returns the n2 o_lag_ e m e p of this kumpula_eddy.
     *
     * @return the n2 o_lag_ e m e p of this kumpula_eddy
     */
    public int getN2O_lag_EMEP();

    /**
     * Sets the n2 o_lag_ e m e p of this kumpula_eddy.
     *
     * @param N2O_lag_EMEP the n2 o_lag_ e m e p of this kumpula_eddy
     */
    public void setN2O_lag_EMEP(int N2O_lag_EMEP);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Kumpula_eddy kumpula_eddy);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Kumpula_eddy> toCacheModel();

    @Override
    public Kumpula_eddy toEscapedModel();

    @Override
    public Kumpula_eddy toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
