package fi.csc.smear.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Sii2meta service. Represents a row in the &quot;SII2_META&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.smear.db.model.impl.Sii2metaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.smear.db.model.impl.Sii2metaImpl}.
 * </p>
 *
 * @author pj
 * @see Sii2meta
 * @see fi.csc.smear.db.model.impl.Sii2metaImpl
 * @see fi.csc.smear.db.model.impl.Sii2metaModelImpl
 * @generated
 */
public interface Sii2metaModel extends BaseModel<Sii2meta> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a sii2meta model instance should use the {@link Sii2meta} interface instead.
     */

    /**
     * Returns the primary key of this sii2meta.
     *
     * @return the primary key of this sii2meta
     */
    public java.util.Date getPrimaryKey();

    /**
     * Sets the primary key of this sii2meta.
     *
     * @param primaryKey the primary key of this sii2meta
     */
    public void setPrimaryKey(java.util.Date primaryKey);

    /**
     * Returns the samptime of this sii2meta.
     *
     * @return the samptime of this sii2meta
     */
    public Date getSamptime();

    /**
     * Sets the samptime of this sii2meta.
     *
     * @param samptime the samptime of this sii2meta
     */
    public void setSamptime(Date samptime);

    /**
     * Returns the t_a of this sii2meta.
     *
     * @return the t_a of this sii2meta
     */
    public float getT_a();

    /**
     * Sets the t_a of this sii2meta.
     *
     * @param T_a the t_a of this sii2meta
     */
    public void setT_a(float T_a);

    /**
     * Returns the t_a_ e m e p of this sii2meta.
     *
     * @return the t_a_ e m e p of this sii2meta
     */
    public int getT_a_EMEP();

    /**
     * Sets the t_a_ e m e p of this sii2meta.
     *
     * @param T_a_EMEP the t_a_ e m e p of this sii2meta
     */
    public void setT_a_EMEP(int T_a_EMEP);

    /**
     * Returns the r h of this sii2meta.
     *
     * @return the r h of this sii2meta
     */
    public float getRH();

    /**
     * Sets the r h of this sii2meta.
     *
     * @param RH the r h of this sii2meta
     */
    public void setRH(float RH);

    /**
     * Returns the r h_ e m e p of this sii2meta.
     *
     * @return the r h_ e m e p of this sii2meta
     */
    public int getRH_EMEP();

    /**
     * Sets the r h_ e m e p of this sii2meta.
     *
     * @param RH_EMEP the r h_ e m e p of this sii2meta
     */
    public void setRH_EMEP(int RH_EMEP);

    /**
     * Returns the net of this sii2meta.
     *
     * @return the net of this sii2meta
     */
    public float getNet();

    /**
     * Sets the net of this sii2meta.
     *
     * @param Net the net of this sii2meta
     */
    public void setNet(float Net);

    /**
     * Returns the net_ e m e p of this sii2meta.
     *
     * @return the net_ e m e p of this sii2meta
     */
    public int getNet_EMEP();

    /**
     * Sets the net_ e m e p of this sii2meta.
     *
     * @param Net_EMEP the net_ e m e p of this sii2meta
     */
    public void setNet_EMEP(int Net_EMEP);

    /**
     * Returns the t_p_5 of this sii2meta.
     *
     * @return the t_p_5 of this sii2meta
     */
    public float getT_p_5();

    /**
     * Sets the t_p_5 of this sii2meta.
     *
     * @param T_p_5 the t_p_5 of this sii2meta
     */
    public void setT_p_5(float T_p_5);

    /**
     * Returns the t_p_5_ e m e p of this sii2meta.
     *
     * @return the t_p_5_ e m e p of this sii2meta
     */
    public int getT_p_5_EMEP();

    /**
     * Sets the t_p_5_ e m e p of this sii2meta.
     *
     * @param T_p_5_EMEP the t_p_5_ e m e p of this sii2meta
     */
    public void setT_p_5_EMEP(int T_p_5_EMEP);

    /**
     * Returns the t_p_ b20 of this sii2meta.
     *
     * @return the t_p_ b20 of this sii2meta
     */
    public float getT_p_B20();

    /**
     * Sets the t_p_ b20 of this sii2meta.
     *
     * @param T_p_B20 the t_p_ b20 of this sii2meta
     */
    public void setT_p_B20(float T_p_B20);

    /**
     * Returns the t_p_ b20_ e m e p of this sii2meta.
     *
     * @return the t_p_ b20_ e m e p of this sii2meta
     */
    public int getT_p_B20_EMEP();

    /**
     * Sets the t_p_ b20_ e m e p of this sii2meta.
     *
     * @param T_p_B20_EMEP the t_p_ b20_ e m e p of this sii2meta
     */
    public void setT_p_B20_EMEP(int T_p_B20_EMEP);

    /**
     * Returns the t_p_ b35 of this sii2meta.
     *
     * @return the t_p_ b35 of this sii2meta
     */
    public float getT_p_B35();

    /**
     * Sets the t_p_ b35 of this sii2meta.
     *
     * @param T_p_B35 the t_p_ b35 of this sii2meta
     */
    public void setT_p_B35(float T_p_B35);

    /**
     * Returns the t_p_ b35_ e m e p of this sii2meta.
     *
     * @return the t_p_ b35_ e m e p of this sii2meta
     */
    public int getT_p_B35_EMEP();

    /**
     * Sets the t_p_ b35_ e m e p of this sii2meta.
     *
     * @param T_p_B35_EMEP the t_p_ b35_ e m e p of this sii2meta
     */
    public void setT_p_B35_EMEP(int T_p_B35_EMEP);

    /**
     * Returns the t_p_ b50 of this sii2meta.
     *
     * @return the t_p_ b50 of this sii2meta
     */
    public float getT_p_B50();

    /**
     * Sets the t_p_ b50 of this sii2meta.
     *
     * @param T_p_B50 the t_p_ b50 of this sii2meta
     */
    public void setT_p_B50(float T_p_B50);

    /**
     * Returns the t_p_ b50_ e m e p of this sii2meta.
     *
     * @return the t_p_ b50_ e m e p of this sii2meta
     */
    public int getT_p_B50_EMEP();

    /**
     * Sets the t_p_ b50_ e m e p of this sii2meta.
     *
     * @param T_p_B50_EMEP the t_p_ b50_ e m e p of this sii2meta
     */
    public void setT_p_B50_EMEP(int T_p_B50_EMEP);

    /**
     * Returns the w t d of this sii2meta.
     *
     * @return the w t d of this sii2meta
     */
    public float getWTD();

    /**
     * Sets the w t d of this sii2meta.
     *
     * @param WTD the w t d of this sii2meta
     */
    public void setWTD(float WTD);

    /**
     * Returns the w t d_ e m e p of this sii2meta.
     *
     * @return the w t d_ e m e p of this sii2meta
     */
    public int getWTD_EMEP();

    /**
     * Sets the w t d_ e m e p of this sii2meta.
     *
     * @param WTD_EMEP the w t d_ e m e p of this sii2meta
     */
    public void setWTD_EMEP(int WTD_EMEP);

    /**
     * Returns the precip of this sii2meta.
     *
     * @return the precip of this sii2meta
     */
    public float getPrecip();

    /**
     * Sets the precip of this sii2meta.
     *
     * @param Precip the precip of this sii2meta
     */
    public void setPrecip(float Precip);

    /**
     * Returns the precip_ e m e p of this sii2meta.
     *
     * @return the precip_ e m e p of this sii2meta
     */
    public int getPrecip_EMEP();

    /**
     * Sets the precip_ e m e p of this sii2meta.
     *
     * @param Precip_EMEP the precip_ e m e p of this sii2meta
     */
    public void setPrecip_EMEP(int Precip_EMEP);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Sii2meta sii2meta);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Sii2meta> toCacheModel();

    @Override
    public Sii2meta toEscapedModel();

    @Override
    public Sii2meta toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
