package fi.csc.smear.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Vareddy service. Represents a row in the &quot;VAR_EDDY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.smear.db.model.impl.VareddyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.smear.db.model.impl.VareddyImpl}.
 * </p>
 *
 * @author pj
 * @see Vareddy
 * @see fi.csc.smear.db.model.impl.VareddyImpl
 * @see fi.csc.smear.db.model.impl.VareddyModelImpl
 * @generated
 */
public interface VareddyModel extends BaseModel<Vareddy> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a vareddy model instance should use the {@link Vareddy} interface instead.
     */

    /**
     * Returns the primary key of this vareddy.
     *
     * @return the primary key of this vareddy
     */
    public java.util.Date getPrimaryKey();

    /**
     * Sets the primary key of this vareddy.
     *
     * @param primaryKey the primary key of this vareddy
     */
    public void setPrimaryKey(java.util.Date primaryKey);

    /**
     * Returns the samptime of this vareddy.
     *
     * @return the samptime of this vareddy
     */
    public Date getSamptime();

    /**
     * Sets the samptime of this vareddy.
     *
     * @param samptime the samptime of this vareddy
     */
    public void setSamptime(Date samptime);

    /**
     * Returns the h of this vareddy.
     *
     * @return the h of this vareddy
     */
    public float getH();

    /**
     * Sets the h of this vareddy.
     *
     * @param H the h of this vareddy
     */
    public void setH(float H);

    /**
     * Returns the h_ e m e p of this vareddy.
     *
     * @return the h_ e m e p of this vareddy
     */
    public int getH_EMEP();

    /**
     * Sets the h_ e m e p of this vareddy.
     *
     * @param H_EMEP the h_ e m e p of this vareddy
     */
    public void setH_EMEP(int H_EMEP);

    /**
     * Returns the l e of this vareddy.
     *
     * @return the l e of this vareddy
     */
    public float getLE();

    /**
     * Sets the l e of this vareddy.
     *
     * @param LE the l e of this vareddy
     */
    public void setLE(float LE);

    /**
     * Returns the l e_ e m e p of this vareddy.
     *
     * @return the l e_ e m e p of this vareddy
     */
    public int getLE_EMEP();

    /**
     * Sets the l e_ e m e p of this vareddy.
     *
     * @param LE_EMEP the l e_ e m e p of this vareddy
     */
    public void setLE_EMEP(int LE_EMEP);

    /**
     * Returns the e of this vareddy.
     *
     * @return the e of this vareddy
     */
    public float getE();

    /**
     * Sets the e of this vareddy.
     *
     * @param E the e of this vareddy
     */
    public void setE(float E);

    /**
     * Returns the e_ e m e p of this vareddy.
     *
     * @return the e_ e m e p of this vareddy
     */
    public int getE_EMEP();

    /**
     * Sets the e_ e m e p of this vareddy.
     *
     * @param E_EMEP the e_ e m e p of this vareddy
     */
    public void setE_EMEP(int E_EMEP);

    /**
     * Returns the f_c of this vareddy.
     *
     * @return the f_c of this vareddy
     */
    public float getF_c();

    /**
     * Sets the f_c of this vareddy.
     *
     * @param F_c the f_c of this vareddy
     */
    public void setF_c(float F_c);

    /**
     * Returns the f_c_ e m e p of this vareddy.
     *
     * @return the f_c_ e m e p of this vareddy
     */
    public int getF_c_EMEP();

    /**
     * Sets the f_c_ e m e p of this vareddy.
     *
     * @param F_c_EMEP the f_c_ e m e p of this vareddy
     */
    public void setF_c_EMEP(int F_c_EMEP);

    /**
     * Returns the tau of this vareddy.
     *
     * @return the tau of this vareddy
     */
    public float getTau();

    /**
     * Sets the tau of this vareddy.
     *
     * @param tau the tau of this vareddy
     */
    public void setTau(float tau);

    /**
     * Returns the tau_ e m e p of this vareddy.
     *
     * @return the tau_ e m e p of this vareddy
     */
    public int getTau_EMEP();

    /**
     * Sets the tau_ e m e p of this vareddy.
     *
     * @param tau_EMEP the tau_ e m e p of this vareddy
     */
    public void setTau_EMEP(int tau_EMEP);

    /**
     * Returns the u_star of this vareddy.
     *
     * @return the u_star of this vareddy
     */
    public float getU_star();

    /**
     * Sets the u_star of this vareddy.
     *
     * @param u_star the u_star of this vareddy
     */
    public void setU_star(float u_star);

    /**
     * Returns the u_star_ e m e p of this vareddy.
     *
     * @return the u_star_ e m e p of this vareddy
     */
    public int getU_star_EMEP();

    /**
     * Sets the u_star_ e m e p of this vareddy.
     *
     * @param u_star_EMEP the u_star_ e m e p of this vareddy
     */
    public void setU_star_EMEP(int u_star_EMEP);

    /**
     * Returns the m o_length of this vareddy.
     *
     * @return the m o_length of this vareddy
     */
    public float getMO_length();

    /**
     * Sets the m o_length of this vareddy.
     *
     * @param MO_length the m o_length of this vareddy
     */
    public void setMO_length(float MO_length);

    /**
     * Returns the m o_length_ e m e p of this vareddy.
     *
     * @return the m o_length_ e m e p of this vareddy
     */
    public int getMO_length_EMEP();

    /**
     * Sets the m o_length_ e m e p of this vareddy.
     *
     * @param MO_length_EMEP the m o_length_ e m e p of this vareddy
     */
    public void setMO_length_EMEP(int MO_length_EMEP);

    /**
     * Returns the std_u of this vareddy.
     *
     * @return the std_u of this vareddy
     */
    public float getStd_u();

    /**
     * Sets the std_u of this vareddy.
     *
     * @param std_u the std_u of this vareddy
     */
    public void setStd_u(float std_u);

    /**
     * Returns the std_u_ e m e p of this vareddy.
     *
     * @return the std_u_ e m e p of this vareddy
     */
    public int getStd_u_EMEP();

    /**
     * Sets the std_u_ e m e p of this vareddy.
     *
     * @param std_u_EMEP the std_u_ e m e p of this vareddy
     */
    public void setStd_u_EMEP(int std_u_EMEP);

    /**
     * Returns the std_v of this vareddy.
     *
     * @return the std_v of this vareddy
     */
    public float getStd_v();

    /**
     * Sets the std_v of this vareddy.
     *
     * @param std_v the std_v of this vareddy
     */
    public void setStd_v(float std_v);

    /**
     * Returns the std_v_ e m e p of this vareddy.
     *
     * @return the std_v_ e m e p of this vareddy
     */
    public int getStd_v_EMEP();

    /**
     * Sets the std_v_ e m e p of this vareddy.
     *
     * @param std_v_EMEP the std_v_ e m e p of this vareddy
     */
    public void setStd_v_EMEP(int std_v_EMEP);

    /**
     * Returns the std_w of this vareddy.
     *
     * @return the std_w of this vareddy
     */
    public float getStd_w();

    /**
     * Sets the std_w of this vareddy.
     *
     * @param std_w the std_w of this vareddy
     */
    public void setStd_w(float std_w);

    /**
     * Returns the std_w_ e m e p of this vareddy.
     *
     * @return the std_w_ e m e p of this vareddy
     */
    public int getStd_w_EMEP();

    /**
     * Sets the std_w_ e m e p of this vareddy.
     *
     * @param std_w_EMEP the std_w_ e m e p of this vareddy
     */
    public void setStd_w_EMEP(int std_w_EMEP);

    /**
     * Returns the std_t of this vareddy.
     *
     * @return the std_t of this vareddy
     */
    public float getStd_t();

    /**
     * Sets the std_t of this vareddy.
     *
     * @param std_t the std_t of this vareddy
     */
    public void setStd_t(float std_t);

    /**
     * Returns the std_t_ e m e p of this vareddy.
     *
     * @return the std_t_ e m e p of this vareddy
     */
    public int getStd_t_EMEP();

    /**
     * Sets the std_t_ e m e p of this vareddy.
     *
     * @param std_t_EMEP the std_t_ e m e p of this vareddy
     */
    public void setStd_t_EMEP(int std_t_EMEP);

    /**
     * Returns the std_c of this vareddy.
     *
     * @return the std_c of this vareddy
     */
    public float getStd_c();

    /**
     * Sets the std_c of this vareddy.
     *
     * @param std_c the std_c of this vareddy
     */
    public void setStd_c(float std_c);

    /**
     * Returns the std_c_ e m e p of this vareddy.
     *
     * @return the std_c_ e m e p of this vareddy
     */
    public int getStd_c_EMEP();

    /**
     * Sets the std_c_ e m e p of this vareddy.
     *
     * @param std_c_EMEP the std_c_ e m e p of this vareddy
     */
    public void setStd_c_EMEP(int std_c_EMEP);

    /**
     * Returns the std_h of this vareddy.
     *
     * @return the std_h of this vareddy
     */
    public float getStd_h();

    /**
     * Sets the std_h of this vareddy.
     *
     * @param std_h the std_h of this vareddy
     */
    public void setStd_h(float std_h);

    /**
     * Returns the std_h_ e m e p of this vareddy.
     *
     * @return the std_h_ e m e p of this vareddy
     */
    public int getStd_h_EMEP();

    /**
     * Sets the std_h_ e m e p of this vareddy.
     *
     * @param std_h_EMEP the std_h_ e m e p of this vareddy
     */
    public void setStd_h_EMEP(int std_h_EMEP);

    /**
     * Returns the av_u of this vareddy.
     *
     * @return the av_u of this vareddy
     */
    public float getAv_u();

    /**
     * Sets the av_u of this vareddy.
     *
     * @param av_u the av_u of this vareddy
     */
    public void setAv_u(float av_u);

    /**
     * Returns the av_u_ e m e p of this vareddy.
     *
     * @return the av_u_ e m e p of this vareddy
     */
    public int getAv_u_EMEP();

    /**
     * Sets the av_u_ e m e p of this vareddy.
     *
     * @param av_u_EMEP the av_u_ e m e p of this vareddy
     */
    public void setAv_u_EMEP(int av_u_EMEP);

    /**
     * Returns the av_v of this vareddy.
     *
     * @return the av_v of this vareddy
     */
    public float getAv_v();

    /**
     * Sets the av_v of this vareddy.
     *
     * @param av_v the av_v of this vareddy
     */
    public void setAv_v(float av_v);

    /**
     * Returns the av_v_ e m e p of this vareddy.
     *
     * @return the av_v_ e m e p of this vareddy
     */
    public int getAv_v_EMEP();

    /**
     * Sets the av_v_ e m e p of this vareddy.
     *
     * @param av_v_EMEP the av_v_ e m e p of this vareddy
     */
    public void setAv_v_EMEP(int av_v_EMEP);

    /**
     * Returns the av_w of this vareddy.
     *
     * @return the av_w of this vareddy
     */
    public float getAv_w();

    /**
     * Sets the av_w of this vareddy.
     *
     * @param av_w the av_w of this vareddy
     */
    public void setAv_w(float av_w);

    /**
     * Returns the av_w_ e m e p of this vareddy.
     *
     * @return the av_w_ e m e p of this vareddy
     */
    public int getAv_w_EMEP();

    /**
     * Sets the av_w_ e m e p of this vareddy.
     *
     * @param av_w_EMEP the av_w_ e m e p of this vareddy
     */
    public void setAv_w_EMEP(int av_w_EMEP);

    /**
     * Returns the av_t of this vareddy.
     *
     * @return the av_t of this vareddy
     */
    public float getAv_t();

    /**
     * Sets the av_t of this vareddy.
     *
     * @param av_t the av_t of this vareddy
     */
    public void setAv_t(float av_t);

    /**
     * Returns the av_t_ e m e p of this vareddy.
     *
     * @return the av_t_ e m e p of this vareddy
     */
    public int getAv_t_EMEP();

    /**
     * Sets the av_t_ e m e p of this vareddy.
     *
     * @param av_t_EMEP the av_t_ e m e p of this vareddy
     */
    public void setAv_t_EMEP(int av_t_EMEP);

    /**
     * Returns the av_c of this vareddy.
     *
     * @return the av_c of this vareddy
     */
    public float getAv_c();

    /**
     * Sets the av_c of this vareddy.
     *
     * @param av_c the av_c of this vareddy
     */
    public void setAv_c(float av_c);

    /**
     * Returns the av_c_ e m e p of this vareddy.
     *
     * @return the av_c_ e m e p of this vareddy
     */
    public int getAv_c_EMEP();

    /**
     * Sets the av_c_ e m e p of this vareddy.
     *
     * @param av_c_EMEP the av_c_ e m e p of this vareddy
     */
    public void setAv_c_EMEP(int av_c_EMEP);

    /**
     * Returns the av_h of this vareddy.
     *
     * @return the av_h of this vareddy
     */
    public float getAv_h();

    /**
     * Sets the av_h of this vareddy.
     *
     * @param av_h the av_h of this vareddy
     */
    public void setAv_h(float av_h);

    /**
     * Returns the av_h_ e m e p of this vareddy.
     *
     * @return the av_h_ e m e p of this vareddy
     */
    public int getAv_h_EMEP();

    /**
     * Sets the av_h_ e m e p of this vareddy.
     *
     * @param av_h_EMEP the av_h_ e m e p of this vareddy
     */
    public void setAv_h_EMEP(int av_h_EMEP);

    /**
     * Returns the u of this vareddy.
     *
     * @return the u of this vareddy
     */
    public float getU();

    /**
     * Sets the u of this vareddy.
     *
     * @param U the u of this vareddy
     */
    public void setU(float U);

    /**
     * Returns the u_ e m e p of this vareddy.
     *
     * @return the u_ e m e p of this vareddy
     */
    public int getU_EMEP();

    /**
     * Sets the u_ e m e p of this vareddy.
     *
     * @param U_EMEP the u_ e m e p of this vareddy
     */
    public void setU_EMEP(int U_EMEP);

    /**
     * Returns the wind_dir of this vareddy.
     *
     * @return the wind_dir of this vareddy
     */
    public float getWind_dir();

    /**
     * Sets the wind_dir of this vareddy.
     *
     * @param wind_dir the wind_dir of this vareddy
     */
    public void setWind_dir(float wind_dir);

    /**
     * Returns the wind_dir_ e m e p of this vareddy.
     *
     * @return the wind_dir_ e m e p of this vareddy
     */
    public int getWind_dir_EMEP();

    /**
     * Sets the wind_dir_ e m e p of this vareddy.
     *
     * @param wind_dir_EMEP the wind_dir_ e m e p of this vareddy
     */
    public void setWind_dir_EMEP(int wind_dir_EMEP);

    /**
     * Returns the c_lag of this vareddy.
     *
     * @return the c_lag of this vareddy
     */
    public float getC_lag();

    /**
     * Sets the c_lag of this vareddy.
     *
     * @param c_lag the c_lag of this vareddy
     */
    public void setC_lag(float c_lag);

    /**
     * Returns the c_lag_ e m e p of this vareddy.
     *
     * @return the c_lag_ e m e p of this vareddy
     */
    public int getC_lag_EMEP();

    /**
     * Sets the c_lag_ e m e p of this vareddy.
     *
     * @param c_lag_EMEP the c_lag_ e m e p of this vareddy
     */
    public void setC_lag_EMEP(int c_lag_EMEP);

    /**
     * Returns the h_lag of this vareddy.
     *
     * @return the h_lag of this vareddy
     */
    public float getH_lag();

    /**
     * Sets the h_lag of this vareddy.
     *
     * @param h_lag the h_lag of this vareddy
     */
    public void setH_lag(float h_lag);

    /**
     * Returns the h_lag_ e m e p of this vareddy.
     *
     * @return the h_lag_ e m e p of this vareddy
     */
    public int getH_lag_EMEP();

    /**
     * Sets the h_lag_ e m e p of this vareddy.
     *
     * @param h_lag_EMEP the h_lag_ e m e p of this vareddy
     */
    public void setH_lag_EMEP(int h_lag_EMEP);

    /**
     * Returns the licor_t_std of this vareddy.
     *
     * @return the licor_t_std of this vareddy
     */
    public float getLicor_t_std();

    /**
     * Sets the licor_t_std of this vareddy.
     *
     * @param licor_t_std the licor_t_std of this vareddy
     */
    public void setLicor_t_std(float licor_t_std);

    /**
     * Returns the licor_t_std_ e m e p of this vareddy.
     *
     * @return the licor_t_std_ e m e p of this vareddy
     */
    public int getLicor_t_std_EMEP();

    /**
     * Sets the licor_t_std_ e m e p of this vareddy.
     *
     * @param licor_t_std_EMEP the licor_t_std_ e m e p of this vareddy
     */
    public void setLicor_t_std_EMEP(int licor_t_std_EMEP);

    /**
     * Returns the licor_t_av of this vareddy.
     *
     * @return the licor_t_av of this vareddy
     */
    public float getLicor_t_av();

    /**
     * Sets the licor_t_av of this vareddy.
     *
     * @param licor_t_av the licor_t_av of this vareddy
     */
    public void setLicor_t_av(float licor_t_av);

    /**
     * Returns the licor_t_av_ e m e p of this vareddy.
     *
     * @return the licor_t_av_ e m e p of this vareddy
     */
    public int getLicor_t_av_EMEP();

    /**
     * Sets the licor_t_av_ e m e p of this vareddy.
     *
     * @param licor_t_av_EMEP the licor_t_av_ e m e p of this vareddy
     */
    public void setLicor_t_av_EMEP(int licor_t_av_EMEP);

    /**
     * Returns the licor_p_std of this vareddy.
     *
     * @return the licor_p_std of this vareddy
     */
    public float getLicor_p_std();

    /**
     * Sets the licor_p_std of this vareddy.
     *
     * @param licor_p_std the licor_p_std of this vareddy
     */
    public void setLicor_p_std(float licor_p_std);

    /**
     * Returns the licor_p_std_ e m e p of this vareddy.
     *
     * @return the licor_p_std_ e m e p of this vareddy
     */
    public int getLicor_p_std_EMEP();

    /**
     * Sets the licor_p_std_ e m e p of this vareddy.
     *
     * @param licor_p_std_EMEP the licor_p_std_ e m e p of this vareddy
     */
    public void setLicor_p_std_EMEP(int licor_p_std_EMEP);

    /**
     * Returns the licor_p_av of this vareddy.
     *
     * @return the licor_p_av of this vareddy
     */
    public float getLicor_p_av();

    /**
     * Sets the licor_p_av of this vareddy.
     *
     * @param licor_p_av the licor_p_av of this vareddy
     */
    public void setLicor_p_av(float licor_p_av);

    /**
     * Returns the licor_p_av_ e m e p of this vareddy.
     *
     * @return the licor_p_av_ e m e p of this vareddy
     */
    public int getLicor_p_av_EMEP();

    /**
     * Sets the licor_p_av_ e m e p of this vareddy.
     *
     * @param licor_p_av_EMEP the licor_p_av_ e m e p of this vareddy
     */
    public void setLicor_p_av_EMEP(int licor_p_av_EMEP);

    /**
     * Returns the h_sub of this vareddy.
     *
     * @return the h_sub of this vareddy
     */
    public float getH_sub();

    /**
     * Sets the h_sub of this vareddy.
     *
     * @param H_sub the h_sub of this vareddy
     */
    public void setH_sub(float H_sub);

    /**
     * Returns the h_sub_ e m e p of this vareddy.
     *
     * @return the h_sub_ e m e p of this vareddy
     */
    public int getH_sub_EMEP();

    /**
     * Sets the h_sub_ e m e p of this vareddy.
     *
     * @param H_sub_EMEP the h_sub_ e m e p of this vareddy
     */
    public void setH_sub_EMEP(int H_sub_EMEP);

    /**
     * Returns the l e_sub of this vareddy.
     *
     * @return the l e_sub of this vareddy
     */
    public float getLE_sub();

    /**
     * Sets the l e_sub of this vareddy.
     *
     * @param LE_sub the l e_sub of this vareddy
     */
    public void setLE_sub(float LE_sub);

    /**
     * Returns the l e_sub_ e m e p of this vareddy.
     *
     * @return the l e_sub_ e m e p of this vareddy
     */
    public int getLE_sub_EMEP();

    /**
     * Sets the l e_sub_ e m e p of this vareddy.
     *
     * @param LE_sub_EMEP the l e_sub_ e m e p of this vareddy
     */
    public void setLE_sub_EMEP(int LE_sub_EMEP);

    /**
     * Returns the e_sub of this vareddy.
     *
     * @return the e_sub of this vareddy
     */
    public float getE_sub();

    /**
     * Sets the e_sub of this vareddy.
     *
     * @param E_sub the e_sub of this vareddy
     */
    public void setE_sub(float E_sub);

    /**
     * Returns the e_sub_ e m e p of this vareddy.
     *
     * @return the e_sub_ e m e p of this vareddy
     */
    public int getE_sub_EMEP();

    /**
     * Sets the e_sub_ e m e p of this vareddy.
     *
     * @param E_sub_EMEP the e_sub_ e m e p of this vareddy
     */
    public void setE_sub_EMEP(int E_sub_EMEP);

    /**
     * Returns the f_c_sub of this vareddy.
     *
     * @return the f_c_sub of this vareddy
     */
    public float getF_c_sub();

    /**
     * Sets the f_c_sub of this vareddy.
     *
     * @param F_c_sub the f_c_sub of this vareddy
     */
    public void setF_c_sub(float F_c_sub);

    /**
     * Returns the f_c_sub_ e m e p of this vareddy.
     *
     * @return the f_c_sub_ e m e p of this vareddy
     */
    public int getF_c_sub_EMEP();

    /**
     * Sets the f_c_sub_ e m e p of this vareddy.
     *
     * @param F_c_sub_EMEP the f_c_sub_ e m e p of this vareddy
     */
    public void setF_c_sub_EMEP(int F_c_sub_EMEP);

    /**
     * Returns the tau_sub of this vareddy.
     *
     * @return the tau_sub of this vareddy
     */
    public float getTau_sub();

    /**
     * Sets the tau_sub of this vareddy.
     *
     * @param tau_sub the tau_sub of this vareddy
     */
    public void setTau_sub(float tau_sub);

    /**
     * Returns the tau_sub_ e m e p of this vareddy.
     *
     * @return the tau_sub_ e m e p of this vareddy
     */
    public int getTau_sub_EMEP();

    /**
     * Sets the tau_sub_ e m e p of this vareddy.
     *
     * @param tau_sub_EMEP the tau_sub_ e m e p of this vareddy
     */
    public void setTau_sub_EMEP(int tau_sub_EMEP);

    /**
     * Returns the u_star_sub of this vareddy.
     *
     * @return the u_star_sub of this vareddy
     */
    public float getU_star_sub();

    /**
     * Sets the u_star_sub of this vareddy.
     *
     * @param u_star_sub the u_star_sub of this vareddy
     */
    public void setU_star_sub(float u_star_sub);

    /**
     * Returns the u_star_sub_ e m e p of this vareddy.
     *
     * @return the u_star_sub_ e m e p of this vareddy
     */
    public int getU_star_sub_EMEP();

    /**
     * Sets the u_star_sub_ e m e p of this vareddy.
     *
     * @param u_star_sub_EMEP the u_star_sub_ e m e p of this vareddy
     */
    public void setU_star_sub_EMEP(int u_star_sub_EMEP);

    /**
     * Returns the m o_length_sub of this vareddy.
     *
     * @return the m o_length_sub of this vareddy
     */
    public float getMO_length_sub();

    /**
     * Sets the m o_length_sub of this vareddy.
     *
     * @param MO_length_sub the m o_length_sub of this vareddy
     */
    public void setMO_length_sub(float MO_length_sub);

    /**
     * Returns the m o_length_sub_ e m e p of this vareddy.
     *
     * @return the m o_length_sub_ e m e p of this vareddy
     */
    public int getMO_length_sub_EMEP();

    /**
     * Sets the m o_length_sub_ e m e p of this vareddy.
     *
     * @param MO_length_sub_EMEP the m o_length_sub_ e m e p of this vareddy
     */
    public void setMO_length_sub_EMEP(int MO_length_sub_EMEP);

    /**
     * Returns the std_u_sub of this vareddy.
     *
     * @return the std_u_sub of this vareddy
     */
    public float getStd_u_sub();

    /**
     * Sets the std_u_sub of this vareddy.
     *
     * @param std_u_sub the std_u_sub of this vareddy
     */
    public void setStd_u_sub(float std_u_sub);

    /**
     * Returns the std_u_sub_ e m e p of this vareddy.
     *
     * @return the std_u_sub_ e m e p of this vareddy
     */
    public int getStd_u_sub_EMEP();

    /**
     * Sets the std_u_sub_ e m e p of this vareddy.
     *
     * @param std_u_sub_EMEP the std_u_sub_ e m e p of this vareddy
     */
    public void setStd_u_sub_EMEP(int std_u_sub_EMEP);

    /**
     * Returns the std_v_sub of this vareddy.
     *
     * @return the std_v_sub of this vareddy
     */
    public float getStd_v_sub();

    /**
     * Sets the std_v_sub of this vareddy.
     *
     * @param std_v_sub the std_v_sub of this vareddy
     */
    public void setStd_v_sub(float std_v_sub);

    /**
     * Returns the std_v_sub_ e m e p of this vareddy.
     *
     * @return the std_v_sub_ e m e p of this vareddy
     */
    public int getStd_v_sub_EMEP();

    /**
     * Sets the std_v_sub_ e m e p of this vareddy.
     *
     * @param std_v_sub_EMEP the std_v_sub_ e m e p of this vareddy
     */
    public void setStd_v_sub_EMEP(int std_v_sub_EMEP);

    /**
     * Returns the std_w_sub of this vareddy.
     *
     * @return the std_w_sub of this vareddy
     */
    public float getStd_w_sub();

    /**
     * Sets the std_w_sub of this vareddy.
     *
     * @param std_w_sub the std_w_sub of this vareddy
     */
    public void setStd_w_sub(float std_w_sub);

    /**
     * Returns the std_w_sub_ e m e p of this vareddy.
     *
     * @return the std_w_sub_ e m e p of this vareddy
     */
    public int getStd_w_sub_EMEP();

    /**
     * Sets the std_w_sub_ e m e p of this vareddy.
     *
     * @param std_w_sub_EMEP the std_w_sub_ e m e p of this vareddy
     */
    public void setStd_w_sub_EMEP(int std_w_sub_EMEP);

    /**
     * Returns the std_t_sub of this vareddy.
     *
     * @return the std_t_sub of this vareddy
     */
    public float getStd_t_sub();

    /**
     * Sets the std_t_sub of this vareddy.
     *
     * @param std_t_sub the std_t_sub of this vareddy
     */
    public void setStd_t_sub(float std_t_sub);

    /**
     * Returns the std_t_sub_ e m e p of this vareddy.
     *
     * @return the std_t_sub_ e m e p of this vareddy
     */
    public int getStd_t_sub_EMEP();

    /**
     * Sets the std_t_sub_ e m e p of this vareddy.
     *
     * @param std_t_sub_EMEP the std_t_sub_ e m e p of this vareddy
     */
    public void setStd_t_sub_EMEP(int std_t_sub_EMEP);

    /**
     * Returns the std_c_sub of this vareddy.
     *
     * @return the std_c_sub of this vareddy
     */
    public float getStd_c_sub();

    /**
     * Sets the std_c_sub of this vareddy.
     *
     * @param std_c_sub the std_c_sub of this vareddy
     */
    public void setStd_c_sub(float std_c_sub);

    /**
     * Returns the std_c_sub_ e m e p of this vareddy.
     *
     * @return the std_c_sub_ e m e p of this vareddy
     */
    public int getStd_c_sub_EMEP();

    /**
     * Sets the std_c_sub_ e m e p of this vareddy.
     *
     * @param std_c_sub_EMEP the std_c_sub_ e m e p of this vareddy
     */
    public void setStd_c_sub_EMEP(int std_c_sub_EMEP);

    /**
     * Returns the std_h_sub of this vareddy.
     *
     * @return the std_h_sub of this vareddy
     */
    public float getStd_h_sub();

    /**
     * Sets the std_h_sub of this vareddy.
     *
     * @param std_h_sub the std_h_sub of this vareddy
     */
    public void setStd_h_sub(float std_h_sub);

    /**
     * Returns the std_h_sub_ e m e p of this vareddy.
     *
     * @return the std_h_sub_ e m e p of this vareddy
     */
    public int getStd_h_sub_EMEP();

    /**
     * Sets the std_h_sub_ e m e p of this vareddy.
     *
     * @param std_h_sub_EMEP the std_h_sub_ e m e p of this vareddy
     */
    public void setStd_h_sub_EMEP(int std_h_sub_EMEP);

    /**
     * Returns the av_u_sub of this vareddy.
     *
     * @return the av_u_sub of this vareddy
     */
    public float getAv_u_sub();

    /**
     * Sets the av_u_sub of this vareddy.
     *
     * @param av_u_sub the av_u_sub of this vareddy
     */
    public void setAv_u_sub(float av_u_sub);

    /**
     * Returns the av_u_sub_ e m e p of this vareddy.
     *
     * @return the av_u_sub_ e m e p of this vareddy
     */
    public int getAv_u_sub_EMEP();

    /**
     * Sets the av_u_sub_ e m e p of this vareddy.
     *
     * @param av_u_sub_EMEP the av_u_sub_ e m e p of this vareddy
     */
    public void setAv_u_sub_EMEP(int av_u_sub_EMEP);

    /**
     * Returns the av_v_sub of this vareddy.
     *
     * @return the av_v_sub of this vareddy
     */
    public float getAv_v_sub();

    /**
     * Sets the av_v_sub of this vareddy.
     *
     * @param av_v_sub the av_v_sub of this vareddy
     */
    public void setAv_v_sub(float av_v_sub);

    /**
     * Returns the av_v_sub_ e m e p of this vareddy.
     *
     * @return the av_v_sub_ e m e p of this vareddy
     */
    public int getAv_v_sub_EMEP();

    /**
     * Sets the av_v_sub_ e m e p of this vareddy.
     *
     * @param av_v_sub_EMEP the av_v_sub_ e m e p of this vareddy
     */
    public void setAv_v_sub_EMEP(int av_v_sub_EMEP);

    /**
     * Returns the av_w_sub of this vareddy.
     *
     * @return the av_w_sub of this vareddy
     */
    public float getAv_w_sub();

    /**
     * Sets the av_w_sub of this vareddy.
     *
     * @param av_w_sub the av_w_sub of this vareddy
     */
    public void setAv_w_sub(float av_w_sub);

    /**
     * Returns the av_w_sub_ e m e p of this vareddy.
     *
     * @return the av_w_sub_ e m e p of this vareddy
     */
    public int getAv_w_sub_EMEP();

    /**
     * Sets the av_w_sub_ e m e p of this vareddy.
     *
     * @param av_w_sub_EMEP the av_w_sub_ e m e p of this vareddy
     */
    public void setAv_w_sub_EMEP(int av_w_sub_EMEP);

    /**
     * Returns the av_t_sub of this vareddy.
     *
     * @return the av_t_sub of this vareddy
     */
    public float getAv_t_sub();

    /**
     * Sets the av_t_sub of this vareddy.
     *
     * @param av_t_sub the av_t_sub of this vareddy
     */
    public void setAv_t_sub(float av_t_sub);

    /**
     * Returns the av_t_sub_ e m e p of this vareddy.
     *
     * @return the av_t_sub_ e m e p of this vareddy
     */
    public int getAv_t_sub_EMEP();

    /**
     * Sets the av_t_sub_ e m e p of this vareddy.
     *
     * @param av_t_sub_EMEP the av_t_sub_ e m e p of this vareddy
     */
    public void setAv_t_sub_EMEP(int av_t_sub_EMEP);

    /**
     * Returns the av_c_sub of this vareddy.
     *
     * @return the av_c_sub of this vareddy
     */
    public float getAv_c_sub();

    /**
     * Sets the av_c_sub of this vareddy.
     *
     * @param av_c_sub the av_c_sub of this vareddy
     */
    public void setAv_c_sub(float av_c_sub);

    /**
     * Returns the av_c_sub_ e m e p of this vareddy.
     *
     * @return the av_c_sub_ e m e p of this vareddy
     */
    public int getAv_c_sub_EMEP();

    /**
     * Sets the av_c_sub_ e m e p of this vareddy.
     *
     * @param av_c_sub_EMEP the av_c_sub_ e m e p of this vareddy
     */
    public void setAv_c_sub_EMEP(int av_c_sub_EMEP);

    /**
     * Returns the av_h_sub of this vareddy.
     *
     * @return the av_h_sub of this vareddy
     */
    public float getAv_h_sub();

    /**
     * Sets the av_h_sub of this vareddy.
     *
     * @param av_h_sub the av_h_sub of this vareddy
     */
    public void setAv_h_sub(float av_h_sub);

    /**
     * Returns the av_h_sub_ e m e p of this vareddy.
     *
     * @return the av_h_sub_ e m e p of this vareddy
     */
    public int getAv_h_sub_EMEP();

    /**
     * Sets the av_h_sub_ e m e p of this vareddy.
     *
     * @param av_h_sub_EMEP the av_h_sub_ e m e p of this vareddy
     */
    public void setAv_h_sub_EMEP(int av_h_sub_EMEP);

    /**
     * Returns the u_sub of this vareddy.
     *
     * @return the u_sub of this vareddy
     */
    public float getU_sub();

    /**
     * Sets the u_sub of this vareddy.
     *
     * @param U_sub the u_sub of this vareddy
     */
    public void setU_sub(float U_sub);

    /**
     * Returns the u_sub_ e m e p of this vareddy.
     *
     * @return the u_sub_ e m e p of this vareddy
     */
    public int getU_sub_EMEP();

    /**
     * Sets the u_sub_ e m e p of this vareddy.
     *
     * @param U_sub_EMEP the u_sub_ e m e p of this vareddy
     */
    public void setU_sub_EMEP(int U_sub_EMEP);

    /**
     * Returns the wind_dir_sub of this vareddy.
     *
     * @return the wind_dir_sub of this vareddy
     */
    public float getWind_dir_sub();

    /**
     * Sets the wind_dir_sub of this vareddy.
     *
     * @param wind_dir_sub the wind_dir_sub of this vareddy
     */
    public void setWind_dir_sub(float wind_dir_sub);

    /**
     * Returns the wind_dir_sub_ e m e p of this vareddy.
     *
     * @return the wind_dir_sub_ e m e p of this vareddy
     */
    public int getWind_dir_sub_EMEP();

    /**
     * Sets the wind_dir_sub_ e m e p of this vareddy.
     *
     * @param wind_dir_sub_EMEP the wind_dir_sub_ e m e p of this vareddy
     */
    public void setWind_dir_sub_EMEP(int wind_dir_sub_EMEP);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Vareddy vareddy);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Vareddy> toCacheModel();

    @Override
    public Vareddy toEscapedModel();

    @Override
    public Vareddy toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
