package fi.csc.smear.db.model.impl;

import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;

import fi.csc.smear.db.model.Hyde_eddy233;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import java.util.Date;

/**
 * The cache model class for representing Hyde_eddy233 in entity cache.
 *
 * @author pj
 * @see Hyde_eddy233
 * @generated
 */
public class Hyde_eddy233CacheModel implements CacheModel<Hyde_eddy233>,
    Externalizable {
    public long samptime;
    public float H;
    public float LE;
    public float E;
    public float F_c;
    public float tau;
    public float u_star;
    public float MO_length;
    public float std_u;
    public float std_v;
    public float std_w;
    public float av_u;
    public float av_v;
    public float av_w;
    public float av_t;
    public float av_c;
    public float av_h;
    public float U;
    public float wind_dir;
    public float eta;
    public float theta;
    public float beta;
    public int c_lag;
    public int h_lag;
    public int err_packet;
    public float licor_t_av;
    public float licor_t_std;
    public float licor_p_av;
    public float licor_p_std;
    public float F_CPC;
    public float std_CPC;
    public float av_CPC;
    public int CPC_lag;
    public float std_t;
    public float std_c;
    public float std_h;
    public int quality;
    public int Qc_H;
    public int Qc_LE;
    public int Qc_E;
    public int Qc_F_c;
    public int Qc_tau;
    public int Qc_F_CPC;
    public int H_EMEP;
    public int LE_EMEP;
    public int E_EMEP;
    public int F_c_EMEP;
    public int tau_EMEP;
    public int u_star_EMEP;
    public int MO_length_EMEP;
    public int std_u_EMEP;
    public int std_v_EMEP;
    public int std_w_EMEP;
    public int av_u_EMEP;
    public int av_v_EMEP;
    public int av_w_EMEP;
    public int av_t_EMEP;
    public int av_c_EMEP;
    public int av_h_EMEP;
    public int U_EMEP;
    public int wind_dir_EMEP;
    public int eta_EMEP;
    public int theta_EMEP;
    public int beta_EMEP;
    public int c_lag_EMEP;
    public int h_lag_EMEP;
    public int err_packet_EMEP;
    public int licor_t_av_EMEP;
    public int licor_t_std_EMEP;
    public int licor_p_av_EMEP;
    public int licor_p_std_EMEP;
    public int F_CPC_EMEP;
    public int std_CPC_EMEP;
    public int av_CPC_EMEP;
    public int CPC_lag_EMEP;
    public int std_t_EMEP;
    public int std_c_EMEP;
    public int std_h_EMEP;
    public int quality_EMEP;
    public int Qc_H_EMEP;
    public int Qc_LE_EMEP;
    public int Qc_E_EMEP;
    public int Qc_F_c_EMEP;
    public int Qc_tau_EMEP;
    public int Qc_F_CPC_EMEP;
    public float NEE;
    public int Qc_gapf_NEE;
    public float GPP;
    public float TER;
    public float H_gapf;
    public int Qc_gapf_H;
    public float ET_gapf;
    public int Qc_gapf_ET;
    public int NEE_EMEP;
    public int Qc_gapf_NEE_EMEP;
    public int GPP_EMEP;
    public int TER_EMEP;
    public int H_gapf_EMEP;
    public int Qc_gapf_H_EMEP;
    public int ET_gapf_EMEP;
    public int Qc_gapf_ET_EMEP;

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(203);

        sb.append("{samptime=");
        sb.append(samptime);
        sb.append(", H=");
        sb.append(H);
        sb.append(", LE=");
        sb.append(LE);
        sb.append(", E=");
        sb.append(E);
        sb.append(", F_c=");
        sb.append(F_c);
        sb.append(", tau=");
        sb.append(tau);
        sb.append(", u_star=");
        sb.append(u_star);
        sb.append(", MO_length=");
        sb.append(MO_length);
        sb.append(", std_u=");
        sb.append(std_u);
        sb.append(", std_v=");
        sb.append(std_v);
        sb.append(", std_w=");
        sb.append(std_w);
        sb.append(", av_u=");
        sb.append(av_u);
        sb.append(", av_v=");
        sb.append(av_v);
        sb.append(", av_w=");
        sb.append(av_w);
        sb.append(", av_t=");
        sb.append(av_t);
        sb.append(", av_c=");
        sb.append(av_c);
        sb.append(", av_h=");
        sb.append(av_h);
        sb.append(", U=");
        sb.append(U);
        sb.append(", wind_dir=");
        sb.append(wind_dir);
        sb.append(", eta=");
        sb.append(eta);
        sb.append(", theta=");
        sb.append(theta);
        sb.append(", beta=");
        sb.append(beta);
        sb.append(", c_lag=");
        sb.append(c_lag);
        sb.append(", h_lag=");
        sb.append(h_lag);
        sb.append(", err_packet=");
        sb.append(err_packet);
        sb.append(", licor_t_av=");
        sb.append(licor_t_av);
        sb.append(", licor_t_std=");
        sb.append(licor_t_std);
        sb.append(", licor_p_av=");
        sb.append(licor_p_av);
        sb.append(", licor_p_std=");
        sb.append(licor_p_std);
        sb.append(", F_CPC=");
        sb.append(F_CPC);
        sb.append(", std_CPC=");
        sb.append(std_CPC);
        sb.append(", av_CPC=");
        sb.append(av_CPC);
        sb.append(", CPC_lag=");
        sb.append(CPC_lag);
        sb.append(", std_t=");
        sb.append(std_t);
        sb.append(", std_c=");
        sb.append(std_c);
        sb.append(", std_h=");
        sb.append(std_h);
        sb.append(", quality=");
        sb.append(quality);
        sb.append(", Qc_H=");
        sb.append(Qc_H);
        sb.append(", Qc_LE=");
        sb.append(Qc_LE);
        sb.append(", Qc_E=");
        sb.append(Qc_E);
        sb.append(", Qc_F_c=");
        sb.append(Qc_F_c);
        sb.append(", Qc_tau=");
        sb.append(Qc_tau);
        sb.append(", Qc_F_CPC=");
        sb.append(Qc_F_CPC);
        sb.append(", H_EMEP=");
        sb.append(H_EMEP);
        sb.append(", LE_EMEP=");
        sb.append(LE_EMEP);
        sb.append(", E_EMEP=");
        sb.append(E_EMEP);
        sb.append(", F_c_EMEP=");
        sb.append(F_c_EMEP);
        sb.append(", tau_EMEP=");
        sb.append(tau_EMEP);
        sb.append(", u_star_EMEP=");
        sb.append(u_star_EMEP);
        sb.append(", MO_length_EMEP=");
        sb.append(MO_length_EMEP);
        sb.append(", std_u_EMEP=");
        sb.append(std_u_EMEP);
        sb.append(", std_v_EMEP=");
        sb.append(std_v_EMEP);
        sb.append(", std_w_EMEP=");
        sb.append(std_w_EMEP);
        sb.append(", av_u_EMEP=");
        sb.append(av_u_EMEP);
        sb.append(", av_v_EMEP=");
        sb.append(av_v_EMEP);
        sb.append(", av_w_EMEP=");
        sb.append(av_w_EMEP);
        sb.append(", av_t_EMEP=");
        sb.append(av_t_EMEP);
        sb.append(", av_c_EMEP=");
        sb.append(av_c_EMEP);
        sb.append(", av_h_EMEP=");
        sb.append(av_h_EMEP);
        sb.append(", U_EMEP=");
        sb.append(U_EMEP);
        sb.append(", wind_dir_EMEP=");
        sb.append(wind_dir_EMEP);
        sb.append(", eta_EMEP=");
        sb.append(eta_EMEP);
        sb.append(", theta_EMEP=");
        sb.append(theta_EMEP);
        sb.append(", beta_EMEP=");
        sb.append(beta_EMEP);
        sb.append(", c_lag_EMEP=");
        sb.append(c_lag_EMEP);
        sb.append(", h_lag_EMEP=");
        sb.append(h_lag_EMEP);
        sb.append(", err_packet_EMEP=");
        sb.append(err_packet_EMEP);
        sb.append(", licor_t_av_EMEP=");
        sb.append(licor_t_av_EMEP);
        sb.append(", licor_t_std_EMEP=");
        sb.append(licor_t_std_EMEP);
        sb.append(", licor_p_av_EMEP=");
        sb.append(licor_p_av_EMEP);
        sb.append(", licor_p_std_EMEP=");
        sb.append(licor_p_std_EMEP);
        sb.append(", F_CPC_EMEP=");
        sb.append(F_CPC_EMEP);
        sb.append(", std_CPC_EMEP=");
        sb.append(std_CPC_EMEP);
        sb.append(", av_CPC_EMEP=");
        sb.append(av_CPC_EMEP);
        sb.append(", CPC_lag_EMEP=");
        sb.append(CPC_lag_EMEP);
        sb.append(", std_t_EMEP=");
        sb.append(std_t_EMEP);
        sb.append(", std_c_EMEP=");
        sb.append(std_c_EMEP);
        sb.append(", std_h_EMEP=");
        sb.append(std_h_EMEP);
        sb.append(", quality_EMEP=");
        sb.append(quality_EMEP);
        sb.append(", Qc_H_EMEP=");
        sb.append(Qc_H_EMEP);
        sb.append(", Qc_LE_EMEP=");
        sb.append(Qc_LE_EMEP);
        sb.append(", Qc_E_EMEP=");
        sb.append(Qc_E_EMEP);
        sb.append(", Qc_F_c_EMEP=");
        sb.append(Qc_F_c_EMEP);
        sb.append(", Qc_tau_EMEP=");
        sb.append(Qc_tau_EMEP);
        sb.append(", Qc_F_CPC_EMEP=");
        sb.append(Qc_F_CPC_EMEP);
        sb.append(", NEE=");
        sb.append(NEE);
        sb.append(", Qc_gapf_NEE=");
        sb.append(Qc_gapf_NEE);
        sb.append(", GPP=");
        sb.append(GPP);
        sb.append(", TER=");
        sb.append(TER);
        sb.append(", H_gapf=");
        sb.append(H_gapf);
        sb.append(", Qc_gapf_H=");
        sb.append(Qc_gapf_H);
        sb.append(", ET_gapf=");
        sb.append(ET_gapf);
        sb.append(", Qc_gapf_ET=");
        sb.append(Qc_gapf_ET);
        sb.append(", NEE_EMEP=");
        sb.append(NEE_EMEP);
        sb.append(", Qc_gapf_NEE_EMEP=");
        sb.append(Qc_gapf_NEE_EMEP);
        sb.append(", GPP_EMEP=");
        sb.append(GPP_EMEP);
        sb.append(", TER_EMEP=");
        sb.append(TER_EMEP);
        sb.append(", H_gapf_EMEP=");
        sb.append(H_gapf_EMEP);
        sb.append(", Qc_gapf_H_EMEP=");
        sb.append(Qc_gapf_H_EMEP);
        sb.append(", ET_gapf_EMEP=");
        sb.append(ET_gapf_EMEP);
        sb.append(", Qc_gapf_ET_EMEP=");
        sb.append(Qc_gapf_ET_EMEP);
        sb.append("}");

        return sb.toString();
    }

    @Override
    public Hyde_eddy233 toEntityModel() {
        Hyde_eddy233Impl hyde_eddy233Impl = new Hyde_eddy233Impl();

        if (samptime == Long.MIN_VALUE) {
            hyde_eddy233Impl.setSamptime(null);
        } else {
            hyde_eddy233Impl.setSamptime(new Date(samptime));
        }

        hyde_eddy233Impl.setH(H);
        hyde_eddy233Impl.setLE(LE);
        hyde_eddy233Impl.setE(E);
        hyde_eddy233Impl.setF_c(F_c);
        hyde_eddy233Impl.setTau(tau);
        hyde_eddy233Impl.setU_star(u_star);
        hyde_eddy233Impl.setMO_length(MO_length);
        hyde_eddy233Impl.setStd_u(std_u);
        hyde_eddy233Impl.setStd_v(std_v);
        hyde_eddy233Impl.setStd_w(std_w);
        hyde_eddy233Impl.setAv_u(av_u);
        hyde_eddy233Impl.setAv_v(av_v);
        hyde_eddy233Impl.setAv_w(av_w);
        hyde_eddy233Impl.setAv_t(av_t);
        hyde_eddy233Impl.setAv_c(av_c);
        hyde_eddy233Impl.setAv_h(av_h);
        hyde_eddy233Impl.setU(U);
        hyde_eddy233Impl.setWind_dir(wind_dir);
        hyde_eddy233Impl.setEta(eta);
        hyde_eddy233Impl.setTheta(theta);
        hyde_eddy233Impl.setBeta(beta);
        hyde_eddy233Impl.setC_lag(c_lag);
        hyde_eddy233Impl.setH_lag(h_lag);
        hyde_eddy233Impl.setErr_packet(err_packet);
        hyde_eddy233Impl.setLicor_t_av(licor_t_av);
        hyde_eddy233Impl.setLicor_t_std(licor_t_std);
        hyde_eddy233Impl.setLicor_p_av(licor_p_av);
        hyde_eddy233Impl.setLicor_p_std(licor_p_std);
        hyde_eddy233Impl.setF_CPC(F_CPC);
        hyde_eddy233Impl.setStd_CPC(std_CPC);
        hyde_eddy233Impl.setAv_CPC(av_CPC);
        hyde_eddy233Impl.setCPC_lag(CPC_lag);
        hyde_eddy233Impl.setStd_t(std_t);
        hyde_eddy233Impl.setStd_c(std_c);
        hyde_eddy233Impl.setStd_h(std_h);
        hyde_eddy233Impl.setQuality(quality);
        hyde_eddy233Impl.setQc_H(Qc_H);
        hyde_eddy233Impl.setQc_LE(Qc_LE);
        hyde_eddy233Impl.setQc_E(Qc_E);
        hyde_eddy233Impl.setQc_F_c(Qc_F_c);
        hyde_eddy233Impl.setQc_tau(Qc_tau);
        hyde_eddy233Impl.setQc_F_CPC(Qc_F_CPC);
        hyde_eddy233Impl.setH_EMEP(H_EMEP);
        hyde_eddy233Impl.setLE_EMEP(LE_EMEP);
        hyde_eddy233Impl.setE_EMEP(E_EMEP);
        hyde_eddy233Impl.setF_c_EMEP(F_c_EMEP);
        hyde_eddy233Impl.setTau_EMEP(tau_EMEP);
        hyde_eddy233Impl.setU_star_EMEP(u_star_EMEP);
        hyde_eddy233Impl.setMO_length_EMEP(MO_length_EMEP);
        hyde_eddy233Impl.setStd_u_EMEP(std_u_EMEP);
        hyde_eddy233Impl.setStd_v_EMEP(std_v_EMEP);
        hyde_eddy233Impl.setStd_w_EMEP(std_w_EMEP);
        hyde_eddy233Impl.setAv_u_EMEP(av_u_EMEP);
        hyde_eddy233Impl.setAv_v_EMEP(av_v_EMEP);
        hyde_eddy233Impl.setAv_w_EMEP(av_w_EMEP);
        hyde_eddy233Impl.setAv_t_EMEP(av_t_EMEP);
        hyde_eddy233Impl.setAv_c_EMEP(av_c_EMEP);
        hyde_eddy233Impl.setAv_h_EMEP(av_h_EMEP);
        hyde_eddy233Impl.setU_EMEP(U_EMEP);
        hyde_eddy233Impl.setWind_dir_EMEP(wind_dir_EMEP);
        hyde_eddy233Impl.setEta_EMEP(eta_EMEP);
        hyde_eddy233Impl.setTheta_EMEP(theta_EMEP);
        hyde_eddy233Impl.setBeta_EMEP(beta_EMEP);
        hyde_eddy233Impl.setC_lag_EMEP(c_lag_EMEP);
        hyde_eddy233Impl.setH_lag_EMEP(h_lag_EMEP);
        hyde_eddy233Impl.setErr_packet_EMEP(err_packet_EMEP);
        hyde_eddy233Impl.setLicor_t_av_EMEP(licor_t_av_EMEP);
        hyde_eddy233Impl.setLicor_t_std_EMEP(licor_t_std_EMEP);
        hyde_eddy233Impl.setLicor_p_av_EMEP(licor_p_av_EMEP);
        hyde_eddy233Impl.setLicor_p_std_EMEP(licor_p_std_EMEP);
        hyde_eddy233Impl.setF_CPC_EMEP(F_CPC_EMEP);
        hyde_eddy233Impl.setStd_CPC_EMEP(std_CPC_EMEP);
        hyde_eddy233Impl.setAv_CPC_EMEP(av_CPC_EMEP);
        hyde_eddy233Impl.setCPC_lag_EMEP(CPC_lag_EMEP);
        hyde_eddy233Impl.setStd_t_EMEP(std_t_EMEP);
        hyde_eddy233Impl.setStd_c_EMEP(std_c_EMEP);
        hyde_eddy233Impl.setStd_h_EMEP(std_h_EMEP);
        hyde_eddy233Impl.setQuality_EMEP(quality_EMEP);
        hyde_eddy233Impl.setQc_H_EMEP(Qc_H_EMEP);
        hyde_eddy233Impl.setQc_LE_EMEP(Qc_LE_EMEP);
        hyde_eddy233Impl.setQc_E_EMEP(Qc_E_EMEP);
        hyde_eddy233Impl.setQc_F_c_EMEP(Qc_F_c_EMEP);
        hyde_eddy233Impl.setQc_tau_EMEP(Qc_tau_EMEP);
        hyde_eddy233Impl.setQc_F_CPC_EMEP(Qc_F_CPC_EMEP);
        hyde_eddy233Impl.setNEE(NEE);
        hyde_eddy233Impl.setQc_gapf_NEE(Qc_gapf_NEE);
        hyde_eddy233Impl.setGPP(GPP);
        hyde_eddy233Impl.setTER(TER);
        hyde_eddy233Impl.setH_gapf(H_gapf);
        hyde_eddy233Impl.setQc_gapf_H(Qc_gapf_H);
        hyde_eddy233Impl.setET_gapf(ET_gapf);
        hyde_eddy233Impl.setQc_gapf_ET(Qc_gapf_ET);
        hyde_eddy233Impl.setNEE_EMEP(NEE_EMEP);
        hyde_eddy233Impl.setQc_gapf_NEE_EMEP(Qc_gapf_NEE_EMEP);
        hyde_eddy233Impl.setGPP_EMEP(GPP_EMEP);
        hyde_eddy233Impl.setTER_EMEP(TER_EMEP);
        hyde_eddy233Impl.setH_gapf_EMEP(H_gapf_EMEP);
        hyde_eddy233Impl.setQc_gapf_H_EMEP(Qc_gapf_H_EMEP);
        hyde_eddy233Impl.setET_gapf_EMEP(ET_gapf_EMEP);
        hyde_eddy233Impl.setQc_gapf_ET_EMEP(Qc_gapf_ET_EMEP);

        hyde_eddy233Impl.resetOriginalValues();

        return hyde_eddy233Impl;
    }

    @Override
    public void readExternal(ObjectInput objectInput) throws IOException {
        samptime = objectInput.readLong();
        H = objectInput.readFloat();
        LE = objectInput.readFloat();
        E = objectInput.readFloat();
        F_c = objectInput.readFloat();
        tau = objectInput.readFloat();
        u_star = objectInput.readFloat();
        MO_length = objectInput.readFloat();
        std_u = objectInput.readFloat();
        std_v = objectInput.readFloat();
        std_w = objectInput.readFloat();
        av_u = objectInput.readFloat();
        av_v = objectInput.readFloat();
        av_w = objectInput.readFloat();
        av_t = objectInput.readFloat();
        av_c = objectInput.readFloat();
        av_h = objectInput.readFloat();
        U = objectInput.readFloat();
        wind_dir = objectInput.readFloat();
        eta = objectInput.readFloat();
        theta = objectInput.readFloat();
        beta = objectInput.readFloat();
        c_lag = objectInput.readInt();
        h_lag = objectInput.readInt();
        err_packet = objectInput.readInt();
        licor_t_av = objectInput.readFloat();
        licor_t_std = objectInput.readFloat();
        licor_p_av = objectInput.readFloat();
        licor_p_std = objectInput.readFloat();
        F_CPC = objectInput.readFloat();
        std_CPC = objectInput.readFloat();
        av_CPC = objectInput.readFloat();
        CPC_lag = objectInput.readInt();
        std_t = objectInput.readFloat();
        std_c = objectInput.readFloat();
        std_h = objectInput.readFloat();
        quality = objectInput.readInt();
        Qc_H = objectInput.readInt();
        Qc_LE = objectInput.readInt();
        Qc_E = objectInput.readInt();
        Qc_F_c = objectInput.readInt();
        Qc_tau = objectInput.readInt();
        Qc_F_CPC = objectInput.readInt();
        H_EMEP = objectInput.readInt();
        LE_EMEP = objectInput.readInt();
        E_EMEP = objectInput.readInt();
        F_c_EMEP = objectInput.readInt();
        tau_EMEP = objectInput.readInt();
        u_star_EMEP = objectInput.readInt();
        MO_length_EMEP = objectInput.readInt();
        std_u_EMEP = objectInput.readInt();
        std_v_EMEP = objectInput.readInt();
        std_w_EMEP = objectInput.readInt();
        av_u_EMEP = objectInput.readInt();
        av_v_EMEP = objectInput.readInt();
        av_w_EMEP = objectInput.readInt();
        av_t_EMEP = objectInput.readInt();
        av_c_EMEP = objectInput.readInt();
        av_h_EMEP = objectInput.readInt();
        U_EMEP = objectInput.readInt();
        wind_dir_EMEP = objectInput.readInt();
        eta_EMEP = objectInput.readInt();
        theta_EMEP = objectInput.readInt();
        beta_EMEP = objectInput.readInt();
        c_lag_EMEP = objectInput.readInt();
        h_lag_EMEP = objectInput.readInt();
        err_packet_EMEP = objectInput.readInt();
        licor_t_av_EMEP = objectInput.readInt();
        licor_t_std_EMEP = objectInput.readInt();
        licor_p_av_EMEP = objectInput.readInt();
        licor_p_std_EMEP = objectInput.readInt();
        F_CPC_EMEP = objectInput.readInt();
        std_CPC_EMEP = objectInput.readInt();
        av_CPC_EMEP = objectInput.readInt();
        CPC_lag_EMEP = objectInput.readInt();
        std_t_EMEP = objectInput.readInt();
        std_c_EMEP = objectInput.readInt();
        std_h_EMEP = objectInput.readInt();
        quality_EMEP = objectInput.readInt();
        Qc_H_EMEP = objectInput.readInt();
        Qc_LE_EMEP = objectInput.readInt();
        Qc_E_EMEP = objectInput.readInt();
        Qc_F_c_EMEP = objectInput.readInt();
        Qc_tau_EMEP = objectInput.readInt();
        Qc_F_CPC_EMEP = objectInput.readInt();
        NEE = objectInput.readFloat();
        Qc_gapf_NEE = objectInput.readInt();
        GPP = objectInput.readFloat();
        TER = objectInput.readFloat();
        H_gapf = objectInput.readFloat();
        Qc_gapf_H = objectInput.readInt();
        ET_gapf = objectInput.readFloat();
        Qc_gapf_ET = objectInput.readInt();
        NEE_EMEP = objectInput.readInt();
        Qc_gapf_NEE_EMEP = objectInput.readInt();
        GPP_EMEP = objectInput.readInt();
        TER_EMEP = objectInput.readInt();
        H_gapf_EMEP = objectInput.readInt();
        Qc_gapf_H_EMEP = objectInput.readInt();
        ET_gapf_EMEP = objectInput.readInt();
        Qc_gapf_ET_EMEP = objectInput.readInt();
    }

    @Override
    public void writeExternal(ObjectOutput objectOutput)
        throws IOException {
        objectOutput.writeLong(samptime);
        objectOutput.writeFloat(H);
        objectOutput.writeFloat(LE);
        objectOutput.writeFloat(E);
        objectOutput.writeFloat(F_c);
        objectOutput.writeFloat(tau);
        objectOutput.writeFloat(u_star);
        objectOutput.writeFloat(MO_length);
        objectOutput.writeFloat(std_u);
        objectOutput.writeFloat(std_v);
        objectOutput.writeFloat(std_w);
        objectOutput.writeFloat(av_u);
        objectOutput.writeFloat(av_v);
        objectOutput.writeFloat(av_w);
        objectOutput.writeFloat(av_t);
        objectOutput.writeFloat(av_c);
        objectOutput.writeFloat(av_h);
        objectOutput.writeFloat(U);
        objectOutput.writeFloat(wind_dir);
        objectOutput.writeFloat(eta);
        objectOutput.writeFloat(theta);
        objectOutput.writeFloat(beta);
        objectOutput.writeInt(c_lag);
        objectOutput.writeInt(h_lag);
        objectOutput.writeInt(err_packet);
        objectOutput.writeFloat(licor_t_av);
        objectOutput.writeFloat(licor_t_std);
        objectOutput.writeFloat(licor_p_av);
        objectOutput.writeFloat(licor_p_std);
        objectOutput.writeFloat(F_CPC);
        objectOutput.writeFloat(std_CPC);
        objectOutput.writeFloat(av_CPC);
        objectOutput.writeInt(CPC_lag);
        objectOutput.writeFloat(std_t);
        objectOutput.writeFloat(std_c);
        objectOutput.writeFloat(std_h);
        objectOutput.writeInt(quality);
        objectOutput.writeInt(Qc_H);
        objectOutput.writeInt(Qc_LE);
        objectOutput.writeInt(Qc_E);
        objectOutput.writeInt(Qc_F_c);
        objectOutput.writeInt(Qc_tau);
        objectOutput.writeInt(Qc_F_CPC);
        objectOutput.writeInt(H_EMEP);
        objectOutput.writeInt(LE_EMEP);
        objectOutput.writeInt(E_EMEP);
        objectOutput.writeInt(F_c_EMEP);
        objectOutput.writeInt(tau_EMEP);
        objectOutput.writeInt(u_star_EMEP);
        objectOutput.writeInt(MO_length_EMEP);
        objectOutput.writeInt(std_u_EMEP);
        objectOutput.writeInt(std_v_EMEP);
        objectOutput.writeInt(std_w_EMEP);
        objectOutput.writeInt(av_u_EMEP);
        objectOutput.writeInt(av_v_EMEP);
        objectOutput.writeInt(av_w_EMEP);
        objectOutput.writeInt(av_t_EMEP);
        objectOutput.writeInt(av_c_EMEP);
        objectOutput.writeInt(av_h_EMEP);
        objectOutput.writeInt(U_EMEP);
        objectOutput.writeInt(wind_dir_EMEP);
        objectOutput.writeInt(eta_EMEP);
        objectOutput.writeInt(theta_EMEP);
        objectOutput.writeInt(beta_EMEP);
        objectOutput.writeInt(c_lag_EMEP);
        objectOutput.writeInt(h_lag_EMEP);
        objectOutput.writeInt(err_packet_EMEP);
        objectOutput.writeInt(licor_t_av_EMEP);
        objectOutput.writeInt(licor_t_std_EMEP);
        objectOutput.writeInt(licor_p_av_EMEP);
        objectOutput.writeInt(licor_p_std_EMEP);
        objectOutput.writeInt(F_CPC_EMEP);
        objectOutput.writeInt(std_CPC_EMEP);
        objectOutput.writeInt(av_CPC_EMEP);
        objectOutput.writeInt(CPC_lag_EMEP);
        objectOutput.writeInt(std_t_EMEP);
        objectOutput.writeInt(std_c_EMEP);
        objectOutput.writeInt(std_h_EMEP);
        objectOutput.writeInt(quality_EMEP);
        objectOutput.writeInt(Qc_H_EMEP);
        objectOutput.writeInt(Qc_LE_EMEP);
        objectOutput.writeInt(Qc_E_EMEP);
        objectOutput.writeInt(Qc_F_c_EMEP);
        objectOutput.writeInt(Qc_tau_EMEP);
        objectOutput.writeInt(Qc_F_CPC_EMEP);
        objectOutput.writeFloat(NEE);
        objectOutput.writeInt(Qc_gapf_NEE);
        objectOutput.writeFloat(GPP);
        objectOutput.writeFloat(TER);
        objectOutput.writeFloat(H_gapf);
        objectOutput.writeInt(Qc_gapf_H);
        objectOutput.writeFloat(ET_gapf);
        objectOutput.writeInt(Qc_gapf_ET);
        objectOutput.writeInt(NEE_EMEP);
        objectOutput.writeInt(Qc_gapf_NEE_EMEP);
        objectOutput.writeInt(GPP_EMEP);
        objectOutput.writeInt(TER_EMEP);
        objectOutput.writeInt(H_gapf_EMEP);
        objectOutput.writeInt(Qc_gapf_H_EMEP);
        objectOutput.writeInt(ET_gapf_EMEP);
        objectOutput.writeInt(Qc_gapf_ET_EMEP);
    }
}
