package fi.csc.smear.db.model.impl;

import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;

import fi.csc.smear.db.model.kvjEddy;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import java.util.Date;

/**
 * The cache model class for representing kvjEddy in entity cache.
 *
 * @author pj
 * @see kvjEddy
 * @generated
 */
public class kvjEddyCacheModel implements CacheModel<kvjEddy>, Externalizable {
    public long samptime;
    public float H;
    public int H_EMEP;
    public int Qc_H;
    public int Qc_H_EMEP;
    public float tau;
    public int tau_EMEP;
    public int Qc_tau;
    public int Qc_tau_EMEP;
    public float u_star;
    public int u_star_EMEP;
    public float MO_length;
    public int MO_length_EMEP;
    public int err_packet;
    public int err_packet_EMEP;
    public float F_CO2_LI72;
    public int F_CO2_LI72_EMEP;
    public int Qc_CO2_LI72;
    public int Qc_CO2_LI72_EMEP;
    public float F_CH4_PICA;
    public int F_CH4_PICA_EMEP;
    public int Qc_CH4_PICA;
    public int Qc_CH4_PICA_EMEP;
    public float F_H2O_LI72;
    public int F_H2O_LI72_EMEP;
    public int Qc_H2O_LI72;
    public int Qc_H2O_LI72_EMEP;
    public float F_H2O_PICA;
    public int F_H2O_PICA_EMEP;
    public int Qc_H2O_PICA;
    public int Qc_H2O_PICA_EMEP;
    public float LE_LI72;
    public int LE_LI72_EMEP;
    public float LE_PICA;
    public int LE_PICA_EMEP;
    public float U;
    public int U_EMEP;
    public float wind_dir;
    public int wind_dir_EMEP;
    public float av_u;
    public int av_u_EMEP;
    public float av_v;
    public int av_v_EMEP;
    public float av_w;
    public int av_w_EMEP;
    public float av_t;
    public int av_t_EMEP;
    public float av_c_LI72;
    public int av_c_LI72_EMEP;
    public float av_h_LI72;
    public int av_h_LI72_EMEP;
    public float av_h_PICA;
    public int av_h_PICA_EMEP;
    public float av_CH4;
    public int av_CH4_EMEP;
    public float std_u;
    public int std_u_EMEP;
    public float std_v;
    public int std_v_EMEP;
    public float std_w;
    public int std_w_EMEP;
    public float std_t;
    public int std_t_EMEP;
    public float std_c_LI72;
    public int std_c_LI72_EMEP;
    public float std_h_LI72;
    public int std_h_LI72_EMEP;
    public float std_h_PICA;
    public int std_h_PICA_EMEP;
    public float std_CH4;
    public int std_CH4_EMEP;
    public float eta;
    public int eta_EMEP;
    public float theta;
    public int theta_EMEP;
    public float beta;
    public int beta_EMEP;
    public float Covs_u;
    public int Covs_u_EMEP;
    public float Covs_v;
    public int Covs_v_EMEP;
    public float Covs_Ts;
    public int Covs_Ts_EMEP;
    public float Covs_CO2_LI72;
    public int Covs_CO2_LI72_EMEP;
    public float Covs_H2O_LI72;
    public int Covs_H2O_LI72_EMEP;
    public float Covs_T_C_LI72;
    public int Covs_T_C_LI72_EMEP;
    public float Covs_P_C_LI72;
    public int Covs_P_C_LI72_EMEP;
    public float Covs_H2O_PICA;
    public int Covs_H2O_PICA_EMEP;
    public float Covs_CH4_PICA;
    public int Covs_CH4_PICA_EMEP;
    public float licor_t_av;
    public int licor_t_av_EMEP;
    public float licor_p_av;
    public int licor_p_av_EMEP;
    public float licor_t_std;
    public int licor_t_std_EMEP;
    public float licor_p_std;
    public int licor_p_std_EMEP;
    public float c_lag_LI72;
    public int c_lag_LI72_EMEP;
    public float h_lag_LI72;
    public int h_lag_LI72_EMEP;
    public float t_lag_LI72;
    public int t_lag_LI72_EMEP;
    public float p_lag_LI72;
    public int p_lag_LI72_EMEP;
    public float h_lag_PICA;
    public int h_lag_PICA_EMEP;
    public float CH4_lag;
    public int CH4_lag_EMEP;
    public int Nspikes_u;
    public int Nspikes_u_EMEP;
    public int Nspikes_v;
    public int Nspikes_v_EMEP;
    public int Nspikes_w;
    public int Nspikes_w_EMEP;
    public int Nspikes_Ts;
    public int Nspikes_Ts_EMEP;
    public int Nspikes_CO2_LI72;
    public int Nspikes_CO2_LI72_EMEP;
    public int Nspikes_H2O_LI72;
    public int Nspikes_H2O_LI72_EMEP;
    public int Nspikes_T_C_LI72;
    public int Nspikes_T_C_LI72_EMEP;
    public int Nspikes_P_C_LI72;
    public int Nspikes_P_C_LI72_EMEP;
    public int Nspikes_H2O_PICA;
    public int Nspikes_H2O_PICA_EMEP;
    public int Nspikes_CH4_PICA;
    public int Nspikes_CH4_PICA_EMEP;
    public float FI_u;
    public int FI_u_EMEP;
    public float FI_Ts;
    public int FI_Ts_EMEP;
    public float FI_CO2_LI72;
    public int FI_CO2_LI72_EMEP;
    public float FI_H2O_LI72;
    public int FI_H2O_LI72_EMEP;
    public float FI_CH4_PICA;
    public int FI_CH4_PICA_EMEP;
    public float FI_H2O_PICA;
    public int FI_H2O_PICA_EMEP;
    public float FST_u;
    public int FST_u_EMEP;
    public float FST_Ts;
    public int FST_Ts_EMEP;
    public float FST_CO2_LI72;
    public int FST_CO2_LI72_EMEP;
    public float FST_H2O_LI72;
    public int FST_H2O_LI72_EMEP;
    public float FST_CH4_PICA;
    public int FST_CH4_PICA_EMEP;
    public float FST_H2O_PICA;
    public int FST_H2O_PICA_EMEP;
    public float RFE_u;
    public int RFE_u_EMEP;
    public float RFE_Ts;
    public int RFE_Ts_EMEP;
    public float RFE_CO2_LI72;
    public int RFE_CO2_LI72_EMEP;
    public float RFE_H2O_LI72;
    public int RFE_H2O_LI72_EMEP;
    public float RFE_CH4_PICA;
    public int RFE_CH4_PICA_EMEP;
    public float RFE_H2O_PICA;
    public int RFE_H2O_PICA_EMEP;
    public float FA_u;
    public int FA_u_EMEP;
    public float FA_v;
    public int FA_v_EMEP;
    public float FA_Ts;
    public int FA_Ts_EMEP;
    public float FA_CO2_LI72;
    public int FA_CO2_LI72_EMEP;
    public float FA_H2O_LI72;
    public int FA_H2O_LI72_EMEP;
    public float FA_CH4_PICA;
    public int FA_CH4_PICA_EMEP;
    public float FA_H2O_PICA;
    public int FA_H2O_PICA_EMEP;
    public float covsvar_u;
    public int covsvar_u_EMEP;
    public float covsvar_v;
    public int covsvar_v_EMEP;
    public float covsvar_Ts;
    public int covsvar_Ts_EMEP;
    public float covsvar_CO2_LI72;
    public int covsvar_CO2_LI72_EMEP;
    public float covsvar_H2O_LI72;
    public int covsvar_H2O_LI72_EMEP;
    public float covsvar_CH4_PICA;
    public int covsvar_CH4_PICA_EMEP;
    public float covsvar_H2O_PICA;
    public int covsvar_H2O_PICA_EMEP;
    public float SKx_u;
    public int SKx_u_EMEP;
    public float SKx_v;
    public int SKx_v_EMEP;
    public float SKx_w;
    public int SKx_w_EMEP;
    public float SKx_Ts;
    public int SKx_Ts_EMEP;
    public float SKx_CO2_LI72;
    public int SKx_CO2_LI72_EMEP;
    public float SKx_H2O_LI72;
    public int SKx_H2O_LI72_EMEP;
    public float SKx_CH4_PICA;
    public int SKx_CH4_PICA_EMEP;
    public float SKx_H2O_PICA;
    public int SKx_H2O_PICA_EMEP;
    public float KUx_u;
    public int KUx_u_EMEP;
    public float KUx_v;
    public int KUx_v_EMEP;
    public float KUx_w;
    public int KUx_w_EMEP;
    public float KUx_Ts;
    public int KUx_Ts_EMEP;
    public float KUx_CO2_LI72;
    public int KUx_CO2_LI72_EMEP;
    public float KUx_H2O_LI72;
    public int KUx_H2O_LI72_EMEP;
    public float KUx_CH4_PICA;
    public int KUx_CH4_PICA_EMEP;
    public float KUx_H2O_PICA;
    public int KUx_H2O_PICA_EMEP;
    public int overall_qflag_u;
    public int overall_qflag_u_EMEP;
    public int overall_qflag_Ts;
    public int overall_qflag_Ts_EMEP;
    public int overall_qflag_CO2_LI72;
    public int overall_qflag_CO2_LI72_EMEP;
    public int overall_qflag_H2O_LI72;
    public int overall_qflag_H2O_LI72_EMEP;
    public int overall_qflag_CH4_PICA;
    public int overall_qflag_CH4_PICA_EMEP;
    public int overall_qflag_H2O_PICA;
    public int overall_qflag_H2O_PICA_EMEP;
    public int ITC_qflag_w;
    public int ITC_qflag_w_EMEP;
    public int ITC_qflag_u;
    public int ITC_qflag_u_EMEP;
    public int ITC_qflag_Ts;
    public int ITC_qflag_Ts_EMEP;
    public int ITC_qflag_CO2_LI72;
    public int ITC_qflag_CO2_LI72_EMEP;
    public int ITC_qflag_H2O_LI72;
    public int ITC_qflag_H2O_LI72_EMEP;
    public int ITC_qflag_CH4_PICA;
    public int ITC_qflag_CH4_PICA_EMEP;
    public int ITC_qflag_H2O_PICA;
    public int ITC_qflag_H2O_PICA_EMEP;
    public int FST_qflag_u;
    public int FST_qflag_u_EMEP;
    public int FST_qflag_Ts;
    public int FST_qflag_Ts_EMEP;
    public int FST_qflag_CO2_LI72;
    public int FST_qflag_CO2_LI72_EMEP;
    public int FST_qflag_H2O_LI72;
    public int FST_qflag_H2O_LI72_EMEP;
    public int FST_qflag_CH4_PICA;
    public int FST_qflag_CH4_PICA_EMEP;
    public int FST_qflag_H2O_PICA;
    public int FST_qflag_H2O_PICA_EMEP;
    public float Hm_u;
    public int Hm_u_EMEP;
    public float Hm_Ts;
    public int Hm_Ts_EMEP;
    public float Hm_CO2_LI72;
    public int Hm_CO2_LI72_EMEP;
    public float Hm_H2O_LI72;
    public int Hm_H2O_LI72_EMEP;
    public float Hm_CH4_PICA;
    public int Hm_CH4_PICA_EMEP;
    public float Hm_H2O_PICA;
    public int Hm_H2O_PICA_EMEP;
    public float Hv_u;
    public int Hv_u_EMEP;
    public float Hv_Ts;
    public int Hv_Ts_EMEP;
    public float Hv_CO2_LI72;
    public int Hv_CO2_LI72_EMEP;
    public float Hv_H2O_LI72;
    public int Hv_H2O_LI72_EMEP;
    public float Hv_CH4_PICA;
    public int Hv_CH4_PICA_EMEP;
    public float Hv_H2O_PICA;
    public int Hv_H2O_PICA_EMEP;
    public float fpr_x_peak;
    public int fpr_x_peak_EMEP;
    public float fpr_x_80;
    public int fpr_x_80_EMEP;

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(595);

        sb.append("{samptime=");
        sb.append(samptime);
        sb.append(", H=");
        sb.append(H);
        sb.append(", H_EMEP=");
        sb.append(H_EMEP);
        sb.append(", Qc_H=");
        sb.append(Qc_H);
        sb.append(", Qc_H_EMEP=");
        sb.append(Qc_H_EMEP);
        sb.append(", tau=");
        sb.append(tau);
        sb.append(", tau_EMEP=");
        sb.append(tau_EMEP);
        sb.append(", Qc_tau=");
        sb.append(Qc_tau);
        sb.append(", Qc_tau_EMEP=");
        sb.append(Qc_tau_EMEP);
        sb.append(", u_star=");
        sb.append(u_star);
        sb.append(", u_star_EMEP=");
        sb.append(u_star_EMEP);
        sb.append(", MO_length=");
        sb.append(MO_length);
        sb.append(", MO_length_EMEP=");
        sb.append(MO_length_EMEP);
        sb.append(", err_packet=");
        sb.append(err_packet);
        sb.append(", err_packet_EMEP=");
        sb.append(err_packet_EMEP);
        sb.append(", F_CO2_LI72=");
        sb.append(F_CO2_LI72);
        sb.append(", F_CO2_LI72_EMEP=");
        sb.append(F_CO2_LI72_EMEP);
        sb.append(", Qc_CO2_LI72=");
        sb.append(Qc_CO2_LI72);
        sb.append(", Qc_CO2_LI72_EMEP=");
        sb.append(Qc_CO2_LI72_EMEP);
        sb.append(", F_CH4_PICA=");
        sb.append(F_CH4_PICA);
        sb.append(", F_CH4_PICA_EMEP=");
        sb.append(F_CH4_PICA_EMEP);
        sb.append(", Qc_CH4_PICA=");
        sb.append(Qc_CH4_PICA);
        sb.append(", Qc_CH4_PICA_EMEP=");
        sb.append(Qc_CH4_PICA_EMEP);
        sb.append(", F_H2O_LI72=");
        sb.append(F_H2O_LI72);
        sb.append(", F_H2O_LI72_EMEP=");
        sb.append(F_H2O_LI72_EMEP);
        sb.append(", Qc_H2O_LI72=");
        sb.append(Qc_H2O_LI72);
        sb.append(", Qc_H2O_LI72_EMEP=");
        sb.append(Qc_H2O_LI72_EMEP);
        sb.append(", F_H2O_PICA=");
        sb.append(F_H2O_PICA);
        sb.append(", F_H2O_PICA_EMEP=");
        sb.append(F_H2O_PICA_EMEP);
        sb.append(", Qc_H2O_PICA=");
        sb.append(Qc_H2O_PICA);
        sb.append(", Qc_H2O_PICA_EMEP=");
        sb.append(Qc_H2O_PICA_EMEP);
        sb.append(", LE_LI72=");
        sb.append(LE_LI72);
        sb.append(", LE_LI72_EMEP=");
        sb.append(LE_LI72_EMEP);
        sb.append(", LE_PICA=");
        sb.append(LE_PICA);
        sb.append(", LE_PICA_EMEP=");
        sb.append(LE_PICA_EMEP);
        sb.append(", U=");
        sb.append(U);
        sb.append(", U_EMEP=");
        sb.append(U_EMEP);
        sb.append(", wind_dir=");
        sb.append(wind_dir);
        sb.append(", wind_dir_EMEP=");
        sb.append(wind_dir_EMEP);
        sb.append(", av_u=");
        sb.append(av_u);
        sb.append(", av_u_EMEP=");
        sb.append(av_u_EMEP);
        sb.append(", av_v=");
        sb.append(av_v);
        sb.append(", av_v_EMEP=");
        sb.append(av_v_EMEP);
        sb.append(", av_w=");
        sb.append(av_w);
        sb.append(", av_w_EMEP=");
        sb.append(av_w_EMEP);
        sb.append(", av_t=");
        sb.append(av_t);
        sb.append(", av_t_EMEP=");
        sb.append(av_t_EMEP);
        sb.append(", av_c_LI72=");
        sb.append(av_c_LI72);
        sb.append(", av_c_LI72_EMEP=");
        sb.append(av_c_LI72_EMEP);
        sb.append(", av_h_LI72=");
        sb.append(av_h_LI72);
        sb.append(", av_h_LI72_EMEP=");
        sb.append(av_h_LI72_EMEP);
        sb.append(", av_h_PICA=");
        sb.append(av_h_PICA);
        sb.append(", av_h_PICA_EMEP=");
        sb.append(av_h_PICA_EMEP);
        sb.append(", av_CH4=");
        sb.append(av_CH4);
        sb.append(", av_CH4_EMEP=");
        sb.append(av_CH4_EMEP);
        sb.append(", std_u=");
        sb.append(std_u);
        sb.append(", std_u_EMEP=");
        sb.append(std_u_EMEP);
        sb.append(", std_v=");
        sb.append(std_v);
        sb.append(", std_v_EMEP=");
        sb.append(std_v_EMEP);
        sb.append(", std_w=");
        sb.append(std_w);
        sb.append(", std_w_EMEP=");
        sb.append(std_w_EMEP);
        sb.append(", std_t=");
        sb.append(std_t);
        sb.append(", std_t_EMEP=");
        sb.append(std_t_EMEP);
        sb.append(", std_c_LI72=");
        sb.append(std_c_LI72);
        sb.append(", std_c_LI72_EMEP=");
        sb.append(std_c_LI72_EMEP);
        sb.append(", std_h_LI72=");
        sb.append(std_h_LI72);
        sb.append(", std_h_LI72_EMEP=");
        sb.append(std_h_LI72_EMEP);
        sb.append(", std_h_PICA=");
        sb.append(std_h_PICA);
        sb.append(", std_h_PICA_EMEP=");
        sb.append(std_h_PICA_EMEP);
        sb.append(", std_CH4=");
        sb.append(std_CH4);
        sb.append(", std_CH4_EMEP=");
        sb.append(std_CH4_EMEP);
        sb.append(", eta=");
        sb.append(eta);
        sb.append(", eta_EMEP=");
        sb.append(eta_EMEP);
        sb.append(", theta=");
        sb.append(theta);
        sb.append(", theta_EMEP=");
        sb.append(theta_EMEP);
        sb.append(", beta=");
        sb.append(beta);
        sb.append(", beta_EMEP=");
        sb.append(beta_EMEP);
        sb.append(", Covs_u=");
        sb.append(Covs_u);
        sb.append(", Covs_u_EMEP=");
        sb.append(Covs_u_EMEP);
        sb.append(", Covs_v=");
        sb.append(Covs_v);
        sb.append(", Covs_v_EMEP=");
        sb.append(Covs_v_EMEP);
        sb.append(", Covs_Ts=");
        sb.append(Covs_Ts);
        sb.append(", Covs_Ts_EMEP=");
        sb.append(Covs_Ts_EMEP);
        sb.append(", Covs_CO2_LI72=");
        sb.append(Covs_CO2_LI72);
        sb.append(", Covs_CO2_LI72_EMEP=");
        sb.append(Covs_CO2_LI72_EMEP);
        sb.append(", Covs_H2O_LI72=");
        sb.append(Covs_H2O_LI72);
        sb.append(", Covs_H2O_LI72_EMEP=");
        sb.append(Covs_H2O_LI72_EMEP);
        sb.append(", Covs_T_C_LI72=");
        sb.append(Covs_T_C_LI72);
        sb.append(", Covs_T_C_LI72_EMEP=");
        sb.append(Covs_T_C_LI72_EMEP);
        sb.append(", Covs_P_C_LI72=");
        sb.append(Covs_P_C_LI72);
        sb.append(", Covs_P_C_LI72_EMEP=");
        sb.append(Covs_P_C_LI72_EMEP);
        sb.append(", Covs_H2O_PICA=");
        sb.append(Covs_H2O_PICA);
        sb.append(", Covs_H2O_PICA_EMEP=");
        sb.append(Covs_H2O_PICA_EMEP);
        sb.append(", Covs_CH4_PICA=");
        sb.append(Covs_CH4_PICA);
        sb.append(", Covs_CH4_PICA_EMEP=");
        sb.append(Covs_CH4_PICA_EMEP);
        sb.append(", licor_t_av=");
        sb.append(licor_t_av);
        sb.append(", licor_t_av_EMEP=");
        sb.append(licor_t_av_EMEP);
        sb.append(", licor_p_av=");
        sb.append(licor_p_av);
        sb.append(", licor_p_av_EMEP=");
        sb.append(licor_p_av_EMEP);
        sb.append(", licor_t_std=");
        sb.append(licor_t_std);
        sb.append(", licor_t_std_EMEP=");
        sb.append(licor_t_std_EMEP);
        sb.append(", licor_p_std=");
        sb.append(licor_p_std);
        sb.append(", licor_p_std_EMEP=");
        sb.append(licor_p_std_EMEP);
        sb.append(", c_lag_LI72=");
        sb.append(c_lag_LI72);
        sb.append(", c_lag_LI72_EMEP=");
        sb.append(c_lag_LI72_EMEP);
        sb.append(", h_lag_LI72=");
        sb.append(h_lag_LI72);
        sb.append(", h_lag_LI72_EMEP=");
        sb.append(h_lag_LI72_EMEP);
        sb.append(", t_lag_LI72=");
        sb.append(t_lag_LI72);
        sb.append(", t_lag_LI72_EMEP=");
        sb.append(t_lag_LI72_EMEP);
        sb.append(", p_lag_LI72=");
        sb.append(p_lag_LI72);
        sb.append(", p_lag_LI72_EMEP=");
        sb.append(p_lag_LI72_EMEP);
        sb.append(", h_lag_PICA=");
        sb.append(h_lag_PICA);
        sb.append(", h_lag_PICA_EMEP=");
        sb.append(h_lag_PICA_EMEP);
        sb.append(", CH4_lag=");
        sb.append(CH4_lag);
        sb.append(", CH4_lag_EMEP=");
        sb.append(CH4_lag_EMEP);
        sb.append(", Nspikes_u=");
        sb.append(Nspikes_u);
        sb.append(", Nspikes_u_EMEP=");
        sb.append(Nspikes_u_EMEP);
        sb.append(", Nspikes_v=");
        sb.append(Nspikes_v);
        sb.append(", Nspikes_v_EMEP=");
        sb.append(Nspikes_v_EMEP);
        sb.append(", Nspikes_w=");
        sb.append(Nspikes_w);
        sb.append(", Nspikes_w_EMEP=");
        sb.append(Nspikes_w_EMEP);
        sb.append(", Nspikes_Ts=");
        sb.append(Nspikes_Ts);
        sb.append(", Nspikes_Ts_EMEP=");
        sb.append(Nspikes_Ts_EMEP);
        sb.append(", Nspikes_CO2_LI72=");
        sb.append(Nspikes_CO2_LI72);
        sb.append(", Nspikes_CO2_LI72_EMEP=");
        sb.append(Nspikes_CO2_LI72_EMEP);
        sb.append(", Nspikes_H2O_LI72=");
        sb.append(Nspikes_H2O_LI72);
        sb.append(", Nspikes_H2O_LI72_EMEP=");
        sb.append(Nspikes_H2O_LI72_EMEP);
        sb.append(", Nspikes_T_C_LI72=");
        sb.append(Nspikes_T_C_LI72);
        sb.append(", Nspikes_T_C_LI72_EMEP=");
        sb.append(Nspikes_T_C_LI72_EMEP);
        sb.append(", Nspikes_P_C_LI72=");
        sb.append(Nspikes_P_C_LI72);
        sb.append(", Nspikes_P_C_LI72_EMEP=");
        sb.append(Nspikes_P_C_LI72_EMEP);
        sb.append(", Nspikes_H2O_PICA=");
        sb.append(Nspikes_H2O_PICA);
        sb.append(", Nspikes_H2O_PICA_EMEP=");
        sb.append(Nspikes_H2O_PICA_EMEP);
        sb.append(", Nspikes_CH4_PICA=");
        sb.append(Nspikes_CH4_PICA);
        sb.append(", Nspikes_CH4_PICA_EMEP=");
        sb.append(Nspikes_CH4_PICA_EMEP);
        sb.append(", FI_u=");
        sb.append(FI_u);
        sb.append(", FI_u_EMEP=");
        sb.append(FI_u_EMEP);
        sb.append(", FI_Ts=");
        sb.append(FI_Ts);
        sb.append(", FI_Ts_EMEP=");
        sb.append(FI_Ts_EMEP);
        sb.append(", FI_CO2_LI72=");
        sb.append(FI_CO2_LI72);
        sb.append(", FI_CO2_LI72_EMEP=");
        sb.append(FI_CO2_LI72_EMEP);
        sb.append(", FI_H2O_LI72=");
        sb.append(FI_H2O_LI72);
        sb.append(", FI_H2O_LI72_EMEP=");
        sb.append(FI_H2O_LI72_EMEP);
        sb.append(", FI_CH4_PICA=");
        sb.append(FI_CH4_PICA);
        sb.append(", FI_CH4_PICA_EMEP=");
        sb.append(FI_CH4_PICA_EMEP);
        sb.append(", FI_H2O_PICA=");
        sb.append(FI_H2O_PICA);
        sb.append(", FI_H2O_PICA_EMEP=");
        sb.append(FI_H2O_PICA_EMEP);
        sb.append(", FST_u=");
        sb.append(FST_u);
        sb.append(", FST_u_EMEP=");
        sb.append(FST_u_EMEP);
        sb.append(", FST_Ts=");
        sb.append(FST_Ts);
        sb.append(", FST_Ts_EMEP=");
        sb.append(FST_Ts_EMEP);
        sb.append(", FST_CO2_LI72=");
        sb.append(FST_CO2_LI72);
        sb.append(", FST_CO2_LI72_EMEP=");
        sb.append(FST_CO2_LI72_EMEP);
        sb.append(", FST_H2O_LI72=");
        sb.append(FST_H2O_LI72);
        sb.append(", FST_H2O_LI72_EMEP=");
        sb.append(FST_H2O_LI72_EMEP);
        sb.append(", FST_CH4_PICA=");
        sb.append(FST_CH4_PICA);
        sb.append(", FST_CH4_PICA_EMEP=");
        sb.append(FST_CH4_PICA_EMEP);
        sb.append(", FST_H2O_PICA=");
        sb.append(FST_H2O_PICA);
        sb.append(", FST_H2O_PICA_EMEP=");
        sb.append(FST_H2O_PICA_EMEP);
        sb.append(", RFE_u=");
        sb.append(RFE_u);
        sb.append(", RFE_u_EMEP=");
        sb.append(RFE_u_EMEP);
        sb.append(", RFE_Ts=");
        sb.append(RFE_Ts);
        sb.append(", RFE_Ts_EMEP=");
        sb.append(RFE_Ts_EMEP);
        sb.append(", RFE_CO2_LI72=");
        sb.append(RFE_CO2_LI72);
        sb.append(", RFE_CO2_LI72_EMEP=");
        sb.append(RFE_CO2_LI72_EMEP);
        sb.append(", RFE_H2O_LI72=");
        sb.append(RFE_H2O_LI72);
        sb.append(", RFE_H2O_LI72_EMEP=");
        sb.append(RFE_H2O_LI72_EMEP);
        sb.append(", RFE_CH4_PICA=");
        sb.append(RFE_CH4_PICA);
        sb.append(", RFE_CH4_PICA_EMEP=");
        sb.append(RFE_CH4_PICA_EMEP);
        sb.append(", RFE_H2O_PICA=");
        sb.append(RFE_H2O_PICA);
        sb.append(", RFE_H2O_PICA_EMEP=");
        sb.append(RFE_H2O_PICA_EMEP);
        sb.append(", FA_u=");
        sb.append(FA_u);
        sb.append(", FA_u_EMEP=");
        sb.append(FA_u_EMEP);
        sb.append(", FA_v=");
        sb.append(FA_v);
        sb.append(", FA_v_EMEP=");
        sb.append(FA_v_EMEP);
        sb.append(", FA_Ts=");
        sb.append(FA_Ts);
        sb.append(", FA_Ts_EMEP=");
        sb.append(FA_Ts_EMEP);
        sb.append(", FA_CO2_LI72=");
        sb.append(FA_CO2_LI72);
        sb.append(", FA_CO2_LI72_EMEP=");
        sb.append(FA_CO2_LI72_EMEP);
        sb.append(", FA_H2O_LI72=");
        sb.append(FA_H2O_LI72);
        sb.append(", FA_H2O_LI72_EMEP=");
        sb.append(FA_H2O_LI72_EMEP);
        sb.append(", FA_CH4_PICA=");
        sb.append(FA_CH4_PICA);
        sb.append(", FA_CH4_PICA_EMEP=");
        sb.append(FA_CH4_PICA_EMEP);
        sb.append(", FA_H2O_PICA=");
        sb.append(FA_H2O_PICA);
        sb.append(", FA_H2O_PICA_EMEP=");
        sb.append(FA_H2O_PICA_EMEP);
        sb.append(", covsvar_u=");
        sb.append(covsvar_u);
        sb.append(", covsvar_u_EMEP=");
        sb.append(covsvar_u_EMEP);
        sb.append(", covsvar_v=");
        sb.append(covsvar_v);
        sb.append(", covsvar_v_EMEP=");
        sb.append(covsvar_v_EMEP);
        sb.append(", covsvar_Ts=");
        sb.append(covsvar_Ts);
        sb.append(", covsvar_Ts_EMEP=");
        sb.append(covsvar_Ts_EMEP);
        sb.append(", covsvar_CO2_LI72=");
        sb.append(covsvar_CO2_LI72);
        sb.append(", covsvar_CO2_LI72_EMEP=");
        sb.append(covsvar_CO2_LI72_EMEP);
        sb.append(", covsvar_H2O_LI72=");
        sb.append(covsvar_H2O_LI72);
        sb.append(", covsvar_H2O_LI72_EMEP=");
        sb.append(covsvar_H2O_LI72_EMEP);
        sb.append(", covsvar_CH4_PICA=");
        sb.append(covsvar_CH4_PICA);
        sb.append(", covsvar_CH4_PICA_EMEP=");
        sb.append(covsvar_CH4_PICA_EMEP);
        sb.append(", covsvar_H2O_PICA=");
        sb.append(covsvar_H2O_PICA);
        sb.append(", covsvar_H2O_PICA_EMEP=");
        sb.append(covsvar_H2O_PICA_EMEP);
        sb.append(", SKx_u=");
        sb.append(SKx_u);
        sb.append(", SKx_u_EMEP=");
        sb.append(SKx_u_EMEP);
        sb.append(", SKx_v=");
        sb.append(SKx_v);
        sb.append(", SKx_v_EMEP=");
        sb.append(SKx_v_EMEP);
        sb.append(", SKx_w=");
        sb.append(SKx_w);
        sb.append(", SKx_w_EMEP=");
        sb.append(SKx_w_EMEP);
        sb.append(", SKx_Ts=");
        sb.append(SKx_Ts);
        sb.append(", SKx_Ts_EMEP=");
        sb.append(SKx_Ts_EMEP);
        sb.append(", SKx_CO2_LI72=");
        sb.append(SKx_CO2_LI72);
        sb.append(", SKx_CO2_LI72_EMEP=");
        sb.append(SKx_CO2_LI72_EMEP);
        sb.append(", SKx_H2O_LI72=");
        sb.append(SKx_H2O_LI72);
        sb.append(", SKx_H2O_LI72_EMEP=");
        sb.append(SKx_H2O_LI72_EMEP);
        sb.append(", SKx_CH4_PICA=");
        sb.append(SKx_CH4_PICA);
        sb.append(", SKx_CH4_PICA_EMEP=");
        sb.append(SKx_CH4_PICA_EMEP);
        sb.append(", SKx_H2O_PICA=");
        sb.append(SKx_H2O_PICA);
        sb.append(", SKx_H2O_PICA_EMEP=");
        sb.append(SKx_H2O_PICA_EMEP);
        sb.append(", KUx_u=");
        sb.append(KUx_u);
        sb.append(", KUx_u_EMEP=");
        sb.append(KUx_u_EMEP);
        sb.append(", KUx_v=");
        sb.append(KUx_v);
        sb.append(", KUx_v_EMEP=");
        sb.append(KUx_v_EMEP);
        sb.append(", KUx_w=");
        sb.append(KUx_w);
        sb.append(", KUx_w_EMEP=");
        sb.append(KUx_w_EMEP);
        sb.append(", KUx_Ts=");
        sb.append(KUx_Ts);
        sb.append(", KUx_Ts_EMEP=");
        sb.append(KUx_Ts_EMEP);
        sb.append(", KUx_CO2_LI72=");
        sb.append(KUx_CO2_LI72);
        sb.append(", KUx_CO2_LI72_EMEP=");
        sb.append(KUx_CO2_LI72_EMEP);
        sb.append(", KUx_H2O_LI72=");
        sb.append(KUx_H2O_LI72);
        sb.append(", KUx_H2O_LI72_EMEP=");
        sb.append(KUx_H2O_LI72_EMEP);
        sb.append(", KUx_CH4_PICA=");
        sb.append(KUx_CH4_PICA);
        sb.append(", KUx_CH4_PICA_EMEP=");
        sb.append(KUx_CH4_PICA_EMEP);
        sb.append(", KUx_H2O_PICA=");
        sb.append(KUx_H2O_PICA);
        sb.append(", KUx_H2O_PICA_EMEP=");
        sb.append(KUx_H2O_PICA_EMEP);
        sb.append(", overall_qflag_u=");
        sb.append(overall_qflag_u);
        sb.append(", overall_qflag_u_EMEP=");
        sb.append(overall_qflag_u_EMEP);
        sb.append(", overall_qflag_Ts=");
        sb.append(overall_qflag_Ts);
        sb.append(", overall_qflag_Ts_EMEP=");
        sb.append(overall_qflag_Ts_EMEP);
        sb.append(", overall_qflag_CO2_LI72=");
        sb.append(overall_qflag_CO2_LI72);
        sb.append(", overall_qflag_CO2_LI72_EMEP=");
        sb.append(overall_qflag_CO2_LI72_EMEP);
        sb.append(", overall_qflag_H2O_LI72=");
        sb.append(overall_qflag_H2O_LI72);
        sb.append(", overall_qflag_H2O_LI72_EMEP=");
        sb.append(overall_qflag_H2O_LI72_EMEP);
        sb.append(", overall_qflag_CH4_PICA=");
        sb.append(overall_qflag_CH4_PICA);
        sb.append(", overall_qflag_CH4_PICA_EMEP=");
        sb.append(overall_qflag_CH4_PICA_EMEP);
        sb.append(", overall_qflag_H2O_PICA=");
        sb.append(overall_qflag_H2O_PICA);
        sb.append(", overall_qflag_H2O_PICA_EMEP=");
        sb.append(overall_qflag_H2O_PICA_EMEP);
        sb.append(", ITC_qflag_w=");
        sb.append(ITC_qflag_w);
        sb.append(", ITC_qflag_w_EMEP=");
        sb.append(ITC_qflag_w_EMEP);
        sb.append(", ITC_qflag_u=");
        sb.append(ITC_qflag_u);
        sb.append(", ITC_qflag_u_EMEP=");
        sb.append(ITC_qflag_u_EMEP);
        sb.append(", ITC_qflag_Ts=");
        sb.append(ITC_qflag_Ts);
        sb.append(", ITC_qflag_Ts_EMEP=");
        sb.append(ITC_qflag_Ts_EMEP);
        sb.append(", ITC_qflag_CO2_LI72=");
        sb.append(ITC_qflag_CO2_LI72);
        sb.append(", ITC_qflag_CO2_LI72_EMEP=");
        sb.append(ITC_qflag_CO2_LI72_EMEP);
        sb.append(", ITC_qflag_H2O_LI72=");
        sb.append(ITC_qflag_H2O_LI72);
        sb.append(", ITC_qflag_H2O_LI72_EMEP=");
        sb.append(ITC_qflag_H2O_LI72_EMEP);
        sb.append(", ITC_qflag_CH4_PICA=");
        sb.append(ITC_qflag_CH4_PICA);
        sb.append(", ITC_qflag_CH4_PICA_EMEP=");
        sb.append(ITC_qflag_CH4_PICA_EMEP);
        sb.append(", ITC_qflag_H2O_PICA=");
        sb.append(ITC_qflag_H2O_PICA);
        sb.append(", ITC_qflag_H2O_PICA_EMEP=");
        sb.append(ITC_qflag_H2O_PICA_EMEP);
        sb.append(", FST_qflag_u=");
        sb.append(FST_qflag_u);
        sb.append(", FST_qflag_u_EMEP=");
        sb.append(FST_qflag_u_EMEP);
        sb.append(", FST_qflag_Ts=");
        sb.append(FST_qflag_Ts);
        sb.append(", FST_qflag_Ts_EMEP=");
        sb.append(FST_qflag_Ts_EMEP);
        sb.append(", FST_qflag_CO2_LI72=");
        sb.append(FST_qflag_CO2_LI72);
        sb.append(", FST_qflag_CO2_LI72_EMEP=");
        sb.append(FST_qflag_CO2_LI72_EMEP);
        sb.append(", FST_qflag_H2O_LI72=");
        sb.append(FST_qflag_H2O_LI72);
        sb.append(", FST_qflag_H2O_LI72_EMEP=");
        sb.append(FST_qflag_H2O_LI72_EMEP);
        sb.append(", FST_qflag_CH4_PICA=");
        sb.append(FST_qflag_CH4_PICA);
        sb.append(", FST_qflag_CH4_PICA_EMEP=");
        sb.append(FST_qflag_CH4_PICA_EMEP);
        sb.append(", FST_qflag_H2O_PICA=");
        sb.append(FST_qflag_H2O_PICA);
        sb.append(", FST_qflag_H2O_PICA_EMEP=");
        sb.append(FST_qflag_H2O_PICA_EMEP);
        sb.append(", Hm_u=");
        sb.append(Hm_u);
        sb.append(", Hm_u_EMEP=");
        sb.append(Hm_u_EMEP);
        sb.append(", Hm_Ts=");
        sb.append(Hm_Ts);
        sb.append(", Hm_Ts_EMEP=");
        sb.append(Hm_Ts_EMEP);
        sb.append(", Hm_CO2_LI72=");
        sb.append(Hm_CO2_LI72);
        sb.append(", Hm_CO2_LI72_EMEP=");
        sb.append(Hm_CO2_LI72_EMEP);
        sb.append(", Hm_H2O_LI72=");
        sb.append(Hm_H2O_LI72);
        sb.append(", Hm_H2O_LI72_EMEP=");
        sb.append(Hm_H2O_LI72_EMEP);
        sb.append(", Hm_CH4_PICA=");
        sb.append(Hm_CH4_PICA);
        sb.append(", Hm_CH4_PICA_EMEP=");
        sb.append(Hm_CH4_PICA_EMEP);
        sb.append(", Hm_H2O_PICA=");
        sb.append(Hm_H2O_PICA);
        sb.append(", Hm_H2O_PICA_EMEP=");
        sb.append(Hm_H2O_PICA_EMEP);
        sb.append(", Hv_u=");
        sb.append(Hv_u);
        sb.append(", Hv_u_EMEP=");
        sb.append(Hv_u_EMEP);
        sb.append(", Hv_Ts=");
        sb.append(Hv_Ts);
        sb.append(", Hv_Ts_EMEP=");
        sb.append(Hv_Ts_EMEP);
        sb.append(", Hv_CO2_LI72=");
        sb.append(Hv_CO2_LI72);
        sb.append(", Hv_CO2_LI72_EMEP=");
        sb.append(Hv_CO2_LI72_EMEP);
        sb.append(", Hv_H2O_LI72=");
        sb.append(Hv_H2O_LI72);
        sb.append(", Hv_H2O_LI72_EMEP=");
        sb.append(Hv_H2O_LI72_EMEP);
        sb.append(", Hv_CH4_PICA=");
        sb.append(Hv_CH4_PICA);
        sb.append(", Hv_CH4_PICA_EMEP=");
        sb.append(Hv_CH4_PICA_EMEP);
        sb.append(", Hv_H2O_PICA=");
        sb.append(Hv_H2O_PICA);
        sb.append(", Hv_H2O_PICA_EMEP=");
        sb.append(Hv_H2O_PICA_EMEP);
        sb.append(", fpr_x_peak=");
        sb.append(fpr_x_peak);
        sb.append(", fpr_x_peak_EMEP=");
        sb.append(fpr_x_peak_EMEP);
        sb.append(", fpr_x_80=");
        sb.append(fpr_x_80);
        sb.append(", fpr_x_80_EMEP=");
        sb.append(fpr_x_80_EMEP);
        sb.append("}");

        return sb.toString();
    }

    @Override
    public kvjEddy toEntityModel() {
        kvjEddyImpl kvjEddyImpl = new kvjEddyImpl();

        if (samptime == Long.MIN_VALUE) {
            kvjEddyImpl.setSamptime(null);
        } else {
            kvjEddyImpl.setSamptime(new Date(samptime));
        }

        kvjEddyImpl.setH(H);
        kvjEddyImpl.setH_EMEP(H_EMEP);
        kvjEddyImpl.setQc_H(Qc_H);
        kvjEddyImpl.setQc_H_EMEP(Qc_H_EMEP);
        kvjEddyImpl.setTau(tau);
        kvjEddyImpl.setTau_EMEP(tau_EMEP);
        kvjEddyImpl.setQc_tau(Qc_tau);
        kvjEddyImpl.setQc_tau_EMEP(Qc_tau_EMEP);
        kvjEddyImpl.setU_star(u_star);
        kvjEddyImpl.setU_star_EMEP(u_star_EMEP);
        kvjEddyImpl.setMO_length(MO_length);
        kvjEddyImpl.setMO_length_EMEP(MO_length_EMEP);
        kvjEddyImpl.setErr_packet(err_packet);
        kvjEddyImpl.setErr_packet_EMEP(err_packet_EMEP);
        kvjEddyImpl.setF_CO2_LI72(F_CO2_LI72);
        kvjEddyImpl.setF_CO2_LI72_EMEP(F_CO2_LI72_EMEP);
        kvjEddyImpl.setQc_CO2_LI72(Qc_CO2_LI72);
        kvjEddyImpl.setQc_CO2_LI72_EMEP(Qc_CO2_LI72_EMEP);
        kvjEddyImpl.setF_CH4_PICA(F_CH4_PICA);
        kvjEddyImpl.setF_CH4_PICA_EMEP(F_CH4_PICA_EMEP);
        kvjEddyImpl.setQc_CH4_PICA(Qc_CH4_PICA);
        kvjEddyImpl.setQc_CH4_PICA_EMEP(Qc_CH4_PICA_EMEP);
        kvjEddyImpl.setF_H2O_LI72(F_H2O_LI72);
        kvjEddyImpl.setF_H2O_LI72_EMEP(F_H2O_LI72_EMEP);
        kvjEddyImpl.setQc_H2O_LI72(Qc_H2O_LI72);
        kvjEddyImpl.setQc_H2O_LI72_EMEP(Qc_H2O_LI72_EMEP);
        kvjEddyImpl.setF_H2O_PICA(F_H2O_PICA);
        kvjEddyImpl.setF_H2O_PICA_EMEP(F_H2O_PICA_EMEP);
        kvjEddyImpl.setQc_H2O_PICA(Qc_H2O_PICA);
        kvjEddyImpl.setQc_H2O_PICA_EMEP(Qc_H2O_PICA_EMEP);
        kvjEddyImpl.setLE_LI72(LE_LI72);
        kvjEddyImpl.setLE_LI72_EMEP(LE_LI72_EMEP);
        kvjEddyImpl.setLE_PICA(LE_PICA);
        kvjEddyImpl.setLE_PICA_EMEP(LE_PICA_EMEP);
        kvjEddyImpl.setU(U);
        kvjEddyImpl.setU_EMEP(U_EMEP);
        kvjEddyImpl.setWind_dir(wind_dir);
        kvjEddyImpl.setWind_dir_EMEP(wind_dir_EMEP);
        kvjEddyImpl.setAv_u(av_u);
        kvjEddyImpl.setAv_u_EMEP(av_u_EMEP);
        kvjEddyImpl.setAv_v(av_v);
        kvjEddyImpl.setAv_v_EMEP(av_v_EMEP);
        kvjEddyImpl.setAv_w(av_w);
        kvjEddyImpl.setAv_w_EMEP(av_w_EMEP);
        kvjEddyImpl.setAv_t(av_t);
        kvjEddyImpl.setAv_t_EMEP(av_t_EMEP);
        kvjEddyImpl.setAv_c_LI72(av_c_LI72);
        kvjEddyImpl.setAv_c_LI72_EMEP(av_c_LI72_EMEP);
        kvjEddyImpl.setAv_h_LI72(av_h_LI72);
        kvjEddyImpl.setAv_h_LI72_EMEP(av_h_LI72_EMEP);
        kvjEddyImpl.setAv_h_PICA(av_h_PICA);
        kvjEddyImpl.setAv_h_PICA_EMEP(av_h_PICA_EMEP);
        kvjEddyImpl.setAv_CH4(av_CH4);
        kvjEddyImpl.setAv_CH4_EMEP(av_CH4_EMEP);
        kvjEddyImpl.setStd_u(std_u);
        kvjEddyImpl.setStd_u_EMEP(std_u_EMEP);
        kvjEddyImpl.setStd_v(std_v);
        kvjEddyImpl.setStd_v_EMEP(std_v_EMEP);
        kvjEddyImpl.setStd_w(std_w);
        kvjEddyImpl.setStd_w_EMEP(std_w_EMEP);
        kvjEddyImpl.setStd_t(std_t);
        kvjEddyImpl.setStd_t_EMEP(std_t_EMEP);
        kvjEddyImpl.setStd_c_LI72(std_c_LI72);
        kvjEddyImpl.setStd_c_LI72_EMEP(std_c_LI72_EMEP);
        kvjEddyImpl.setStd_h_LI72(std_h_LI72);
        kvjEddyImpl.setStd_h_LI72_EMEP(std_h_LI72_EMEP);
        kvjEddyImpl.setStd_h_PICA(std_h_PICA);
        kvjEddyImpl.setStd_h_PICA_EMEP(std_h_PICA_EMEP);
        kvjEddyImpl.setStd_CH4(std_CH4);
        kvjEddyImpl.setStd_CH4_EMEP(std_CH4_EMEP);
        kvjEddyImpl.setEta(eta);
        kvjEddyImpl.setEta_EMEP(eta_EMEP);
        kvjEddyImpl.setTheta(theta);
        kvjEddyImpl.setTheta_EMEP(theta_EMEP);
        kvjEddyImpl.setBeta(beta);
        kvjEddyImpl.setBeta_EMEP(beta_EMEP);
        kvjEddyImpl.setCovs_u(Covs_u);
        kvjEddyImpl.setCovs_u_EMEP(Covs_u_EMEP);
        kvjEddyImpl.setCovs_v(Covs_v);
        kvjEddyImpl.setCovs_v_EMEP(Covs_v_EMEP);
        kvjEddyImpl.setCovs_Ts(Covs_Ts);
        kvjEddyImpl.setCovs_Ts_EMEP(Covs_Ts_EMEP);
        kvjEddyImpl.setCovs_CO2_LI72(Covs_CO2_LI72);
        kvjEddyImpl.setCovs_CO2_LI72_EMEP(Covs_CO2_LI72_EMEP);
        kvjEddyImpl.setCovs_H2O_LI72(Covs_H2O_LI72);
        kvjEddyImpl.setCovs_H2O_LI72_EMEP(Covs_H2O_LI72_EMEP);
        kvjEddyImpl.setCovs_T_C_LI72(Covs_T_C_LI72);
        kvjEddyImpl.setCovs_T_C_LI72_EMEP(Covs_T_C_LI72_EMEP);
        kvjEddyImpl.setCovs_P_C_LI72(Covs_P_C_LI72);
        kvjEddyImpl.setCovs_P_C_LI72_EMEP(Covs_P_C_LI72_EMEP);
        kvjEddyImpl.setCovs_H2O_PICA(Covs_H2O_PICA);
        kvjEddyImpl.setCovs_H2O_PICA_EMEP(Covs_H2O_PICA_EMEP);
        kvjEddyImpl.setCovs_CH4_PICA(Covs_CH4_PICA);
        kvjEddyImpl.setCovs_CH4_PICA_EMEP(Covs_CH4_PICA_EMEP);
        kvjEddyImpl.setLicor_t_av(licor_t_av);
        kvjEddyImpl.setLicor_t_av_EMEP(licor_t_av_EMEP);
        kvjEddyImpl.setLicor_p_av(licor_p_av);
        kvjEddyImpl.setLicor_p_av_EMEP(licor_p_av_EMEP);
        kvjEddyImpl.setLicor_t_std(licor_t_std);
        kvjEddyImpl.setLicor_t_std_EMEP(licor_t_std_EMEP);
        kvjEddyImpl.setLicor_p_std(licor_p_std);
        kvjEddyImpl.setLicor_p_std_EMEP(licor_p_std_EMEP);
        kvjEddyImpl.setC_lag_LI72(c_lag_LI72);
        kvjEddyImpl.setC_lag_LI72_EMEP(c_lag_LI72_EMEP);
        kvjEddyImpl.setH_lag_LI72(h_lag_LI72);
        kvjEddyImpl.setH_lag_LI72_EMEP(h_lag_LI72_EMEP);
        kvjEddyImpl.setT_lag_LI72(t_lag_LI72);
        kvjEddyImpl.setT_lag_LI72_EMEP(t_lag_LI72_EMEP);
        kvjEddyImpl.setP_lag_LI72(p_lag_LI72);
        kvjEddyImpl.setP_lag_LI72_EMEP(p_lag_LI72_EMEP);
        kvjEddyImpl.setH_lag_PICA(h_lag_PICA);
        kvjEddyImpl.setH_lag_PICA_EMEP(h_lag_PICA_EMEP);
        kvjEddyImpl.setCH4_lag(CH4_lag);
        kvjEddyImpl.setCH4_lag_EMEP(CH4_lag_EMEP);
        kvjEddyImpl.setNspikes_u(Nspikes_u);
        kvjEddyImpl.setNspikes_u_EMEP(Nspikes_u_EMEP);
        kvjEddyImpl.setNspikes_v(Nspikes_v);
        kvjEddyImpl.setNspikes_v_EMEP(Nspikes_v_EMEP);
        kvjEddyImpl.setNspikes_w(Nspikes_w);
        kvjEddyImpl.setNspikes_w_EMEP(Nspikes_w_EMEP);
        kvjEddyImpl.setNspikes_Ts(Nspikes_Ts);
        kvjEddyImpl.setNspikes_Ts_EMEP(Nspikes_Ts_EMEP);
        kvjEddyImpl.setNspikes_CO2_LI72(Nspikes_CO2_LI72);
        kvjEddyImpl.setNspikes_CO2_LI72_EMEP(Nspikes_CO2_LI72_EMEP);
        kvjEddyImpl.setNspikes_H2O_LI72(Nspikes_H2O_LI72);
        kvjEddyImpl.setNspikes_H2O_LI72_EMEP(Nspikes_H2O_LI72_EMEP);
        kvjEddyImpl.setNspikes_T_C_LI72(Nspikes_T_C_LI72);
        kvjEddyImpl.setNspikes_T_C_LI72_EMEP(Nspikes_T_C_LI72_EMEP);
        kvjEddyImpl.setNspikes_P_C_LI72(Nspikes_P_C_LI72);
        kvjEddyImpl.setNspikes_P_C_LI72_EMEP(Nspikes_P_C_LI72_EMEP);
        kvjEddyImpl.setNspikes_H2O_PICA(Nspikes_H2O_PICA);
        kvjEddyImpl.setNspikes_H2O_PICA_EMEP(Nspikes_H2O_PICA_EMEP);
        kvjEddyImpl.setNspikes_CH4_PICA(Nspikes_CH4_PICA);
        kvjEddyImpl.setNspikes_CH4_PICA_EMEP(Nspikes_CH4_PICA_EMEP);
        kvjEddyImpl.setFI_u(FI_u);
        kvjEddyImpl.setFI_u_EMEP(FI_u_EMEP);
        kvjEddyImpl.setFI_Ts(FI_Ts);
        kvjEddyImpl.setFI_Ts_EMEP(FI_Ts_EMEP);
        kvjEddyImpl.setFI_CO2_LI72(FI_CO2_LI72);
        kvjEddyImpl.setFI_CO2_LI72_EMEP(FI_CO2_LI72_EMEP);
        kvjEddyImpl.setFI_H2O_LI72(FI_H2O_LI72);
        kvjEddyImpl.setFI_H2O_LI72_EMEP(FI_H2O_LI72_EMEP);
        kvjEddyImpl.setFI_CH4_PICA(FI_CH4_PICA);
        kvjEddyImpl.setFI_CH4_PICA_EMEP(FI_CH4_PICA_EMEP);
        kvjEddyImpl.setFI_H2O_PICA(FI_H2O_PICA);
        kvjEddyImpl.setFI_H2O_PICA_EMEP(FI_H2O_PICA_EMEP);
        kvjEddyImpl.setFST_u(FST_u);
        kvjEddyImpl.setFST_u_EMEP(FST_u_EMEP);
        kvjEddyImpl.setFST_Ts(FST_Ts);
        kvjEddyImpl.setFST_Ts_EMEP(FST_Ts_EMEP);
        kvjEddyImpl.setFST_CO2_LI72(FST_CO2_LI72);
        kvjEddyImpl.setFST_CO2_LI72_EMEP(FST_CO2_LI72_EMEP);
        kvjEddyImpl.setFST_H2O_LI72(FST_H2O_LI72);
        kvjEddyImpl.setFST_H2O_LI72_EMEP(FST_H2O_LI72_EMEP);
        kvjEddyImpl.setFST_CH4_PICA(FST_CH4_PICA);
        kvjEddyImpl.setFST_CH4_PICA_EMEP(FST_CH4_PICA_EMEP);
        kvjEddyImpl.setFST_H2O_PICA(FST_H2O_PICA);
        kvjEddyImpl.setFST_H2O_PICA_EMEP(FST_H2O_PICA_EMEP);
        kvjEddyImpl.setRFE_u(RFE_u);
        kvjEddyImpl.setRFE_u_EMEP(RFE_u_EMEP);
        kvjEddyImpl.setRFE_Ts(RFE_Ts);
        kvjEddyImpl.setRFE_Ts_EMEP(RFE_Ts_EMEP);
        kvjEddyImpl.setRFE_CO2_LI72(RFE_CO2_LI72);
        kvjEddyImpl.setRFE_CO2_LI72_EMEP(RFE_CO2_LI72_EMEP);
        kvjEddyImpl.setRFE_H2O_LI72(RFE_H2O_LI72);
        kvjEddyImpl.setRFE_H2O_LI72_EMEP(RFE_H2O_LI72_EMEP);
        kvjEddyImpl.setRFE_CH4_PICA(RFE_CH4_PICA);
        kvjEddyImpl.setRFE_CH4_PICA_EMEP(RFE_CH4_PICA_EMEP);
        kvjEddyImpl.setRFE_H2O_PICA(RFE_H2O_PICA);
        kvjEddyImpl.setRFE_H2O_PICA_EMEP(RFE_H2O_PICA_EMEP);
        kvjEddyImpl.setFA_u(FA_u);
        kvjEddyImpl.setFA_u_EMEP(FA_u_EMEP);
        kvjEddyImpl.setFA_v(FA_v);
        kvjEddyImpl.setFA_v_EMEP(FA_v_EMEP);
        kvjEddyImpl.setFA_Ts(FA_Ts);
        kvjEddyImpl.setFA_Ts_EMEP(FA_Ts_EMEP);
        kvjEddyImpl.setFA_CO2_LI72(FA_CO2_LI72);
        kvjEddyImpl.setFA_CO2_LI72_EMEP(FA_CO2_LI72_EMEP);
        kvjEddyImpl.setFA_H2O_LI72(FA_H2O_LI72);
        kvjEddyImpl.setFA_H2O_LI72_EMEP(FA_H2O_LI72_EMEP);
        kvjEddyImpl.setFA_CH4_PICA(FA_CH4_PICA);
        kvjEddyImpl.setFA_CH4_PICA_EMEP(FA_CH4_PICA_EMEP);
        kvjEddyImpl.setFA_H2O_PICA(FA_H2O_PICA);
        kvjEddyImpl.setFA_H2O_PICA_EMEP(FA_H2O_PICA_EMEP);
        kvjEddyImpl.setCovsvar_u(covsvar_u);
        kvjEddyImpl.setCovsvar_u_EMEP(covsvar_u_EMEP);
        kvjEddyImpl.setCovsvar_v(covsvar_v);
        kvjEddyImpl.setCovsvar_v_EMEP(covsvar_v_EMEP);
        kvjEddyImpl.setCovsvar_Ts(covsvar_Ts);
        kvjEddyImpl.setCovsvar_Ts_EMEP(covsvar_Ts_EMEP);
        kvjEddyImpl.setCovsvar_CO2_LI72(covsvar_CO2_LI72);
        kvjEddyImpl.setCovsvar_CO2_LI72_EMEP(covsvar_CO2_LI72_EMEP);
        kvjEddyImpl.setCovsvar_H2O_LI72(covsvar_H2O_LI72);
        kvjEddyImpl.setCovsvar_H2O_LI72_EMEP(covsvar_H2O_LI72_EMEP);
        kvjEddyImpl.setCovsvar_CH4_PICA(covsvar_CH4_PICA);
        kvjEddyImpl.setCovsvar_CH4_PICA_EMEP(covsvar_CH4_PICA_EMEP);
        kvjEddyImpl.setCovsvar_H2O_PICA(covsvar_H2O_PICA);
        kvjEddyImpl.setCovsvar_H2O_PICA_EMEP(covsvar_H2O_PICA_EMEP);
        kvjEddyImpl.setSKx_u(SKx_u);
        kvjEddyImpl.setSKx_u_EMEP(SKx_u_EMEP);
        kvjEddyImpl.setSKx_v(SKx_v);
        kvjEddyImpl.setSKx_v_EMEP(SKx_v_EMEP);
        kvjEddyImpl.setSKx_w(SKx_w);
        kvjEddyImpl.setSKx_w_EMEP(SKx_w_EMEP);
        kvjEddyImpl.setSKx_Ts(SKx_Ts);
        kvjEddyImpl.setSKx_Ts_EMEP(SKx_Ts_EMEP);
        kvjEddyImpl.setSKx_CO2_LI72(SKx_CO2_LI72);
        kvjEddyImpl.setSKx_CO2_LI72_EMEP(SKx_CO2_LI72_EMEP);
        kvjEddyImpl.setSKx_H2O_LI72(SKx_H2O_LI72);
        kvjEddyImpl.setSKx_H2O_LI72_EMEP(SKx_H2O_LI72_EMEP);
        kvjEddyImpl.setSKx_CH4_PICA(SKx_CH4_PICA);
        kvjEddyImpl.setSKx_CH4_PICA_EMEP(SKx_CH4_PICA_EMEP);
        kvjEddyImpl.setSKx_H2O_PICA(SKx_H2O_PICA);
        kvjEddyImpl.setSKx_H2O_PICA_EMEP(SKx_H2O_PICA_EMEP);
        kvjEddyImpl.setKUx_u(KUx_u);
        kvjEddyImpl.setKUx_u_EMEP(KUx_u_EMEP);
        kvjEddyImpl.setKUx_v(KUx_v);
        kvjEddyImpl.setKUx_v_EMEP(KUx_v_EMEP);
        kvjEddyImpl.setKUx_w(KUx_w);
        kvjEddyImpl.setKUx_w_EMEP(KUx_w_EMEP);
        kvjEddyImpl.setKUx_Ts(KUx_Ts);
        kvjEddyImpl.setKUx_Ts_EMEP(KUx_Ts_EMEP);
        kvjEddyImpl.setKUx_CO2_LI72(KUx_CO2_LI72);
        kvjEddyImpl.setKUx_CO2_LI72_EMEP(KUx_CO2_LI72_EMEP);
        kvjEddyImpl.setKUx_H2O_LI72(KUx_H2O_LI72);
        kvjEddyImpl.setKUx_H2O_LI72_EMEP(KUx_H2O_LI72_EMEP);
        kvjEddyImpl.setKUx_CH4_PICA(KUx_CH4_PICA);
        kvjEddyImpl.setKUx_CH4_PICA_EMEP(KUx_CH4_PICA_EMEP);
        kvjEddyImpl.setKUx_H2O_PICA(KUx_H2O_PICA);
        kvjEddyImpl.setKUx_H2O_PICA_EMEP(KUx_H2O_PICA_EMEP);
        kvjEddyImpl.setOverall_qflag_u(overall_qflag_u);
        kvjEddyImpl.setOverall_qflag_u_EMEP(overall_qflag_u_EMEP);
        kvjEddyImpl.setOverall_qflag_Ts(overall_qflag_Ts);
        kvjEddyImpl.setOverall_qflag_Ts_EMEP(overall_qflag_Ts_EMEP);
        kvjEddyImpl.setOverall_qflag_CO2_LI72(overall_qflag_CO2_LI72);
        kvjEddyImpl.setOverall_qflag_CO2_LI72_EMEP(overall_qflag_CO2_LI72_EMEP);
        kvjEddyImpl.setOverall_qflag_H2O_LI72(overall_qflag_H2O_LI72);
        kvjEddyImpl.setOverall_qflag_H2O_LI72_EMEP(overall_qflag_H2O_LI72_EMEP);
        kvjEddyImpl.setOverall_qflag_CH4_PICA(overall_qflag_CH4_PICA);
        kvjEddyImpl.setOverall_qflag_CH4_PICA_EMEP(overall_qflag_CH4_PICA_EMEP);
        kvjEddyImpl.setOverall_qflag_H2O_PICA(overall_qflag_H2O_PICA);
        kvjEddyImpl.setOverall_qflag_H2O_PICA_EMEP(overall_qflag_H2O_PICA_EMEP);
        kvjEddyImpl.setITC_qflag_w(ITC_qflag_w);
        kvjEddyImpl.setITC_qflag_w_EMEP(ITC_qflag_w_EMEP);
        kvjEddyImpl.setITC_qflag_u(ITC_qflag_u);
        kvjEddyImpl.setITC_qflag_u_EMEP(ITC_qflag_u_EMEP);
        kvjEddyImpl.setITC_qflag_Ts(ITC_qflag_Ts);
        kvjEddyImpl.setITC_qflag_Ts_EMEP(ITC_qflag_Ts_EMEP);
        kvjEddyImpl.setITC_qflag_CO2_LI72(ITC_qflag_CO2_LI72);
        kvjEddyImpl.setITC_qflag_CO2_LI72_EMEP(ITC_qflag_CO2_LI72_EMEP);
        kvjEddyImpl.setITC_qflag_H2O_LI72(ITC_qflag_H2O_LI72);
        kvjEddyImpl.setITC_qflag_H2O_LI72_EMEP(ITC_qflag_H2O_LI72_EMEP);
        kvjEddyImpl.setITC_qflag_CH4_PICA(ITC_qflag_CH4_PICA);
        kvjEddyImpl.setITC_qflag_CH4_PICA_EMEP(ITC_qflag_CH4_PICA_EMEP);
        kvjEddyImpl.setITC_qflag_H2O_PICA(ITC_qflag_H2O_PICA);
        kvjEddyImpl.setITC_qflag_H2O_PICA_EMEP(ITC_qflag_H2O_PICA_EMEP);
        kvjEddyImpl.setFST_qflag_u(FST_qflag_u);
        kvjEddyImpl.setFST_qflag_u_EMEP(FST_qflag_u_EMEP);
        kvjEddyImpl.setFST_qflag_Ts(FST_qflag_Ts);
        kvjEddyImpl.setFST_qflag_Ts_EMEP(FST_qflag_Ts_EMEP);
        kvjEddyImpl.setFST_qflag_CO2_LI72(FST_qflag_CO2_LI72);
        kvjEddyImpl.setFST_qflag_CO2_LI72_EMEP(FST_qflag_CO2_LI72_EMEP);
        kvjEddyImpl.setFST_qflag_H2O_LI72(FST_qflag_H2O_LI72);
        kvjEddyImpl.setFST_qflag_H2O_LI72_EMEP(FST_qflag_H2O_LI72_EMEP);
        kvjEddyImpl.setFST_qflag_CH4_PICA(FST_qflag_CH4_PICA);
        kvjEddyImpl.setFST_qflag_CH4_PICA_EMEP(FST_qflag_CH4_PICA_EMEP);
        kvjEddyImpl.setFST_qflag_H2O_PICA(FST_qflag_H2O_PICA);
        kvjEddyImpl.setFST_qflag_H2O_PICA_EMEP(FST_qflag_H2O_PICA_EMEP);
        kvjEddyImpl.setHm_u(Hm_u);
        kvjEddyImpl.setHm_u_EMEP(Hm_u_EMEP);
        kvjEddyImpl.setHm_Ts(Hm_Ts);
        kvjEddyImpl.setHm_Ts_EMEP(Hm_Ts_EMEP);
        kvjEddyImpl.setHm_CO2_LI72(Hm_CO2_LI72);
        kvjEddyImpl.setHm_CO2_LI72_EMEP(Hm_CO2_LI72_EMEP);
        kvjEddyImpl.setHm_H2O_LI72(Hm_H2O_LI72);
        kvjEddyImpl.setHm_H2O_LI72_EMEP(Hm_H2O_LI72_EMEP);
        kvjEddyImpl.setHm_CH4_PICA(Hm_CH4_PICA);
        kvjEddyImpl.setHm_CH4_PICA_EMEP(Hm_CH4_PICA_EMEP);
        kvjEddyImpl.setHm_H2O_PICA(Hm_H2O_PICA);
        kvjEddyImpl.setHm_H2O_PICA_EMEP(Hm_H2O_PICA_EMEP);
        kvjEddyImpl.setHv_u(Hv_u);
        kvjEddyImpl.setHv_u_EMEP(Hv_u_EMEP);
        kvjEddyImpl.setHv_Ts(Hv_Ts);
        kvjEddyImpl.setHv_Ts_EMEP(Hv_Ts_EMEP);
        kvjEddyImpl.setHv_CO2_LI72(Hv_CO2_LI72);
        kvjEddyImpl.setHv_CO2_LI72_EMEP(Hv_CO2_LI72_EMEP);
        kvjEddyImpl.setHv_H2O_LI72(Hv_H2O_LI72);
        kvjEddyImpl.setHv_H2O_LI72_EMEP(Hv_H2O_LI72_EMEP);
        kvjEddyImpl.setHv_CH4_PICA(Hv_CH4_PICA);
        kvjEddyImpl.setHv_CH4_PICA_EMEP(Hv_CH4_PICA_EMEP);
        kvjEddyImpl.setHv_H2O_PICA(Hv_H2O_PICA);
        kvjEddyImpl.setHv_H2O_PICA_EMEP(Hv_H2O_PICA_EMEP);
        kvjEddyImpl.setFpr_x_peak(fpr_x_peak);
        kvjEddyImpl.setFpr_x_peak_EMEP(fpr_x_peak_EMEP);
        kvjEddyImpl.setFpr_x_80(fpr_x_80);
        kvjEddyImpl.setFpr_x_80_EMEP(fpr_x_80_EMEP);

        kvjEddyImpl.resetOriginalValues();

        return kvjEddyImpl;
    }

    @Override
    public void readExternal(ObjectInput objectInput) throws IOException {
        samptime = objectInput.readLong();
        H = objectInput.readFloat();
        H_EMEP = objectInput.readInt();
        Qc_H = objectInput.readInt();
        Qc_H_EMEP = objectInput.readInt();
        tau = objectInput.readFloat();
        tau_EMEP = objectInput.readInt();
        Qc_tau = objectInput.readInt();
        Qc_tau_EMEP = objectInput.readInt();
        u_star = objectInput.readFloat();
        u_star_EMEP = objectInput.readInt();
        MO_length = objectInput.readFloat();
        MO_length_EMEP = objectInput.readInt();
        err_packet = objectInput.readInt();
        err_packet_EMEP = objectInput.readInt();
        F_CO2_LI72 = objectInput.readFloat();
        F_CO2_LI72_EMEP = objectInput.readInt();
        Qc_CO2_LI72 = objectInput.readInt();
        Qc_CO2_LI72_EMEP = objectInput.readInt();
        F_CH4_PICA = objectInput.readFloat();
        F_CH4_PICA_EMEP = objectInput.readInt();
        Qc_CH4_PICA = objectInput.readInt();
        Qc_CH4_PICA_EMEP = objectInput.readInt();
        F_H2O_LI72 = objectInput.readFloat();
        F_H2O_LI72_EMEP = objectInput.readInt();
        Qc_H2O_LI72 = objectInput.readInt();
        Qc_H2O_LI72_EMEP = objectInput.readInt();
        F_H2O_PICA = objectInput.readFloat();
        F_H2O_PICA_EMEP = objectInput.readInt();
        Qc_H2O_PICA = objectInput.readInt();
        Qc_H2O_PICA_EMEP = objectInput.readInt();
        LE_LI72 = objectInput.readFloat();
        LE_LI72_EMEP = objectInput.readInt();
        LE_PICA = objectInput.readFloat();
        LE_PICA_EMEP = objectInput.readInt();
        U = objectInput.readFloat();
        U_EMEP = objectInput.readInt();
        wind_dir = objectInput.readFloat();
        wind_dir_EMEP = objectInput.readInt();
        av_u = objectInput.readFloat();
        av_u_EMEP = objectInput.readInt();
        av_v = objectInput.readFloat();
        av_v_EMEP = objectInput.readInt();
        av_w = objectInput.readFloat();
        av_w_EMEP = objectInput.readInt();
        av_t = objectInput.readFloat();
        av_t_EMEP = objectInput.readInt();
        av_c_LI72 = objectInput.readFloat();
        av_c_LI72_EMEP = objectInput.readInt();
        av_h_LI72 = objectInput.readFloat();
        av_h_LI72_EMEP = objectInput.readInt();
        av_h_PICA = objectInput.readFloat();
        av_h_PICA_EMEP = objectInput.readInt();
        av_CH4 = objectInput.readFloat();
        av_CH4_EMEP = objectInput.readInt();
        std_u = objectInput.readFloat();
        std_u_EMEP = objectInput.readInt();
        std_v = objectInput.readFloat();
        std_v_EMEP = objectInput.readInt();
        std_w = objectInput.readFloat();
        std_w_EMEP = objectInput.readInt();
        std_t = objectInput.readFloat();
        std_t_EMEP = objectInput.readInt();
        std_c_LI72 = objectInput.readFloat();
        std_c_LI72_EMEP = objectInput.readInt();
        std_h_LI72 = objectInput.readFloat();
        std_h_LI72_EMEP = objectInput.readInt();
        std_h_PICA = objectInput.readFloat();
        std_h_PICA_EMEP = objectInput.readInt();
        std_CH4 = objectInput.readFloat();
        std_CH4_EMEP = objectInput.readInt();
        eta = objectInput.readFloat();
        eta_EMEP = objectInput.readInt();
        theta = objectInput.readFloat();
        theta_EMEP = objectInput.readInt();
        beta = objectInput.readFloat();
        beta_EMEP = objectInput.readInt();
        Covs_u = objectInput.readFloat();
        Covs_u_EMEP = objectInput.readInt();
        Covs_v = objectInput.readFloat();
        Covs_v_EMEP = objectInput.readInt();
        Covs_Ts = objectInput.readFloat();
        Covs_Ts_EMEP = objectInput.readInt();
        Covs_CO2_LI72 = objectInput.readFloat();
        Covs_CO2_LI72_EMEP = objectInput.readInt();
        Covs_H2O_LI72 = objectInput.readFloat();
        Covs_H2O_LI72_EMEP = objectInput.readInt();
        Covs_T_C_LI72 = objectInput.readFloat();
        Covs_T_C_LI72_EMEP = objectInput.readInt();
        Covs_P_C_LI72 = objectInput.readFloat();
        Covs_P_C_LI72_EMEP = objectInput.readInt();
        Covs_H2O_PICA = objectInput.readFloat();
        Covs_H2O_PICA_EMEP = objectInput.readInt();
        Covs_CH4_PICA = objectInput.readFloat();
        Covs_CH4_PICA_EMEP = objectInput.readInt();
        licor_t_av = objectInput.readFloat();
        licor_t_av_EMEP = objectInput.readInt();
        licor_p_av = objectInput.readFloat();
        licor_p_av_EMEP = objectInput.readInt();
        licor_t_std = objectInput.readFloat();
        licor_t_std_EMEP = objectInput.readInt();
        licor_p_std = objectInput.readFloat();
        licor_p_std_EMEP = objectInput.readInt();
        c_lag_LI72 = objectInput.readFloat();
        c_lag_LI72_EMEP = objectInput.readInt();
        h_lag_LI72 = objectInput.readFloat();
        h_lag_LI72_EMEP = objectInput.readInt();
        t_lag_LI72 = objectInput.readFloat();
        t_lag_LI72_EMEP = objectInput.readInt();
        p_lag_LI72 = objectInput.readFloat();
        p_lag_LI72_EMEP = objectInput.readInt();
        h_lag_PICA = objectInput.readFloat();
        h_lag_PICA_EMEP = objectInput.readInt();
        CH4_lag = objectInput.readFloat();
        CH4_lag_EMEP = objectInput.readInt();
        Nspikes_u = objectInput.readInt();
        Nspikes_u_EMEP = objectInput.readInt();
        Nspikes_v = objectInput.readInt();
        Nspikes_v_EMEP = objectInput.readInt();
        Nspikes_w = objectInput.readInt();
        Nspikes_w_EMEP = objectInput.readInt();
        Nspikes_Ts = objectInput.readInt();
        Nspikes_Ts_EMEP = objectInput.readInt();
        Nspikes_CO2_LI72 = objectInput.readInt();
        Nspikes_CO2_LI72_EMEP = objectInput.readInt();
        Nspikes_H2O_LI72 = objectInput.readInt();
        Nspikes_H2O_LI72_EMEP = objectInput.readInt();
        Nspikes_T_C_LI72 = objectInput.readInt();
        Nspikes_T_C_LI72_EMEP = objectInput.readInt();
        Nspikes_P_C_LI72 = objectInput.readInt();
        Nspikes_P_C_LI72_EMEP = objectInput.readInt();
        Nspikes_H2O_PICA = objectInput.readInt();
        Nspikes_H2O_PICA_EMEP = objectInput.readInt();
        Nspikes_CH4_PICA = objectInput.readInt();
        Nspikes_CH4_PICA_EMEP = objectInput.readInt();
        FI_u = objectInput.readFloat();
        FI_u_EMEP = objectInput.readInt();
        FI_Ts = objectInput.readFloat();
        FI_Ts_EMEP = objectInput.readInt();
        FI_CO2_LI72 = objectInput.readFloat();
        FI_CO2_LI72_EMEP = objectInput.readInt();
        FI_H2O_LI72 = objectInput.readFloat();
        FI_H2O_LI72_EMEP = objectInput.readInt();
        FI_CH4_PICA = objectInput.readFloat();
        FI_CH4_PICA_EMEP = objectInput.readInt();
        FI_H2O_PICA = objectInput.readFloat();
        FI_H2O_PICA_EMEP = objectInput.readInt();
        FST_u = objectInput.readFloat();
        FST_u_EMEP = objectInput.readInt();
        FST_Ts = objectInput.readFloat();
        FST_Ts_EMEP = objectInput.readInt();
        FST_CO2_LI72 = objectInput.readFloat();
        FST_CO2_LI72_EMEP = objectInput.readInt();
        FST_H2O_LI72 = objectInput.readFloat();
        FST_H2O_LI72_EMEP = objectInput.readInt();
        FST_CH4_PICA = objectInput.readFloat();
        FST_CH4_PICA_EMEP = objectInput.readInt();
        FST_H2O_PICA = objectInput.readFloat();
        FST_H2O_PICA_EMEP = objectInput.readInt();
        RFE_u = objectInput.readFloat();
        RFE_u_EMEP = objectInput.readInt();
        RFE_Ts = objectInput.readFloat();
        RFE_Ts_EMEP = objectInput.readInt();
        RFE_CO2_LI72 = objectInput.readFloat();
        RFE_CO2_LI72_EMEP = objectInput.readInt();
        RFE_H2O_LI72 = objectInput.readFloat();
        RFE_H2O_LI72_EMEP = objectInput.readInt();
        RFE_CH4_PICA = objectInput.readFloat();
        RFE_CH4_PICA_EMEP = objectInput.readInt();
        RFE_H2O_PICA = objectInput.readFloat();
        RFE_H2O_PICA_EMEP = objectInput.readInt();
        FA_u = objectInput.readFloat();
        FA_u_EMEP = objectInput.readInt();
        FA_v = objectInput.readFloat();
        FA_v_EMEP = objectInput.readInt();
        FA_Ts = objectInput.readFloat();
        FA_Ts_EMEP = objectInput.readInt();
        FA_CO2_LI72 = objectInput.readFloat();
        FA_CO2_LI72_EMEP = objectInput.readInt();
        FA_H2O_LI72 = objectInput.readFloat();
        FA_H2O_LI72_EMEP = objectInput.readInt();
        FA_CH4_PICA = objectInput.readFloat();
        FA_CH4_PICA_EMEP = objectInput.readInt();
        FA_H2O_PICA = objectInput.readFloat();
        FA_H2O_PICA_EMEP = objectInput.readInt();
        covsvar_u = objectInput.readFloat();
        covsvar_u_EMEP = objectInput.readInt();
        covsvar_v = objectInput.readFloat();
        covsvar_v_EMEP = objectInput.readInt();
        covsvar_Ts = objectInput.readFloat();
        covsvar_Ts_EMEP = objectInput.readInt();
        covsvar_CO2_LI72 = objectInput.readFloat();
        covsvar_CO2_LI72_EMEP = objectInput.readInt();
        covsvar_H2O_LI72 = objectInput.readFloat();
        covsvar_H2O_LI72_EMEP = objectInput.readInt();
        covsvar_CH4_PICA = objectInput.readFloat();
        covsvar_CH4_PICA_EMEP = objectInput.readInt();
        covsvar_H2O_PICA = objectInput.readFloat();
        covsvar_H2O_PICA_EMEP = objectInput.readInt();
        SKx_u = objectInput.readFloat();
        SKx_u_EMEP = objectInput.readInt();
        SKx_v = objectInput.readFloat();
        SKx_v_EMEP = objectInput.readInt();
        SKx_w = objectInput.readFloat();
        SKx_w_EMEP = objectInput.readInt();
        SKx_Ts = objectInput.readFloat();
        SKx_Ts_EMEP = objectInput.readInt();
        SKx_CO2_LI72 = objectInput.readFloat();
        SKx_CO2_LI72_EMEP = objectInput.readInt();
        SKx_H2O_LI72 = objectInput.readFloat();
        SKx_H2O_LI72_EMEP = objectInput.readInt();
        SKx_CH4_PICA = objectInput.readFloat();
        SKx_CH4_PICA_EMEP = objectInput.readInt();
        SKx_H2O_PICA = objectInput.readFloat();
        SKx_H2O_PICA_EMEP = objectInput.readInt();
        KUx_u = objectInput.readFloat();
        KUx_u_EMEP = objectInput.readInt();
        KUx_v = objectInput.readFloat();
        KUx_v_EMEP = objectInput.readInt();
        KUx_w = objectInput.readFloat();
        KUx_w_EMEP = objectInput.readInt();
        KUx_Ts = objectInput.readFloat();
        KUx_Ts_EMEP = objectInput.readInt();
        KUx_CO2_LI72 = objectInput.readFloat();
        KUx_CO2_LI72_EMEP = objectInput.readInt();
        KUx_H2O_LI72 = objectInput.readFloat();
        KUx_H2O_LI72_EMEP = objectInput.readInt();
        KUx_CH4_PICA = objectInput.readFloat();
        KUx_CH4_PICA_EMEP = objectInput.readInt();
        KUx_H2O_PICA = objectInput.readFloat();
        KUx_H2O_PICA_EMEP = objectInput.readInt();
        overall_qflag_u = objectInput.readInt();
        overall_qflag_u_EMEP = objectInput.readInt();
        overall_qflag_Ts = objectInput.readInt();
        overall_qflag_Ts_EMEP = objectInput.readInt();
        overall_qflag_CO2_LI72 = objectInput.readInt();
        overall_qflag_CO2_LI72_EMEP = objectInput.readInt();
        overall_qflag_H2O_LI72 = objectInput.readInt();
        overall_qflag_H2O_LI72_EMEP = objectInput.readInt();
        overall_qflag_CH4_PICA = objectInput.readInt();
        overall_qflag_CH4_PICA_EMEP = objectInput.readInt();
        overall_qflag_H2O_PICA = objectInput.readInt();
        overall_qflag_H2O_PICA_EMEP = objectInput.readInt();
        ITC_qflag_w = objectInput.readInt();
        ITC_qflag_w_EMEP = objectInput.readInt();
        ITC_qflag_u = objectInput.readInt();
        ITC_qflag_u_EMEP = objectInput.readInt();
        ITC_qflag_Ts = objectInput.readInt();
        ITC_qflag_Ts_EMEP = objectInput.readInt();
        ITC_qflag_CO2_LI72 = objectInput.readInt();
        ITC_qflag_CO2_LI72_EMEP = objectInput.readInt();
        ITC_qflag_H2O_LI72 = objectInput.readInt();
        ITC_qflag_H2O_LI72_EMEP = objectInput.readInt();
        ITC_qflag_CH4_PICA = objectInput.readInt();
        ITC_qflag_CH4_PICA_EMEP = objectInput.readInt();
        ITC_qflag_H2O_PICA = objectInput.readInt();
        ITC_qflag_H2O_PICA_EMEP = objectInput.readInt();
        FST_qflag_u = objectInput.readInt();
        FST_qflag_u_EMEP = objectInput.readInt();
        FST_qflag_Ts = objectInput.readInt();
        FST_qflag_Ts_EMEP = objectInput.readInt();
        FST_qflag_CO2_LI72 = objectInput.readInt();
        FST_qflag_CO2_LI72_EMEP = objectInput.readInt();
        FST_qflag_H2O_LI72 = objectInput.readInt();
        FST_qflag_H2O_LI72_EMEP = objectInput.readInt();
        FST_qflag_CH4_PICA = objectInput.readInt();
        FST_qflag_CH4_PICA_EMEP = objectInput.readInt();
        FST_qflag_H2O_PICA = objectInput.readInt();
        FST_qflag_H2O_PICA_EMEP = objectInput.readInt();
        Hm_u = objectInput.readFloat();
        Hm_u_EMEP = objectInput.readInt();
        Hm_Ts = objectInput.readFloat();
        Hm_Ts_EMEP = objectInput.readInt();
        Hm_CO2_LI72 = objectInput.readFloat();
        Hm_CO2_LI72_EMEP = objectInput.readInt();
        Hm_H2O_LI72 = objectInput.readFloat();
        Hm_H2O_LI72_EMEP = objectInput.readInt();
        Hm_CH4_PICA = objectInput.readFloat();
        Hm_CH4_PICA_EMEP = objectInput.readInt();
        Hm_H2O_PICA = objectInput.readFloat();
        Hm_H2O_PICA_EMEP = objectInput.readInt();
        Hv_u = objectInput.readFloat();
        Hv_u_EMEP = objectInput.readInt();
        Hv_Ts = objectInput.readFloat();
        Hv_Ts_EMEP = objectInput.readInt();
        Hv_CO2_LI72 = objectInput.readFloat();
        Hv_CO2_LI72_EMEP = objectInput.readInt();
        Hv_H2O_LI72 = objectInput.readFloat();
        Hv_H2O_LI72_EMEP = objectInput.readInt();
        Hv_CH4_PICA = objectInput.readFloat();
        Hv_CH4_PICA_EMEP = objectInput.readInt();
        Hv_H2O_PICA = objectInput.readFloat();
        Hv_H2O_PICA_EMEP = objectInput.readInt();
        fpr_x_peak = objectInput.readFloat();
        fpr_x_peak_EMEP = objectInput.readInt();
        fpr_x_80 = objectInput.readFloat();
        fpr_x_80_EMEP = objectInput.readInt();
    }

    @Override
    public void writeExternal(ObjectOutput objectOutput)
        throws IOException {
        objectOutput.writeLong(samptime);
        objectOutput.writeFloat(H);
        objectOutput.writeInt(H_EMEP);
        objectOutput.writeInt(Qc_H);
        objectOutput.writeInt(Qc_H_EMEP);
        objectOutput.writeFloat(tau);
        objectOutput.writeInt(tau_EMEP);
        objectOutput.writeInt(Qc_tau);
        objectOutput.writeInt(Qc_tau_EMEP);
        objectOutput.writeFloat(u_star);
        objectOutput.writeInt(u_star_EMEP);
        objectOutput.writeFloat(MO_length);
        objectOutput.writeInt(MO_length_EMEP);
        objectOutput.writeInt(err_packet);
        objectOutput.writeInt(err_packet_EMEP);
        objectOutput.writeFloat(F_CO2_LI72);
        objectOutput.writeInt(F_CO2_LI72_EMEP);
        objectOutput.writeInt(Qc_CO2_LI72);
        objectOutput.writeInt(Qc_CO2_LI72_EMEP);
        objectOutput.writeFloat(F_CH4_PICA);
        objectOutput.writeInt(F_CH4_PICA_EMEP);
        objectOutput.writeInt(Qc_CH4_PICA);
        objectOutput.writeInt(Qc_CH4_PICA_EMEP);
        objectOutput.writeFloat(F_H2O_LI72);
        objectOutput.writeInt(F_H2O_LI72_EMEP);
        objectOutput.writeInt(Qc_H2O_LI72);
        objectOutput.writeInt(Qc_H2O_LI72_EMEP);
        objectOutput.writeFloat(F_H2O_PICA);
        objectOutput.writeInt(F_H2O_PICA_EMEP);
        objectOutput.writeInt(Qc_H2O_PICA);
        objectOutput.writeInt(Qc_H2O_PICA_EMEP);
        objectOutput.writeFloat(LE_LI72);
        objectOutput.writeInt(LE_LI72_EMEP);
        objectOutput.writeFloat(LE_PICA);
        objectOutput.writeInt(LE_PICA_EMEP);
        objectOutput.writeFloat(U);
        objectOutput.writeInt(U_EMEP);
        objectOutput.writeFloat(wind_dir);
        objectOutput.writeInt(wind_dir_EMEP);
        objectOutput.writeFloat(av_u);
        objectOutput.writeInt(av_u_EMEP);
        objectOutput.writeFloat(av_v);
        objectOutput.writeInt(av_v_EMEP);
        objectOutput.writeFloat(av_w);
        objectOutput.writeInt(av_w_EMEP);
        objectOutput.writeFloat(av_t);
        objectOutput.writeInt(av_t_EMEP);
        objectOutput.writeFloat(av_c_LI72);
        objectOutput.writeInt(av_c_LI72_EMEP);
        objectOutput.writeFloat(av_h_LI72);
        objectOutput.writeInt(av_h_LI72_EMEP);
        objectOutput.writeFloat(av_h_PICA);
        objectOutput.writeInt(av_h_PICA_EMEP);
        objectOutput.writeFloat(av_CH4);
        objectOutput.writeInt(av_CH4_EMEP);
        objectOutput.writeFloat(std_u);
        objectOutput.writeInt(std_u_EMEP);
        objectOutput.writeFloat(std_v);
        objectOutput.writeInt(std_v_EMEP);
        objectOutput.writeFloat(std_w);
        objectOutput.writeInt(std_w_EMEP);
        objectOutput.writeFloat(std_t);
        objectOutput.writeInt(std_t_EMEP);
        objectOutput.writeFloat(std_c_LI72);
        objectOutput.writeInt(std_c_LI72_EMEP);
        objectOutput.writeFloat(std_h_LI72);
        objectOutput.writeInt(std_h_LI72_EMEP);
        objectOutput.writeFloat(std_h_PICA);
        objectOutput.writeInt(std_h_PICA_EMEP);
        objectOutput.writeFloat(std_CH4);
        objectOutput.writeInt(std_CH4_EMEP);
        objectOutput.writeFloat(eta);
        objectOutput.writeInt(eta_EMEP);
        objectOutput.writeFloat(theta);
        objectOutput.writeInt(theta_EMEP);
        objectOutput.writeFloat(beta);
        objectOutput.writeInt(beta_EMEP);
        objectOutput.writeFloat(Covs_u);
        objectOutput.writeInt(Covs_u_EMEP);
        objectOutput.writeFloat(Covs_v);
        objectOutput.writeInt(Covs_v_EMEP);
        objectOutput.writeFloat(Covs_Ts);
        objectOutput.writeInt(Covs_Ts_EMEP);
        objectOutput.writeFloat(Covs_CO2_LI72);
        objectOutput.writeInt(Covs_CO2_LI72_EMEP);
        objectOutput.writeFloat(Covs_H2O_LI72);
        objectOutput.writeInt(Covs_H2O_LI72_EMEP);
        objectOutput.writeFloat(Covs_T_C_LI72);
        objectOutput.writeInt(Covs_T_C_LI72_EMEP);
        objectOutput.writeFloat(Covs_P_C_LI72);
        objectOutput.writeInt(Covs_P_C_LI72_EMEP);
        objectOutput.writeFloat(Covs_H2O_PICA);
        objectOutput.writeInt(Covs_H2O_PICA_EMEP);
        objectOutput.writeFloat(Covs_CH4_PICA);
        objectOutput.writeInt(Covs_CH4_PICA_EMEP);
        objectOutput.writeFloat(licor_t_av);
        objectOutput.writeInt(licor_t_av_EMEP);
        objectOutput.writeFloat(licor_p_av);
        objectOutput.writeInt(licor_p_av_EMEP);
        objectOutput.writeFloat(licor_t_std);
        objectOutput.writeInt(licor_t_std_EMEP);
        objectOutput.writeFloat(licor_p_std);
        objectOutput.writeInt(licor_p_std_EMEP);
        objectOutput.writeFloat(c_lag_LI72);
        objectOutput.writeInt(c_lag_LI72_EMEP);
        objectOutput.writeFloat(h_lag_LI72);
        objectOutput.writeInt(h_lag_LI72_EMEP);
        objectOutput.writeFloat(t_lag_LI72);
        objectOutput.writeInt(t_lag_LI72_EMEP);
        objectOutput.writeFloat(p_lag_LI72);
        objectOutput.writeInt(p_lag_LI72_EMEP);
        objectOutput.writeFloat(h_lag_PICA);
        objectOutput.writeInt(h_lag_PICA_EMEP);
        objectOutput.writeFloat(CH4_lag);
        objectOutput.writeInt(CH4_lag_EMEP);
        objectOutput.writeInt(Nspikes_u);
        objectOutput.writeInt(Nspikes_u_EMEP);
        objectOutput.writeInt(Nspikes_v);
        objectOutput.writeInt(Nspikes_v_EMEP);
        objectOutput.writeInt(Nspikes_w);
        objectOutput.writeInt(Nspikes_w_EMEP);
        objectOutput.writeInt(Nspikes_Ts);
        objectOutput.writeInt(Nspikes_Ts_EMEP);
        objectOutput.writeInt(Nspikes_CO2_LI72);
        objectOutput.writeInt(Nspikes_CO2_LI72_EMEP);
        objectOutput.writeInt(Nspikes_H2O_LI72);
        objectOutput.writeInt(Nspikes_H2O_LI72_EMEP);
        objectOutput.writeInt(Nspikes_T_C_LI72);
        objectOutput.writeInt(Nspikes_T_C_LI72_EMEP);
        objectOutput.writeInt(Nspikes_P_C_LI72);
        objectOutput.writeInt(Nspikes_P_C_LI72_EMEP);
        objectOutput.writeInt(Nspikes_H2O_PICA);
        objectOutput.writeInt(Nspikes_H2O_PICA_EMEP);
        objectOutput.writeInt(Nspikes_CH4_PICA);
        objectOutput.writeInt(Nspikes_CH4_PICA_EMEP);
        objectOutput.writeFloat(FI_u);
        objectOutput.writeInt(FI_u_EMEP);
        objectOutput.writeFloat(FI_Ts);
        objectOutput.writeInt(FI_Ts_EMEP);
        objectOutput.writeFloat(FI_CO2_LI72);
        objectOutput.writeInt(FI_CO2_LI72_EMEP);
        objectOutput.writeFloat(FI_H2O_LI72);
        objectOutput.writeInt(FI_H2O_LI72_EMEP);
        objectOutput.writeFloat(FI_CH4_PICA);
        objectOutput.writeInt(FI_CH4_PICA_EMEP);
        objectOutput.writeFloat(FI_H2O_PICA);
        objectOutput.writeInt(FI_H2O_PICA_EMEP);
        objectOutput.writeFloat(FST_u);
        objectOutput.writeInt(FST_u_EMEP);
        objectOutput.writeFloat(FST_Ts);
        objectOutput.writeInt(FST_Ts_EMEP);
        objectOutput.writeFloat(FST_CO2_LI72);
        objectOutput.writeInt(FST_CO2_LI72_EMEP);
        objectOutput.writeFloat(FST_H2O_LI72);
        objectOutput.writeInt(FST_H2O_LI72_EMEP);
        objectOutput.writeFloat(FST_CH4_PICA);
        objectOutput.writeInt(FST_CH4_PICA_EMEP);
        objectOutput.writeFloat(FST_H2O_PICA);
        objectOutput.writeInt(FST_H2O_PICA_EMEP);
        objectOutput.writeFloat(RFE_u);
        objectOutput.writeInt(RFE_u_EMEP);
        objectOutput.writeFloat(RFE_Ts);
        objectOutput.writeInt(RFE_Ts_EMEP);
        objectOutput.writeFloat(RFE_CO2_LI72);
        objectOutput.writeInt(RFE_CO2_LI72_EMEP);
        objectOutput.writeFloat(RFE_H2O_LI72);
        objectOutput.writeInt(RFE_H2O_LI72_EMEP);
        objectOutput.writeFloat(RFE_CH4_PICA);
        objectOutput.writeInt(RFE_CH4_PICA_EMEP);
        objectOutput.writeFloat(RFE_H2O_PICA);
        objectOutput.writeInt(RFE_H2O_PICA_EMEP);
        objectOutput.writeFloat(FA_u);
        objectOutput.writeInt(FA_u_EMEP);
        objectOutput.writeFloat(FA_v);
        objectOutput.writeInt(FA_v_EMEP);
        objectOutput.writeFloat(FA_Ts);
        objectOutput.writeInt(FA_Ts_EMEP);
        objectOutput.writeFloat(FA_CO2_LI72);
        objectOutput.writeInt(FA_CO2_LI72_EMEP);
        objectOutput.writeFloat(FA_H2O_LI72);
        objectOutput.writeInt(FA_H2O_LI72_EMEP);
        objectOutput.writeFloat(FA_CH4_PICA);
        objectOutput.writeInt(FA_CH4_PICA_EMEP);
        objectOutput.writeFloat(FA_H2O_PICA);
        objectOutput.writeInt(FA_H2O_PICA_EMEP);
        objectOutput.writeFloat(covsvar_u);
        objectOutput.writeInt(covsvar_u_EMEP);
        objectOutput.writeFloat(covsvar_v);
        objectOutput.writeInt(covsvar_v_EMEP);
        objectOutput.writeFloat(covsvar_Ts);
        objectOutput.writeInt(covsvar_Ts_EMEP);
        objectOutput.writeFloat(covsvar_CO2_LI72);
        objectOutput.writeInt(covsvar_CO2_LI72_EMEP);
        objectOutput.writeFloat(covsvar_H2O_LI72);
        objectOutput.writeInt(covsvar_H2O_LI72_EMEP);
        objectOutput.writeFloat(covsvar_CH4_PICA);
        objectOutput.writeInt(covsvar_CH4_PICA_EMEP);
        objectOutput.writeFloat(covsvar_H2O_PICA);
        objectOutput.writeInt(covsvar_H2O_PICA_EMEP);
        objectOutput.writeFloat(SKx_u);
        objectOutput.writeInt(SKx_u_EMEP);
        objectOutput.writeFloat(SKx_v);
        objectOutput.writeInt(SKx_v_EMEP);
        objectOutput.writeFloat(SKx_w);
        objectOutput.writeInt(SKx_w_EMEP);
        objectOutput.writeFloat(SKx_Ts);
        objectOutput.writeInt(SKx_Ts_EMEP);
        objectOutput.writeFloat(SKx_CO2_LI72);
        objectOutput.writeInt(SKx_CO2_LI72_EMEP);
        objectOutput.writeFloat(SKx_H2O_LI72);
        objectOutput.writeInt(SKx_H2O_LI72_EMEP);
        objectOutput.writeFloat(SKx_CH4_PICA);
        objectOutput.writeInt(SKx_CH4_PICA_EMEP);
        objectOutput.writeFloat(SKx_H2O_PICA);
        objectOutput.writeInt(SKx_H2O_PICA_EMEP);
        objectOutput.writeFloat(KUx_u);
        objectOutput.writeInt(KUx_u_EMEP);
        objectOutput.writeFloat(KUx_v);
        objectOutput.writeInt(KUx_v_EMEP);
        objectOutput.writeFloat(KUx_w);
        objectOutput.writeInt(KUx_w_EMEP);
        objectOutput.writeFloat(KUx_Ts);
        objectOutput.writeInt(KUx_Ts_EMEP);
        objectOutput.writeFloat(KUx_CO2_LI72);
        objectOutput.writeInt(KUx_CO2_LI72_EMEP);
        objectOutput.writeFloat(KUx_H2O_LI72);
        objectOutput.writeInt(KUx_H2O_LI72_EMEP);
        objectOutput.writeFloat(KUx_CH4_PICA);
        objectOutput.writeInt(KUx_CH4_PICA_EMEP);
        objectOutput.writeFloat(KUx_H2O_PICA);
        objectOutput.writeInt(KUx_H2O_PICA_EMEP);
        objectOutput.writeInt(overall_qflag_u);
        objectOutput.writeInt(overall_qflag_u_EMEP);
        objectOutput.writeInt(overall_qflag_Ts);
        objectOutput.writeInt(overall_qflag_Ts_EMEP);
        objectOutput.writeInt(overall_qflag_CO2_LI72);
        objectOutput.writeInt(overall_qflag_CO2_LI72_EMEP);
        objectOutput.writeInt(overall_qflag_H2O_LI72);
        objectOutput.writeInt(overall_qflag_H2O_LI72_EMEP);
        objectOutput.writeInt(overall_qflag_CH4_PICA);
        objectOutput.writeInt(overall_qflag_CH4_PICA_EMEP);
        objectOutput.writeInt(overall_qflag_H2O_PICA);
        objectOutput.writeInt(overall_qflag_H2O_PICA_EMEP);
        objectOutput.writeInt(ITC_qflag_w);
        objectOutput.writeInt(ITC_qflag_w_EMEP);
        objectOutput.writeInt(ITC_qflag_u);
        objectOutput.writeInt(ITC_qflag_u_EMEP);
        objectOutput.writeInt(ITC_qflag_Ts);
        objectOutput.writeInt(ITC_qflag_Ts_EMEP);
        objectOutput.writeInt(ITC_qflag_CO2_LI72);
        objectOutput.writeInt(ITC_qflag_CO2_LI72_EMEP);
        objectOutput.writeInt(ITC_qflag_H2O_LI72);
        objectOutput.writeInt(ITC_qflag_H2O_LI72_EMEP);
        objectOutput.writeInt(ITC_qflag_CH4_PICA);
        objectOutput.writeInt(ITC_qflag_CH4_PICA_EMEP);
        objectOutput.writeInt(ITC_qflag_H2O_PICA);
        objectOutput.writeInt(ITC_qflag_H2O_PICA_EMEP);
        objectOutput.writeInt(FST_qflag_u);
        objectOutput.writeInt(FST_qflag_u_EMEP);
        objectOutput.writeInt(FST_qflag_Ts);
        objectOutput.writeInt(FST_qflag_Ts_EMEP);
        objectOutput.writeInt(FST_qflag_CO2_LI72);
        objectOutput.writeInt(FST_qflag_CO2_LI72_EMEP);
        objectOutput.writeInt(FST_qflag_H2O_LI72);
        objectOutput.writeInt(FST_qflag_H2O_LI72_EMEP);
        objectOutput.writeInt(FST_qflag_CH4_PICA);
        objectOutput.writeInt(FST_qflag_CH4_PICA_EMEP);
        objectOutput.writeInt(FST_qflag_H2O_PICA);
        objectOutput.writeInt(FST_qflag_H2O_PICA_EMEP);
        objectOutput.writeFloat(Hm_u);
        objectOutput.writeInt(Hm_u_EMEP);
        objectOutput.writeFloat(Hm_Ts);
        objectOutput.writeInt(Hm_Ts_EMEP);
        objectOutput.writeFloat(Hm_CO2_LI72);
        objectOutput.writeInt(Hm_CO2_LI72_EMEP);
        objectOutput.writeFloat(Hm_H2O_LI72);
        objectOutput.writeInt(Hm_H2O_LI72_EMEP);
        objectOutput.writeFloat(Hm_CH4_PICA);
        objectOutput.writeInt(Hm_CH4_PICA_EMEP);
        objectOutput.writeFloat(Hm_H2O_PICA);
        objectOutput.writeInt(Hm_H2O_PICA_EMEP);
        objectOutput.writeFloat(Hv_u);
        objectOutput.writeInt(Hv_u_EMEP);
        objectOutput.writeFloat(Hv_Ts);
        objectOutput.writeInt(Hv_Ts_EMEP);
        objectOutput.writeFloat(Hv_CO2_LI72);
        objectOutput.writeInt(Hv_CO2_LI72_EMEP);
        objectOutput.writeFloat(Hv_H2O_LI72);
        objectOutput.writeInt(Hv_H2O_LI72_EMEP);
        objectOutput.writeFloat(Hv_CH4_PICA);
        objectOutput.writeInt(Hv_CH4_PICA_EMEP);
        objectOutput.writeFloat(Hv_H2O_PICA);
        objectOutput.writeInt(Hv_H2O_PICA_EMEP);
        objectOutput.writeFloat(fpr_x_peak);
        objectOutput.writeInt(fpr_x_peak_EMEP);
        objectOutput.writeFloat(fpr_x_80);
        objectOutput.writeInt(fpr_x_80_EMEP);
    }
}
