package fi.csc.smear.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.smear.db.model.kvjEddy;
import fi.csc.smear.db.service.kvjEddyLocalServiceUtil;

/**
 * The extended model base implementation for the kvjEddy service. Represents a row in the &quot;KVJ_EDDY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link kvjEddyImpl}.
 * </p>
 *
 * @author pj
 * @see kvjEddyImpl
 * @see fi.csc.smear.db.model.kvjEddy
 * @generated
 */
public abstract class kvjEddyBaseImpl extends kvjEddyModelImpl
    implements kvjEddy {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kvj eddy model instance should use the {@link kvjEddy} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            kvjEddyLocalServiceUtil.addkvjEddy(this);
        } else {
            kvjEddyLocalServiceUtil.updatekvjEddy(this);
        }
    }
}
