package fi.csc.smear.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.smear.db.model.Sii1meta;
import fi.csc.smear.db.model.Sii1metaModel;
import fi.csc.smear.db.model.Sii1metaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Sii1meta service. Represents a row in the &quot;SII1_META&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.smear.db.model.Sii1metaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Sii1metaImpl}.
 * </p>
 *
 * @author pj
 * @see Sii1metaImpl
 * @see fi.csc.smear.db.model.Sii1meta
 * @see fi.csc.smear.db.model.Sii1metaModel
 * @generated
 */
@JSON(strict = true)
public class Sii1metaModelImpl extends BaseModelImpl<Sii1meta>
    implements Sii1metaModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sii1meta model instance should use the {@link fi.csc.smear.db.model.Sii1meta} interface instead.
     */
    public static final String TABLE_NAME = "SII1_META";
    public static final Object[][] TABLE_COLUMNS = {
            { "samptime", Types.TIMESTAMP },
            { "T_a", Types.FLOAT },
            { "T_a_EMEP", Types.INTEGER },
            { "RH", Types.FLOAT },
            { "RH_EMEP", Types.INTEGER },
            { "PAR", Types.FLOAT },
            { "PAR_EMEP", Types.INTEGER },
            { "R_PAR", Types.FLOAT },
            { "R_PAR_EMEP", Types.INTEGER },
            { "Net_CNR4", Types.FLOAT },
            { "Net_CNR4_EMEP", Types.INTEGER },
            { "Net_NRLite", Types.FLOAT },
            { "Net_NRLite_EMEP", Types.INTEGER },
            { "Wsoil_1", Types.FLOAT },
            { "Wsoil_1_EMEP", Types.INTEGER },
            { "Wsoil_2", Types.FLOAT },
            { "Wsoil_2_EMEP", Types.INTEGER },
            { "T_p_B5", Types.FLOAT },
            { "T_p_B5_EMEP", Types.INTEGER },
            { "T_p_B20", Types.FLOAT },
            { "T_p_B20_EMEP", Types.INTEGER },
            { "T_p_B35", Types.FLOAT },
            { "T_p_B35_EMEP", Types.INTEGER },
            { "T_p_B50", Types.FLOAT },
            { "T_p_B50_EMEP", Types.INTEGER },
            { "T_p_C1", Types.FLOAT },
            { "T_p_C1_EMEP", Types.INTEGER },
            { "T_p_C2", Types.FLOAT },
            { "T_p_C2_EMEP", Types.INTEGER },
            { "T_p_C5", Types.FLOAT },
            { "T_p_C5_EMEP", Types.INTEGER },
            { "T_p_C10", Types.FLOAT },
            { "T_p_C10_EMEP", Types.INTEGER },
            { "T_p_C15", Types.FLOAT },
            { "T_p_C15_EMEP", Types.INTEGER },
            { "T_p_C20", Types.FLOAT },
            { "T_p_C20_EMEP", Types.INTEGER },
            { "T_p_C30", Types.FLOAT },
            { "T_p_C30_EMEP", Types.INTEGER },
            { "T_p_C50", Types.FLOAT },
            { "T_p_C50_EMEP", Types.INTEGER },
            { "T_p_C70", Types.FLOAT },
            { "T_p_C70_EMEP", Types.INTEGER },
            { "T_p_C100", Types.FLOAT },
            { "T_p_C100_EMEP", Types.INTEGER },
            { "WTD", Types.FLOAT },
            { "WTD_EMEP", Types.INTEGER },
            { "Precip", Types.FLOAT },
            { "Precip_EMEP", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table SII1_META (samptime DATE not null primary key,T_a DOUBLE,T_a_EMEP INTEGER,RH DOUBLE,RH_EMEP INTEGER,PAR DOUBLE,PAR_EMEP INTEGER,R_PAR DOUBLE,R_PAR_EMEP INTEGER,Net_CNR4 DOUBLE,Net_CNR4_EMEP INTEGER,Net_NRLite DOUBLE,Net_NRLite_EMEP INTEGER,Wsoil_1 DOUBLE,Wsoil_1_EMEP INTEGER,Wsoil_2 DOUBLE,Wsoil_2_EMEP INTEGER,T_p_B5 DOUBLE,T_p_B5_EMEP INTEGER,T_p_B20 DOUBLE,T_p_B20_EMEP INTEGER,T_p_B35 DOUBLE,T_p_B35_EMEP INTEGER,T_p_B50 DOUBLE,T_p_B50_EMEP INTEGER,T_p_C1 DOUBLE,T_p_C1_EMEP INTEGER,T_p_C2 DOUBLE,T_p_C2_EMEP INTEGER,T_p_C5 DOUBLE,T_p_C5_EMEP INTEGER,T_p_C10 DOUBLE,T_p_C10_EMEP INTEGER,T_p_C15 DOUBLE,T_p_C15_EMEP INTEGER,T_p_C20 DOUBLE,T_p_C20_EMEP INTEGER,T_p_C30 DOUBLE,T_p_C30_EMEP INTEGER,T_p_C50 DOUBLE,T_p_C50_EMEP INTEGER,T_p_C70 DOUBLE,T_p_C70_EMEP INTEGER,T_p_C100 DOUBLE,T_p_C100_EMEP INTEGER,WTD DOUBLE,WTD_EMEP INTEGER,Precip DOUBLE,Precip_EMEP INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table SII1_META";
    public static final String ORDER_BY_JPQL = " ORDER BY sii1meta.samptime ASC";
    public static final String ORDER_BY_SQL = " ORDER BY SII1_META.samptime ASC";
    public static final String DATA_SOURCE = "smear";
    public static final String SESSION_FACTORY = "smearSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.smear.db.model.Sii1meta"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.smear.db.model.Sii1meta"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.smear.db.model.Sii1meta"));
    private static ClassLoader _classLoader = Sii1meta.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Sii1meta.class
        };
    private Date _samptime;
    private float _T_a;
    private int _T_a_EMEP;
    private float _RH;
    private int _RH_EMEP;
    private float _PAR;
    private int _PAR_EMEP;
    private float _R_PAR;
    private int _R_PAR_EMEP;
    private float _Net_CNR4;
    private int _Net_CNR4_EMEP;
    private float _Net_NRLite;
    private int _Net_NRLite_EMEP;
    private float _Wsoil_1;
    private int _Wsoil_1_EMEP;
    private float _Wsoil_2;
    private int _Wsoil_2_EMEP;
    private float _T_p_B5;
    private int _T_p_B5_EMEP;
    private float _T_p_B20;
    private int _T_p_B20_EMEP;
    private float _T_p_B35;
    private int _T_p_B35_EMEP;
    private float _T_p_B50;
    private int _T_p_B50_EMEP;
    private float _T_p_C1;
    private int _T_p_C1_EMEP;
    private float _T_p_C2;
    private int _T_p_C2_EMEP;
    private float _T_p_C5;
    private int _T_p_C5_EMEP;
    private float _T_p_C10;
    private int _T_p_C10_EMEP;
    private float _T_p_C15;
    private int _T_p_C15_EMEP;
    private float _T_p_C20;
    private int _T_p_C20_EMEP;
    private float _T_p_C30;
    private int _T_p_C30_EMEP;
    private float _T_p_C50;
    private int _T_p_C50_EMEP;
    private float _T_p_C70;
    private int _T_p_C70_EMEP;
    private float _T_p_C100;
    private int _T_p_C100_EMEP;
    private float _WTD;
    private int _WTD_EMEP;
    private float _Precip;
    private int _Precip_EMEP;
    private Sii1meta _escapedModel;

    public Sii1metaModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Sii1meta toModel(Sii1metaSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Sii1meta model = new Sii1metaImpl();

        model.setSamptime(soapModel.getSamptime());
        model.setT_a(soapModel.getT_a());
        model.setT_a_EMEP(soapModel.getT_a_EMEP());
        model.setRH(soapModel.getRH());
        model.setRH_EMEP(soapModel.getRH_EMEP());
        model.setPAR(soapModel.getPAR());
        model.setPAR_EMEP(soapModel.getPAR_EMEP());
        model.setR_PAR(soapModel.getR_PAR());
        model.setR_PAR_EMEP(soapModel.getR_PAR_EMEP());
        model.setNet_CNR4(soapModel.getNet_CNR4());
        model.setNet_CNR4_EMEP(soapModel.getNet_CNR4_EMEP());
        model.setNet_NRLite(soapModel.getNet_NRLite());
        model.setNet_NRLite_EMEP(soapModel.getNet_NRLite_EMEP());
        model.setWsoil_1(soapModel.getWsoil_1());
        model.setWsoil_1_EMEP(soapModel.getWsoil_1_EMEP());
        model.setWsoil_2(soapModel.getWsoil_2());
        model.setWsoil_2_EMEP(soapModel.getWsoil_2_EMEP());
        model.setT_p_B5(soapModel.getT_p_B5());
        model.setT_p_B5_EMEP(soapModel.getT_p_B5_EMEP());
        model.setT_p_B20(soapModel.getT_p_B20());
        model.setT_p_B20_EMEP(soapModel.getT_p_B20_EMEP());
        model.setT_p_B35(soapModel.getT_p_B35());
        model.setT_p_B35_EMEP(soapModel.getT_p_B35_EMEP());
        model.setT_p_B50(soapModel.getT_p_B50());
        model.setT_p_B50_EMEP(soapModel.getT_p_B50_EMEP());
        model.setT_p_C1(soapModel.getT_p_C1());
        model.setT_p_C1_EMEP(soapModel.getT_p_C1_EMEP());
        model.setT_p_C2(soapModel.getT_p_C2());
        model.setT_p_C2_EMEP(soapModel.getT_p_C2_EMEP());
        model.setT_p_C5(soapModel.getT_p_C5());
        model.setT_p_C5_EMEP(soapModel.getT_p_C5_EMEP());
        model.setT_p_C10(soapModel.getT_p_C10());
        model.setT_p_C10_EMEP(soapModel.getT_p_C10_EMEP());
        model.setT_p_C15(soapModel.getT_p_C15());
        model.setT_p_C15_EMEP(soapModel.getT_p_C15_EMEP());
        model.setT_p_C20(soapModel.getT_p_C20());
        model.setT_p_C20_EMEP(soapModel.getT_p_C20_EMEP());
        model.setT_p_C30(soapModel.getT_p_C30());
        model.setT_p_C30_EMEP(soapModel.getT_p_C30_EMEP());
        model.setT_p_C50(soapModel.getT_p_C50());
        model.setT_p_C50_EMEP(soapModel.getT_p_C50_EMEP());
        model.setT_p_C70(soapModel.getT_p_C70());
        model.setT_p_C70_EMEP(soapModel.getT_p_C70_EMEP());
        model.setT_p_C100(soapModel.getT_p_C100());
        model.setT_p_C100_EMEP(soapModel.getT_p_C100_EMEP());
        model.setWTD(soapModel.getWTD());
        model.setWTD_EMEP(soapModel.getWTD_EMEP());
        model.setPrecip(soapModel.getPrecip());
        model.setPrecip_EMEP(soapModel.getPrecip_EMEP());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Sii1meta> toModels(Sii1metaSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Sii1meta> models = new ArrayList<Sii1meta>(soapModels.length);

        for (Sii1metaSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public java.util.Date getPrimaryKey() {
        return _samptime;
    }

    @Override
    public void setPrimaryKey(java.util.Date primaryKey) {
        setSamptime(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _samptime;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((java.util.Date) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return Sii1meta.class;
    }

    @Override
    public String getModelClassName() {
        return Sii1meta.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("samptime", getSamptime());
        attributes.put("T_a", getT_a());
        attributes.put("T_a_EMEP", getT_a_EMEP());
        attributes.put("RH", getRH());
        attributes.put("RH_EMEP", getRH_EMEP());
        attributes.put("PAR", getPAR());
        attributes.put("PAR_EMEP", getPAR_EMEP());
        attributes.put("R_PAR", getR_PAR());
        attributes.put("R_PAR_EMEP", getR_PAR_EMEP());
        attributes.put("Net_CNR4", getNet_CNR4());
        attributes.put("Net_CNR4_EMEP", getNet_CNR4_EMEP());
        attributes.put("Net_NRLite", getNet_NRLite());
        attributes.put("Net_NRLite_EMEP", getNet_NRLite_EMEP());
        attributes.put("Wsoil_1", getWsoil_1());
        attributes.put("Wsoil_1_EMEP", getWsoil_1_EMEP());
        attributes.put("Wsoil_2", getWsoil_2());
        attributes.put("Wsoil_2_EMEP", getWsoil_2_EMEP());
        attributes.put("T_p_B5", getT_p_B5());
        attributes.put("T_p_B5_EMEP", getT_p_B5_EMEP());
        attributes.put("T_p_B20", getT_p_B20());
        attributes.put("T_p_B20_EMEP", getT_p_B20_EMEP());
        attributes.put("T_p_B35", getT_p_B35());
        attributes.put("T_p_B35_EMEP", getT_p_B35_EMEP());
        attributes.put("T_p_B50", getT_p_B50());
        attributes.put("T_p_B50_EMEP", getT_p_B50_EMEP());
        attributes.put("T_p_C1", getT_p_C1());
        attributes.put("T_p_C1_EMEP", getT_p_C1_EMEP());
        attributes.put("T_p_C2", getT_p_C2());
        attributes.put("T_p_C2_EMEP", getT_p_C2_EMEP());
        attributes.put("T_p_C5", getT_p_C5());
        attributes.put("T_p_C5_EMEP", getT_p_C5_EMEP());
        attributes.put("T_p_C10", getT_p_C10());
        attributes.put("T_p_C10_EMEP", getT_p_C10_EMEP());
        attributes.put("T_p_C15", getT_p_C15());
        attributes.put("T_p_C15_EMEP", getT_p_C15_EMEP());
        attributes.put("T_p_C20", getT_p_C20());
        attributes.put("T_p_C20_EMEP", getT_p_C20_EMEP());
        attributes.put("T_p_C30", getT_p_C30());
        attributes.put("T_p_C30_EMEP", getT_p_C30_EMEP());
        attributes.put("T_p_C50", getT_p_C50());
        attributes.put("T_p_C50_EMEP", getT_p_C50_EMEP());
        attributes.put("T_p_C70", getT_p_C70());
        attributes.put("T_p_C70_EMEP", getT_p_C70_EMEP());
        attributes.put("T_p_C100", getT_p_C100());
        attributes.put("T_p_C100_EMEP", getT_p_C100_EMEP());
        attributes.put("WTD", getWTD());
        attributes.put("WTD_EMEP", getWTD_EMEP());
        attributes.put("Precip", getPrecip());
        attributes.put("Precip_EMEP", getPrecip_EMEP());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Date samptime = (Date) attributes.get("samptime");

        if (samptime != null) {
            setSamptime(samptime);
        }

        Float T_a = (Float) attributes.get("T_a");

        if (T_a != null) {
            setT_a(T_a);
        }

        Integer T_a_EMEP = (Integer) attributes.get("T_a_EMEP");

        if (T_a_EMEP != null) {
            setT_a_EMEP(T_a_EMEP);
        }

        Float RH = (Float) attributes.get("RH");

        if (RH != null) {
            setRH(RH);
        }

        Integer RH_EMEP = (Integer) attributes.get("RH_EMEP");

        if (RH_EMEP != null) {
            setRH_EMEP(RH_EMEP);
        }

        Float PAR = (Float) attributes.get("PAR");

        if (PAR != null) {
            setPAR(PAR);
        }

        Integer PAR_EMEP = (Integer) attributes.get("PAR_EMEP");

        if (PAR_EMEP != null) {
            setPAR_EMEP(PAR_EMEP);
        }

        Float R_PAR = (Float) attributes.get("R_PAR");

        if (R_PAR != null) {
            setR_PAR(R_PAR);
        }

        Integer R_PAR_EMEP = (Integer) attributes.get("R_PAR_EMEP");

        if (R_PAR_EMEP != null) {
            setR_PAR_EMEP(R_PAR_EMEP);
        }

        Float Net_CNR4 = (Float) attributes.get("Net_CNR4");

        if (Net_CNR4 != null) {
            setNet_CNR4(Net_CNR4);
        }

        Integer Net_CNR4_EMEP = (Integer) attributes.get("Net_CNR4_EMEP");

        if (Net_CNR4_EMEP != null) {
            setNet_CNR4_EMEP(Net_CNR4_EMEP);
        }

        Float Net_NRLite = (Float) attributes.get("Net_NRLite");

        if (Net_NRLite != null) {
            setNet_NRLite(Net_NRLite);
        }

        Integer Net_NRLite_EMEP = (Integer) attributes.get("Net_NRLite_EMEP");

        if (Net_NRLite_EMEP != null) {
            setNet_NRLite_EMEP(Net_NRLite_EMEP);
        }

        Float Wsoil_1 = (Float) attributes.get("Wsoil_1");

        if (Wsoil_1 != null) {
            setWsoil_1(Wsoil_1);
        }

        Integer Wsoil_1_EMEP = (Integer) attributes.get("Wsoil_1_EMEP");

        if (Wsoil_1_EMEP != null) {
            setWsoil_1_EMEP(Wsoil_1_EMEP);
        }

        Float Wsoil_2 = (Float) attributes.get("Wsoil_2");

        if (Wsoil_2 != null) {
            setWsoil_2(Wsoil_2);
        }

        Integer Wsoil_2_EMEP = (Integer) attributes.get("Wsoil_2_EMEP");

        if (Wsoil_2_EMEP != null) {
            setWsoil_2_EMEP(Wsoil_2_EMEP);
        }

        Float T_p_B5 = (Float) attributes.get("T_p_B5");

        if (T_p_B5 != null) {
            setT_p_B5(T_p_B5);
        }

        Integer T_p_B5_EMEP = (Integer) attributes.get("T_p_B5_EMEP");

        if (T_p_B5_EMEP != null) {
            setT_p_B5_EMEP(T_p_B5_EMEP);
        }

        Float T_p_B20 = (Float) attributes.get("T_p_B20");

        if (T_p_B20 != null) {
            setT_p_B20(T_p_B20);
        }

        Integer T_p_B20_EMEP = (Integer) attributes.get("T_p_B20_EMEP");

        if (T_p_B20_EMEP != null) {
            setT_p_B20_EMEP(T_p_B20_EMEP);
        }

        Float T_p_B35 = (Float) attributes.get("T_p_B35");

        if (T_p_B35 != null) {
            setT_p_B35(T_p_B35);
        }

        Integer T_p_B35_EMEP = (Integer) attributes.get("T_p_B35_EMEP");

        if (T_p_B35_EMEP != null) {
            setT_p_B35_EMEP(T_p_B35_EMEP);
        }

        Float T_p_B50 = (Float) attributes.get("T_p_B50");

        if (T_p_B50 != null) {
            setT_p_B50(T_p_B50);
        }

        Integer T_p_B50_EMEP = (Integer) attributes.get("T_p_B50_EMEP");

        if (T_p_B50_EMEP != null) {
            setT_p_B50_EMEP(T_p_B50_EMEP);
        }

        Float T_p_C1 = (Float) attributes.get("T_p_C1");

        if (T_p_C1 != null) {
            setT_p_C1(T_p_C1);
        }

        Integer T_p_C1_EMEP = (Integer) attributes.get("T_p_C1_EMEP");

        if (T_p_C1_EMEP != null) {
            setT_p_C1_EMEP(T_p_C1_EMEP);
        }

        Float T_p_C2 = (Float) attributes.get("T_p_C2");

        if (T_p_C2 != null) {
            setT_p_C2(T_p_C2);
        }

        Integer T_p_C2_EMEP = (Integer) attributes.get("T_p_C2_EMEP");

        if (T_p_C2_EMEP != null) {
            setT_p_C2_EMEP(T_p_C2_EMEP);
        }

        Float T_p_C5 = (Float) attributes.get("T_p_C5");

        if (T_p_C5 != null) {
            setT_p_C5(T_p_C5);
        }

        Integer T_p_C5_EMEP = (Integer) attributes.get("T_p_C5_EMEP");

        if (T_p_C5_EMEP != null) {
            setT_p_C5_EMEP(T_p_C5_EMEP);
        }

        Float T_p_C10 = (Float) attributes.get("T_p_C10");

        if (T_p_C10 != null) {
            setT_p_C10(T_p_C10);
        }

        Integer T_p_C10_EMEP = (Integer) attributes.get("T_p_C10_EMEP");

        if (T_p_C10_EMEP != null) {
            setT_p_C10_EMEP(T_p_C10_EMEP);
        }

        Float T_p_C15 = (Float) attributes.get("T_p_C15");

        if (T_p_C15 != null) {
            setT_p_C15(T_p_C15);
        }

        Integer T_p_C15_EMEP = (Integer) attributes.get("T_p_C15_EMEP");

        if (T_p_C15_EMEP != null) {
            setT_p_C15_EMEP(T_p_C15_EMEP);
        }

        Float T_p_C20 = (Float) attributes.get("T_p_C20");

        if (T_p_C20 != null) {
            setT_p_C20(T_p_C20);
        }

        Integer T_p_C20_EMEP = (Integer) attributes.get("T_p_C20_EMEP");

        if (T_p_C20_EMEP != null) {
            setT_p_C20_EMEP(T_p_C20_EMEP);
        }

        Float T_p_C30 = (Float) attributes.get("T_p_C30");

        if (T_p_C30 != null) {
            setT_p_C30(T_p_C30);
        }

        Integer T_p_C30_EMEP = (Integer) attributes.get("T_p_C30_EMEP");

        if (T_p_C30_EMEP != null) {
            setT_p_C30_EMEP(T_p_C30_EMEP);
        }

        Float T_p_C50 = (Float) attributes.get("T_p_C50");

        if (T_p_C50 != null) {
            setT_p_C50(T_p_C50);
        }

        Integer T_p_C50_EMEP = (Integer) attributes.get("T_p_C50_EMEP");

        if (T_p_C50_EMEP != null) {
            setT_p_C50_EMEP(T_p_C50_EMEP);
        }

        Float T_p_C70 = (Float) attributes.get("T_p_C70");

        if (T_p_C70 != null) {
            setT_p_C70(T_p_C70);
        }

        Integer T_p_C70_EMEP = (Integer) attributes.get("T_p_C70_EMEP");

        if (T_p_C70_EMEP != null) {
            setT_p_C70_EMEP(T_p_C70_EMEP);
        }

        Float T_p_C100 = (Float) attributes.get("T_p_C100");

        if (T_p_C100 != null) {
            setT_p_C100(T_p_C100);
        }

        Integer T_p_C100_EMEP = (Integer) attributes.get("T_p_C100_EMEP");

        if (T_p_C100_EMEP != null) {
            setT_p_C100_EMEP(T_p_C100_EMEP);
        }

        Float WTD = (Float) attributes.get("WTD");

        if (WTD != null) {
            setWTD(WTD);
        }

        Integer WTD_EMEP = (Integer) attributes.get("WTD_EMEP");

        if (WTD_EMEP != null) {
            setWTD_EMEP(WTD_EMEP);
        }

        Float Precip = (Float) attributes.get("Precip");

        if (Precip != null) {
            setPrecip(Precip);
        }

        Integer Precip_EMEP = (Integer) attributes.get("Precip_EMEP");

        if (Precip_EMEP != null) {
            setPrecip_EMEP(Precip_EMEP);
        }
    }

    @JSON
    @Override
    public Date getSamptime() {
        return _samptime;
    }

    @Override
    public void setSamptime(Date samptime) {
        _samptime = samptime;
    }

    @JSON
    @Override
    public float getT_a() {
        return _T_a;
    }

    @Override
    public void setT_a(float T_a) {
        _T_a = T_a;
    }

    @JSON
    @Override
    public int getT_a_EMEP() {
        return _T_a_EMEP;
    }

    @Override
    public void setT_a_EMEP(int T_a_EMEP) {
        _T_a_EMEP = T_a_EMEP;
    }

    @JSON
    @Override
    public float getRH() {
        return _RH;
    }

    @Override
    public void setRH(float RH) {
        _RH = RH;
    }

    @JSON
    @Override
    public int getRH_EMEP() {
        return _RH_EMEP;
    }

    @Override
    public void setRH_EMEP(int RH_EMEP) {
        _RH_EMEP = RH_EMEP;
    }

    @JSON
    @Override
    public float getPAR() {
        return _PAR;
    }

    @Override
    public void setPAR(float PAR) {
        _PAR = PAR;
    }

    @JSON
    @Override
    public int getPAR_EMEP() {
        return _PAR_EMEP;
    }

    @Override
    public void setPAR_EMEP(int PAR_EMEP) {
        _PAR_EMEP = PAR_EMEP;
    }

    @JSON
    @Override
    public float getR_PAR() {
        return _R_PAR;
    }

    @Override
    public void setR_PAR(float R_PAR) {
        _R_PAR = R_PAR;
    }

    @JSON
    @Override
    public int getR_PAR_EMEP() {
        return _R_PAR_EMEP;
    }

    @Override
    public void setR_PAR_EMEP(int R_PAR_EMEP) {
        _R_PAR_EMEP = R_PAR_EMEP;
    }

    @JSON
    @Override
    public float getNet_CNR4() {
        return _Net_CNR4;
    }

    @Override
    public void setNet_CNR4(float Net_CNR4) {
        _Net_CNR4 = Net_CNR4;
    }

    @JSON
    @Override
    public int getNet_CNR4_EMEP() {
        return _Net_CNR4_EMEP;
    }

    @Override
    public void setNet_CNR4_EMEP(int Net_CNR4_EMEP) {
        _Net_CNR4_EMEP = Net_CNR4_EMEP;
    }

    @JSON
    @Override
    public float getNet_NRLite() {
        return _Net_NRLite;
    }

    @Override
    public void setNet_NRLite(float Net_NRLite) {
        _Net_NRLite = Net_NRLite;
    }

    @JSON
    @Override
    public int getNet_NRLite_EMEP() {
        return _Net_NRLite_EMEP;
    }

    @Override
    public void setNet_NRLite_EMEP(int Net_NRLite_EMEP) {
        _Net_NRLite_EMEP = Net_NRLite_EMEP;
    }

    @JSON
    @Override
    public float getWsoil_1() {
        return _Wsoil_1;
    }

    @Override
    public void setWsoil_1(float Wsoil_1) {
        _Wsoil_1 = Wsoil_1;
    }

    @JSON
    @Override
    public int getWsoil_1_EMEP() {
        return _Wsoil_1_EMEP;
    }

    @Override
    public void setWsoil_1_EMEP(int Wsoil_1_EMEP) {
        _Wsoil_1_EMEP = Wsoil_1_EMEP;
    }

    @JSON
    @Override
    public float getWsoil_2() {
        return _Wsoil_2;
    }

    @Override
    public void setWsoil_2(float Wsoil_2) {
        _Wsoil_2 = Wsoil_2;
    }

    @JSON
    @Override
    public int getWsoil_2_EMEP() {
        return _Wsoil_2_EMEP;
    }

    @Override
    public void setWsoil_2_EMEP(int Wsoil_2_EMEP) {
        _Wsoil_2_EMEP = Wsoil_2_EMEP;
    }

    @JSON
    @Override
    public float getT_p_B5() {
        return _T_p_B5;
    }

    @Override
    public void setT_p_B5(float T_p_B5) {
        _T_p_B5 = T_p_B5;
    }

    @JSON
    @Override
    public int getT_p_B5_EMEP() {
        return _T_p_B5_EMEP;
    }

    @Override
    public void setT_p_B5_EMEP(int T_p_B5_EMEP) {
        _T_p_B5_EMEP = T_p_B5_EMEP;
    }

    @JSON
    @Override
    public float getT_p_B20() {
        return _T_p_B20;
    }

    @Override
    public void setT_p_B20(float T_p_B20) {
        _T_p_B20 = T_p_B20;
    }

    @JSON
    @Override
    public int getT_p_B20_EMEP() {
        return _T_p_B20_EMEP;
    }

    @Override
    public void setT_p_B20_EMEP(int T_p_B20_EMEP) {
        _T_p_B20_EMEP = T_p_B20_EMEP;
    }

    @JSON
    @Override
    public float getT_p_B35() {
        return _T_p_B35;
    }

    @Override
    public void setT_p_B35(float T_p_B35) {
        _T_p_B35 = T_p_B35;
    }

    @JSON
    @Override
    public int getT_p_B35_EMEP() {
        return _T_p_B35_EMEP;
    }

    @Override
    public void setT_p_B35_EMEP(int T_p_B35_EMEP) {
        _T_p_B35_EMEP = T_p_B35_EMEP;
    }

    @JSON
    @Override
    public float getT_p_B50() {
        return _T_p_B50;
    }

    @Override
    public void setT_p_B50(float T_p_B50) {
        _T_p_B50 = T_p_B50;
    }

    @JSON
    @Override
    public int getT_p_B50_EMEP() {
        return _T_p_B50_EMEP;
    }

    @Override
    public void setT_p_B50_EMEP(int T_p_B50_EMEP) {
        _T_p_B50_EMEP = T_p_B50_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C1() {
        return _T_p_C1;
    }

    @Override
    public void setT_p_C1(float T_p_C1) {
        _T_p_C1 = T_p_C1;
    }

    @JSON
    @Override
    public int getT_p_C1_EMEP() {
        return _T_p_C1_EMEP;
    }

    @Override
    public void setT_p_C1_EMEP(int T_p_C1_EMEP) {
        _T_p_C1_EMEP = T_p_C1_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C2() {
        return _T_p_C2;
    }

    @Override
    public void setT_p_C2(float T_p_C2) {
        _T_p_C2 = T_p_C2;
    }

    @JSON
    @Override
    public int getT_p_C2_EMEP() {
        return _T_p_C2_EMEP;
    }

    @Override
    public void setT_p_C2_EMEP(int T_p_C2_EMEP) {
        _T_p_C2_EMEP = T_p_C2_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C5() {
        return _T_p_C5;
    }

    @Override
    public void setT_p_C5(float T_p_C5) {
        _T_p_C5 = T_p_C5;
    }

    @JSON
    @Override
    public int getT_p_C5_EMEP() {
        return _T_p_C5_EMEP;
    }

    @Override
    public void setT_p_C5_EMEP(int T_p_C5_EMEP) {
        _T_p_C5_EMEP = T_p_C5_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C10() {
        return _T_p_C10;
    }

    @Override
    public void setT_p_C10(float T_p_C10) {
        _T_p_C10 = T_p_C10;
    }

    @JSON
    @Override
    public int getT_p_C10_EMEP() {
        return _T_p_C10_EMEP;
    }

    @Override
    public void setT_p_C10_EMEP(int T_p_C10_EMEP) {
        _T_p_C10_EMEP = T_p_C10_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C15() {
        return _T_p_C15;
    }

    @Override
    public void setT_p_C15(float T_p_C15) {
        _T_p_C15 = T_p_C15;
    }

    @JSON
    @Override
    public int getT_p_C15_EMEP() {
        return _T_p_C15_EMEP;
    }

    @Override
    public void setT_p_C15_EMEP(int T_p_C15_EMEP) {
        _T_p_C15_EMEP = T_p_C15_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C20() {
        return _T_p_C20;
    }

    @Override
    public void setT_p_C20(float T_p_C20) {
        _T_p_C20 = T_p_C20;
    }

    @JSON
    @Override
    public int getT_p_C20_EMEP() {
        return _T_p_C20_EMEP;
    }

    @Override
    public void setT_p_C20_EMEP(int T_p_C20_EMEP) {
        _T_p_C20_EMEP = T_p_C20_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C30() {
        return _T_p_C30;
    }

    @Override
    public void setT_p_C30(float T_p_C30) {
        _T_p_C30 = T_p_C30;
    }

    @JSON
    @Override
    public int getT_p_C30_EMEP() {
        return _T_p_C30_EMEP;
    }

    @Override
    public void setT_p_C30_EMEP(int T_p_C30_EMEP) {
        _T_p_C30_EMEP = T_p_C30_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C50() {
        return _T_p_C50;
    }

    @Override
    public void setT_p_C50(float T_p_C50) {
        _T_p_C50 = T_p_C50;
    }

    @JSON
    @Override
    public int getT_p_C50_EMEP() {
        return _T_p_C50_EMEP;
    }

    @Override
    public void setT_p_C50_EMEP(int T_p_C50_EMEP) {
        _T_p_C50_EMEP = T_p_C50_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C70() {
        return _T_p_C70;
    }

    @Override
    public void setT_p_C70(float T_p_C70) {
        _T_p_C70 = T_p_C70;
    }

    @JSON
    @Override
    public int getT_p_C70_EMEP() {
        return _T_p_C70_EMEP;
    }

    @Override
    public void setT_p_C70_EMEP(int T_p_C70_EMEP) {
        _T_p_C70_EMEP = T_p_C70_EMEP;
    }

    @JSON
    @Override
    public float getT_p_C100() {
        return _T_p_C100;
    }

    @Override
    public void setT_p_C100(float T_p_C100) {
        _T_p_C100 = T_p_C100;
    }

    @JSON
    @Override
    public int getT_p_C100_EMEP() {
        return _T_p_C100_EMEP;
    }

    @Override
    public void setT_p_C100_EMEP(int T_p_C100_EMEP) {
        _T_p_C100_EMEP = T_p_C100_EMEP;
    }

    @JSON
    @Override
    public float getWTD() {
        return _WTD;
    }

    @Override
    public void setWTD(float WTD) {
        _WTD = WTD;
    }

    @JSON
    @Override
    public int getWTD_EMEP() {
        return _WTD_EMEP;
    }

    @Override
    public void setWTD_EMEP(int WTD_EMEP) {
        _WTD_EMEP = WTD_EMEP;
    }

    @JSON
    @Override
    public float getPrecip() {
        return _Precip;
    }

    @Override
    public void setPrecip(float Precip) {
        _Precip = Precip;
    }

    @JSON
    @Override
    public int getPrecip_EMEP() {
        return _Precip_EMEP;
    }

    @Override
    public void setPrecip_EMEP(int Precip_EMEP) {
        _Precip_EMEP = Precip_EMEP;
    }

    @Override
    public Sii1meta toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Sii1meta) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Sii1metaImpl sii1metaImpl = new Sii1metaImpl();

        sii1metaImpl.setSamptime(getSamptime());
        sii1metaImpl.setT_a(getT_a());
        sii1metaImpl.setT_a_EMEP(getT_a_EMEP());
        sii1metaImpl.setRH(getRH());
        sii1metaImpl.setRH_EMEP(getRH_EMEP());
        sii1metaImpl.setPAR(getPAR());
        sii1metaImpl.setPAR_EMEP(getPAR_EMEP());
        sii1metaImpl.setR_PAR(getR_PAR());
        sii1metaImpl.setR_PAR_EMEP(getR_PAR_EMEP());
        sii1metaImpl.setNet_CNR4(getNet_CNR4());
        sii1metaImpl.setNet_CNR4_EMEP(getNet_CNR4_EMEP());
        sii1metaImpl.setNet_NRLite(getNet_NRLite());
        sii1metaImpl.setNet_NRLite_EMEP(getNet_NRLite_EMEP());
        sii1metaImpl.setWsoil_1(getWsoil_1());
        sii1metaImpl.setWsoil_1_EMEP(getWsoil_1_EMEP());
        sii1metaImpl.setWsoil_2(getWsoil_2());
        sii1metaImpl.setWsoil_2_EMEP(getWsoil_2_EMEP());
        sii1metaImpl.setT_p_B5(getT_p_B5());
        sii1metaImpl.setT_p_B5_EMEP(getT_p_B5_EMEP());
        sii1metaImpl.setT_p_B20(getT_p_B20());
        sii1metaImpl.setT_p_B20_EMEP(getT_p_B20_EMEP());
        sii1metaImpl.setT_p_B35(getT_p_B35());
        sii1metaImpl.setT_p_B35_EMEP(getT_p_B35_EMEP());
        sii1metaImpl.setT_p_B50(getT_p_B50());
        sii1metaImpl.setT_p_B50_EMEP(getT_p_B50_EMEP());
        sii1metaImpl.setT_p_C1(getT_p_C1());
        sii1metaImpl.setT_p_C1_EMEP(getT_p_C1_EMEP());
        sii1metaImpl.setT_p_C2(getT_p_C2());
        sii1metaImpl.setT_p_C2_EMEP(getT_p_C2_EMEP());
        sii1metaImpl.setT_p_C5(getT_p_C5());
        sii1metaImpl.setT_p_C5_EMEP(getT_p_C5_EMEP());
        sii1metaImpl.setT_p_C10(getT_p_C10());
        sii1metaImpl.setT_p_C10_EMEP(getT_p_C10_EMEP());
        sii1metaImpl.setT_p_C15(getT_p_C15());
        sii1metaImpl.setT_p_C15_EMEP(getT_p_C15_EMEP());
        sii1metaImpl.setT_p_C20(getT_p_C20());
        sii1metaImpl.setT_p_C20_EMEP(getT_p_C20_EMEP());
        sii1metaImpl.setT_p_C30(getT_p_C30());
        sii1metaImpl.setT_p_C30_EMEP(getT_p_C30_EMEP());
        sii1metaImpl.setT_p_C50(getT_p_C50());
        sii1metaImpl.setT_p_C50_EMEP(getT_p_C50_EMEP());
        sii1metaImpl.setT_p_C70(getT_p_C70());
        sii1metaImpl.setT_p_C70_EMEP(getT_p_C70_EMEP());
        sii1metaImpl.setT_p_C100(getT_p_C100());
        sii1metaImpl.setT_p_C100_EMEP(getT_p_C100_EMEP());
        sii1metaImpl.setWTD(getWTD());
        sii1metaImpl.setWTD_EMEP(getWTD_EMEP());
        sii1metaImpl.setPrecip(getPrecip());
        sii1metaImpl.setPrecip_EMEP(getPrecip_EMEP());

        sii1metaImpl.resetOriginalValues();

        return sii1metaImpl;
    }

    @Override
    public int compareTo(Sii1meta sii1meta) {
        java.util.Date primaryKey = sii1meta.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Sii1meta)) {
            return false;
        }

        Sii1meta sii1meta = (Sii1meta) obj;

        java.util.Date primaryKey = sii1meta.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Sii1meta> toCacheModel() {
        Sii1metaCacheModel sii1metaCacheModel = new Sii1metaCacheModel();

        Date samptime = getSamptime();

        if (samptime != null) {
            sii1metaCacheModel.samptime = samptime.getTime();
        } else {
            sii1metaCacheModel.samptime = Long.MIN_VALUE;
        }

        sii1metaCacheModel.T_a = getT_a();

        sii1metaCacheModel.T_a_EMEP = getT_a_EMEP();

        sii1metaCacheModel.RH = getRH();

        sii1metaCacheModel.RH_EMEP = getRH_EMEP();

        sii1metaCacheModel.PAR = getPAR();

        sii1metaCacheModel.PAR_EMEP = getPAR_EMEP();

        sii1metaCacheModel.R_PAR = getR_PAR();

        sii1metaCacheModel.R_PAR_EMEP = getR_PAR_EMEP();

        sii1metaCacheModel.Net_CNR4 = getNet_CNR4();

        sii1metaCacheModel.Net_CNR4_EMEP = getNet_CNR4_EMEP();

        sii1metaCacheModel.Net_NRLite = getNet_NRLite();

        sii1metaCacheModel.Net_NRLite_EMEP = getNet_NRLite_EMEP();

        sii1metaCacheModel.Wsoil_1 = getWsoil_1();

        sii1metaCacheModel.Wsoil_1_EMEP = getWsoil_1_EMEP();

        sii1metaCacheModel.Wsoil_2 = getWsoil_2();

        sii1metaCacheModel.Wsoil_2_EMEP = getWsoil_2_EMEP();

        sii1metaCacheModel.T_p_B5 = getT_p_B5();

        sii1metaCacheModel.T_p_B5_EMEP = getT_p_B5_EMEP();

        sii1metaCacheModel.T_p_B20 = getT_p_B20();

        sii1metaCacheModel.T_p_B20_EMEP = getT_p_B20_EMEP();

        sii1metaCacheModel.T_p_B35 = getT_p_B35();

        sii1metaCacheModel.T_p_B35_EMEP = getT_p_B35_EMEP();

        sii1metaCacheModel.T_p_B50 = getT_p_B50();

        sii1metaCacheModel.T_p_B50_EMEP = getT_p_B50_EMEP();

        sii1metaCacheModel.T_p_C1 = getT_p_C1();

        sii1metaCacheModel.T_p_C1_EMEP = getT_p_C1_EMEP();

        sii1metaCacheModel.T_p_C2 = getT_p_C2();

        sii1metaCacheModel.T_p_C2_EMEP = getT_p_C2_EMEP();

        sii1metaCacheModel.T_p_C5 = getT_p_C5();

        sii1metaCacheModel.T_p_C5_EMEP = getT_p_C5_EMEP();

        sii1metaCacheModel.T_p_C10 = getT_p_C10();

        sii1metaCacheModel.T_p_C10_EMEP = getT_p_C10_EMEP();

        sii1metaCacheModel.T_p_C15 = getT_p_C15();

        sii1metaCacheModel.T_p_C15_EMEP = getT_p_C15_EMEP();

        sii1metaCacheModel.T_p_C20 = getT_p_C20();

        sii1metaCacheModel.T_p_C20_EMEP = getT_p_C20_EMEP();

        sii1metaCacheModel.T_p_C30 = getT_p_C30();

        sii1metaCacheModel.T_p_C30_EMEP = getT_p_C30_EMEP();

        sii1metaCacheModel.T_p_C50 = getT_p_C50();

        sii1metaCacheModel.T_p_C50_EMEP = getT_p_C50_EMEP();

        sii1metaCacheModel.T_p_C70 = getT_p_C70();

        sii1metaCacheModel.T_p_C70_EMEP = getT_p_C70_EMEP();

        sii1metaCacheModel.T_p_C100 = getT_p_C100();

        sii1metaCacheModel.T_p_C100_EMEP = getT_p_C100_EMEP();

        sii1metaCacheModel.WTD = getWTD();

        sii1metaCacheModel.WTD_EMEP = getWTD_EMEP();

        sii1metaCacheModel.Precip = getPrecip();

        sii1metaCacheModel.Precip_EMEP = getPrecip_EMEP();

        return sii1metaCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(99);

        sb.append("{samptime=");
        sb.append(getSamptime());
        sb.append(", T_a=");
        sb.append(getT_a());
        sb.append(", T_a_EMEP=");
        sb.append(getT_a_EMEP());
        sb.append(", RH=");
        sb.append(getRH());
        sb.append(", RH_EMEP=");
        sb.append(getRH_EMEP());
        sb.append(", PAR=");
        sb.append(getPAR());
        sb.append(", PAR_EMEP=");
        sb.append(getPAR_EMEP());
        sb.append(", R_PAR=");
        sb.append(getR_PAR());
        sb.append(", R_PAR_EMEP=");
        sb.append(getR_PAR_EMEP());
        sb.append(", Net_CNR4=");
        sb.append(getNet_CNR4());
        sb.append(", Net_CNR4_EMEP=");
        sb.append(getNet_CNR4_EMEP());
        sb.append(", Net_NRLite=");
        sb.append(getNet_NRLite());
        sb.append(", Net_NRLite_EMEP=");
        sb.append(getNet_NRLite_EMEP());
        sb.append(", Wsoil_1=");
        sb.append(getWsoil_1());
        sb.append(", Wsoil_1_EMEP=");
        sb.append(getWsoil_1_EMEP());
        sb.append(", Wsoil_2=");
        sb.append(getWsoil_2());
        sb.append(", Wsoil_2_EMEP=");
        sb.append(getWsoil_2_EMEP());
        sb.append(", T_p_B5=");
        sb.append(getT_p_B5());
        sb.append(", T_p_B5_EMEP=");
        sb.append(getT_p_B5_EMEP());
        sb.append(", T_p_B20=");
        sb.append(getT_p_B20());
        sb.append(", T_p_B20_EMEP=");
        sb.append(getT_p_B20_EMEP());
        sb.append(", T_p_B35=");
        sb.append(getT_p_B35());
        sb.append(", T_p_B35_EMEP=");
        sb.append(getT_p_B35_EMEP());
        sb.append(", T_p_B50=");
        sb.append(getT_p_B50());
        sb.append(", T_p_B50_EMEP=");
        sb.append(getT_p_B50_EMEP());
        sb.append(", T_p_C1=");
        sb.append(getT_p_C1());
        sb.append(", T_p_C1_EMEP=");
        sb.append(getT_p_C1_EMEP());
        sb.append(", T_p_C2=");
        sb.append(getT_p_C2());
        sb.append(", T_p_C2_EMEP=");
        sb.append(getT_p_C2_EMEP());
        sb.append(", T_p_C5=");
        sb.append(getT_p_C5());
        sb.append(", T_p_C5_EMEP=");
        sb.append(getT_p_C5_EMEP());
        sb.append(", T_p_C10=");
        sb.append(getT_p_C10());
        sb.append(", T_p_C10_EMEP=");
        sb.append(getT_p_C10_EMEP());
        sb.append(", T_p_C15=");
        sb.append(getT_p_C15());
        sb.append(", T_p_C15_EMEP=");
        sb.append(getT_p_C15_EMEP());
        sb.append(", T_p_C20=");
        sb.append(getT_p_C20());
        sb.append(", T_p_C20_EMEP=");
        sb.append(getT_p_C20_EMEP());
        sb.append(", T_p_C30=");
        sb.append(getT_p_C30());
        sb.append(", T_p_C30_EMEP=");
        sb.append(getT_p_C30_EMEP());
        sb.append(", T_p_C50=");
        sb.append(getT_p_C50());
        sb.append(", T_p_C50_EMEP=");
        sb.append(getT_p_C50_EMEP());
        sb.append(", T_p_C70=");
        sb.append(getT_p_C70());
        sb.append(", T_p_C70_EMEP=");
        sb.append(getT_p_C70_EMEP());
        sb.append(", T_p_C100=");
        sb.append(getT_p_C100());
        sb.append(", T_p_C100_EMEP=");
        sb.append(getT_p_C100_EMEP());
        sb.append(", WTD=");
        sb.append(getWTD());
        sb.append(", WTD_EMEP=");
        sb.append(getWTD_EMEP());
        sb.append(", Precip=");
        sb.append(getPrecip());
        sb.append(", Precip_EMEP=");
        sb.append(getPrecip_EMEP());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(151);

        sb.append("<model><model-name>");
        sb.append("fi.csc.smear.db.model.Sii1meta");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>samptime</column-name><column-value><![CDATA[");
        sb.append(getSamptime());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_a</column-name><column-value><![CDATA[");
        sb.append(getT_a());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_a_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_a_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>RH</column-name><column-value><![CDATA[");
        sb.append(getRH());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>RH_EMEP</column-name><column-value><![CDATA[");
        sb.append(getRH_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>PAR</column-name><column-value><![CDATA[");
        sb.append(getPAR());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>PAR_EMEP</column-name><column-value><![CDATA[");
        sb.append(getPAR_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>R_PAR</column-name><column-value><![CDATA[");
        sb.append(getR_PAR());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>R_PAR_EMEP</column-name><column-value><![CDATA[");
        sb.append(getR_PAR_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Net_CNR4</column-name><column-value><![CDATA[");
        sb.append(getNet_CNR4());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Net_CNR4_EMEP</column-name><column-value><![CDATA[");
        sb.append(getNet_CNR4_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Net_NRLite</column-name><column-value><![CDATA[");
        sb.append(getNet_NRLite());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Net_NRLite_EMEP</column-name><column-value><![CDATA[");
        sb.append(getNet_NRLite_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Wsoil_1</column-name><column-value><![CDATA[");
        sb.append(getWsoil_1());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Wsoil_1_EMEP</column-name><column-value><![CDATA[");
        sb.append(getWsoil_1_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Wsoil_2</column-name><column-value><![CDATA[");
        sb.append(getWsoil_2());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Wsoil_2_EMEP</column-name><column-value><![CDATA[");
        sb.append(getWsoil_2_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B5</column-name><column-value><![CDATA[");
        sb.append(getT_p_B5());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B5_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_B5_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B20</column-name><column-value><![CDATA[");
        sb.append(getT_p_B20());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B20_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_B20_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B35</column-name><column-value><![CDATA[");
        sb.append(getT_p_B35());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B35_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_B35_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B50</column-name><column-value><![CDATA[");
        sb.append(getT_p_B50());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_B50_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_B50_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C1</column-name><column-value><![CDATA[");
        sb.append(getT_p_C1());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C1_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C1_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C2</column-name><column-value><![CDATA[");
        sb.append(getT_p_C2());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C2_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C2_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C5</column-name><column-value><![CDATA[");
        sb.append(getT_p_C5());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C5_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C5_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C10</column-name><column-value><![CDATA[");
        sb.append(getT_p_C10());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C10_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C10_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C15</column-name><column-value><![CDATA[");
        sb.append(getT_p_C15());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C15_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C15_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C20</column-name><column-value><![CDATA[");
        sb.append(getT_p_C20());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C20_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C20_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C30</column-name><column-value><![CDATA[");
        sb.append(getT_p_C30());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C30_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C30_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C50</column-name><column-value><![CDATA[");
        sb.append(getT_p_C50());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C50_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C50_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C70</column-name><column-value><![CDATA[");
        sb.append(getT_p_C70());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C70_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C70_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C100</column-name><column-value><![CDATA[");
        sb.append(getT_p_C100());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>T_p_C100_EMEP</column-name><column-value><![CDATA[");
        sb.append(getT_p_C100_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>WTD</column-name><column-value><![CDATA[");
        sb.append(getWTD());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>WTD_EMEP</column-name><column-value><![CDATA[");
        sb.append(getWTD_EMEP());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Precip</column-name><column-value><![CDATA[");
        sb.append(getPrecip());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Precip_EMEP</column-name><column-value><![CDATA[");
        sb.append(getPrecip_EMEP());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
