package fi.csc.smear.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.smear.db.model.Sii2meta;
import fi.csc.smear.db.service.Sii2metaLocalServiceUtil;

/**
 * The extended model base implementation for the Sii2meta service. Represents a row in the &quot;SII2_META&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Sii2metaImpl}.
 * </p>
 *
 * @author pj
 * @see Sii2metaImpl
 * @see fi.csc.smear.db.model.Sii2meta
 * @generated
 */
public abstract class Sii2metaBaseImpl extends Sii2metaModelImpl
    implements Sii2meta {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sii2meta model instance should use the {@link Sii2meta} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Sii2metaLocalServiceUtil.addSii2meta(this);
        } else {
            Sii2metaLocalServiceUtil.updateSii2meta(this);
        }
    }
}
